package model

import (
	"context"
	"math"
	"time"

	"github.com/Laisky/errors/v2"
	"github.com/Laisky/zap"
	"github.com/google/uuid"
	"gorm.io/gorm"

	"github.com/Laisky/one-api/common/logger"
)

const (
	// QuotaRefundPending identifies an owned refund that still needs a durable credit.
	QuotaRefundPending = "pending"
	// QuotaRefundCompleted identifies a refund credited in the same transaction as its marker.
	QuotaRefundCompleted = "completed"
)

// QuotaRefund is an internal, immutable refund intent. ID is generated by the
// gateway per abandoned attempt, never supplied by the client. The status and
// balance credit commit atomically, so retries after an uncertain commit or a
// process restart cannot credit the reservation twice. Pending intents survive
// request-context recycling and are retried by the lifecycle-managed worker.
// Completed rows must not be deleted while their IDs can still be replayed.
type QuotaRefund struct {
	ID          string `gorm:"type:varchar(36);primaryKey"`
	TokenID     int
	UserID      int
	Amount      int64
	RequestID   string `gorm:"size:128"`
	Reason      string `gorm:"size:128"`
	Status      string `gorm:"size:16;index:idx_quota_refund_pending,priority:1"`
	RetryAt     int64  `gorm:"index:idx_quota_refund_pending,priority:2"`
	Attempts    int64
	CompletedAt int64
	CreatedAt   int64 `gorm:"autoCreateTime"`
}

// EnsureQuotaRefund persists intent before any balance credit. It validates the
// token owner and positive amount, and accepts replay only with identical
// immutable fields. A failed enqueue never falls back to an untracked credit.
func EnsureQuotaRefund(ctx context.Context, intent QuotaRefund) error {
	if _, err := uuid.Parse(intent.ID); err != nil {
		return errors.Wrap(err, "invalid internal refund ID")
	}
	if intent.TokenID <= 0 || intent.Amount <= 0 || len(intent.RequestID) > 128 || len(intent.Reason) > 128 {
		return errors.New("invalid quota refund intent")
	}
	var token Token
	if err := DB.WithContext(ctx).Where("id = ?", intent.TokenID).Take(&token).Error; err != nil {
		return errors.Wrap(err, "read refund owner")
	}
	if intent.UserID != 0 && intent.UserID != token.UserId {
		return errors.New("quota refund token owner mismatch")
	}
	intent.UserID = token.UserId
	intent.Status, intent.RetryAt, intent.Attempts, intent.CompletedAt, intent.CreatedAt = QuotaRefundPending, 0, 0, 0, 0

	var existing QuotaRefund
	lookup := DB.WithContext(ctx).Where("id = ?", intent.ID).Take(&existing).Error
	if lookup == nil {
		return sameQuotaRefund(existing, intent)
	}
	if !errors.Is(lookup, gorm.ErrRecordNotFound) {
		return errors.Wrap(lookup, "read existing refund intent")
	}
	if err := DB.WithContext(ctx).Create(&intent).Error; err != nil {
		// An overlapping enqueue or a lost INSERT acknowledgement may have
		// persisted this ID. Re-read outside the failed insert transaction.
		if lookupErr := DB.WithContext(ctx).Where("id = ?", intent.ID).Take(&existing).Error; lookupErr == nil {
			return sameQuotaRefund(existing, intent)
		}
		return errors.Wrap(err, "persist quota refund intent")
	}
	return nil
}

// sameQuotaRefund rejects an ID reused for a different reservation. Mutable
// recovery fields are deliberately excluded; replay cannot reset a completion.
func sameQuotaRefund(stored, proposed QuotaRefund) error {
	if stored.TokenID != proposed.TokenID || stored.UserID != proposed.UserID || stored.Amount != proposed.Amount ||
		stored.RequestID != proposed.RequestID || stored.Reason != proposed.Reason {
		return errors.New("quota refund ID already belongs to another intent")
	}
	return nil
}

// ApplyQuotaRefund atomically claims a pending ID and credits both balances.
// An error leaves its durable intent pending unless an uncertain COMMIT actually
// succeeded, in which case another call observes completed and makes no credit.
// Cache failures cannot trigger a second financial movement.
func ApplyQuotaRefund(ctx context.Context, id string) error {
	var intent QuotaRefund
	var token Token
	err := runWithSQLiteBusyRetry(ctx, func() error {
		return errors.WithStack(DB.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
			if err := tx.Where("id = ?", id).Take(&intent).Error; err != nil {
				return errors.Wrap(err, "read pending quota refund")
			}
			if err := tx.Where("id = ? AND user_id = ?", intent.TokenID, intent.UserID).Take(&token).Error; err != nil {
				return errors.Wrap(err, "read original refund token owner")
			}
			if intent.Status == QuotaRefundCompleted {
				return nil
			}
			if intent.Status != QuotaRefundPending || intent.Amount <= 0 {
				return errors.New("invalid persisted quota refund state")
			}
			claim := tx.Model(&QuotaRefund{}).Where("id = ? AND status = ?", id, QuotaRefundPending).
				Updates(map[string]any{"status": QuotaRefundCompleted, "completed_at": time.Now().UTC().Unix()})
			if claim.Error != nil {
				return errors.Wrap(claim.Error, "claim pending quota refund")
			}
			if claim.RowsAffected == 0 {
				return nil // Another transaction has already credited this ID.
			}
			// Guard the upper bound as well as transaction atomicity; refunding
			// after an unrelated large top-up must not overflow a balance.
			credit := tx.Model(&User{}).Where("id = ? AND quota <= ?", token.UserId, int64(math.MaxInt64)-intent.Amount).
				Update("quota", gorm.Expr("quota + ?", intent.Amount))
			if credit.Error != nil {
				return errors.Wrap(credit.Error, "credit refund owner")
			}
			if credit.RowsAffected != 1 {
				return errors.New("missing or overflowing refund owner balance")
			}
			if token.UnlimitedQuota {
				return nil
			}
			credit = tx.Model(&Token{}).Where("id = ? AND user_id = ? AND remain_quota <= ? AND used_quota >= ?",
				token.Id, intent.UserID, int64(math.MaxInt64)-intent.Amount, int64(math.MinInt64)+intent.Amount).
				Updates(map[string]any{"remain_quota": gorm.Expr("remain_quota + ?", intent.Amount),
					"used_quota": gorm.Expr("used_quota - ?", intent.Amount), "accessed_time": time.Now().UTC().Unix()})
			if credit.Error != nil {
				return errors.Wrap(credit.Error, "credit refund token")
			}
			if credit.RowsAffected != 1 {
				return errors.New("missing or overflowing refund token balance")
			}
			return nil
		}))
	})
	if err != nil {
		return errors.Wrap(err, "apply owned quota refund")
	}
	clearTokenCache(ctx, token.Key)
	if err := CacheUpdateUserQuota(ctx, intent.UserID); err != nil {
		logger.FromContext(ctx).Warn("quota refund committed but cache refresh failed", zap.String("refund_id", id), zap.Error(err))
	}
	return nil
}

// RefundQuotaWithRecovery first persists the intent, then retries the idempotent
// credit on a bounded context. Five short attempts cover transient failures; a
// persisted pending row remains available to the recovery worker after exhaustion.
// The returned persisted flag distinguishes a queued refund from an enqueue
// outage that still requires the caller's critical audit record.
func RefundQuotaWithRecovery(ctx context.Context, intent QuotaRefund) (persisted bool, err error) {
	for attempt := 0; attempt < 5; attempt++ {
		if !persisted {
			err = EnsureQuotaRefund(ctx, intent)
			persisted = err == nil
		}
		if persisted {
			err = ApplyQuotaRefund(ctx, intent.ID)
		}
		if err == nil {
			return persisted, nil
		}
		if attempt == 4 {
			break
		}
		timer := time.NewTimer(time.Duration(1<<attempt) * 25 * time.Millisecond)
		select {
		case <-ctx.Done():
			timer.Stop()
			return persisted, errors.Wrap(ctx.Err(), "owned refund deadline")
		case <-timer.C:
		}
	}
	return persisted, errors.Wrap(err, "owned refund deferred for recovery")
}
