package togetherai

import "github.com/Laisky/one-api/relay/adaptor"

// otherModels returns the other model defaults for togetherai.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func otherModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"ByteDance-Seed/Seedream-3.0": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.018874368,
				DefaultSize:      "1024x1024",
				MinImages:        1,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1024x1536": 1.5,
					"1536x1024": 1.5,
					"1920x1080": 1.9775390625,
					"2048x2048": 4,
					"3840x2160": 7.91015625,
					"4096x4096": 16,
					"512x512":   0.25,
				},
			},
		},
		"ByteDance-Seed/Seedream-4.0": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.03145728,
				DefaultSize:      "1024x1024",
				MinImages:        1,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1024x1536": 1.5,
					"1536x1024": 1.5,
					"1920x1080": 1.9775390625,
					"2048x2048": 4,
					"3840x2160": 7.91015625,
					"4096x4096": 16,
					"512x512":   0.25,
				},
			},
		},
		"HiDream-ai/HiDream-I1-Dev": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.004718592,
				DefaultSize:      "1024x1024",
				MinImages:        1,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1024x1536": 1.5,
					"1536x1024": 1.5,
					"1920x1080": 1.9775390625,
					"2048x2048": 4,
					"3840x2160": 7.91015625,
					"4096x4096": 16,
					"512x512":   0.25,
				},
			},
		},
		"HiDream-ai/HiDream-I1-Fast": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.0033554432,
				DefaultSize:      "1024x1024",
				MinImages:        1,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1024x1536": 1.5,
					"1536x1024": 1.5,
					"1920x1080": 1.9775390625,
					"2048x2048": 4,
					"3840x2160": 7.91015625,
					"4096x4096": 16,
					"512x512":   0.25,
				},
			},
		},
		"HiDream-ai/HiDream-I1-Full": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.009437184,
				DefaultSize:      "1024x1024",
				MinImages:        1,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1024x1536": 1.5,
					"1536x1024": 1.5,
					"1920x1080": 1.9775390625,
					"2048x2048": 4,
					"3840x2160": 7.91015625,
					"4096x4096": 16,
					"512x512":   0.25,
				},
			},
		},
		"LiquidAI/LFM2-24B-A2B": {
			Ratio:                       nativeRate(0.03),
			CompletionRatio:             4,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "LiquidAI/LFM2-24B-A2B",
			Description:                 "Liquid Foundation Model 2, 24B MoE with hybrid-conv/attn architecture for edge deployment.",
		},
		"LiquidAI/LFM2.5-8B-A1B": {
			Ratio:                       nativeRate(0.03),
			CompletionRatio:             4,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "LiquidAI/LFM2.5-8B-A1B",
			Description:                 "Liquid Foundation Model 2.5, 8B/1B-active edge MoE reasoning model, $0.03/$0.12 per 1M.",
		},
		"Lykon/DreamShaper": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.0006291455999999999,
				DefaultSize:      "1024x1024",
				MinImages:        1,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1024x1536": 1.5,
					"1536x1024": 1.5,
					"1920x1080": 1.9775390625,
					"2048x2048": 4,
					"3840x2160": 7.91015625,
					"4096x4096": 16,
					"512x512":   0.25,
				},
			},
		},
		"MiniMaxAI/MiniMax-M2.5": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.06),
			ContextLength:               202752,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "fp4",
			HuggingFaceID:               "MiniMaxAI/MiniMax-M2",
			Description:                 "Earlier checkpoint of MiniMax M2 interleaved-thinking MoE.",
		},
		"MiniMaxAI/MiniMax-M2.7": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.06),
			ContextLength:               202752,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "fp4",
			HuggingFaceID:               "MiniMaxAI/MiniMax-M2",
			Description:                 "MiniMax M2 interleaved-thinking MoE (230B/10B active) for coding and agentic workflows.",
		},
		"MiniMaxAI/MiniMax-M3": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.06),
			ContextLength:               524288,
			MaxOutputTokens:             524288,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "fp8",
			HuggingFaceID:               "MiniMaxAI/MiniMax-M3",
			Description:                 "MiniMaxAI/MiniMax-M3 on togetherai; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Prism-ML/Ternary-Bonsai-27B": {
			Ratio:           0,
			CompletionRatio: 1,
			ContextLength:   262144,
			Description:     "Prism-ML/Ternary-Bonsai-27B on togetherai; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"RunDiffusion/Juggernaut-pro-flux": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.005138022399999999,
				DefaultSize:      "1024x1024",
				MinImages:        1,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1024x1536": 1.5,
					"1536x1024": 1.5,
					"1920x1080": 1.9775390625,
					"2048x2048": 4,
					"3840x2160": 7.91015625,
					"4096x4096": 16,
					"512x512":   0.25,
				},
			},
		},
		"Rundiffusion/Juggernaut-Lightning-Flux": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.0017825792,
				DefaultSize:      "1024x1024",
				MinImages:        1,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1024x1536": 1.5,
					"1536x1024": 1.5,
					"1920x1080": 1.9775390625,
					"2048x2048": 4,
					"3840x2160": 7.91015625,
					"4096x4096": 16,
					"512x512":   0.25,
				},
			},
		},
		"Wan-AI/Wan2.6-image": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.03145728,
				DefaultSize:      "1024x1024",
				MinImages:        1,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1024x1536": 1.5,
					"1536x1024": 1.5,
					"1920x1080": 1.9775390625,
					"2048x2048": 4,
					"3840x2160": 7.91015625,
					"4096x4096": 16,
					"512x512":   0.25,
				},
			},
		},
		"canopylabs/orpheus-3b-0.1-ft": {
			Ratio:           nativeRate(15),
			CompletionRatio: 1,
		},
		"cartesia/sonic": {
			Ratio:           nativeRate(65),
			CompletionRatio: 1,
		},
		"cartesia/sonic-2": {
			Ratio:           nativeRate(65),
			CompletionRatio: 1,
		},
		"cartesia/sonic-3": {
			Ratio:           nativeRate(65),
			CompletionRatio: 1,
		},
		"deepcogito/cogito-v2-1-671b": {
			Ratio:                       nativeRate(1.25),
			CompletionRatio:             1,
			ContextLength:               163840,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "deepcogito/cogito-v2-1-671b",
			Description:                 "Cogito v2.1 671B hybrid-reasoning model using IDA for optional extended thinking.",
		},
		"essentialai/rnj-1-instruct": {
			Ratio:                       nativeRate(0.15),
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "essentialai/rnj-1-instruct",
			Description:                 "Essential AI RNJ-1 instruction model in BF16 with 32K context and tool-calling.",
		},
		"hexgrad/Kokoro-82M": {
			Ratio:           nativeRate(1e+01),
			CompletionRatio: 1,
		},
		"ideogram/ideogram-3.0": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.06291456,
				DefaultSize:      "1024x1024",
				MinImages:        1,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1024x1536": 1.5,
					"1536x1024": 1.5,
					"1920x1080": 1.9775390625,
					"2048x2048": 4,
					"3840x2160": 7.91015625,
					"4096x4096": 16,
					"512x512":   0.25,
				},
			},
		},
		"ideogram/ideogram-4.0": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.06,
				DefaultSize:      "1024x1024",
				MinImages:        1,
			},
		},
		"intfloat/multilingual-e5-large-instruct": {
			Ratio:           nativeRate(0.02),
			CompletionRatio: 1,
			Embedding: &adaptor.EmbeddingPricingConfig{
				TextTokenRatio: nativeRate(0.02),
			},
		},
		"meta-llama/Llama-3.3-70B-Instruct-Turbo": {
			Ratio:                       nativeRate(1.04),
			CompletionRatio:             1,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "fp8",
			HuggingFaceID:               "meta-llama/Llama-3.3-70B-Instruct",
			Description:                 "meta-llama/Llama-3.3-70B-Instruct-Turbo on togetherai; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"meta-llama/Llama-Guard-4-12B": {
			Ratio:                       nativeRate(0.2),
			CompletionRatio:             1,
			ContextLength:               1048576,
			MaxOutputTokens:             1024,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "fp8",
			HuggingFaceID:               "meta-llama/Llama-Guard-4-12B",
			Description:                 "Meta Llama Guard 4 12B safety/classification model accepting text+image input with 1M context.",
		},
		"meta-llama/Meta-Llama-3-8B-Instruct-Lite": {
			Ratio:                       nativeRate(0.14),
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "meta-llama/Meta-Llama-3-8B-Instruct",
			Description:                 "Lightweight quantised variant of Meta Llama 3 8B for fast low-cost inference.",
		},
		"meta-models/Muse-Glimmer-30B": {
			Ratio:            nativeRate(0.35),
			CompletionRatio:  4.285714285714286,
			CachedInputRatio: nativeRate(0.04),
			ContextLength:    131072,
			Description:      "meta-models/Muse-Glimmer-30B on togetherai; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"moonshotai/Kimi-K2.5": {
			Ratio:                       nativeRate(0.5),
			CompletionRatio:             5.6,
			ContextLength:               262144,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "fp4",
			HuggingFaceID:               "moonshotai/Kimi-K2-Instruct",
			Description:                 "Kimi K2.5 agentic MoE (1T/32B active) with vision support and 262K context. (RETIRED 2026-05-21; use moonshotai/Kimi-K2.6)",
		},
		"moonshotai/Kimi-K2.6": {
			Ratio:                       nativeRate(1.2),
			CompletionRatio:             3.75,
			CachedInputRatio:            nativeRate(0.2),
			ContextLength:               262144,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "fp4",
			HuggingFaceID:               "moonshotai/Kimi-K2-Instruct",
			Description:                 "Kimi K2.6 agentic MoE (1T/32B active) with cached input pricing, optimised for tool use and SWE.",
		},
		"moonshotai/Kimi-K2.7-Code": {
			Ratio:                       nativeRate(0.95),
			CompletionRatio:             4.2105263157894735,
			CachedInputRatio:            nativeRate(0.19),
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			HuggingFaceID:               "moonshotai/Kimi-K2.7-Code",
			Description:                 "Moonshot Kimi K2.7 Code multimodal coding model, 256K context, $0.95/$4.00 per 1M.",
		},
		"moonshotai/Kimi-K3": {
			Ratio:             nativeRate(3),
			CompletionRatio:   5,
			CachedInputRatio:  nativeRate(0.3),
			ContextLength:     1048576,
			SupportedFeatures: []string{"tools", "json_mode", "structured_outputs"},
			Description:       "moonshotai/Kimi-K3 on togetherai; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"nvidia/nemotron-3-asr-streaming-0.6b": {
			Ratio:           0,
			CompletionRatio: 1,
			Audio: &adaptor.AudioPricingConfig{
				UsdPerSecond: 2.5e-05,
			},
		},
		"nvidia/nemotron-3-ultra-550b-a55b": {
			Ratio:                       nativeRate(0.6),
			CompletionRatio:             6,
			CachedInputRatio:            nativeRate(0.2),
			ContextLength:               512300,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			HuggingFaceID:               "nvidia/Nemotron-3-Ultra-550B-A55B",
			Description:                 "NVIDIA Nemotron-3 Ultra 550B A55B reasoning MoE, 512K context, $0.60/$3.60 per 1M.",
		},
		"nvidia/nemotron-3.5-asr-streaming-0.6b": {
			Ratio:           0,
			CompletionRatio: 1,
			Audio: &adaptor.AudioPricingConfig{
				UsdPerSecond: 2.5e-05,
			},
		},
		"nvidia/parakeet-tdt-0.6b-v3": {
			Ratio:           0,
			CompletionRatio: 1,
			Audio: &adaptor.AudioPricingConfig{
				UsdPerSecond: 2.5e-05,
			},
		},
		"openai/gpt-image-1.5": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.034,
				DefaultSize:      "1024x1024",
				MinImages:        1,
			},
		},
		"openai/gpt-image-2": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.053,
				DefaultSize:      "1024x1024",
				MinImages:        1,
			},
		},
		"openai/gpt-oss-120b": {
			Ratio:                       nativeRate(0.15),
			CompletionRatio:             4,
			ContextLength:               131072,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			SupportedReasoningEfforts:   []string{"low", "medium", "high"},
			DefaultReasoningEffort:      "medium",
			Quantization:                "fp4",
			HuggingFaceID:               "openai/gpt-oss-120b",
			Description:                 "openai/gpt-oss-120b on togetherai; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-oss-20b": {
			Ratio:                       nativeRate(0.05),
			CompletionRatio:             4,
			ContextLength:               128000,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			SupportedReasoningEfforts:   []string{"low", "medium", "high"},
			DefaultReasoningEffort:      "medium",
			Quantization:                "fp4",
			HuggingFaceID:               "openai/gpt-oss-20b",
			Description:                 "OpenAI gpt-oss-20b compact dense open-weight model with 128K context.",
		},
		"openai/whisper-large-v3": {
			Ratio:           0,
			CompletionRatio: 1,
			Audio: &adaptor.AudioPricingConfig{
				UsdPerSecond: 2.5e-05,
			},
		},
		"pearl-ai/gemma-4-31b-it": {
			Ratio:                       nativeRate(0.28),
			CompletionRatio:             3.0714285714285716,
			ContextLength:               32000,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "int8",
			HuggingFaceID:               "google/gemma-4-31b-it",
			Description:                 "Pearl AI checkpoint of Google Gemma 4 31B instruction model, $0.28/$0.86 per 1M.",
		},
		"stabilityai/stable-diffusion-3-medium": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.0019922944,
				DefaultSize:      "1024x1024",
				MinImages:        1,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1024x1536": 1.5,
					"1536x1024": 1.5,
					"1920x1080": 1.9775390625,
					"2048x2048": 4,
					"3840x2160": 7.91015625,
					"4096x4096": 16,
					"512x512":   0.25,
				},
			},
		},
		"stabilityai/stable-diffusion-xl-base-1.0": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.0019922944,
				DefaultSize:      "1024x1024",
				MinImages:        1,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1024x1536": 1.5,
					"1536x1024": 1.5,
					"1920x1080": 1.9775390625,
					"2048x2048": 4,
					"3840x2160": 7.91015625,
					"4096x4096": 16,
					"512x512":   0.25,
				},
			},
		},
		"thinkingmachines/Inkling": {
			Ratio:             nativeRate(1),
			CompletionRatio:   4.05,
			CachedInputRatio:  nativeRate(0.17),
			ContextLength:     524288,
			SupportedFeatures: []string{"tools", "json_mode", "structured_outputs"},
			Description:       "thinkingmachines/Inkling on togetherai; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"together/Tev1-4B-experimental": {
			Ratio:           nativeRate(0.042),
			CompletionRatio: 0,
			ContextLength:   32768,
			Description:     "together/Tev1-4B-experimental on togetherai; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"zai-org/GLM-5": {
			Ratio:                       nativeRate(1),
			CompletionRatio:             3.2,
			ContextLength:               202752,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "fp4",
			HuggingFaceID:               "zai-org/GLM-5",
			Description:                 "Z.ai GLM-5 hybrid-reasoning MoE (754B/40B active), state-of-the-art open-source agentic model. (RETIRED — not available on Together's Serverless API as of 2026-07-13; use zai-org/GLM-5.1 or zai-org/GLM-5.2)",
		},
		"zai-org/GLM-5.1": {
			Ratio:                       nativeRate(1.4),
			CompletionRatio:             3.142857142857143,
			CachedInputRatio:            nativeRate(0.26),
			ContextLength:               202752,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "fp4",
			HuggingFaceID:               "zai-org/GLM-5.1",
			Description:                 "Z.ai GLM-5.1 hybrid-reasoning MoE (754B/40B active) with strong agentic performance.",
		},
		"zai-org/GLM-5.2": {
			Ratio:                       nativeRate(1.4),
			CompletionRatio:             3.1428571428571432,
			CachedInputRatio:            nativeRate(0.26),
			ContextLength:               1048575,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "fp4",
			HuggingFaceID:               "zai-org/GLM-5.2",
			Description:                 "zai-org/GLM-5.2 on togetherai; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"zai-org/GLM-5.3": {
			Ratio:             nativeRate(1.4),
			CompletionRatio:   3.1428571428571432,
			CachedInputRatio:  nativeRate(0.26),
			ContextLength:     1048575,
			SupportedFeatures: []string{"tools", "json_mode", "structured_outputs"},
			Description:       "zai-org/GLM-5.3 on togetherai; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"zai-org/GLM-5.3-Flash": {
			Ratio:             nativeRate(0.15),
			CompletionRatio:   3.3333333333333335,
			CachedInputRatio:  nativeRate(0.03),
			ContextLength:     1048575,
			SupportedFeatures: []string{"tools", "json_mode", "structured_outputs"},
			Description:       "zai-org/GLM-5.3-Flash on togetherai; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
