package togetherai

import "github.com/Laisky/one-api/relay/adaptor"

// qwenModels returns the qwen model defaults for togetherai.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func qwenModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"Qwen/Qwen-Image": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.006081740799999999,
				DefaultSize:      "1024x1024",
				MinImages:        1,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1024x1536": 1.5,
					"1536x1024": 1.5,
					"1920x1080": 1.9775390625,
					"2048x2048": 4,
					"3840x2160": 7.91015625,
					"4096x4096": 16,
					"512x512":   0.25,
				},
			},
		},
		"Qwen/Qwen-Image-2.0": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.04,
				DefaultSize:      "1024x1024",
				MinImages:        1,
			},
		},
		"Qwen/Qwen-Image-2.0-Pro": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.08,
				DefaultSize:      "1024x1024",
				MinImages:        1,
			},
		},
		"Qwen/Qwen2.5-7B-Instruct-Turbo": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "fp8",
			HuggingFaceID:               "Qwen/Qwen2.5-7B-Instruct",
			Description:                 "FP8-quantised Qwen 2.5 7B instruction model with 32K context.",
		},
		"Qwen/Qwen3-235B-A22B-Instruct-2507-tput": {
			Ratio:                       nativeRate(0.2),
			CompletionRatio:             3,
			ContextLength:               262144,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "fp8",
			HuggingFaceID:               "Qwen/Qwen3-235B-A22B-Instruct",
			Description:                 "Throughput-optimised Qwen3 235B MoE instruct (July 2025 checkpoint), non-thinking mode.",
		},
		"Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             1,
			ContextLength:               256000,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "fp8",
			HuggingFaceID:               "Qwen/Qwen3-Coder-480B-A35B-Instruct",
			Description:                 "Qwen3 480B coding MoE (480B/35B active) in FP8, non-thinking mode, 256K context. (RETIRED 2026-06-04)",
		},
		"Qwen/Qwen3-Coder-Next-FP8": {
			Ratio:                       nativeRate(0.5),
			CompletionRatio:             2.4,
			ContextLength:               262144,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "fp8",
			Description:                 "Next-generation Qwen3 coding model in FP8 (architecture not yet published). (RETIRED 2026-05-14)",
		},
		"Qwen/Qwen3.5-397B-A17B": {
			Ratio:                       nativeRate(0.6),
			CompletionRatio:             6,
			CachedInputRatio:            nativeRate(0.35),
			ContextLength:               262144,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "fp4",
			HuggingFaceID:               "Qwen/Qwen3.5-397B-A17B",
			Description:                 "Qwen 3.5 397B vision-language MoE with 262K context and strong multilingual coding.",
		},
		"Qwen/Qwen3.5-9B": {
			Ratio:                       nativeRate(0.17),
			CompletionRatio:             1.4705882352941175,
			ContextLength:               262144,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "fp8",
			HuggingFaceID:               "Qwen/Qwen3.5-9B",
			Description:                 "Qwen/Qwen3.5-9B on togetherai; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3.6-Plus": {
			Ratio:                       nativeRate(0.5),
			CompletionRatio:             6,
			ContextLength:               1000000,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "fp8",
			HuggingFaceID:               "Qwen/Qwen3.6-Plus",
			Description:                 "Qwen/Qwen3.6-Plus on togetherai; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3.7-Max": {
			Ratio:                       nativeRate(1.5),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.5),
			ContextLength:               1000000,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "fp8",
			HuggingFaceID:               "Qwen/Qwen3.7-Max",
			Description:                 "Qwen/Qwen3.7-Max on togetherai; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3.7-Plus": {
			Ratio:                       nativeRate(0.32),
			CompletionRatio:             4,
			ContextLength:               1000000,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "fp8",
			HuggingFaceID:               "Qwen/Qwen3.7-Plus",
			Description:                 "Qwen/Qwen3.7-Plus on togetherai; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3.8-2.4T-A95B": {
			Ratio:            nativeRate(2),
			CompletionRatio:  3,
			CachedInputRatio: nativeRate(0.5),
			Description:      "Qwen/Qwen3.8-2.4T-A95B on togetherai; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3.8-Flash": {
			Ratio:           nativeRate(0.09),
			CompletionRatio: 3.1333333333333333,
			ContextLength:   1000000,
			Description:     "Qwen/Qwen3.8-Flash on togetherai; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
