package alibailian

import "github.com/Laisky/one-api/relay/adaptor"

// qwenModels returns the qwen model defaults for alibailian.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func qwenModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"qwen-coder-plus": {
			Ratio:                       nativeRate(3.5),
			CompletionRatio:             2,
			CachedInputRatio:            0.05142857142857143,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-Coder-32B-Instruct",
			Description:                 "qwen-coder-plus on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-coder-plus-latest": {
			Ratio:                       nativeRate(3.6),
			CompletionRatio:             2,
			CachedInputRatio:            0.05142857142857143,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-Coder-32B-Instruct",
			Description:                 "Qwen Coder Plus (latest alias) on Bailian.",
		},
		"qwen-coder-turbo": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.41200000000000003),
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-Coder-7B-Instruct",
			Description:                 "qwen-coder-turbo on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-coder-turbo-latest": {
			Ratio:                       nativeRate(2.06),
			CompletionRatio:             2.995,
			CachedInputRatio:            nativeRate(0.41200000000000003),
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-Coder-7B-Instruct",
			Description:                 "Qwen Coder Turbo (latest alias) on Bailian.",
		},
		"qwen-flash": {
			Ratio:            nativeRate(0.15),
			CompletionRatio:  10,
			CachedInputRatio: nativeRate(0.030000000000000002),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.6),
				CompletionRatio:     10,
				InputTokenThreshold: 128001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(1.2),
					CompletionRatio:     10,
					InputTokenThreshold: 256001,
				},
			},
			ContextLength:               1000000,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			Description:                 "qwen-flash on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-flash-2025-07-28": {
			Ratio:           nativeRate(0.15),
			CompletionRatio: 10,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.6),
				CompletionRatio:     10,
				InputTokenThreshold: 128001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(1.2),
					CompletionRatio:     10,
					InputTokenThreshold: 256001,
				},
			},
			Description: "qwen-flash-2025-07-28 on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-flash-character": {
			Ratio:           nativeRate(0.25),
			CompletionRatio: 6,
			Description:     "qwen-flash-character on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-flash-character-2026-02-26": {
			Ratio:           nativeRate(0.18),
			CompletionRatio: 8.333333333333334,
			Description:     "qwen-flash-character-2026-02-26 on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-long": {
			Ratio:                       nativeRate(0.5),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.1),
			ContextLength:               10000000,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			Description:                 "qwen-long on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-long-2025-01-25": {
			Ratio:           nativeRate(0.5),
			CompletionRatio: 4,
			Description:     "qwen-long-2025-01-25 on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-long-latest": {
			Ratio:           nativeRate(0.5),
			CompletionRatio: 4,
			Description:     "qwen-long-latest on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-math-plus": {
			Ratio:           nativeRate(4),
			CompletionRatio: 3,
			Description:     "qwen-math-plus on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-math-turbo": {
			Ratio:           nativeRate(2),
			CompletionRatio: 3,
			Description:     "qwen-math-turbo on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-max": {
			Ratio:                       nativeRate(2.4),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.48000000000000004),
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			Description:                 "qwen-max on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-mt-plus": {
			Ratio:                       nativeRate(1.86),
			CompletionRatio:             2.995,
			CachedInputRatio:            nativeRate(0.37200000000000005),
			ContextLength:               4096,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			Description:                 "Qwen MT Plus on Bailian: flagship machine-translation model.",
		},
		"qwen-mt-turbo": {
			Ratio:                       0.05142857142857143,
			CompletionRatio:             2.79,
			CachedInputRatio:            nativeRate(0.144),
			ContextLength:               4096,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			Description:                 "Qwen MT Turbo on Bailian: cost-efficient machine-translation model.",
		},
		"qwen-omni-turbo": {
			Ratio:                       nativeRate(0.4),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.08),
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			Description:                 "Qwen-Omni Turbo on Bailian: closed-weight multimodal tier (text I/O rate billed here).",
		},
		"qwen-plus": {
			Ratio:                       nativeRate(0.8),
			CompletionRatio:             2.5,
			CachedInputRatio:            nativeRate(0.16),
			ContextLength:               1000000,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			Description:                 "Qwen Plus on Bailian: balanced flagship chat tier with tiered 1M context (0-128K base tier billed here).",
		},
		"qwen-plus-2024-12-20": {
			Ratio:           nativeRate(0.8),
			CompletionRatio: 2.5,
			Description:     "qwen-plus-2024-12-20 on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-plus-2025-01-12": {
			Ratio:           nativeRate(0.8),
			CompletionRatio: 2.5,
			Description:     "qwen-plus-2025-01-12 on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-plus-2025-01-25": {
			Ratio:           nativeRate(0.8),
			CompletionRatio: 2.5,
			Description:     "qwen-plus-2025-01-25 on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-plus-character": {
			Ratio:           nativeRate(0.8),
			CompletionRatio: 2.5,
			Description:     "qwen-plus-character on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-turbo": {
			Ratio:                       nativeRate(0.31),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.062),
			ContextLength:               1000000,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-Turbo",
			Description:                 "Qwen Turbo on Bailian: cost-efficient chat tier with up to 1M context (deprecated; use qwen-flash).",
		},
		"qwen-vl-max": {
			Ratio:                       nativeRate(1.6),
			CompletionRatio:             2.5,
			CachedInputRatio:            nativeRate(0.32),
			ContextLength:               32000,
			MaxOutputTokens:             2000,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			Description:                 "qwen-vl-max on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-vl-ocr": {
			Ratio:                       nativeRate(5.15),
			CompletionRatio:             1,
			CachedInputRatio:            nativeRate(1.03),
			ContextLength:               34096,
			MaxOutputTokens:             4096,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			Description:                 "Qwen-VL OCR on Bailian: OCR-tuned multimodal tier (5.15 CNY/1M).",
		},
		"qwen-vl-plus": {
			Ratio:                       nativeRate(0.8),
			CompletionRatio:             2.5,
			CachedInputRatio:            nativeRate(0.164),
			ContextLength:               32000,
			MaxOutputTokens:             2000,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			Description:                 "qwen-vl-plus on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-coder-30b-a3b-instruct": {
			Ratio:           nativeRate(1.5),
			CompletionRatio: 4,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(2.25),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(3.75),
					CompletionRatio:     4,
					InputTokenThreshold: 128001,
				},
			},
			Description: "qwen3-coder-30b-a3b-instruct on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-coder-480b-a35b-instruct": {
			Ratio:           nativeRate(6),
			CompletionRatio: 4,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(9),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(15),
					CompletionRatio:     4,
					InputTokenThreshold: 128001,
				},
			},
			Description: "qwen3-coder-480b-a35b-instruct on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-coder-flash": {
			Ratio:            nativeRate(1),
			CompletionRatio:  4,
			CachedInputRatio: nativeRate(0.2),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1.5),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(2.5),
					CompletionRatio:     4,
					InputTokenThreshold: 128001,
				},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(5),
					CompletionRatio:     5,
					InputTokenThreshold: 256001,
				},
			},
			ContextLength:               1000000,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			Description:                 "qwen3-coder-flash on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-coder-flash-2025-07-28": {
			Ratio:           nativeRate(1),
			CompletionRatio: 4,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1.5),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(2.5),
					CompletionRatio:     4,
					InputTokenThreshold: 128001,
				},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(5),
					CompletionRatio:     5,
					InputTokenThreshold: 256001,
				},
			},
			Description: "qwen3-coder-flash-2025-07-28 on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-coder-next": {
			Ratio:            nativeRate(1),
			CompletionRatio:  4,
			CachedInputRatio: nativeRate(0.2),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1.5),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(2.5),
					CompletionRatio:     4,
					InputTokenThreshold: 128001,
				},
			},
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-Coder-Next",
			Description:                 "qwen3-coder-next on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-coder-plus": {
			Ratio:            nativeRate(4),
			CompletionRatio:  4,
			CachedInputRatio: nativeRate(0.8),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(6),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(1e+01),
					CompletionRatio:     4,
					InputTokenThreshold: 128001,
				},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(2e+01),
					CompletionRatio:     10,
					InputTokenThreshold: 256001,
				},
			},
			ContextLength:               1000000,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			Description:                 "qwen3-coder-plus on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-coder-plus-2025-07-22": {
			Ratio:           nativeRate(4),
			CompletionRatio: 4,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(6),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(1e+01),
					CompletionRatio:     4,
					InputTokenThreshold: 128001,
				},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(2e+01),
					CompletionRatio:     10,
					InputTokenThreshold: 256001,
				},
			},
			Description: "qwen3-coder-plus-2025-07-22 on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-coder-plus-2025-09-23": {
			Ratio:           nativeRate(4),
			CompletionRatio: 4,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(6),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(1e+01),
					CompletionRatio:     4,
					InputTokenThreshold: 128001,
				},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(2e+01),
					CompletionRatio:     10,
					InputTokenThreshold: 256001,
				},
			},
			Description: "qwen3-coder-plus-2025-09-23 on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-max": {
			Ratio:            nativeRate(2.5),
			CompletionRatio:  4,
			CachedInputRatio: nativeRate(0.5),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(4),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(7),
					CompletionRatio:     4,
					InputTokenThreshold: 128001,
				},
			},
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			Description:                 "qwen3-max on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-max-2025-09-23": {
			Ratio:           nativeRate(6),
			CompletionRatio: 4,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1e+01),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(15),
					CompletionRatio:     4,
					InputTokenThreshold: 128001,
				},
			},
			Description: "qwen3-max-2025-09-23 on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-max-2026-01-23": {
			Ratio:           nativeRate(2.5),
			CompletionRatio: 4,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(4),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(7),
					CompletionRatio:     4,
					InputTokenThreshold: 128001,
				},
			},
			Description: "qwen3-max-2026-01-23 on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-max-preview": {
			Ratio:           nativeRate(6),
			CompletionRatio: 4,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1e+01),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(15),
					CompletionRatio:     4,
					InputTokenThreshold: 128001,
				},
			},
			Description: "qwen3-max-preview on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-omni-flash": {
			Ratio:                       nativeRate(1.8),
			CompletionRatio:             3.8333,
			CachedInputRatio:            0.025714285714285714,
			ContextLength:               262144,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			Description:                 "Qwen3-Omni Flash on Bailian: closed-weight multimodal tier (text I/O rate billed here).",
		},
		"qwen3-vl-235b-a22b-instruct": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.4),
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-VL-235B-A22B-Instruct",
			Description:                 "qwen3-vl-235b-a22b-instruct on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-vl-235b-a22b-thinking": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             10,
			CachedInputRatio:            nativeRate(0.4),
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			MaxReasoningTokens:          38912,
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-VL-235B-A22B-Thinking",
			Description:                 "qwen3-vl-235b-a22b-thinking on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-vl-30b-a3b-instruct": {
			Ratio:                       nativeRate(0.75),
			CompletionRatio:             4,
			CachedInputRatio:            0.010714285714285714,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-VL-30B-A3B-Instruct",
			Description:                 "qwen3-vl-30b-a3b-instruct on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-vl-30b-a3b-thinking": {
			Ratio:                       nativeRate(0.75),
			CompletionRatio:             10,
			CachedInputRatio:            0.010714285714285714,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			MaxReasoningTokens:          38912,
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-VL-30B-A3B-Thinking",
			Description:                 "qwen3-vl-30b-a3b-thinking on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-vl-32b-instruct": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.4),
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-VL-32B-Instruct",
			Description:                 "qwen3-vl-32b-instruct on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-vl-32b-thinking": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             10,
			CachedInputRatio:            nativeRate(0.4),
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			MaxReasoningTokens:          38912,
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-VL-32B-Thinking",
			Description:                 "qwen3-vl-32b-thinking on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-vl-8b-instruct": {
			Ratio:                       nativeRate(0.5),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.1),
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-VL-8B-Instruct",
			Description:                 "qwen3-vl-8b-instruct on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-vl-8b-thinking": {
			Ratio:                       nativeRate(0.5),
			CompletionRatio:             10,
			CachedInputRatio:            nativeRate(0.1),
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			MaxReasoningTokens:          38912,
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-VL-8B-Thinking",
			Description:                 "qwen3-vl-8b-thinking on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-vl-flash": {
			Ratio:            nativeRate(0.15),
			CompletionRatio:  10,
			CachedInputRatio: nativeRate(0.030000000000000002),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.3),
				CompletionRatio:     10,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(0.6),
					CompletionRatio:     10,
					InputTokenThreshold: 128001,
				},
			},
			ContextLength:               262144,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			Description:                 "qwen3-vl-flash on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-vl-flash-2025-10-15": {
			Ratio:           nativeRate(0.15),
			CompletionRatio: 10,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.3),
				CompletionRatio:     10,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(0.6),
					CompletionRatio:     10,
					InputTokenThreshold: 128001,
				},
			},
			Description: "qwen3-vl-flash-2025-10-15 on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-vl-flash-2026-01-22": {
			Ratio:           nativeRate(0.15),
			CompletionRatio: 10,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.3),
				CompletionRatio:     10,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(0.6),
					CompletionRatio:     10,
					InputTokenThreshold: 128001,
				},
			},
			Description: "qwen3-vl-flash-2026-01-22 on alibailian; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
