// Code generated by scripts/model_catalog/refresh.py; DO NOT EDIT.
package alibailian

import (
	_ "embed"
	"github.com/Laisky/one-api/relay/adaptor"
	"github.com/Laisky/one-api/relay/adaptor/internal/catalogsnapshot"
)

// auditedCatalog20260924 contains only public defaults, not tenant configuration.
//
//go:embed catalog_20260924.json
var auditedCatalog20260924 []byte

// init applies the reviewed snapshot after legacy family initializers. It keeps
// omitted historic IDs and does not make network calls or enforce account tiers.
func init() {
	ModelRatios = catalogsnapshot.Apply(ModelRatios, auditedCatalog20260924)
	ModelList = adaptor.GetModelListFromPricing(ModelRatios)
}
