package baiduv2

import "github.com/Laisky/one-api/relay/adaptor"

// ernieModels returns the ernie model defaults for baiduv2.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func ernieModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"ERNIE-4.5-Turbo-128K-Preview": {
			Ratio:            nativeRate(0.8),
			CompletionRatio:  4,
			CachedInputRatio: nativeRate(0.2),
			Description:      "ERNIE-4.5-Turbo-128K-Preview on baiduv2; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"ERNIE-4.5-Turbo-20260402": {
			Ratio:            nativeRate(0.8),
			CompletionRatio:  4,
			CachedInputRatio: nativeRate(0.2),
			Description:      "ERNIE-4.5-Turbo-20260402 on baiduv2; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"ERNIE-4.5-Turbo-32K": {
			Ratio:            nativeRate(0.8),
			CompletionRatio:  4,
			CachedInputRatio: nativeRate(0.2),
			Description:      "ERNIE-4.5-Turbo-32K on baiduv2; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"ERNIE-4.5-Turbo-VL": {
			Ratio:            nativeRate(3),
			CompletionRatio:  3,
			CachedInputRatio: nativeRate(0.75),
			Description:      "ERNIE-4.5-Turbo-VL on baiduv2; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"ERNIE-4.5-Turbo-VL-32K": {
			Ratio:            nativeRate(3),
			CompletionRatio:  3,
			CachedInputRatio: nativeRate(0.75),
			Description:      "ERNIE-4.5-Turbo-VL-32K on baiduv2; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"ERNIE-5.0": {
			Ratio:           nativeRate(6),
			CompletionRatio: 4,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1e+01),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
			},
			Description: "ERNIE-5.0 on baiduv2; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"ERNIE-5.0-Thinking-Exp": {
			Ratio:           nativeRate(6),
			CompletionRatio: 4,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1e+01),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
			},
			Description: "ERNIE-5.0-Thinking-Exp on baiduv2; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"ERNIE-5.0-Thinking-Latest": {
			Ratio:           nativeRate(6),
			CompletionRatio: 4,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1e+01),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
			},
			Description: "ERNIE-5.0-Thinking-Latest on baiduv2; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"ERNIE-5.0-Thinking-Preview": {
			Ratio:           nativeRate(6),
			CompletionRatio: 4,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1e+01),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
			},
			Description: "ERNIE-5.0-Thinking-Preview on baiduv2; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"ERNIE-5.1": {
			Ratio:           nativeRate(4),
			CompletionRatio: 4.5,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(6),
				CompletionRatio:     3.6666666666666665,
				InputTokenThreshold: 32001,
			},
			},
			Description: "ERNIE-5.1 on baiduv2; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"ernie-3.5-128k": {
			Ratio:                       nativeRate(0.8),
			CompletionRatio:             2.5,
			CachedInputRatio:            nativeRate(0.32),
			ContextLength:               131072,
			MaxOutputTokens:             4096,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE 3.5 128K: long-context closed-weight general-purpose chat model.",
		},
		"ernie-3.5-8k": {
			Ratio:                       nativeRate(0.8),
			CompletionRatio:             2.5,
			CachedInputRatio:            nativeRate(0.32),
			ContextLength:               8192,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE 3.5 8K: closed-weight general-purpose chat model. Deprecated: retired 2026-06-30 (registered 2026-05-28), replacement ERNIE-4.5-Turbo-128K.",
		},
		"ernie-3.5-8k-preview": {
			Ratio:                       nativeRate(0.8),
			CompletionRatio:             2.5,
			CachedInputRatio:            nativeRate(0.32),
			ContextLength:               8192,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE 3.5 8K (preview): closed-weight general-purpose chat model.",
		},
		"ernie-4.0-8k": {
			Ratio:                       nativeRate(3e+01),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(12),
			ContextLength:               8192,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE 4.0 8K: closed-weight flagship chat model on Qianfan v2. Deprecated: retired 2026-06-30 (registered 2026-05-28), replacement ERNIE-4.5-Turbo-128K.",
		},
		"ernie-4.0-8k-latest": {
			Ratio:                       nativeRate(3e+01),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(12),
			ContextLength:               8192,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE 4.0 8K (latest alias): closed-weight flagship chat model on Qianfan v2.",
		},
		"ernie-4.0-8k-preview": {
			Ratio:                       nativeRate(3e+01),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(12),
			ContextLength:               8192,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE 4.0 8K (preview): closed-weight flagship chat model on Qianfan v2.",
		},
		"ernie-4.0-turbo-128k": {
			Ratio:                       1.4285714285714286,
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(8),
			ContextLength:               131072,
			MaxOutputTokens:             4096,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE 4.0 Turbo 128K: long-context closed-weight balanced-cost chat model. Deprecated: retired 2026-06-30 (registered 2026-05-28), replacement ERNIE-4.5-Turbo-128K.",
		},
		"ernie-4.0-turbo-8k": {
			Ratio:                       1.4285714285714286,
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(8),
			ContextLength:               8192,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE 4.0 Turbo 8K: closed-weight balanced-cost chat model. Deprecated: retired 2026-06-30 (registered 2026-05-28), replacement ERNIE-4.5-Turbo-128K.",
		},
		"ernie-4.0-turbo-8k-latest": {
			Ratio:                       1.4285714285714286,
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(8),
			ContextLength:               8192,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE 4.0 Turbo 8K (latest alias): closed-weight balanced-cost chat model.",
		},
		"ernie-4.0-turbo-8k-preview": {
			Ratio:                       1.4285714285714286,
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(8),
			ContextLength:               8192,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE 4.0 Turbo 8K (preview): closed-weight balanced-cost chat model.",
		},
		"ernie-4.5": {
			Ratio:                       nativeRate(4),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(1.6),
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE 4.5: closed-weight flagship chat model on Qianfan v2 (text-only). Deprecated: ERNIE-4.5-8K-Preview registered 2026-05-28, retirement date 2026-06-30 (past retirement as of 2026-07-13), replacement ERNIE-4.5-Turbo-128K.",
		},
		"ernie-4.5-turbo-128k": {
			Ratio:                       nativeRate(0.8),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.2),
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE 4.5 Turbo 128K: long-context closed-weight balanced-cost chat model.",
		},
		"ernie-4.5-turbo-32k": {
			Ratio:                       nativeRate(0.8),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.2),
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE 4.5 Turbo 32K: closed-weight balanced-cost chat model priced at 20% of ERNIE 4.5.",
		},
		"ernie-4.5-turbo-vl": {
			Ratio:                       nativeRate(3),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.75),
			ContextLength:               131072,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE 4.5 Turbo VL: closed-weight multimodal chat model accepting text and image inputs.",
		},
		"ernie-5.0": {
			Ratio:           nativeRate(6),
			CompletionRatio: 4,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               0.7142857142857143,
				CompletionRatio:     4,
				InputTokenThreshold: 32768,
			},
			},
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image", "audio", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE 5.0 native omni-modal flagship (released 2026-05-09) with text+image+audio+video input on Qianfan v2 API; 128K context.",
		},
		"ernie-5.1": {
			Ratio:           nativeRate(4),
			CompletionRatio: 4.5,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(6),
				CompletionRatio:     3.6666666666666665,
				InputTokenThreshold: 32768,
			},
			},
			ContextLength:               131072,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			MaxReasoningTokens:          61440,
			Description:                 "Baidu ERNIE 5.1 next-generation text chat model (released 2026-05-09) on Qianfan v2 API; 128K context.",
		},
		"ernie-char-8k": {
			Ratio:                       2.857142857142857,
			CompletionRatio:             1,
			CachedInputRatio:            nativeRate(16),
			ContextLength:               8192,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE Character 8K: closed-weight role-play / persona chat model. Deprecated: already retired (已退役) effective 2026-06-09 (registered 2026-05-28); no replacement listed.",
		},
		"ernie-char-fiction-8k": {
			Ratio:                       2.857142857142857,
			CompletionRatio:             1,
			CachedInputRatio:            nativeRate(16),
			ContextLength:               8192,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE Character Fiction 8K: closed-weight model tuned for fictional persona dialogue. Deprecated: retired 2025-12-23 (registered 2025-11-21), replacement DeepSeek-V3.1.",
		},
		"ernie-lite-8k": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE Lite 8K: cost-efficient closed-weight chat tier on Qianfan v2. Deprecated: already retired (已退役) effective 2026-06-09 (registered 2026-05-28); briefly delisted 2026-01-27 (then replacement ERNIE-Lite-Pro-128K/DeepSeek-V3) before final retirement.",
		},
		"ernie-lite-pro-128k": {
			Ratio:                       nativeRate(0.2),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.08),
			ContextLength:               131072,
			MaxOutputTokens:             4096,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE Lite Pro 128K: long-context cost-efficient closed-weight chat tier. Deprecated: retired 2026-06-30 (registered 2026-05-28), replacement ERNIE-4.5-Turbo-128K.",
		},
		"ernie-novel-8k": {
			Ratio:                       2.857142857142857,
			CompletionRatio:             1,
			CachedInputRatio:            nativeRate(16),
			ContextLength:               8192,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE Novel 8K: closed-weight model specialized for long-form fiction continuation. Deprecated: already retired (已退役) effective 2026-06-09 (registered 2026-05-28; an earlier dated snapshot also retired 2025-12-11).",
		},
		"ernie-speed-128k": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               131072,
			MaxOutputTokens:             4096,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE Speed 128K: long-context throughput-optimized closed-weight chat tier. Deprecated: already retired (已退役) effective 2026-06-09 (registered 2026-05-28; a third-party notice also cites a 2026-01-27 delisting).",
		},
		"ernie-speed-8k": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE Speed 8K: throughput-optimized closed-weight chat tier on Qianfan v2. Deprecated: already retired (已退役) effective 2026-06-09 (registered 2026-05-28).",
		},
		"ernie-speed-pro-128k": {
			Ratio:                       0.02142857142857143,
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.12000000000000001),
			ContextLength:               131072,
			MaxOutputTokens:             4096,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE Speed Pro 128K: enhanced throughput-optimized closed-weight chat tier. Deprecated: retired 2026-06-30 (registered 2026-05-28; ERNIE-Speed-Pro-8K retires the same day), replacement ERNIE-4.5-Turbo-128K.",
		},
		"ernie-tiny-8k": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE Tiny 8K: ultra low-cost closed-weight chat tier on Qianfan v2. Deprecated: already retired (已退役) effective 2026-06-09 (registered 2026-05-28; an earlier dated snapshot retired 2026-01-27, then replacement DeepSeek-V3/ERNIE-4.5-Turbo-32K).",
		},
		"ernie-x1": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.8),
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE X1: closed-weight deep-thinking reasoning chat model on Qianfan v2.",
		},
		"ernie-x1-turbo": {
			Ratio:                       nativeRate(1),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.4),
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE X1 Turbo: closed-weight reasoning chat model priced at half of ERNIE X1. Deprecated: ERNIE-X1-Turbo-32K/-32K-Preview/-Preview/-Latest retired 2026-06-30 (registered 2026-05-28), replacement ERNIE-4.5-Turbo-128K.",
		},
		"ernie-x1.1": {
			Ratio:                       nativeRate(1),
			CompletionRatio:             4,
			ContextLength:               65536,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Baidu ERNIE X1.1 improved deep-reasoning model on Qianfan v2 API; 64K context.",
		},
	}
}
