package baiduv2

import "github.com/Laisky/one-api/relay/adaptor"

// deepseekModels returns the deepseek model defaults for baiduv2.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func deepseekModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"DeepSeek-V4-Pro-0813": {
			Ratio:            nativeRate(4.5),
			CompletionRatio:  3,
			CachedInputRatio: nativeRate(0.15),
			TimeWindows: []adaptor.TimeWindow{adaptor.TimeWindow{
				Name:     "qianfan-holiday-peak",
				TimeZone: "Asia/Shanghai",
				Ranges: []adaptor.ClockRange{adaptor.ClockRange{
					Start: "08:00",
					End:   "22:00",
				},
				},
				DateFrom: "2026-09-24",
				DateTo:   "2026-10-08",
				Overlay: adaptor.ModelConfig{
					Ratio:            nativeRate(5.4),
					CompletionRatio:  2.9999999999999996,
					CachedInputRatio: nativeRate(0.18000000000000002),
				},
			},
				adaptor.TimeWindow{
					Name:     "qianfan-holiday-offpeak",
					TimeZone: "Asia/Shanghai",
					Ranges: []adaptor.ClockRange{adaptor.ClockRange{
						Start: "22:00",
						End:   "08:00",
					},
					},
					DateFrom: "2026-09-24",
					DateTo:   "2026-10-08",
					Overlay: adaptor.ModelConfig{
						Ratio:            nativeRate(2.7),
						CompletionRatio:  2.9999999999999996,
						CachedInputRatio: nativeRate(0.09000000000000001),
					},
				},
				adaptor.TimeWindow{
					Name:     "qianfan-peak",
					TimeZone: "Asia/Shanghai",
					Ranges: []adaptor.ClockRange{adaptor.ClockRange{
						Start: "08:00",
						End:   "22:00",
					},
					},
					Overlay: adaptor.ModelConfig{
						Ratio:            nativeRate(9),
						CompletionRatio:  3,
						CachedInputRatio: nativeRate(0.3),
					},
				},
			},
			Description: "DeepSeek-V4-Pro-0813 on baiduv2; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"DeepSeek-V4.1-Flash": {
			Ratio:            nativeRate(1),
			CompletionRatio:  4,
			CachedInputRatio: nativeRate(0.02),
			TimeWindows: []adaptor.TimeWindow{adaptor.TimeWindow{
				Name:     "qianfan-holiday-peak",
				TimeZone: "Asia/Shanghai",
				Ranges: []adaptor.ClockRange{adaptor.ClockRange{
					Start: "08:00",
					End:   "22:00",
				},
				},
				DateFrom: "2026-09-24",
				DateTo:   "2026-10-08",
				Overlay: adaptor.ModelConfig{
					Ratio:            nativeRate(1.2),
					CompletionRatio:  4,
					CachedInputRatio: nativeRate(0.024),
				},
			},
				adaptor.TimeWindow{
					Name:     "qianfan-holiday-offpeak",
					TimeZone: "Asia/Shanghai",
					Ranges: []adaptor.ClockRange{adaptor.ClockRange{
						Start: "22:00",
						End:   "08:00",
					},
					},
					DateFrom: "2026-09-24",
					DateTo:   "2026-10-08",
					Overlay: adaptor.ModelConfig{
						Ratio:            nativeRate(0.6),
						CompletionRatio:  4,
						CachedInputRatio: nativeRate(0.012),
					},
				},
				adaptor.TimeWindow{
					Name:     "qianfan-peak",
					TimeZone: "Asia/Shanghai",
					Ranges: []adaptor.ClockRange{adaptor.ClockRange{
						Start: "08:00",
						End:   "22:00",
					},
					},
					Overlay: adaptor.ModelConfig{
						Ratio:            nativeRate(2),
						CompletionRatio:  4,
						CachedInputRatio: nativeRate(0.04),
					},
				},
			},
			Description: "DeepSeek-V4.1-Flash on baiduv2; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek-r1": {
			Ratio:                       nativeRate(4),
			CompletionRatio:             4,
			ContextLength:               65536,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			MaxReasoningTokens:          32768,
			Quantization:                "fp8",
			HuggingFaceID:               "deepseek-ai/DeepSeek-R1",
			Description:                 "DeepSeek R1 hosted on Baidu Qianfan v2: open-weight reasoning chat model (thinking mode). Deprecated: retired 2026-06-30 (registered 2026-05-26, R1-250528 build; earlier R1-250120 build retired 2026-04-28), replacements DeepSeek-V4-Pro/DeepSeek-V4-Flash/DeepSeek-V3.2.",
		},
		"deepseek-r1-distill-qwen-14b": {
			Ratio:                       nativeRate(3),
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			MaxReasoningTokens:          32768,
			Quantization:                "bf16",
			HuggingFaceID:               "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B",
			Description:                 "DeepSeek R1 distilled into Qwen-14B, hosted on Baidu Qianfan v2. Deprecated: retired 2026-07-02 (registered 2026-06-11), replacements DeepSeek-V4-Pro/DeepSeek-V4-Flash.",
		},
		"deepseek-r1-distill-qwen-32b": {
			Ratio:                       nativeRate(4),
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			MaxReasoningTokens:          32768,
			Quantization:                "bf16",
			HuggingFaceID:               "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
			Description:                 "DeepSeek R1 distilled into Qwen-32B, hosted on Baidu Qianfan v2. Deprecated: retired 2026-07-02 (registered 2026-06-11), replacements DeepSeek-V4-Pro/DeepSeek-V4-Flash.",
		},
		"deepseek-v3": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             4,
			ContextLength:               65536,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "fp8",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V3",
			Description:                 "DeepSeek V3 hosted on Baidu Qianfan v2: open-weight MoE chat model (non-thinking mode). Deprecated: retired 2026-06-30 (registered 2026-05-26), replacements DeepSeek-V4-Pro/DeepSeek-V4-Flash/DeepSeek-V3.2.",
		},
		"deepseek-v3.2": {
			Ratio:            nativeRate(2),
			CompletionRatio:  1.5,
			CachedInputRatio: nativeRate(0.4),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(4),
				CompletionRatio:     1.5,
				CachedInputRatio:    nativeRate(0.4),
				InputTokenThreshold: 32768,
			},
			},
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "fp8",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V3.2",
			Description:                 "DeepSeek V3.2 hosted on Baidu Qianfan v2: open-weight MoE chat model; recommended replacement for retiring DeepSeek-V3/DeepSeek-R1. 128K context with tiered pricing.",
		},
		"deepseek-v4-flash": {
			Ratio:                       nativeRate(1),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.2),
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "fp8",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V4",
			Description:                 "DeepSeek V4 Flash hosted on Baidu Qianfan v2: open-weight cost-efficient chat model; replacement for retiring DeepSeek/ERNIE tiers.",
		},
		"deepseek-v4-pro": {
			Ratio:                       nativeRate(12),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(1),
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "fp8",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V4",
			Description:                 "DeepSeek V4 Pro hosted on Baidu Qianfan v2: open-weight flagship chat model; primary replacement for many retiring ERNIE/DeepSeek models.",
		},
	}
}
