package openrouter

import (
	"github.com/Laisky/one-api/relay/adaptor"
	"github.com/Laisky/one-api/relay/billing/ratio"
)

// openRouterModelConfig converts OpenRouter's published per-1M token prices into one-api's billing fields.
// inputPerMillion and outputPerMillion are USD prices per 1M tokens, cachedInputPerMillion is the cache-read price,
// and cacheWritePerMillion is OpenRouter's single published cache-write price, which one-api stores in CacheWrite5mRatio.
func openRouterModelConfig(inputPerMillion, outputPerMillion, cachedInputPerMillion, cacheWritePerMillion float64) adaptor.ModelConfig {
	cfg := adaptor.ModelConfig{
		Ratio:           inputPerMillion * ratio.MilliTokensUsd,
		CompletionRatio: 1,
	}
	if inputPerMillion > 0 && outputPerMillion > 0 {
		cfg.CompletionRatio = outputPerMillion / inputPerMillion
	}
	if cachedInputPerMillion != 0 {
		cfg.CachedInputRatio = cachedInputPerMillion * ratio.MilliTokensUsd
	}
	if cacheWritePerMillion != 0 {
		cfg.CacheWrite5mRatio = cacheWritePerMillion * ratio.MilliTokensUsd
	}

	return cfg
}

// ModelRatios defines the OpenRouter model pricing snapshot derived from the official models API.
// Source: https://openrouter.ai/api/v1/models (retrieved 2026-04-28).
// Rows whose official API still reports negative placeholder token prices are intentionally excluded:
// openrouter/auto, openrouter/bodybuilder, and openrouter/pareto-code.
var ModelRatios = map[string]adaptor.ModelConfig{
	"ai21/jamba-large-1.7":                                          openRouterModelConfig(2, 8, 0, 0),
	"aion-labs/aion-1.0":                                            openRouterModelConfig(4, 8, 0, 0),
	"aion-labs/aion-1.0-mini":                                       openRouterModelConfig(0.7, 1.4, 0, 0),
	"aion-labs/aion-2.0":                                            openRouterModelConfig(0.8, 1.6, 0.2, 0),
	"aion-labs/aion-rp-llama-3.1-8b":                                openRouterModelConfig(0.8, 1.6, 0, 0),
	"alfredpros/codellama-7b-instruct-solidity":                     openRouterModelConfig(0.8, 1.2, 0, 0),
	"alibaba/tongyi-deepresearch-30b-a3b":                           openRouterModelConfig(0.09, 0.45, 0.09, 0),
	"allenai/olmo-3-32b-think":                                      openRouterModelConfig(0.15, 0.5, 0, 0),
	"allenai/olmo-3.1-32b-instruct":                                 openRouterModelConfig(0.2, 0.6, 0, 0),
	"alpindale/goliath-120b":                                        openRouterModelConfig(3.75, 7.5, 0, 0),
	"amazon/nova-2-lite-v1":                                         openRouterModelConfig(0.3, 2.5, 0, 0),
	"amazon/nova-lite-v1":                                           openRouterModelConfig(0.06, 0.24, 0, 0),
	"amazon/nova-micro-v1":                                          openRouterModelConfig(0.035, 0.14, 0, 0),
	"amazon/nova-premier-v1":                                        openRouterModelConfig(2.5, 12.5, 0.625, 0),
	"amazon/nova-pro-v1":                                            openRouterModelConfig(0.8, 3.2, 0, 0),
	"anthracite-org/magnum-v4-72b":                                  openRouterModelConfig(3, 5, 0, 0),
	"anthropic/claude-3-haiku":                                      openRouterModelConfig(0.25, 1.25, 0.03, 0.3),
	"anthropic/claude-3.5-haiku":                                    openRouterModelConfig(0.8, 4, 0.08, 1),
	"anthropic/claude-3.7-sonnet":                                   openRouterModelConfig(3, 15, 0.3, 3.75),
	"anthropic/claude-3.7-sonnet:thinking":                          openRouterModelConfig(3, 15, 0.3, 3.75),
	"anthropic/claude-haiku-4.5":                                    openRouterModelConfig(1, 5, 0.1, 1.25),
	"anthropic/claude-opus-4":                                       openRouterModelConfig(15, 75, 1.5, 18.75),
	"anthropic/claude-opus-4.1":                                     openRouterModelConfig(15, 75, 1.5, 18.75),
	"anthropic/claude-opus-4.5":                                     openRouterModelConfig(5, 25, 0.5, 6.25),
	"anthropic/claude-opus-4.6":                                     openRouterModelConfig(5, 25, 0.5, 6.25),
	"anthropic/claude-opus-4.6-fast":                                openRouterModelConfig(30, 150, 3, 37.5),
	"anthropic/claude-opus-4.7":                                     openRouterModelConfig(5, 25, 0.5, 6.25),
	"anthropic/claude-sonnet-4":                                     openRouterModelConfig(3, 15, 0.3, 3.75),
	"anthropic/claude-sonnet-4.5":                                   openRouterModelConfig(3, 15, 0.3, 3.75),
	"anthropic/claude-sonnet-4.6":                                   openRouterModelConfig(3, 15, 0.3, 3.75),
	"arcee-ai/coder-large":                                          openRouterModelConfig(0.5, 0.8, 0, 0),
	"arcee-ai/maestro-reasoning":                                    openRouterModelConfig(0.9, 3.3, 0, 0),
	"arcee-ai/spotlight":                                            openRouterModelConfig(0.18, 0.18, 0, 0),
	"arcee-ai/trinity-large-preview":                                openRouterModelConfig(0.15, 0.45, 0, 0),
	"arcee-ai/trinity-large-thinking":                               openRouterModelConfig(0.22, 0.85, 0.06, 0),
	"arcee-ai/trinity-mini":                                         openRouterModelConfig(0.045, 0.15, 0, 0),
	"arcee-ai/virtuoso-large":                                       openRouterModelConfig(0.75, 1.2, 0, 0),
	"baidu/ernie-4.5-21b-a3b":                                       openRouterModelConfig(0.07, 0.28, 0, 0),
	"baidu/ernie-4.5-21b-a3b-thinking":                              openRouterModelConfig(0.07, 0.28, 0, 0),
	"baidu/ernie-4.5-300b-a47b":                                     openRouterModelConfig(0.28, 1.1, 0, 0),
	"baidu/ernie-4.5-vl-28b-a3b":                                    openRouterModelConfig(0.14, 0.56, 0, 0),
	"baidu/ernie-4.5-vl-424b-a47b":                                  openRouterModelConfig(0.42, 1.25, 0, 0),
	"baidu/qianfan-ocr-fast:free":                                   openRouterModelConfig(0, 0, 0, 0),
	"bytedance-seed/seed-1.6":                                       openRouterModelConfig(0.25, 2, 0, 0),
	"bytedance-seed/seed-1.6-flash":                                 openRouterModelConfig(0.075, 0.3, 0, 0),
	"bytedance-seed/seed-2.0-lite":                                  openRouterModelConfig(0.25, 2, 0, 0),
	"bytedance-seed/seed-2.0-mini":                                  openRouterModelConfig(0.1, 0.4, 0, 0),
	"bytedance/ui-tars-1.5-7b":                                      openRouterModelConfig(0.1, 0.2, 0.1, 0),
	"cognitivecomputations/dolphin-mistral-24b-venice-edition:free": openRouterModelConfig(0, 0, 0, 0),
	"cohere/command-a":                                              openRouterModelConfig(2.5, 10, 0, 0),
	"cohere/command-r-08-2024":                                      openRouterModelConfig(0.15, 0.6, 0, 0),
	"cohere/command-r-plus-08-2024":                                 openRouterModelConfig(2.5, 10, 0, 0),
	"cohere/command-r7b-12-2024":                                    openRouterModelConfig(0.0375, 0.15, 0, 0),
	"deepcogito/cogito-v2.1-671b":                                   openRouterModelConfig(1.25, 1.25, 0, 0),
	"deepseek/deepseek-chat":                                        openRouterModelConfig(0.32, 0.89, 0, 0),
	"deepseek/deepseek-chat-v3-0324":                                openRouterModelConfig(0.2, 0.77, 0.135, 0),
	"deepseek/deepseek-chat-v3.1":                                   openRouterModelConfig(0.15, 0.75, 0, 0),
	"deepseek/deepseek-r1":                                          openRouterModelConfig(0.7, 2.5, 0, 0),
	"deepseek/deepseek-r1-0528":                                     openRouterModelConfig(0.5, 2.15, 0.35, 0),
	"deepseek/deepseek-r1-distill-llama-70b":                        openRouterModelConfig(0.7, 0.8, 0, 0),
	"deepseek/deepseek-r1-distill-qwen-32b":                         openRouterModelConfig(0.29, 0.29, 0, 0),
	"deepseek/deepseek-v3.1-terminus":                               openRouterModelConfig(0.21, 0.79, 0.13, 0),
	"deepseek/deepseek-v3.2":                                        openRouterModelConfig(0.252, 0.378, 0.0252, 0),
	"deepseek/deepseek-v3.2-exp":                                    openRouterModelConfig(0.27, 0.41, 0, 0),
	"deepseek/deepseek-v3.2-speciale":                               openRouterModelConfig(0.4, 1.2, 0.2, 0),
	"deepseek/deepseek-v4-flash":                                    openRouterModelConfig(0.14, 0.28, 0.0028, 0),
	"deepseek/deepseek-v4-pro":                                      openRouterModelConfig(0.435, 0.87, 0.003625, 0),
	"essentialai/rnj-1-instruct":                                    openRouterModelConfig(0.15, 0.15, 0, 0),
	"google/gemini-2.0-flash-001":                                   openRouterModelConfig(0.1, 0.4, 0.025, 0.083333333333),
	"google/gemini-2.0-flash-lite-001":                              openRouterModelConfig(0.075, 0.3, 0, 0),
	"google/gemini-2.5-flash":                                       openRouterModelConfig(0.3, 2.5, 0.03, 0.083333333333),
	"google/gemini-2.5-flash-image":                                 openRouterModelConfig(0.3, 2.5, 0.03, 0.083333333333),
	"google/gemini-2.5-flash-lite":                                  openRouterModelConfig(0.1, 0.4, 0.01, 0.083333333333),
	"google/gemini-2.5-flash-lite-preview-09-2025":                  openRouterModelConfig(0.1, 0.4, 0.01, 0.083333333333),
	"google/gemini-2.5-pro":                                         openRouterModelConfig(1.25, 10, 0.125, 0.375),
	"google/gemini-2.5-pro-preview":                                 openRouterModelConfig(1.25, 10, 0.125, 0.375),
	"google/gemini-2.5-pro-preview-05-06":                           openRouterModelConfig(1.25, 10, 0.125, 0.375),
	"google/gemini-3-flash-preview":                                 openRouterModelConfig(0.5, 3, 0.05, 0.083333333333),
	"google/gemini-3-pro-image-preview":                             openRouterModelConfig(2, 12, 0.2, 0.375),
	"google/gemini-3.1-flash-image-preview":                         openRouterModelConfig(0.5, 3, 0, 0),
	"google/gemini-3.1-flash-lite-preview":                          openRouterModelConfig(0.25, 1.5, 0.025, 0.083333333333),
	"google/gemini-3.1-pro-preview":                                 openRouterModelConfig(2, 12, 0.2, 0.375),
	"google/gemini-3.1-pro-preview-customtools":                     openRouterModelConfig(2, 12, 0.2, 0.375),
	"google/gemma-2-27b-it":                                         openRouterModelConfig(0.65, 0.65, 0, 0),
	"google/gemma-3-12b-it":                                         openRouterModelConfig(0.04, 0.13, 0, 0),
	"google/gemma-3-12b-it:free":                                    openRouterModelConfig(0, 0, 0, 0),
	"google/gemma-3-27b-it":                                         openRouterModelConfig(0.08, 0.16, 0, 0),
	"google/gemma-3-27b-it:free":                                    openRouterModelConfig(0, 0, 0, 0),
	"google/gemma-3-4b-it":                                          openRouterModelConfig(0.04, 0.08, 0, 0),
	"google/gemma-3-4b-it:free":                                     openRouterModelConfig(0, 0, 0, 0),
	"google/gemma-3n-e2b-it:free":                                   openRouterModelConfig(0, 0, 0, 0),
	"google/gemma-3n-e4b-it":                                        openRouterModelConfig(0.06, 0.12, 0, 0),
	"google/gemma-3n-e4b-it:free":                                   openRouterModelConfig(0, 0, 0, 0),
	"google/gemma-4-26b-a4b-it":                                     openRouterModelConfig(0.06, 0.33, 0, 0),
	"google/gemma-4-26b-a4b-it:free":                                openRouterModelConfig(0, 0, 0, 0),
	"google/gemma-4-31b-it":                                         openRouterModelConfig(0.13, 0.38, 0, 0),
	"google/gemma-4-31b-it:free":                                    openRouterModelConfig(0, 0, 0, 0),
	"google/lyria-3-clip-preview":                                   openRouterModelConfig(0, 0, 0, 0),
	"google/lyria-3-pro-preview":                                    openRouterModelConfig(0, 0, 0, 0),
	"gryphe/mythomax-l2-13b":                                        openRouterModelConfig(0.06, 0.06, 0, 0),
	"ibm-granite/granite-4.0-h-micro":                               openRouterModelConfig(0.017, 0.11, 0, 0),
	"inception/mercury-2":                                           openRouterModelConfig(0.25, 0.75, 0.025, 0),
	"inclusionai/ling-2.6-1t:free":                                  openRouterModelConfig(0, 0, 0, 0),
	"inclusionai/ling-2.6-flash":                                    openRouterModelConfig(0.08, 0.24, 0.016, 0),
	"inclusionai/ling-2.6-flash:free":                               openRouterModelConfig(0, 0, 0, 0),
	"inflection/inflection-3-pi":                                    openRouterModelConfig(2.5, 10, 0, 0),
	"inflection/inflection-3-productivity":                          openRouterModelConfig(2.5, 10, 0, 0),
	"kwaipilot/kat-coder-pro-v2":                                    openRouterModelConfig(0.3, 1.2, 0.06, 0),
	"liquid/lfm-2-24b-a2b":                                          openRouterModelConfig(0.03, 0.12, 0, 0),
	"liquid/lfm-2.5-1.2b-instruct:free":                             openRouterModelConfig(0, 0, 0, 0),
	"liquid/lfm-2.5-1.2b-thinking:free":                             openRouterModelConfig(0, 0, 0, 0),
	"mancer/weaver":                                                 openRouterModelConfig(0.75, 1, 0, 0),
	"meta-llama/llama-3-70b-instruct":                               openRouterModelConfig(0.51, 0.74, 0, 0),
	"meta-llama/llama-3-8b-instruct":                                openRouterModelConfig(0.03, 0.04, 0, 0),
	"meta-llama/llama-3.1-70b-instruct":                             openRouterModelConfig(0.4, 0.4, 0, 0),
	"meta-llama/llama-3.1-8b-instruct":                              openRouterModelConfig(0.02, 0.05, 0, 0),
	"meta-llama/llama-3.2-11b-vision-instruct":                      openRouterModelConfig(0.245, 0.245, 0, 0),
	"meta-llama/llama-3.2-1b-instruct":                              openRouterModelConfig(0.027, 0.2, 0, 0),
	"meta-llama/llama-3.2-3b-instruct":                              openRouterModelConfig(0.051, 0.34, 0, 0),
	"meta-llama/llama-3.2-3b-instruct:free":                         openRouterModelConfig(0, 0, 0, 0),
	"meta-llama/llama-3.3-70b-instruct":                             openRouterModelConfig(0.1, 0.32, 0, 0),
	"meta-llama/llama-3.3-70b-instruct:free":                        openRouterModelConfig(0, 0, 0, 0),
	"meta-llama/llama-4-maverick":                                   openRouterModelConfig(0.15, 0.6, 0, 0),
	"meta-llama/llama-4-scout":                                      openRouterModelConfig(0.08, 0.3, 0, 0),
	"meta-llama/llama-guard-3-8b":                                   openRouterModelConfig(0.48, 0.03, 0, 0),
	"meta-llama/llama-guard-4-12b":                                  openRouterModelConfig(0.18, 0.18, 0, 0),
	"microsoft/phi-4":                                               openRouterModelConfig(0.065, 0.14, 0, 0),
	"microsoft/wizardlm-2-8x22b":                                    openRouterModelConfig(0.62, 0.62, 0, 0),
	"minimax/minimax-01":                                            openRouterModelConfig(0.2, 1.1, 0, 0),
	"minimax/minimax-m1":                                            openRouterModelConfig(0.4, 2.2, 0, 0),
	"minimax/minimax-m2":                                            openRouterModelConfig(0.255, 1, 0.03, 0),
	"minimax/minimax-m2-her":                                        openRouterModelConfig(0.3, 1.2, 0.03, 0),
	"minimax/minimax-m2.1":                                          openRouterModelConfig(0.29, 0.95, 0.03, 0),
	"minimax/minimax-m2.5":                                          openRouterModelConfig(0.15, 1.15, 0.03, 0),
	"minimax/minimax-m2.5:free":                                     openRouterModelConfig(0, 0, 0, 0),
	"minimax/minimax-m2.7":                                          openRouterModelConfig(0.3, 1.2, 0.059, 0),
	"mistralai/codestral-2508":                                      openRouterModelConfig(0.3, 0.9, 0.03, 0),
	"mistralai/devstral-2512":                                       openRouterModelConfig(0.4, 2, 0.04, 0),
	"mistralai/devstral-medium":                                     openRouterModelConfig(0.4, 2, 0.04, 0),
	"mistralai/devstral-small":                                      openRouterModelConfig(0.1, 0.3, 0.01, 0),
	"mistralai/ministral-14b-2512":                                  openRouterModelConfig(0.2, 0.2, 0.02, 0),
	"mistralai/ministral-3b-2512":                                   openRouterModelConfig(0.1, 0.1, 0.01, 0),
	"mistralai/ministral-8b-2512":                                   openRouterModelConfig(0.15, 0.15, 0.015, 0),
	"mistralai/mistral-7b-instruct-v0.1":                            openRouterModelConfig(0.11, 0.19, 0, 0),
	"mistralai/mistral-large":                                       openRouterModelConfig(2, 6, 0.2, 0),
	"mistralai/mistral-large-2407":                                  openRouterModelConfig(2, 6, 0.2, 0),
	"mistralai/mistral-large-2411":                                  openRouterModelConfig(2, 6, 0.2, 0),
	"mistralai/mistral-large-2512":                                  openRouterModelConfig(0.5, 1.5, 0.05, 0),
	"mistralai/mistral-medium-3":                                    openRouterModelConfig(0.4, 2, 0.04, 0),
	"mistralai/mistral-medium-3.1":                                  openRouterModelConfig(0.4, 2, 0.04, 0),
	"mistralai/mistral-nemo":                                        openRouterModelConfig(0.02, 0.04, 0, 0),
	"mistralai/mistral-saba":                                        openRouterModelConfig(0.2, 0.6, 0.02, 0),
	"mistralai/mistral-small-24b-instruct-2501":                     openRouterModelConfig(0.05, 0.08, 0, 0),
	"mistralai/mistral-small-2603":                                  openRouterModelConfig(0.15, 0.6, 0.015, 0),
	"mistralai/mistral-small-3.1-24b-instruct":                      openRouterModelConfig(0.35, 0.56, 0, 0),
	"mistralai/mistral-small-3.2-24b-instruct":                      openRouterModelConfig(0.075, 0.2, 0, 0),
	"mistralai/mistral-small-creative":                              openRouterModelConfig(0.1, 0.3, 0.01, 0),
	"mistralai/mixtral-8x22b-instruct":                              openRouterModelConfig(2, 6, 0.2, 0),
	"mistralai/mixtral-8x7b-instruct":                               openRouterModelConfig(0.54, 0.54, 0, 0),
	"mistralai/pixtral-large-2411":                                  openRouterModelConfig(2, 6, 0.2, 0),
	"mistralai/voxtral-small-24b-2507":                              openRouterModelConfig(0.1, 0.3, 0.01, 0),
	"moonshotai/kimi-k2":                                            openRouterModelConfig(0.57, 2.3, 0, 0),
	"moonshotai/kimi-k2-0905":                                       openRouterModelConfig(0.4, 2, 0, 0),
	"moonshotai/kimi-k2-thinking":                                   openRouterModelConfig(0.6, 2.5, 0.15, 0),
	"moonshotai/kimi-k2.5":                                          openRouterModelConfig(0.44, 2, 0.22, 0),
	"moonshotai/kimi-k2.6":                                          openRouterModelConfig(0.7448, 4.655, 0.1463, 0),
	"morph/morph-v3-fast":                                           openRouterModelConfig(0.8, 1.2, 0, 0),
	"morph/morph-v3-large":                                          openRouterModelConfig(0.9, 1.9, 0, 0),
	"nex-agi/deepseek-v3.1-nex-n1":                                  openRouterModelConfig(0.135, 0.5, 0, 0),
	"nousresearch/hermes-2-pro-llama-3-8b":                          openRouterModelConfig(0.14, 0.14, 0, 0),
	"nousresearch/hermes-3-llama-3.1-405b":                          openRouterModelConfig(1, 1, 0, 0),
	"nousresearch/hermes-3-llama-3.1-405b:free":                     openRouterModelConfig(0, 0, 0, 0),
	"nousresearch/hermes-3-llama-3.1-70b":                           openRouterModelConfig(0.3, 0.3, 0, 0),
	"nousresearch/hermes-4-405b":                                    openRouterModelConfig(1, 3, 0, 0),
	"nousresearch/hermes-4-70b":                                     openRouterModelConfig(0.13, 0.4, 0, 0),
	"nvidia/llama-3.1-nemotron-70b-instruct":                        openRouterModelConfig(1.2, 1.2, 0, 0),
	"nvidia/llama-3.3-nemotron-super-49b-v1.5":                      openRouterModelConfig(0.1, 0.4, 0, 0),
	"nvidia/nemotron-3-nano-30b-a3b":                                openRouterModelConfig(0.05, 0.2, 0, 0),
	"nvidia/nemotron-3-nano-30b-a3b:free":                           openRouterModelConfig(0, 0, 0, 0),
	"nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free":            openRouterModelConfig(0, 0, 0, 0),
	"nvidia/nemotron-3-super-120b-a12b":                             openRouterModelConfig(0.09, 0.45, 0, 0),
	"nvidia/nemotron-3-super-120b-a12b:free":                        openRouterModelConfig(0, 0, 0, 0),
	"nvidia/nemotron-nano-12b-v2-vl":                                openRouterModelConfig(0.2, 0.6, 0, 0),
	"nvidia/nemotron-nano-12b-v2-vl:free":                           openRouterModelConfig(0, 0, 0, 0),
	"nvidia/nemotron-nano-9b-v2":                                    openRouterModelConfig(0.04, 0.16, 0, 0),
	"nvidia/nemotron-nano-9b-v2:free":                               openRouterModelConfig(0, 0, 0, 0),
	"openai/gpt-3.5-turbo":                                          openRouterModelConfig(0.5, 1.5, 0, 0),
	"openai/gpt-3.5-turbo-0613":                                     openRouterModelConfig(1, 2, 0, 0),
	"openai/gpt-3.5-turbo-16k":                                      openRouterModelConfig(3, 4, 0, 0),
	"openai/gpt-3.5-turbo-instruct":                                 openRouterModelConfig(1.5, 2, 0, 0),
	"openai/gpt-4":                                                  openRouterModelConfig(30, 60, 0, 0),
	"openai/gpt-4-0314":                                             openRouterModelConfig(30, 60, 0, 0),
	"openai/gpt-4-1106-preview":                                     openRouterModelConfig(10, 30, 0, 0),
	"openai/gpt-4-turbo":                                            openRouterModelConfig(10, 30, 0, 0),
	"openai/gpt-4-turbo-preview":                                    openRouterModelConfig(10, 30, 0, 0),
	"openai/gpt-4.1":                                                openRouterModelConfig(2, 8, 0.5, 0),
	"openai/gpt-4.1-mini":                                           openRouterModelConfig(0.4, 1.6, 0.1, 0),
	"openai/gpt-4.1-nano":                                           openRouterModelConfig(0.1, 0.4, 0.025, 0),
	"openai/gpt-4o":                                                 openRouterModelConfig(2.5, 10, 0, 0),
	"openai/gpt-4o-2024-05-13":                                      openRouterModelConfig(5, 15, 0, 0),
	"openai/gpt-4o-2024-08-06":                                      openRouterModelConfig(2.5, 10, 1.25, 0),
	"openai/gpt-4o-2024-11-20":                                      openRouterModelConfig(2.5, 10, 1.25, 0),
	"openai/gpt-4o-audio-preview":                                   openRouterModelConfig(2.5, 10, 0, 0),
	"openai/gpt-4o-mini":                                            openRouterModelConfig(0.15, 0.6, 0.075, 0),
	"openai/gpt-4o-mini-2024-07-18":                                 openRouterModelConfig(0.15, 0.6, 0.075, 0),
	"openai/gpt-4o-mini-search-preview":                             openRouterModelConfig(0.15, 0.6, 0, 0),
	"openai/gpt-4o-search-preview":                                  openRouterModelConfig(2.5, 10, 0, 0),
	"openai/gpt-5":                                                  openRouterModelConfig(1.25, 10, 0.125, 0),
	"openai/gpt-5-chat":                                             openRouterModelConfig(1.25, 10, 0.125, 0),
	"openai/gpt-5-codex":                                            openRouterModelConfig(1.25, 10, 0.125, 0),
	"openai/gpt-5-image":                                            openRouterModelConfig(10, 10, 1.25, 0),
	"openai/gpt-5-image-mini":                                       openRouterModelConfig(2.5, 2, 0.25, 0),
	"openai/gpt-5-mini":                                             openRouterModelConfig(0.25, 2, 0.025, 0),
	"openai/gpt-5-nano":                                             openRouterModelConfig(0.05, 0.4, 0.01, 0),
	"openai/gpt-5-pro":                                              openRouterModelConfig(15, 120, 0, 0),
	"openai/gpt-5.1":                                                openRouterModelConfig(1.25, 10, 0.13, 0),
	"openai/gpt-5.1-chat":                                           openRouterModelConfig(1.25, 10, 0.125, 0),
	"openai/gpt-5.1-codex":                                          openRouterModelConfig(1.25, 10, 0.125, 0),
	"openai/gpt-5.1-codex-max":                                      openRouterModelConfig(1.25, 10, 0.125, 0),
	"openai/gpt-5.1-codex-mini":                                     openRouterModelConfig(0.25, 2, 0.03, 0),
	"openai/gpt-5.2":                                                openRouterModelConfig(1.75, 14, 0.175, 0),
	"openai/gpt-5.2-chat":                                           openRouterModelConfig(1.75, 14, 0.175, 0),
	"openai/gpt-5.2-codex":                                          openRouterModelConfig(1.75, 14, 0.175, 0),
	"openai/gpt-5.2-pro":                                            openRouterModelConfig(21, 168, 0, 0),
	"openai/gpt-5.3-chat":                                           openRouterModelConfig(1.75, 14, 0.175, 0),
	"openai/gpt-5.3-codex":                                          openRouterModelConfig(1.75, 14, 0.175, 0),
	"openai/gpt-5.4":                                                openRouterModelConfig(2.5, 15, 0.25, 0),
	"openai/gpt-5.4-image-2":                                        openRouterModelConfig(8, 15, 2, 0),
	"openai/gpt-5.4-mini":                                           openRouterModelConfig(0.75, 4.5, 0.075, 0),
	"openai/gpt-5.4-nano":                                           openRouterModelConfig(0.2, 1.25, 0.02, 0),
	"openai/gpt-5.4-pro":                                            openRouterModelConfig(30, 180, 0, 0),
	"openai/gpt-5.5":                                                openRouterModelConfig(5, 30, 0.5, 0),
	"openai/gpt-5.5-pro":                                            openRouterModelConfig(30, 180, 0, 0),
	"openai/gpt-audio":                                              openRouterModelConfig(2.5, 10, 0, 0),
	"openai/gpt-audio-mini":                                         openRouterModelConfig(0.6, 2.4, 0, 0),
	"openai/gpt-oss-120b":                                           openRouterModelConfig(0.039, 0.19, 0, 0),
	"openai/gpt-oss-120b:free":                                      openRouterModelConfig(0, 0, 0, 0),
	"openai/gpt-oss-20b":                                            openRouterModelConfig(0.03, 0.14, 0, 0),
	"openai/gpt-oss-20b:free":                                       openRouterModelConfig(0, 0, 0, 0),
	"openai/gpt-oss-safeguard-20b":                                  openRouterModelConfig(0.075, 0.3, 0.037, 0),
	"openai/o1":                                                     openRouterModelConfig(15, 60, 7.5, 0),
	"openai/o1-pro":                                                 openRouterModelConfig(150, 600, 0, 0),
	"openai/o3":                                                     openRouterModelConfig(2, 8, 0.5, 0),
	"openai/o3-deep-research":                                       openRouterModelConfig(10, 40, 2.5, 0),
	"openai/o3-mini":                                                openRouterModelConfig(1.1, 4.4, 0.55, 0),
	"openai/o3-mini-high":                                           openRouterModelConfig(1.1, 4.4, 0.55, 0),
	"openai/o3-pro":                                                 openRouterModelConfig(20, 80, 0, 0),
	"openai/o4-mini":                                                openRouterModelConfig(1.1, 4.4, 0.275, 0),
	"openai/o4-mini-deep-research":                                  openRouterModelConfig(2, 8, 0.5, 0),
	"openai/o4-mini-high":                                           openRouterModelConfig(1.1, 4.4, 0.275, 0),
	"openrouter/free":                                               openRouterModelConfig(0, 0, 0, 0),
	"perplexity/sonar":                                              openRouterModelConfig(1, 1, 0, 0),
	"perplexity/sonar-deep-research":                                openRouterModelConfig(2, 8, 0, 0),
	"perplexity/sonar-pro":                                          openRouterModelConfig(3, 15, 0, 0),
	"perplexity/sonar-pro-search":                                   openRouterModelConfig(3, 15, 0, 0),
	"perplexity/sonar-reasoning-pro":                                openRouterModelConfig(2, 8, 0, 0),
	"poolside/laguna-m.1:free":                                      openRouterModelConfig(0, 0, 0, 0),
	"poolside/laguna-xs.2:free":                                     openRouterModelConfig(0, 0, 0, 0),
	"prime-intellect/intellect-3":                                   openRouterModelConfig(0.2, 1.1, 0, 0),
	"qwen/qwen-2.5-72b-instruct":                                    openRouterModelConfig(0.36, 0.4, 0, 0),
	"qwen/qwen-2.5-7b-instruct":                                     openRouterModelConfig(0.04, 0.1, 0, 0),
	"qwen/qwen-2.5-coder-32b-instruct":                              openRouterModelConfig(0.66, 1, 0, 0),
	"qwen/qwen-max":                                                 openRouterModelConfig(1.04, 4.16, 0.208, 0),
	"qwen/qwen-plus":                                                openRouterModelConfig(0.26, 0.78, 0.052, 0.325),
	"qwen/qwen-plus-2025-07-28":                                     openRouterModelConfig(0.26, 0.78, 0, 0.325),
	"qwen/qwen-plus-2025-07-28:thinking":                            openRouterModelConfig(0.26, 0.78, 0, 0.325),
	"qwen/qwen-turbo":                                               openRouterModelConfig(0.0325, 0.13, 0.0065, 0),
	"qwen/qwen-vl-max":                                              openRouterModelConfig(0.52, 2.08, 0, 0),
	"qwen/qwen-vl-plus":                                             openRouterModelConfig(0.1365, 0.4095, 0.0273, 0),
	"qwen/qwen2.5-vl-72b-instruct":                                  openRouterModelConfig(0.25, 0.75, 0, 0),
	"qwen/qwen3-14b":                                                openRouterModelConfig(0.06, 0.24, 0, 0),
	"qwen/qwen3-235b-a22b":                                          openRouterModelConfig(0.455, 1.82, 0, 0),
	"qwen/qwen3-235b-a22b-2507":                                     openRouterModelConfig(0.071, 0.1, 0, 0),
	"qwen/qwen3-235b-a22b-thinking-2507":                            openRouterModelConfig(0.1495, 1.495, 0, 0),
	"qwen/qwen3-30b-a3b":                                            openRouterModelConfig(0.08, 0.28, 0, 0),
	"qwen/qwen3-30b-a3b-instruct-2507":                              openRouterModelConfig(0.09, 0.3, 0, 0),
	"qwen/qwen3-30b-a3b-thinking-2507":                              openRouterModelConfig(0.08, 0.4, 0.08, 0),
	"qwen/qwen3-32b":                                                openRouterModelConfig(0.08, 0.24, 0.04, 0),
	"qwen/qwen3-8b":                                                 openRouterModelConfig(0.05, 0.4, 0.05, 0),
	"qwen/qwen3-coder":                                              openRouterModelConfig(0.22, 1.8, 0, 0),
	"qwen/qwen3-coder-30b-a3b-instruct":                             openRouterModelConfig(0.07, 0.27, 0, 0),
	"qwen/qwen3-coder-flash":                                        openRouterModelConfig(0.195, 0.975, 0.039, 0.24375),
	"qwen/qwen3-coder-next":                                         openRouterModelConfig(0.14, 0.8, 0.09, 0),
	"qwen/qwen3-coder-plus":                                         openRouterModelConfig(0.65, 3.25, 0.13, 0.8125),
	"qwen/qwen3-coder:free":                                         openRouterModelConfig(0, 0, 0, 0),
	"qwen/qwen3-max":                                                openRouterModelConfig(0.78, 3.9, 0.156, 0.975),
	"qwen/qwen3-max-thinking":                                       openRouterModelConfig(0.78, 3.9, 0, 0),
	"qwen/qwen3-next-80b-a3b-instruct":                              openRouterModelConfig(0.09, 1.1, 0, 0),
	"qwen/qwen3-next-80b-a3b-instruct:free":                         openRouterModelConfig(0, 0, 0, 0),
	"qwen/qwen3-next-80b-a3b-thinking":                              openRouterModelConfig(0.0975, 0.78, 0, 0),
	"qwen/qwen3-vl-235b-a22b-instruct":                              openRouterModelConfig(0.2, 0.88, 0.11, 0),
	"qwen/qwen3-vl-235b-a22b-thinking":                              openRouterModelConfig(0.26, 2.6, 0, 0),
	"qwen/qwen3-vl-30b-a3b-instruct":                                openRouterModelConfig(0.13, 0.52, 0, 0),
	"qwen/qwen3-vl-30b-a3b-thinking":                                openRouterModelConfig(0.13, 1.56, 0, 0),
	"qwen/qwen3-vl-32b-instruct":                                    openRouterModelConfig(0.104, 0.416, 0, 0),
	"qwen/qwen3-vl-8b-instruct":                                     openRouterModelConfig(0.08, 0.5, 0, 0),
	"qwen/qwen3-vl-8b-thinking":                                     openRouterModelConfig(0.117, 1.365, 0, 0),
	"qwen/qwen3.5-122b-a10b":                                        openRouterModelConfig(0.26, 2.08, 0, 0),
	"qwen/qwen3.5-27b":                                              openRouterModelConfig(0.195, 1.56, 0, 0),
	"qwen/qwen3.5-35b-a3b":                                          openRouterModelConfig(0.1625, 1.3, 0, 0),
	"qwen/qwen3.5-397b-a17b":                                        openRouterModelConfig(0.39, 2.34, 0.195, 0),
	"qwen/qwen3.5-9b":                                               openRouterModelConfig(0.1, 0.15, 0, 0),
	"qwen/qwen3.5-flash-02-23":                                      openRouterModelConfig(0.065, 0.26, 0, 0.08125),
	"qwen/qwen3.5-plus-02-15":                                       openRouterModelConfig(0.26, 1.56, 0, 0.325),
	"qwen/qwen3.5-plus-20260420":                                    openRouterModelConfig(0.4, 2.4, 0, 0),
	"qwen/qwen3.6-27b":                                              openRouterModelConfig(0.325, 3.25, 0, 0),
	"qwen/qwen3.6-35b-a3b":                                          openRouterModelConfig(0.1612, 0.96525, 0.1612, 0),
	"qwen/qwen3.6-flash":                                            openRouterModelConfig(0.25, 1.5, 0, 0.3125),
	"qwen/qwen3.6-max-preview":                                      openRouterModelConfig(1.04, 6.24, 0, 1.3),
	"qwen/qwen3.6-plus":                                             openRouterModelConfig(0.325, 1.95, 0, 0.40625),
	"qwen/qwq-32b":                                                  openRouterModelConfig(0.15, 0.58, 0, 0),
	"rekaai/reka-edge":                                              openRouterModelConfig(0.1, 0.1, 0, 0),
	"rekaai/reka-flash-3":                                           openRouterModelConfig(0.1, 0.2, 0, 0),
	"relace/relace-apply-3":                                         openRouterModelConfig(0.85, 1.25, 0, 0),
	"relace/relace-search":                                          openRouterModelConfig(1, 3, 0, 0),
	"sao10k/l3-euryale-70b":                                         openRouterModelConfig(1.48, 1.48, 0, 0),
	"sao10k/l3-lunaris-8b":                                          openRouterModelConfig(0.04, 0.05, 0, 0),
	"sao10k/l3.1-70b-hanami-x1":                                     openRouterModelConfig(3, 3, 0, 0),
	"sao10k/l3.1-euryale-70b":                                       openRouterModelConfig(0.85, 0.85, 0, 0),
	"sao10k/l3.3-euryale-70b":                                       openRouterModelConfig(0.65, 0.75, 0, 0),
	"stepfun/step-3.5-flash":                                        openRouterModelConfig(0.1, 0.3, 0, 0),
	"switchpoint/router":                                            openRouterModelConfig(0.85, 3.4, 0, 0),
	"tencent/hunyuan-a13b-instruct":                                 openRouterModelConfig(0.14, 0.57, 0, 0),
	"tencent/hy3-preview:free":                                      openRouterModelConfig(0, 0, 0, 0),
	"thedrummer/cydonia-24b-v4.1":                                   openRouterModelConfig(0.3, 0.5, 0.15, 0),
	"thedrummer/rocinante-12b":                                      openRouterModelConfig(0.17, 0.43, 0, 0),
	"thedrummer/skyfall-36b-v2":                                     openRouterModelConfig(0.55, 0.8, 0.25, 0),
	"thedrummer/unslopnemo-12b":                                     openRouterModelConfig(0.4, 0.4, 0, 0),
	"tngtech/deepseek-r1t2-chimera":                                 openRouterModelConfig(0.3, 1.1, 0.15, 0),
	"undi95/remm-slerp-l2-13b":                                      openRouterModelConfig(0.45, 0.65, 0, 0),
	"upstage/solar-pro-3":                                           openRouterModelConfig(0.15, 0.6, 0.015, 0),
	"writer/palmyra-x5":                                             openRouterModelConfig(0.6, 6, 0, 0),
	"x-ai/grok-3":                                                   openRouterModelConfig(3, 15, 0.75, 0),
	"x-ai/grok-3-beta":                                              openRouterModelConfig(3, 15, 0.75, 0),
	"x-ai/grok-3-mini":                                              openRouterModelConfig(0.3, 0.5, 0.075, 0),
	"x-ai/grok-3-mini-beta":                                         openRouterModelConfig(0.3, 0.5, 0.075, 0),
	"x-ai/grok-4":                                                   openRouterModelConfig(3, 15, 0.75, 0),
	"x-ai/grok-4-fast":                                              openRouterModelConfig(0.2, 0.5, 0.05, 0),
	"x-ai/grok-4.1-fast":                                            openRouterModelConfig(0.2, 0.5, 0.05, 0),
	"x-ai/grok-4.20":                                                openRouterModelConfig(2, 6, 0.2, 0),
	"x-ai/grok-4.20-multi-agent":                                    openRouterModelConfig(2, 6, 0.2, 0),
	"x-ai/grok-code-fast-1":                                         openRouterModelConfig(0.2, 1.5, 0.02, 0),
	"xiaomi/mimo-v2-flash":                                          openRouterModelConfig(0.09, 0.29, 0.045, 0),
	"xiaomi/mimo-v2-omni":                                           openRouterModelConfig(0.4, 2, 0.08, 0),
	"xiaomi/mimo-v2-pro":                                            openRouterModelConfig(1, 3, 0.2, 0),
	"xiaomi/mimo-v2.5":                                              openRouterModelConfig(0.4, 2, 0.08, 0),
	"xiaomi/mimo-v2.5-pro":                                          openRouterModelConfig(1, 3, 0.2, 0),
	"z-ai/glm-4-32b":                                                openRouterModelConfig(0.1, 0.1, 0, 0),
	"z-ai/glm-4.5":                                                  openRouterModelConfig(0.6, 2.2, 0.11, 0),
	"z-ai/glm-4.5-air":                                              openRouterModelConfig(0.13, 0.85, 0.025, 0),
	"z-ai/glm-4.5-air:free":                                         openRouterModelConfig(0, 0, 0, 0),
	"z-ai/glm-4.5v":                                                 openRouterModelConfig(0.6, 1.8, 0.11, 0),
	"z-ai/glm-4.6":                                                  openRouterModelConfig(0.39, 1.9, 0, 0),
	"z-ai/glm-4.6v":                                                 openRouterModelConfig(0.3, 0.9, 0.05, 0),
	"z-ai/glm-4.7":                                                  openRouterModelConfig(0.38, 1.74, 0, 0),
	"z-ai/glm-4.7-flash":                                            openRouterModelConfig(0.06, 0.4, 0.01, 0),
	"z-ai/glm-5":                                                    openRouterModelConfig(0.6, 2.08, 0.12, 0),
	"z-ai/glm-5-turbo":                                              openRouterModelConfig(1.2, 4, 0.24, 0),
	"z-ai/glm-5.1":                                                  openRouterModelConfig(1.05, 3.5, 0.525, 0),
	"z-ai/glm-5v-turbo":                                             openRouterModelConfig(1.2, 4, 0.24, 0),
	"~anthropic/claude-haiku-latest":                                openRouterModelConfig(1, 5, 0.1, 1.25),
	"~anthropic/claude-opus-latest":                                 openRouterModelConfig(5, 25, 0.5, 6.25),
	"~anthropic/claude-sonnet-latest":                               openRouterModelConfig(3, 15, 0.3, 3.75),
	"~google/gemini-flash-latest":                                   openRouterModelConfig(0.5, 3, 0.05, 0.083333333333),
	"~google/gemini-pro-latest":                                     openRouterModelConfig(2, 12, 0.2, 0.375),
	"~moonshotai/kimi-latest":                                       openRouterModelConfig(0.7448, 4.655, 0.1463, 0),
	"~openai/gpt-latest":                                            openRouterModelConfig(5, 30, 0.5, 0),
	"~openai/gpt-mini-latest":                                       openRouterModelConfig(0.75, 4.5, 0.075, 0),
}

// OpenRouterToolingDefaults enumerates OpenRouter's published web tooling prices.
// Source: https://openrouter.ai/docs/features/web-search
var OpenRouterToolingDefaults = adaptor.ChannelToolConfig{
	Pricing: map[string]adaptor.ToolPricingConfig{
		// Exa plugin defaults to 5 results per request (5 * $0.004 = $0.02)
		"web_plugin_exa":                      {UsdPerCall: 0.02},
		"openai_native_search_low":            {UsdPerCall: 0.03},
		"openai_native_search_medium":         {UsdPerCall: 0.035},
		"openai_native_search_high":           {UsdPerCall: 0.05},
		"openai_mini_native_search_low":       {UsdPerCall: 0.025},
		"openai_mini_native_search_medium":    {UsdPerCall: 0.0275},
		"openai_mini_native_search_high":      {UsdPerCall: 0.03},
		"perplexity_native_search_low":        {UsdPerCall: 0.005},
		"perplexity_native_search_medium":     {UsdPerCall: 0.008},
		"perplexity_native_search_high":       {UsdPerCall: 0.012},
		"perplexity_pro_native_search_low":    {UsdPerCall: 0.006},
		"perplexity_pro_native_search_medium": {UsdPerCall: 0.01},
		"perplexity_pro_native_search_high":   {UsdPerCall: 0.014},
	},
}
