package openrouter

import "github.com/Laisky/one-api/relay/adaptor"

// x_aiModels returns the x_ai model defaults for openrouter.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func x_aiModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"x-ai/grok-4.20": {
			Ratio:            nativeRate(1.25),
			CompletionRatio:  2,
			CachedInputRatio: nativeRate(0.19999999999999998),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(2.5),
				CompletionRatio:     2,
				CachedInputRatio:    nativeRate(0.39999999999999997),
				InputTokenThreshold: 200000,
			},
			},
			ContextLength:               2000000,
			MaxOutputTokens:             1800000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"include_reasoning", "logprobs", "max_tokens", "reasoning", "response_format", "seed", "structured_outputs", "temperature", "tool_choice", "tools", "top_logprobs", "top_p"},
			Description:                 "x-ai/grok-4.20 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"x-ai/grok-4.20-multi-agent": {
			Ratio:            nativeRate(1.25),
			CompletionRatio:  2,
			CachedInputRatio: nativeRate(0.19999999999999998),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(2.5),
				CompletionRatio:     2,
				CachedInputRatio:    nativeRate(0.39999999999999997),
				InputTokenThreshold: 200000,
			},
			},
			ContextLength:               2000000,
			MaxOutputTokens:             1800000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"include_reasoning", "logprobs", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "temperature", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"xhigh", "high", "medium", "low"},
			DefaultReasoningEffort:      "medium",
			Description:                 "x-ai/grok-4.20-multi-agent on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"x-ai/grok-4.3": {
			Ratio:            nativeRate(1.25),
			CompletionRatio:  2,
			CachedInputRatio: nativeRate(0.19999999999999998),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(2.5),
				CompletionRatio:     2,
				CachedInputRatio:    nativeRate(0.39999999999999997),
				InputTokenThreshold: 200000,
			},
			},
			ContextLength:               1000000,
			MaxOutputTokens:             900000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"include_reasoning", "logprobs", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "temperature", "tool_choice", "tools", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"high", "medium", "low", "none"},
			DefaultReasoningEffort:      "low",
			Description:                 "x-ai/grok-4.3 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"x-ai/grok-4.5": {
			Ratio:            nativeRate(2),
			CompletionRatio:  3,
			CachedInputRatio: nativeRate(0.3),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(4),
				CompletionRatio:     3,
				CachedInputRatio:    nativeRate(0.6),
				InputTokenThreshold: 200000,
			},
			},
			ContextLength:               500000,
			MaxOutputTokens:             450000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"include_reasoning", "logprobs", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "temperature", "tool_choice", "tools", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"high", "medium", "low"},
			DefaultReasoningEffort:      "high",
			Description:                 "x-ai/grok-4.5 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"x-ai/grok-4.6": {
			Ratio:            nativeRate(2),
			CompletionRatio:  3,
			CachedInputRatio: nativeRate(0.5),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(4),
				CompletionRatio:     3,
				CachedInputRatio:    nativeRate(1),
				InputTokenThreshold: 200000,
			},
			},
			ContextLength:               500000,
			MaxOutputTokens:             450000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"include_reasoning", "logprobs", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"xhigh", "high", "medium", "low"},
			DefaultReasoningEffort:      "high",
			Description:                 "x-ai/grok-4.6 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"x-ai/grok-4.7": {
			Ratio:            nativeRate(1.5999999999999999),
			CompletionRatio:  3,
			CachedInputRatio: nativeRate(0.39999999999999997),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(3.1999999999999997),
				CompletionRatio:     3,
				CachedInputRatio:    nativeRate(0.7999999999999999),
				InputTokenThreshold: 200000,
			},
			},
			ContextLength:               500000,
			MaxOutputTokens:             450000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"include_reasoning", "logprobs", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "temperature", "tool_choice", "tools", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"xhigh", "high", "medium", "low"},
			DefaultReasoningEffort:      "high",
			Description:                 "x-ai/grok-4.7 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"x-ai/grok-build-0.1": {
			Ratio:            nativeRate(1),
			CompletionRatio:  2,
			CachedInputRatio: nativeRate(0.19999999999999998),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(2),
				CompletionRatio:     2,
				CachedInputRatio:    nativeRate(0.39999999999999997),
				InputTokenThreshold: 200000,
			},
			},
			ContextLength:               256000,
			MaxOutputTokens:             230400,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"include_reasoning", "logprobs", "max_tokens", "reasoning", "response_format", "seed", "structured_outputs", "temperature", "tool_choice", "tools", "top_logprobs", "top_p"},
			Description:                 "x-ai/grok-build-0.1 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"~x-ai/grok-latest": {
			Ratio:            nativeRate(1.5999999999999999),
			CompletionRatio:  3,
			CachedInputRatio: nativeRate(0.39999999999999997),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(3.1999999999999997),
				CompletionRatio:     3,
				CachedInputRatio:    nativeRate(0.7999999999999999),
				InputTokenThreshold: 200000,
			},
			},
			ContextLength:               500000,
			MaxOutputTokens:             450000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"include_reasoning", "logprobs", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "temperature", "tool_choice", "tools", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"xhigh", "high", "medium", "low"},
			DefaultReasoningEffort:      "high",
			Description:                 "~x-ai/grok-latest on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
