package openrouter

import "github.com/Laisky/one-api/relay/adaptor"

// qwen_2Models returns the qwen model defaults for openrouter.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func qwen_2Models() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"qwen/qwen3.7-max": {
			Ratio:                       nativeRate(1.475),
			CompletionRatio:             2.9999999999999996,
			CachedInputRatio:            nativeRate(0.295),
			CacheWrite5mRatio:           nativeRate(1.84375),
			ContextLength:               1000000,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_tokens", "presence_penalty", "reasoning", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			Description:                 "qwen/qwen3.7-max on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.7-plus": {
			Ratio:             nativeRate(0.32),
			CompletionRatio:   4,
			CachedInputRatio:  nativeRate(0.064),
			CacheWrite5mRatio: nativeRate(0.39999999999999997),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.96),
				CompletionRatio:     4,
				CachedInputRatio:    nativeRate(0.192),
				CacheWrite5mRatio:   nativeRate(1.2),
				InputTokenThreshold: 256000,
			},
			},
			ContextLength:               1000000,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_tokens", "presence_penalty", "reasoning", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			Description:                 "qwen/qwen3.7-plus on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.8-2.4t-a95b": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.25),
			ContextLength:               1048576,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"xhigh", "medium", "low"},
			DefaultReasoningEffort:      "xhigh",
			HuggingFaceID:               "Qwen/Qwen3.8-2.4T-A95B",
			Description:                 "qwen/qwen3.8-2.4t-a95b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.8-27b": {
			Ratio:                       nativeRate(0.42),
			CompletionRatio:             7.142857142857143,
			CachedInputRatio:            nativeRate(0.08499999999999999),
			ContextLength:               1000000,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_a", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"xhigh", "medium", "low"},
			DefaultReasoningEffort:      "xhigh",
			HuggingFaceID:               "Qwen/Qwen3.8-27B",
			Description:                 "qwen/qwen3.8-27b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.8-27b:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               262144,
			MaxOutputTokens:             235929,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "max_tokens", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_p"},
			SupportedReasoningEfforts:   []string{"xhigh", "medium", "low"},
			DefaultReasoningEffort:      "xhigh",
			HuggingFaceID:               "Qwen/Qwen3.8-27B",
			Description:                 "qwen/qwen3.8-27b:free on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.8-flash": {
			Ratio:                       nativeRate(0.15),
			CompletionRatio:             3.1333333333333333,
			CachedInputRatio:            nativeRate(0.016),
			CacheWrite5mRatio:           nativeRate(0.19999999999999998),
			ContextLength:               1000000,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_tokens", "presence_penalty", "reasoning", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3.8-Flash-Next",
			Description:                 "qwen/qwen3.8-flash on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.8-max-0902": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.25),
			CacheWrite5mRatio:           nativeRate(2.5),
			ContextLength:               1000000,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_tokens", "presence_penalty", "reasoning", "reasoning_effort", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"xhigh", "high", "medium", "low", "minimal"},
			DefaultReasoningEffort:      "xhigh",
			Description:                 "qwen/qwen3.8-max-0902 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.8-max-prime": {
			Ratio:                       nativeRate(4),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.5),
			ContextLength:               1000000,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_tokens", "presence_penalty", "reasoning", "reasoning_effort", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"xhigh", "high", "medium", "low", "minimal"},
			DefaultReasoningEffort:      "xhigh",
			Description:                 "qwen/qwen3.8-max-prime on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.8-omni-flash": {
			Ratio:                       nativeRate(0.15),
			CompletionRatio:             3.1333333333333333,
			CachedInputRatio:            nativeRate(0.016),
			ContextLength:               1000000,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text", "image", "audio", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_tokens", "presence_penalty", "reasoning", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			Description:                 "qwen/qwen3.8-omni-flash on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
