package openrouter

import "github.com/Laisky/one-api/relay/adaptor"

// inclusionaiModels returns the inclusionai model defaults for openrouter.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func inclusionaiModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"inclusionai/ling-2.6-1t": {
			Ratio:                       nativeRate(0.075),
			CompletionRatio:             8.333333333333334,
			CachedInputRatio:            nativeRate(0.015),
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Ling-2.6-1T is an instant (instruct) model from inclusionAI and the company’s trillion-parameter flagship, designed for real-world agents that require fast execution and high efficiency at scale. It uses a “fast...",
		},
		"inclusionai/ling-2.6-flash": {
			Ratio:                       nativeRate(0.01),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.002),
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Ling-2.6-flash is an instant (instruct) model from inclusionAI with 104B total parameters and 7.4B active parameters, designed for real-world agents that require fast responses, strong execution, and high token efficiency....",
		},
		"inclusionai/ling-3.0-flash": {
			Ratio:                       nativeRate(0.020999999999999998),
			CompletionRatio:             3.0000000000000004,
			CachedInputRatio:            nativeRate(0.004200000000000001),
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "inclusionAI/Ling-3.0-flash",
			Description:                 "inclusionai/ling-3.0-flash on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"inclusionai/ling-3.0-flash-fin": {
			Ratio:                       nativeRate(0.06),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.012),
			ContextLength:               262144,
			MaxOutputTokens:             235929,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			Description:                 "inclusionai/ling-3.0-flash-fin on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"inclusionai/ling-3.0-flash-fin:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_tokens", "presence_penalty", "reasoning", "repetition_penalty", "seed", "stop", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			Description:                 "inclusionai/ling-3.0-flash-fin:free on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"inclusionai/ling-3.0-flash-sante:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_tokens", "presence_penalty", "reasoning", "repetition_penalty", "seed", "stop", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			Description:                 "inclusionai/ling-3.0-flash-sante:free on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"inclusionai/ling-3.0-flash-vl": {
			Ratio:                       nativeRate(0.06),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.012),
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "inclusionAI/Ling-3.0-flash-VL",
			Description:                 "inclusionai/ling-3.0-flash-vl on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"inclusionai/ring-2.6-1t": {
			Ratio:                       nativeRate(0.075),
			CompletionRatio:             8.333333333333334,
			CachedInputRatio:            nativeRate(0.015),
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Ring-2.6-1T is a 1T-parameter-scale thinking model with 63B active parameters, built for real-world agent workflows that require both strong capability and operational efficiency.",
		},
	}
}
