package openrouter

import "github.com/Laisky/one-api/relay/adaptor"

// openai_2Models returns the openai model defaults for openrouter.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func openai_2Models() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"openai/gpt-5.6-terra": {
			Ratio:             nativeRate(2),
			CompletionRatio:   6,
			CachedInputRatio:  nativeRate(0.19999999999999998),
			CacheWrite5mRatio: nativeRate(2.5),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(4),
				CompletionRatio:     4.5,
				CachedInputRatio:    nativeRate(0.39999999999999997),
				CacheWrite5mRatio:   nativeRate(5),
				InputTokenThreshold: 272000,
			},
			},
			ContextLength:               1050000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low", "none"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-5.6-terra on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-5.6-terra-pro": {
			Ratio:             nativeRate(2),
			CompletionRatio:   6,
			CachedInputRatio:  nativeRate(0.19999999999999998),
			CacheWrite5mRatio: nativeRate(2.5),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(4),
				CompletionRatio:     4.5,
				CachedInputRatio:    nativeRate(0.39999999999999997),
				CacheWrite5mRatio:   nativeRate(5),
				InputTokenThreshold: 272000,
			},
			},
			ContextLength:               1050000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low", "none"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-5.6-terra-pro on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-6-astra": {
			Ratio:             nativeRate(1e+01),
			CompletionRatio:   5,
			CachedInputRatio:  nativeRate(1),
			CacheWrite5mRatio: nativeRate(12.5),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(2e+01),
				CompletionRatio:     3.75,
				CachedInputRatio:    nativeRate(2),
				CacheWrite5mRatio:   nativeRate(25),
				InputTokenThreshold: 272000,
			},
			},
			ContextLength:               1050000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-6-astra on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-6-astra-pro": {
			Ratio:             nativeRate(1e+01),
			CompletionRatio:   5,
			CachedInputRatio:  nativeRate(1),
			CacheWrite5mRatio: nativeRate(12.5),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(2e+01),
				CompletionRatio:     3.75,
				CachedInputRatio:    nativeRate(2),
				CacheWrite5mRatio:   nativeRate(25),
				InputTokenThreshold: 272000,
			},
			},
			ContextLength:               1050000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-6-astra-pro on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-6-luna": {
			Ratio:             nativeRate(0.09999999999999999),
			CompletionRatio:   5,
			CachedInputRatio:  nativeRate(0.01),
			CacheWrite5mRatio: nativeRate(0.125),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.19999999999999998),
				CompletionRatio:     3.7500000000000004,
				CachedInputRatio:    nativeRate(0.02),
				CacheWrite5mRatio:   nativeRate(0.25),
				InputTokenThreshold: 272000,
			},
			},
			ContextLength:               1050000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low", "none"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-6-luna on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-6-luna-pro": {
			Ratio:             nativeRate(0.09999999999999999),
			CompletionRatio:   5,
			CachedInputRatio:  nativeRate(0.01),
			CacheWrite5mRatio: nativeRate(0.125),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.19999999999999998),
				CompletionRatio:     3.7500000000000004,
				CachedInputRatio:    nativeRate(0.02),
				CacheWrite5mRatio:   nativeRate(0.25),
				InputTokenThreshold: 272000,
			},
			},
			ContextLength:               1050000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low", "none"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-6-luna-pro on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-6-sol": {
			Ratio:             nativeRate(2),
			CompletionRatio:   5,
			CachedInputRatio:  nativeRate(0.19999999999999998),
			CacheWrite5mRatio: nativeRate(2.5),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(4),
				CompletionRatio:     3.75,
				CachedInputRatio:    nativeRate(0.39999999999999997),
				CacheWrite5mRatio:   nativeRate(5),
				InputTokenThreshold: 272000,
			},
			},
			ContextLength:               1050000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low", "none"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-6-sol on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-6-sol-pro": {
			Ratio:             nativeRate(2),
			CompletionRatio:   5,
			CachedInputRatio:  nativeRate(0.19999999999999998),
			CacheWrite5mRatio: nativeRate(2.5),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(4),
				CompletionRatio:     3.75,
				CachedInputRatio:    nativeRate(0.39999999999999997),
				CacheWrite5mRatio:   nativeRate(5),
				InputTokenThreshold: 272000,
			},
			},
			ContextLength:               1050000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low", "none"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-6-sol-pro on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-audio": {
			Ratio:                       nativeRate(2.5),
			CompletionRatio:             4,
			ContextLength:               128000,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "audio"},
			OutputModalities:            []string{"text", "audio"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens", "logit_bias"},
			Description:                 "The gpt-audio model is OpenAI's first generally available audio model. The new snapshot features an upgraded decoder for more natural sounding voices and maintains better voice consistency. Audio is priced...",
		},
		"openai/gpt-audio-mini": {
			Ratio:                       nativeRate(0.6),
			CompletionRatio:             4,
			ContextLength:               128000,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "audio"},
			OutputModalities:            []string{"text", "audio"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens", "logit_bias"},
			Description:                 "A cost-efficient version of GPT Audio. The new snapshot features an upgraded decoder for more natural sounding voices and maintains better voice consistency. Input is priced at $0.60 per million...",
		},
		"openai/gpt-chat-latest": {
			Ratio:                       nativeRate(5),
			CompletionRatio:             6,
			CachedInputRatio:            nativeRate(0.5),
			ContextLength:               400000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"max_tokens", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			Description:                 "openai/gpt-chat-latest on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-oss-120b": {
			Ratio:                       nativeRate(0.15),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.075),
			ContextLength:               131072,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_a", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"high", "medium", "low"},
			DefaultReasoningEffort:      "medium",
			HuggingFaceID:               "openai/gpt-oss-120b",
			Description:                 "openai/gpt-oss-120b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-oss-120b:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               131072,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "stop", "seed", "max_tokens"},
			HuggingFaceID:               "openai/gpt-oss-120b",
			Description:                 "gpt-oss-120b is an open-weight, 117B-parameter Mixture-of-Experts (MoE) language model from OpenAI designed for high-reasoning, agentic, and general-purpose production use cases. It activates 5.1B parameters per forward pass and is optimized...",
		},
		"openai/gpt-oss-20b": {
			Ratio:                       nativeRate(0.018),
			CompletionRatio:             5,
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"high", "medium", "low"},
			DefaultReasoningEffort:      "medium",
			HuggingFaceID:               "openai/gpt-oss-20b",
			Description:                 "openai/gpt-oss-20b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-oss-20b:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "stop", "seed", "max_tokens"},
			HuggingFaceID:               "openai/gpt-oss-20b",
			Description:                 "gpt-oss-20b is an open-weight 21B parameter model released by OpenAI under the Apache 2.0 license. It uses a Mixture-of-Experts (MoE) architecture with 3.6B active parameters per forward pass, optimized for...",
		},
		"openai/gpt-oss-safeguard-20b": {
			Ratio:                       nativeRate(0.075),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.0375),
			ContextLength:               131072,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_p"},
			HuggingFaceID:               "openai/gpt-oss-safeguard-20b",
			Description:                 "openai/gpt-oss-safeguard-20b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/o1": {
			Ratio:                       nativeRate(15),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(7.5),
			ContextLength:               200000,
			MaxOutputTokens:             100000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			Description:                 "openai/o1 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/o1-pro": {
			Ratio:                       nativeRate(1.5e+02),
			CompletionRatio:             4,
			ContextLength:               200000,
			MaxOutputTokens:             100000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "response_format", "seed", "structured_outputs"},
			Description:                 "openai/o1-pro on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/o3": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.5),
			ContextLength:               200000,
			MaxOutputTokens:             100000,
			InputModalities:             []string{"image", "text", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			Description:                 "openai/o3 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/o3-deep-research": {
			Ratio:                       nativeRate(1e+01),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(2.5),
			ContextLength:               200000,
			MaxOutputTokens:             100000,
			InputModalities:             []string{"image", "text", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens", "logit_bias"},
			Description:                 "o3-deep-research is OpenAI's advanced model for deep research, designed to tackle complex, multi-step research tasks.\n\nNote: This model always uses the 'web_search' tool which adds additional cost.",
		},
		"openai/o3-mini": {
			Ratio:                       nativeRate(1.1),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.55),
			ContextLength:               200000,
			MaxOutputTokens:             100000,
			InputModalities:             []string{"text", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			Description:                 "openai/o3-mini on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/o3-mini-high": {
			Ratio:                       nativeRate(1.1),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.55),
			ContextLength:               200000,
			MaxOutputTokens:             100000,
			InputModalities:             []string{"text", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"high"},
			DefaultReasoningEffort:      "high",
			Description:                 "openai/o3-mini-high on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/o3-pro": {
			Ratio:                       nativeRate(2e+01),
			CompletionRatio:             4,
			ContextLength:               200000,
			MaxOutputTokens:             100000,
			InputModalities:             []string{"text", "file", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			Description:                 "openai/o3-pro on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/o4-mini": {
			Ratio:                       nativeRate(1.1),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.275),
			ContextLength:               200000,
			MaxOutputTokens:             100000,
			InputModalities:             []string{"image", "text", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			Description:                 "openai/o4-mini on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/o4-mini-deep-research": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.5),
			ContextLength:               200000,
			MaxOutputTokens:             100000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens", "logit_bias"},
			Description:                 "o4-mini-deep-research is OpenAI's faster, more affordable deep research model—ideal for tackling complex, multi-step research tasks.\n\nNote: This model always uses the 'web_search' tool which adds additional cost.",
		},
		"openai/o4-mini-high": {
			Ratio:                       nativeRate(1.1),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.275),
			ContextLength:               200000,
			MaxOutputTokens:             100000,
			InputModalities:             []string{"image", "text", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"high"},
			DefaultReasoningEffort:      "high",
			Description:                 "openai/o4-mini-high on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"~openai/gpt-astra-latest": {
			Ratio:             nativeRate(1e+01),
			CompletionRatio:   5,
			CachedInputRatio:  nativeRate(1),
			CacheWrite5mRatio: nativeRate(12.5),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(2e+01),
				CompletionRatio:     3.75,
				CachedInputRatio:    nativeRate(2),
				CacheWrite5mRatio:   nativeRate(25),
				InputTokenThreshold: 272000,
			},
			},
			ContextLength:               1050000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low"},
			DefaultReasoningEffort:      "medium",
			Description:                 "~openai/gpt-astra-latest on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"~openai/gpt-latest": {
			Ratio:                       nativeRate(5),
			CompletionRatio:             6,
			CachedInputRatio:            nativeRate(0.5),
			CacheWrite5mRatio:           nativeRate(6.25),
			ContextLength:               1050000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens", "max_completion_tokens"},
			Description:                 "This model always redirects to the latest model in the OpenAI GPT family.",
		},
		"~openai/gpt-luna-latest": {
			Ratio:             nativeRate(0.09999999999999999),
			CompletionRatio:   5,
			CachedInputRatio:  nativeRate(0.01),
			CacheWrite5mRatio: nativeRate(0.125),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.19999999999999998),
				CompletionRatio:     3.7500000000000004,
				CachedInputRatio:    nativeRate(0.02),
				CacheWrite5mRatio:   nativeRate(0.25),
				InputTokenThreshold: 272000,
			},
			},
			ContextLength:               1050000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low", "none"},
			DefaultReasoningEffort:      "medium",
			Description:                 "~openai/gpt-luna-latest on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"~openai/gpt-mini-latest": {
			Ratio:                       nativeRate(0.75),
			CompletionRatio:             6,
			CachedInputRatio:            nativeRate(0.075),
			ContextLength:               400000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"xhigh", "high", "medium", "low", "none"},
			DefaultReasoningEffort:      "medium",
			Description:                 "~openai/gpt-mini-latest on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"~openai/gpt-sol-latest": {
			Ratio:             nativeRate(2),
			CompletionRatio:   5,
			CachedInputRatio:  nativeRate(0.19999999999999998),
			CacheWrite5mRatio: nativeRate(2.5),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(4),
				CompletionRatio:     3.75,
				CachedInputRatio:    nativeRate(0.39999999999999997),
				CacheWrite5mRatio:   nativeRate(5),
				InputTokenThreshold: 272000,
			},
			},
			ContextLength:               1050000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low", "none"},
			DefaultReasoningEffort:      "medium",
			Description:                 "~openai/gpt-sol-latest on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"~openai/gpt-terra-latest": {
			Ratio:             nativeRate(2),
			CompletionRatio:   6,
			CachedInputRatio:  nativeRate(0.19999999999999998),
			CacheWrite5mRatio: nativeRate(2.5),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(4),
				CompletionRatio:     4.5,
				CachedInputRatio:    nativeRate(0.39999999999999997),
				CacheWrite5mRatio:   nativeRate(5),
				InputTokenThreshold: 272000,
			},
			},
			ContextLength:               1050000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low", "none"},
			DefaultReasoningEffort:      "medium",
			Description:                 "~openai/gpt-terra-latest on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
