package openrouter

import "github.com/Laisky/one-api/relay/adaptor"

// anthropicModels returns the anthropic model defaults for openrouter.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func anthropicModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"anthropic/claude-3-haiku": {
			Ratio:                       nativeRate(0.25),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.03),
			CacheWrite5mRatio:           nativeRate(0.3),
			CacheWrite1hRatio:           nativeRate(0.5),
			ContextLength:               200000,
			MaxOutputTokens:             4096,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"max_tokens", "stop", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			Description:                 "anthropic/claude-3-haiku on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"anthropic/claude-3.5-haiku": {
			Ratio:                       nativeRate(0.8),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.08),
			CacheWrite5mRatio:           nativeRate(1),
			ContextLength:               200000,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "stop", "max_tokens"},
			Description:                 "Claude 3.5 Haiku features offers enhanced capabilities in speed, coding accuracy, and tool use. Engineered to excel in real-time applications, it delivers quick response times that are essential for dynamic... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"anthropic/claude-fable-5": {
			Ratio:                       nativeRate(1e+01),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(1),
			CacheWrite5mRatio:           nativeRate(12.5),
			CacheWrite1hRatio:           nativeRate(2e+01),
			ContextLength:               1000000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "stop", "structured_outputs", "tool_choice", "tools", "verbosity"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low"},
			DefaultReasoningEffort:      "high",
			Description:                 "anthropic/claude-fable-5 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"anthropic/claude-fable-5.1": {
			Ratio:                       nativeRate(1e+01),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.25),
			CacheWrite5mRatio:           nativeRate(12.5),
			CacheWrite1hRatio:           nativeRate(2e+01),
			ContextLength:               1000000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "stop", "structured_outputs", "tool_choice", "tools", "verbosity"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low"},
			DefaultReasoningEffort:      "high",
			Description:                 "anthropic/claude-fable-5.1 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"anthropic/claude-haiku-4.5": {
			Ratio:                       nativeRate(1),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.09999999999999999),
			CacheWrite5mRatio:           nativeRate(1.25),
			CacheWrite1hRatio:           nativeRate(2),
			ContextLength:               200000,
			MaxOutputTokens:             64000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "response_format", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			Description:                 "anthropic/claude-haiku-4.5 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"anthropic/claude-opus-4": {
			Ratio:                       nativeRate(15),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(1.5),
			CacheWrite5mRatio:           nativeRate(18.75),
			ContextLength:               200000,
			MaxOutputTokens:             32000,
			InputModalities:             []string{"image", "text", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "stop", "max_tokens"},
			Description:                 "Claude Opus 4 is benchmarked as the world’s best coding model, at time of release, bringing sustained performance on complex, long-running tasks and agent workflows. It sets new benchmarks in...",
		},
		"anthropic/claude-opus-4.1": {
			Ratio:                       nativeRate(15),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(1.5),
			CacheWrite5mRatio:           nativeRate(18.75),
			CacheWrite1hRatio:           nativeRate(3e+01),
			ContextLength:               200000,
			MaxOutputTokens:             32000,
			InputModalities:             []string{"image", "text", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "stop", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			Description:                 "anthropic/claude-opus-4.1 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"anthropic/claude-opus-4.5": {
			Ratio:                       nativeRate(5),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.5),
			CacheWrite5mRatio:           nativeRate(6.25),
			CacheWrite1hRatio:           nativeRate(1e+01),
			ContextLength:               200000,
			MaxOutputTokens:             64000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "response_format", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "verbosity"},
			Description:                 "anthropic/claude-opus-4.5 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"anthropic/claude-opus-4.6": {
			Ratio:                       nativeRate(5),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.5),
			CacheWrite5mRatio:           nativeRate(6.25),
			CacheWrite1hRatio:           nativeRate(1e+01),
			ContextLength:               1000000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p", "verbosity"},
			SupportedReasoningEfforts:   []string{"max", "high", "medium", "low"},
			DefaultReasoningEffort:      "high",
			Description:                 "anthropic/claude-opus-4.6 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"anthropic/claude-opus-4.6-fast": {
			Ratio:                       nativeRate(3e+01),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(3),
			CacheWrite5mRatio:           nativeRate(37.5),
			ContextLength:               1000000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "stop", "max_tokens", "verbosity"},
			Description:                 "Fast-mode variant of [Opus 4.6](/anthropic/claude-opus-4.6) - identical capabilities with higher output speed at premium 6x pricing.\n\nLearn more in Anthropic's docs: https://platform.claude.com/docs/en/build-with-claude/fast-mode [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"anthropic/claude-opus-4.7": {
			Ratio:                       nativeRate(5),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.5),
			CacheWrite5mRatio:           nativeRate(6.25),
			CacheWrite1hRatio:           nativeRate(1e+01),
			ContextLength:               1000000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "stop", "structured_outputs", "tool_choice", "tools", "verbosity"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low"},
			DefaultReasoningEffort:      "high",
			Description:                 "anthropic/claude-opus-4.7 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"anthropic/claude-opus-4.7-fast": {
			Ratio:                       nativeRate(3e+01),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(3),
			CacheWrite5mRatio:           nativeRate(37.5),
			ContextLength:               1000000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"stop", "max_tokens", "verbosity"},
			Description:                 "Fast-mode variant of Claude Opus 4.7 - identical capabilities with higher output speed at premium 6x pricing.",
		},
		"anthropic/claude-opus-4.8": {
			Ratio:                       nativeRate(5),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.5),
			CacheWrite5mRatio:           nativeRate(6.25),
			CacheWrite1hRatio:           nativeRate(1e+01),
			ContextLength:               1000000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "verbosity"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low"},
			DefaultReasoningEffort:      "high",
			Description:                 "anthropic/claude-opus-4.8 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"anthropic/claude-opus-4.8-fast": {
			Ratio:                       nativeRate(1e+01),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(1),
			CacheWrite5mRatio:           nativeRate(12.5),
			ContextLength:               1000000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"stop", "max_tokens", "verbosity"},
			Description:                 "Fast-mode (research preview) variant of Claude Opus 4.8 - identical capabilities with higher output speed at 2x pricing.",
		},
		"anthropic/claude-opus-5": {
			Ratio:                       nativeRate(5),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.5),
			CacheWrite5mRatio:           nativeRate(6.25),
			CacheWrite1hRatio:           nativeRate(1e+01),
			ContextLength:               1000000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "verbosity"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low"},
			DefaultReasoningEffort:      "high",
			Description:                 "anthropic/claude-opus-5 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"anthropic/claude-opus-5.5": {
			Ratio:                       nativeRate(4),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.19999999999999998),
			CacheWrite5mRatio:           nativeRate(5),
			CacheWrite1hRatio:           nativeRate(8),
			ContextLength:               1000000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "verbosity"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low"},
			DefaultReasoningEffort:      "high",
			Description:                 "anthropic/claude-opus-5.5 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"anthropic/claude-sonnet-4": {
			Ratio:             nativeRate(3),
			CompletionRatio:   5,
			CachedInputRatio:  nativeRate(0.3),
			CacheWrite5mRatio: nativeRate(3.75),
			CacheWrite1hRatio: nativeRate(6),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(6),
				CompletionRatio:     3.75,
				CachedInputRatio:    nativeRate(0.6),
				CacheWrite5mRatio:   nativeRate(7.5),
				CacheWrite1hRatio:   nativeRate(12),
				InputTokenThreshold: 200000,
			},
			},
			ContextLength:               200000,
			MaxOutputTokens:             64000,
			InputModalities:             []string{"image", "text", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "stop", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			Description:                 "anthropic/claude-sonnet-4 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"anthropic/claude-sonnet-4.5": {
			Ratio:             nativeRate(3),
			CompletionRatio:   5,
			CachedInputRatio:  nativeRate(0.3),
			CacheWrite5mRatio: nativeRate(3.75),
			CacheWrite1hRatio: nativeRate(6),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(6),
				CompletionRatio:     3.75,
				CachedInputRatio:    nativeRate(0.6),
				CacheWrite5mRatio:   nativeRate(7.5),
				CacheWrite1hRatio:   nativeRate(12),
				InputTokenThreshold: 200000,
			},
			},
			ContextLength:               1000000,
			MaxOutputTokens:             64000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "response_format", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			Description:                 "anthropic/claude-sonnet-4.5 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"anthropic/claude-sonnet-4.6": {
			Ratio:                       nativeRate(3),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.3),
			CacheWrite5mRatio:           nativeRate(3.75),
			CacheWrite1hRatio:           nativeRate(6),
			ContextLength:               1000000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p", "verbosity"},
			SupportedReasoningEfforts:   []string{"max", "high", "medium", "low"},
			DefaultReasoningEffort:      "medium",
			Description:                 "anthropic/claude-sonnet-4.6 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"anthropic/claude-sonnet-5": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.19999999999999998),
			CacheWrite5mRatio:           nativeRate(2.5),
			CacheWrite1hRatio:           nativeRate(4),
			ContextLength:               1000000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "stop", "structured_outputs", "tool_choice", "tools", "verbosity"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low"},
			DefaultReasoningEffort:      "high",
			Description:                 "anthropic/claude-sonnet-5 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"~anthropic/claude-fable-latest": {
			Ratio:                       nativeRate(1e+01),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.25),
			CacheWrite5mRatio:           nativeRate(12.5),
			CacheWrite1hRatio:           nativeRate(2e+01),
			ContextLength:               1000000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "stop", "structured_outputs", "tool_choice", "tools", "verbosity"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low"},
			DefaultReasoningEffort:      "high",
			Description:                 "~anthropic/claude-fable-latest on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"~anthropic/claude-haiku-latest": {
			Ratio:                       nativeRate(1),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.09999999999999999),
			CacheWrite5mRatio:           nativeRate(1.25),
			CacheWrite1hRatio:           nativeRate(2),
			ContextLength:               200000,
			MaxOutputTokens:             64000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "response_format", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			Description:                 "~anthropic/claude-haiku-latest on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"~anthropic/claude-opus-latest": {
			Ratio:                       nativeRate(4),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.19999999999999998),
			CacheWrite5mRatio:           nativeRate(5),
			CacheWrite1hRatio:           nativeRate(8),
			ContextLength:               1000000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "verbosity"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low"},
			DefaultReasoningEffort:      "high",
			Description:                 "~anthropic/claude-opus-latest on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"~anthropic/claude-sonnet-latest": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.19999999999999998),
			CacheWrite5mRatio:           nativeRate(2.5),
			CacheWrite1hRatio:           nativeRate(4),
			ContextLength:               1000000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "stop", "structured_outputs", "tool_choice", "tools", "verbosity"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low"},
			DefaultReasoningEffort:      "high",
			Description:                 "~anthropic/claude-sonnet-latest on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
