package openrouter

import "github.com/Laisky/one-api/relay/adaptor"

// metaModels returns the meta model defaults for openrouter.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func metaModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"meta/muse-glimmer-30b": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.04),
			ContextLength:               131072,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"xhigh", "high", "medium", "low"},
			DefaultReasoningEffort:      "medium",
			HuggingFaceID:               "meta-models/Muse-Glimmer-30B",
			Description:                 "meta/muse-glimmer-30b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"meta/muse-spark-1.1": {
			Ratio:                       nativeRate(1.25),
			CompletionRatio:             3.4,
			CachedInputRatio:            nativeRate(0.15),
			ContextLength:               1048576,
			MaxOutputTokens:             943718,
			InputModalities:             []string{"text", "image", "video", "file", "audio"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			SupportedReasoningEfforts:   []string{"xhigh", "high", "medium", "low", "minimal"},
			DefaultReasoningEffort:      "medium",
			Description:                 "meta/muse-spark-1.1 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"meta/muse-spark-1.2": {
			Ratio:                       nativeRate(1.25),
			CompletionRatio:             3.4,
			CachedInputRatio:            nativeRate(0.15),
			ContextLength:               1048576,
			MaxOutputTokens:             943718,
			InputModalities:             []string{"text", "image", "video", "file", "audio"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			SupportedReasoningEfforts:   []string{"xhigh", "high", "medium", "low", "minimal"},
			DefaultReasoningEffort:      "medium",
			Description:                 "meta/muse-spark-1.2 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"meta/muse-spark-1.2-contributor": {
			Ratio:                       nativeRate(0.09999999999999999),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.002),
			ContextLength:               1048576,
			MaxOutputTokens:             943718,
			InputModalities:             []string{"text", "image", "video", "file", "audio"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			SupportedReasoningEfforts:   []string{"xhigh", "high", "medium", "low", "minimal"},
			DefaultReasoningEffort:      "medium",
			Description:                 "meta/muse-spark-1.2-contributor on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"meta/muse-spark-1.3": {
			Ratio:                       nativeRate(1.25),
			CompletionRatio:             3.4,
			CachedInputRatio:            nativeRate(0.15),
			ContextLength:               1048576,
			MaxOutputTokens:             943718,
			InputModalities:             []string{"text", "image", "video", "file", "audio"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low", "minimal"},
			DefaultReasoningEffort:      "medium",
			Description:                 "meta/muse-spark-1.3 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"meta/muse-spark-1.3-contributor": {
			Ratio:                       nativeRate(0.09999999999999999),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.002),
			ContextLength:               1048576,
			MaxOutputTokens:             943718,
			InputModalities:             []string{"text", "image", "video", "file", "audio"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low", "minimal"},
			DefaultReasoningEffort:      "medium",
			Description:                 "meta/muse-spark-1.3-contributor on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
