package openrouter

import "github.com/Laisky/one-api/relay/adaptor"

// meta_llamaModels returns the meta_llama model defaults for openrouter.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func meta_llamaModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"meta-llama/llama-3-70b-instruct": {
			Ratio:                       nativeRate(0.51),
			CompletionRatio:             1.4509803921568627,
			ContextLength:               8192,
			MaxOutputTokens:             8000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			HuggingFaceID:               "meta-llama/Meta-Llama-3-70B-Instruct",
			Description:                 "Meta's latest class of model (Llama 3) launched with a variety of sizes & flavors. This 70B instruct-tuned version was optimized for high quality dialogue usecases. It has demonstrated strong... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"meta-llama/llama-3-8b-instruct": {
			Ratio:                       nativeRate(0.14),
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logit_bias"},
			HuggingFaceID:               "meta-llama/Meta-Llama-3-8B-Instruct",
			Description:                 "Meta's latest class of model (Llama 3) launched with a variety of sizes & flavors. This 8B instruct-tuned version was optimized for high quality dialogue usecases. It has demonstrated strong... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"meta-llama/llama-3.1-70b-instruct": {
			Ratio:                       nativeRate(0.39999999999999997),
			CompletionRatio:             1,
			ContextLength:               131072,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "meta-llama/Meta-Llama-3.1-70B-Instruct",
			Description:                 "meta-llama/llama-3.1-70b-instruct on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"meta-llama/llama-3.1-8b-instruct": {
			Ratio:                       nativeRate(0.049999999999999996),
			CompletionRatio:             1.6,
			CachedInputRatio:            nativeRate(0.024999999999999998),
			ContextLength:               131072,
			MaxOutputTokens:             117964,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "meta-llama/Meta-Llama-3.1-8B-Instruct",
			Description:                 "meta-llama/llama-3.1-8b-instruct on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"meta-llama/llama-3.2-11b-vision-instruct": {
			Ratio:                       nativeRate(0.345),
			CompletionRatio:             1,
			ContextLength:               131072,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logit_bias"},
			HuggingFaceID:               "meta-llama/Llama-3.2-11B-Vision-Instruct",
			Description:                 "Llama 3.2 11B Vision is a multimodal model with 11 billion parameters, designed to handle tasks combining visual and textual data. It excels in tasks such as image captioning and...",
		},
		"meta-llama/llama-3.2-1b-instruct": {
			Ratio:                       nativeRate(0.027),
			CompletionRatio:             7.444444444444445,
			ContextLength:               60000,
			MaxOutputTokens:             54000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "seed", "stop", "temperature", "top_k", "top_p"},
			HuggingFaceID:               "meta-llama/Llama-3.2-1B-Instruct",
			Description:                 "meta-llama/llama-3.2-1b-instruct on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"meta-llama/llama-3.2-3b-instruct": {
			Ratio:                       nativeRate(0.049999999999999996),
			CompletionRatio:             6.6000000000000005,
			ContextLength:               131072,
			MaxOutputTokens:             117964,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "seed", "stop", "structured_outputs", "temperature", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "meta-llama/Llama-3.2-3B-Instruct",
			Description:                 "meta-llama/llama-3.2-3b-instruct on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"meta-llama/llama-3.2-3b-instruct:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "stop", "max_tokens"},
			HuggingFaceID:               "meta-llama/Llama-3.2-3B-Instruct",
			Description:                 "Llama 3.2 3B is a 3-billion-parameter multilingual large language model, optimized for advanced natural language processing tasks like dialogue generation, reasoning, and summarization. Designed with the latest transformer architecture, it...",
		},
		"meta-llama/llama-3.3-70b-instruct": {
			Ratio:                       nativeRate(0.09999999999999999),
			CompletionRatio:             3.2,
			ContextLength:               131072,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "meta-llama/Llama-3.3-70B-Instruct",
			Description:                 "meta-llama/llama-3.3-70b-instruct on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"meta-llama/llama-3.3-70b-instruct:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "stop", "max_tokens"},
			HuggingFaceID:               "meta-llama/Llama-3.3-70B-Instruct",
			Description:                 "The Meta Llama 3.3 multilingual large language model (LLM) is a pretrained and instruction tuned generative model in 70B (text in/text out). The Llama 3.3 instruction tuned text only model...",
		},
		"meta-llama/llama-4-maverick": {
			Ratio:                       nativeRate(0.1875),
			CompletionRatio:             3.48,
			ContextLength:               1048576,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "meta-llama/Llama-4-Maverick-17B-128E-Instruct",
			Description:                 "meta-llama/llama-4-maverick on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"meta-llama/llama-4-scout": {
			Ratio:                       nativeRate(0.09999999999999999),
			CompletionRatio:             3,
			ContextLength:               1310720,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "meta-llama/Llama-4-Scout-17B-16E-Instruct",
			Description:                 "meta-llama/llama-4-scout on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"meta-llama/llama-guard-3-8b": {
			Ratio:                       nativeRate(0.48),
			CompletionRatio:             0.0625,
			ContextLength:               131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "seed", "max_tokens"},
			HuggingFaceID:               "meta-llama/Llama-Guard-3-8B",
			Description:                 "Llama Guard 3 is a Llama-3.1-8B pretrained model, fine-tuned for content safety classification. Similar to previous versions, it can be used to classify content in both LLM inputs (prompt classification)... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"meta-llama/llama-guard-4-12b": {
			Ratio:                       nativeRate(0.18),
			CompletionRatio:             1,
			ContextLength:               163840,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "seed", "stop", "temperature", "top_k", "top_p"},
			HuggingFaceID:               "meta-llama/Llama-Guard-4-12B",
			Description:                 "meta-llama/llama-guard-4-12b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
