package openrouter

import "github.com/Laisky/one-api/relay/adaptor"

// nvidiaModels returns the nvidia model defaults for openrouter.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func nvidiaModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"nvidia/llama-3.3-nemotron-super-49b-v1.5": {
			Ratio:                       nativeRate(0.4),
			CompletionRatio:             1,
			ContextLength:               131072,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logit_bias"},
			HuggingFaceID:               "nvidia/Llama-3_3-Nemotron-Super-49B-v1_5",
			Description:                 "Llama-3.3-Nemotron-Super-49B-v1.5 is a 49B-parameter, English-centric reasoning/chat model derived from Meta’s Llama-3.3-70B-Instruct with a 128K context. It’s post-trained for agentic workflows (RAG, tool calling) via SFT across math, code, science, and...",
		},
		"nvidia/nemotron-3-nano-30b-a3b": {
			Ratio:                       nativeRate(0.049999999999999996),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.03),
			ContextLength:               262144,
			MaxOutputTokens:             235929,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16",
			Description:                 "nvidia/nemotron-3-nano-30b-a3b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"nvidia/nemotron-3-nano-30b-a3b:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               256000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "seed", "max_tokens"},
			HuggingFaceID:               "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16",
			Description:                 "NVIDIA Nemotron 3 Nano 30B A3B is a small language MoE model with highest compute efficiency and accuracy for developers to build specialized agentic AI systems. The model is fully...",
		},
		"nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               256000,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "audio", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "seed", "temperature", "tool_choice", "tools", "top_p"},
			HuggingFaceID:               "nvidia/Nemotron-3-Nano-Omni-30B-A3B-Reasoning-BF16",
			Description:                 "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"nvidia/nemotron-3-super-120b-a12b": {
			Ratio:                       nativeRate(0.08),
			CompletionRatio:             5.624999999999999,
			ContextLength:               262144,
			MaxOutputTokens:             235929,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"medium", "low"},
			DefaultReasoningEffort:      "medium",
			HuggingFaceID:               "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-FP8",
			Description:                 "nvidia/nemotron-3-super-120b-a12b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"nvidia/nemotron-3-super-120b-a12b:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               262144,
			MaxOutputTokens:             235929,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "temperature", "tool_choice", "tools", "top_p"},
			SupportedReasoningEfforts:   []string{"medium", "low"},
			DefaultReasoningEffort:      "medium",
			HuggingFaceID:               "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-FP8",
			Description:                 "nvidia/nemotron-3-super-120b-a12b:free on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"nvidia/nemotron-3-ultra-550b-a55b": {
			Ratio:                       nativeRate(0.6),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.12),
			ContextLength:               262144,
			MaxOutputTokens:             182520,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "max_tokens", "min_p", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			SupportedReasoningEfforts:   []string{"high", "medium"},
			DefaultReasoningEffort:      "high",
			HuggingFaceID:               "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-BF16",
			Description:                 "nvidia/nemotron-3-ultra-550b-a55b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"nvidia/nemotron-3-ultra-550b-a55b:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               1000000,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "reasoning_effort", "seed", "temperature", "tool_choice", "tools", "top_p"},
			SupportedReasoningEfforts:   []string{"high", "medium"},
			DefaultReasoningEffort:      "high",
			HuggingFaceID:               "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-BF16",
			Description:                 "nvidia/nemotron-3-ultra-550b-a55b:free on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"nvidia/nemotron-3.5-content-safety": {
			Ratio:                       nativeRate(0.19999999999999998),
			CompletionRatio:             1,
			ContextLength:               131072,
			MaxOutputTokens:             117964,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "seed", "stop", "temperature", "top_k", "top_p"},
			HuggingFaceID:               "nvidia/Nemotron-3.5-Content-Safety",
			Description:                 "nvidia/nemotron-3.5-content-safety on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"nvidia/nemotron-3.5-content-safety:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               128000,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "seed", "temperature", "top_p"},
			HuggingFaceID:               "nvidia/Nemotron-3.5-Content-Safety",
			Description:                 "nvidia/nemotron-3.5-content-safety:free on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"nvidia/nemotron-3.5-lightning": {
			Ratio:                       nativeRate(0.08),
			CompletionRatio:             2.4999999999999996,
			CachedInputRatio:            nativeRate(0.04),
			ContextLength:               262144,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-BF16",
			Description:                 "nvidia/nemotron-3.5-lightning on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"nvidia/nemotron-3.5-lightning:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               1000000,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "seed", "temperature", "tool_choice", "tools", "top_p"},
			HuggingFaceID:               "nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-BF16",
			Description:                 "nvidia/nemotron-3.5-lightning:free on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"nvidia/nemotron-nano-12b-v2-vl:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               128000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"image", "text", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "seed", "max_tokens"},
			HuggingFaceID:               "nvidia/NVIDIA-Nemotron-Nano-12B-v2-VL-BF16",
			Description:                 "NVIDIA Nemotron Nano 2 VL is a 12-billion-parameter open multimodal reasoning model designed for video understanding and document intelligence. It introduces a hybrid Transformer-Mamba architecture, combining transformer-level accuracy with Mamba’s...",
		},
		"nvidia/nemotron-nano-9b-v2": {
			Ratio:                       nativeRate(0.04),
			CompletionRatio:             4,
			ContextLength:               131072,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logit_bias"},
			HuggingFaceID:               "nvidia/NVIDIA-Nemotron-Nano-9B-v2",
			Description:                 "NVIDIA-Nemotron-Nano-9B-v2 is a large language model (LLM) trained from scratch by NVIDIA, and designed as a unified model for both reasoning and non-reasoning tasks. It responds to user queries and... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"nvidia/nemotron-nano-9b-v2:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               128000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "seed", "max_tokens"},
			HuggingFaceID:               "nvidia/NVIDIA-Nemotron-Nano-9B-v2",
			Description:                 "NVIDIA-Nemotron-Nano-9B-v2 is a large language model (LLM) trained from scratch by NVIDIA, and designed as a unified model for both reasoning and non-reasoning tasks. It responds to user queries and...",
		},
	}
}
