package openrouter

import "github.com/Laisky/one-api/relay/adaptor"

// moonshotaiModels returns the moonshotai model defaults for openrouter.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func moonshotaiModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"moonshotai/kimi-k2": {
			Ratio:                       nativeRate(0.5700000000000001),
			CompletionRatio:             4.035087719298245,
			ContextLength:               131072,
			MaxOutputTokens:             98304,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"frequency_penalty", "max_tokens", "presence_penalty", "repetition_penalty", "seed", "stop", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "moonshotai/Kimi-K2-Instruct",
			Description:                 "moonshotai/kimi-k2 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"moonshotai/kimi-k2-0905": {
			Ratio:                       nativeRate(0.6),
			CompletionRatio:             4.166666666666667,
			ContextLength:               262144,
			MaxOutputTokens:             98304,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "max_tokens", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "moonshotai/Kimi-K2-Instruct-0905",
			Description:                 "moonshotai/kimi-k2-0905 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"moonshotai/kimi-k2-thinking": {
			Ratio:                       nativeRate(0.6),
			CompletionRatio:             4.166666666666667,
			CachedInputRatio:            nativeRate(0.15),
			ContextLength:               262144,
			MaxOutputTokens:             98304,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_tokens", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "moonshotai/Kimi-K2-Thinking",
			Description:                 "moonshotai/kimi-k2-thinking on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"moonshotai/kimi-k2.5": {
			Ratio:                       nativeRate(0.44999999999999996),
			CompletionRatio:             5.000000000000001,
			CachedInputRatio:            nativeRate(0.07),
			ContextLength:               262144,
			MaxOutputTokens:             235929,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "moonshotai/Kimi-K2.5",
			Description:                 "moonshotai/kimi-k2.5 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"moonshotai/kimi-k2.6": {
			Ratio:                       nativeRate(0.95),
			CompletionRatio:             4.2105263157894735,
			CachedInputRatio:            nativeRate(0.16),
			ContextLength:               262144,
			MaxOutputTokens:             235929,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "parallel_tool_calls", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "moonshotai/Kimi-K2.6",
			Description:                 "moonshotai/kimi-k2.6 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"moonshotai/kimi-k2.7-code": {
			Ratio:                       nativeRate(0.7062),
			CompletionRatio:             4.672897196261682,
			CachedInputRatio:            nativeRate(0.18),
			ContextLength:               262144,
			MaxOutputTokens:             235929,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "parallel_tool_calls", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "moonshotai/Kimi-K2.7-Code",
			Description:                 "moonshotai/kimi-k2.7-code on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"moonshotai/kimi-k3": {
			Ratio:                       nativeRate(3),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.3),
			ContextLength:               1048576,
			MaxOutputTokens:             943718,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"max", "high", "low"},
			DefaultReasoningEffort:      "max",
			HuggingFaceID:               "moonshotai/Kimi-K3",
			Description:                 "moonshotai/kimi-k3 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"~moonshotai/kimi-latest": {
			Ratio:                       nativeRate(0.9099999999999999),
			CompletionRatio:             7.678571428571429,
			CachedInputRatio:            nativeRate(0.195),
			ContextLength:               1048576,
			MaxOutputTokens:             943718,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"max", "high", "low"},
			DefaultReasoningEffort:      "max",
			Description:                 "~moonshotai/kimi-latest on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
