package openrouter

import "github.com/Laisky/one-api/relay/adaptor"

// aion_labsModels returns the aion_labs model defaults for openrouter.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func aion_labsModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"aion-labs/aion-1.0": {
			Ratio:                       nativeRate(4),
			CompletionRatio:             2,
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "max_tokens"},
			Description:                 "Aion-1.0 is a multi-model system designed for high performance across various tasks, including reasoning and coding. It is built on DeepSeek-R1, augmented with additional models and techniques such as Tree... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"aion-labs/aion-1.0-mini": {
			Ratio:                       nativeRate(0.7),
			CompletionRatio:             2,
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "max_tokens"},
			HuggingFaceID:               "FuseAI/FuseO1-DeepSeekR1-QwQ-SkyT1-32B-Preview",
			Description:                 "Aion-1.0-Mini 32B parameter model is a distilled version of the DeepSeek-R1 model, designed for strong performance in reasoning domains such as mathematics, coding, and logic. It is a modified variant... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"aion-labs/aion-2.0": {
			Ratio:                       nativeRate(0.7999999999999999),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.19999999999999998),
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "response_format", "temperature", "tool_choice", "tools", "top_p"},
			Description:                 "aion-labs/aion-2.0 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"aion-labs/aion-3.0": {
			Ratio:                       nativeRate(3),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.75),
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "response_format", "temperature", "tool_choice", "tools", "top_p"},
			Description:                 "aion-labs/aion-3.0 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"aion-labs/aion-3.0-mini": {
			Ratio:                       nativeRate(0.7),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.18),
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "response_format", "temperature", "tool_choice", "tools", "top_p"},
			Description:                 "aion-labs/aion-3.0-mini on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"aion-labs/aion-3.5": {
			Ratio:                       nativeRate(3),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.75),
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "reasoning_effort", "response_format", "temperature", "tool_choice", "tools", "top_p"},
			SupportedReasoningEfforts:   []string{"max", "high", "low"},
			DefaultReasoningEffort:      "high",
			Description:                 "aion-labs/aion-3.5 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"aion-labs/aion-3.5-mini": {
			Ratio:                       nativeRate(0.7),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.18),
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "reasoning_effort", "response_format", "temperature", "tool_choice", "tools", "top_p"},
			SupportedReasoningEfforts:   []string{"max", "high", "low"},
			DefaultReasoningEffort:      "high",
			Description:                 "aion-labs/aion-3.5-mini on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"aion-labs/aion-rp-llama-3.1-8b": {
			Ratio:                       nativeRate(0.7999999999999999),
			CompletionRatio:             2,
			ContextLength:               32768,
			MaxOutputTokens:             29491,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"max_tokens", "temperature", "top_p"},
			Description:                 "aion-labs/aion-rp-llama-3.1-8b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
