package openrouter

import "github.com/Laisky/one-api/relay/adaptor"

// xiaomiModels returns the xiaomi model defaults for openrouter.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func xiaomiModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"xiaomi/mimo-v2-flash": {
			Ratio:                       nativeRate(0.1),
			CompletionRatio:             2.9999999999999996,
			CachedInputRatio:            nativeRate(0.01),
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			HuggingFaceID:               "XiaomiMiMo/MiMo-V2-Flash",
			Description:                 "MiMo-V2-Flash is an open-source foundation language model developed by Xiaomi. It is a Mixture-of-Experts model with 309B total parameters and 15B active parameters, adopting hybrid attention architecture. MiMo-V2-Flash supports a... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"xiaomi/mimo-v2-omni": {
			Ratio:                       nativeRate(0.4),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.08),
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "audio", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "max_tokens"},
			Description:                 "MiMo-V2-Omni is a frontier omni-modal model that natively processes image, video, and audio inputs within a unified architecture. It combines strong multimodal perception with agentic capability - visual grounding, multi-step... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"xiaomi/mimo-v2-pro": {
			Ratio:                       nativeRate(1),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.2),
			ContextLength:               1048576,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "max_tokens"},
			Description:                 "MiMo-V2-Pro is Xiaomi's flagship foundation model, featuring over 1T total parameters and a 1M context length, deeply optimized for agentic scenarios. It is highly adaptable to general agent frameworks like... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"xiaomi/mimo-v2.5": {
			Ratio:                       nativeRate(0.14),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.0028),
			ContextLength:               1050000,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text", "audio", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "XiaomiMiMo/MiMo-V2.5",
			Description:                 "xiaomi/mimo-v2.5 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"xiaomi/mimo-v2.5-pro": {
			Ratio:                       nativeRate(0.435),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.0036),
			ContextLength:               1050000,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "XiaomiMiMo/MiMo-V2.5-Pro",
			Description:                 "xiaomi/mimo-v2.5-pro on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"xiaomi/mimo-v2.6-flash": {
			Ratio:                       nativeRate(0.14),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.0028),
			ContextLength:               1048576,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text", "image", "video", "audio"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "XiaomiMiMo/MiMo-V2.6-Flash-RL",
			Description:                 "xiaomi/mimo-v2.6-flash on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"xiaomi/mimo-v2.6-pro": {
			Ratio:                       nativeRate(0.435),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.0036),
			ContextLength:               1048576,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text", "image", "video", "audio"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "XiaomiMiMo/MiMo-V2.6-Pro-RL",
			Description:                 "xiaomi/mimo-v2.6-pro on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"xiaomi/mimo-v2.6-pro-ultraspeed": {
			Ratio:                       nativeRate(4.35),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.036),
			ContextLength:               1048576,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text", "image", "video", "audio"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "max_tokens", "presence_penalty", "reasoning", "response_format", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_p"},
			Description:                 "xiaomi/mimo-v2.6-pro-ultraspeed on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
