package openrouter

import "github.com/Laisky/one-api/relay/adaptor"

// minimaxModels returns the minimax model defaults for openrouter.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func minimaxModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"minimax/minimax-01": {
			Ratio:                       nativeRate(0.19999999999999998),
			CompletionRatio:             5.500000000000001,
			ContextLength:               1000192,
			MaxOutputTokens:             900172,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"max_tokens", "temperature", "top_p"},
			HuggingFaceID:               "MiniMaxAI/MiniMax-Text-01",
			Description:                 "minimax/minimax-01 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"minimax/minimax-m1": {
			Ratio:                       nativeRate(0.39999999999999997),
			CompletionRatio:             5.500000000000001,
			ContextLength:               1000000,
			MaxOutputTokens:             40000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "max_tokens", "presence_penalty", "reasoning", "repetition_penalty", "seed", "stop", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			Description:                 "minimax/minimax-m1 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"minimax/minimax-m2": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             4,
			ContextLength:               204800,
			MaxOutputTokens:             176947,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_tokens", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "MiniMaxAI/MiniMax-M2",
			Description:                 "minimax/minimax-m2 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"minimax/minimax-m2-her": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.03),
			ContextLength:               65536,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"max_tokens", "temperature", "top_p"},
			Description:                 "minimax/minimax-m2-her on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"minimax/minimax-m2.1": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.03),
			ContextLength:               204800,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "max_tokens", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "MiniMaxAI/MiniMax-M2.1",
			Description:                 "minimax/minimax-m2.1 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"minimax/minimax-m2.5": {
			Ratio:                       nativeRate(0.27),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.027),
			ContextLength:               204800,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "MiniMaxAI/MiniMax-M2.5",
			Description:                 "minimax/minimax-m2.5 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"minimax/minimax-m2.5:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               196608,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "stop", "seed", "max_tokens"},
			HuggingFaceID:               "MiniMaxAI/MiniMax-M2.5",
			Description:                 "MiniMax-M2.5 is a SOTA large language model designed for real-world productivity. Trained in a diverse range of complex real-world digital working environments, M2.5 builds upon the coding expertise of M2.1... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"minimax/minimax-m2.7": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.06),
			ContextLength:               204800,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "MiniMaxAI/MiniMax-M2.7",
			Description:                 "minimax/minimax-m2.7 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"minimax/minimax-m3": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.06),
			ContextLength:               1048576,
			MaxOutputTokens:             512000,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "MiniMaxAI/Minimax-M3",
			Description:                 "minimax/minimax-m3 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
