package openrouter

import "github.com/Laisky/one-api/relay/adaptor"

// openaiModels returns the openai model defaults for openrouter.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func openaiModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"openai/gpt-3.5-turbo": {
			Ratio:                       nativeRate(0.5),
			CompletionRatio:             3,
			ContextLength:               16385,
			MaxOutputTokens:             4096,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_logprobs", "top_p"},
			Description:                 "openai/gpt-3.5-turbo on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-3.5-turbo-0613": {
			Ratio:                       nativeRate(1),
			CompletionRatio:             2,
			ContextLength:               4095,
			MaxOutputTokens:             3685,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_completion_tokens", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_logprobs", "top_p"},
			Description:                 "openai/gpt-3.5-turbo-0613 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-3.5-turbo-16k": {
			Ratio:                       nativeRate(3),
			CompletionRatio:             1.3333333333333333,
			ContextLength:               16385,
			MaxOutputTokens:             4096,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_completion_tokens", "max_tokens", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_logprobs", "top_p"},
			Description:                 "openai/gpt-3.5-turbo-16k on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-3.5-turbo-instruct": {
			Ratio:                       nativeRate(1.5),
			CompletionRatio:             1.3333333333333333,
			ContextLength:               4095,
			MaxOutputTokens:             3685,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "top_logprobs", "top_p"},
			Description:                 "openai/gpt-3.5-turbo-instruct on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-4": {
			Ratio:                       nativeRate(3e+01),
			CompletionRatio:             2,
			ContextLength:               8191,
			MaxOutputTokens:             4096,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_completion_tokens", "max_tokens", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_logprobs", "top_p"},
			Description:                 "openai/gpt-4 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-4-0314": {
			Ratio:                       nativeRate(3e+01),
			CompletionRatio:             2,
			ContextLength:               8191,
			MaxOutputTokens:             4096,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens", "logit_bias"},
			Description:                 "GPT-4-0314 is the first version of GPT-4 released, with a context length of 8,192 tokens, and was supported until June 14. Training data: up to Sep 2021. [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"openai/gpt-4-1106-preview": {
			Ratio:                       nativeRate(1e+01),
			CompletionRatio:             3,
			ContextLength:               128000,
			MaxOutputTokens:             4096,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens", "logit_bias"},
			Description:                 "The latest GPT-4 Turbo model with vision capabilities. Vision requests can now use JSON mode and function calling.\n\nTraining data: up to April 2023. [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"openai/gpt-4-turbo": {
			Ratio:                       nativeRate(1e+01),
			CompletionRatio:             3,
			ContextLength:               128000,
			MaxOutputTokens:             4096,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_logprobs", "top_p"},
			Description:                 "openai/gpt-4-turbo on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-4-turbo-preview": {
			Ratio:                       nativeRate(1e+01),
			CompletionRatio:             3,
			ContextLength:               128000,
			MaxOutputTokens:             4096,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens", "logit_bias"},
			Description:                 "The preview GPT-4 model with improved instruction following, JSON mode, reproducible outputs, parallel function calling, and more. Training data: up to Dec 2023. **Note:** heavily rate limited by OpenAI while...",
		},
		"openai/gpt-4.1": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.5),
			ContextLength:               1047576,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"image", "text", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"max_completion_tokens", "max_tokens", "response_format", "seed", "structured_outputs", "temperature", "tool_choice", "tools", "top_p"},
			Description:                 "openai/gpt-4.1 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-4.1-mini": {
			Ratio:                       nativeRate(0.39999999999999997),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.09999999999999999),
			ContextLength:               1047576,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"image", "text", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"max_completion_tokens", "max_tokens", "response_format", "seed", "structured_outputs", "temperature", "tool_choice", "tools", "top_p"},
			Description:                 "openai/gpt-4.1-mini on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-4.1-nano": {
			Ratio:                       nativeRate(0.09999999999999999),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.024999999999999998),
			ContextLength:               1047576,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"image", "text", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"max_completion_tokens", "max_tokens", "response_format", "seed", "structured_outputs", "temperature", "tool_choice", "tools", "top_p"},
			Description:                 "openai/gpt-4.1-nano on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-4o": {
			Ratio:                       nativeRate(2.5),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(1.25),
			ContextLength:               128000,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_completion_tokens", "max_tokens", "prediction", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_logprobs", "top_p", "web_search_options"},
			Description:                 "openai/gpt-4o on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-4o-2024-05-13": {
			Ratio:                       nativeRate(5),
			CompletionRatio:             3,
			ContextLength:               128000,
			MaxOutputTokens:             4096,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_completion_tokens", "max_tokens", "prediction", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_logprobs", "top_p", "web_search_options"},
			Description:                 "openai/gpt-4o-2024-05-13 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-4o-2024-08-06": {
			Ratio:                       nativeRate(2.5),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(1.25),
			ContextLength:               128000,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_completion_tokens", "max_tokens", "prediction", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_logprobs", "top_p", "web_search_options"},
			Description:                 "openai/gpt-4o-2024-08-06 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-4o-2024-11-20": {
			Ratio:                       nativeRate(2.5),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(1.25),
			ContextLength:               128000,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "prediction", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_logprobs", "top_p", "web_search_options"},
			Description:                 "openai/gpt-4o-2024-11-20 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-4o-audio-preview": {
			Ratio:                       nativeRate(2.5),
			CompletionRatio:             4,
			ContextLength:               128000,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"audio", "text"},
			OutputModalities:            []string{"text", "audio"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens", "logit_bias"},
			Description:                 "The gpt-4o-audio-preview model adds support for audio inputs as prompts. This enhancement allows the model to detect nuances within audio recordings and add depth to generated user experiences. Audio outputs... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"openai/gpt-4o-mini": {
			Ratio:                       nativeRate(0.15),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.075),
			ContextLength:               128000,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_completion_tokens", "max_tokens", "prediction", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_logprobs", "top_p", "web_search_options"},
			Description:                 "openai/gpt-4o-mini on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-4o-mini-2024-07-18": {
			Ratio:                       nativeRate(0.15),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.075),
			ContextLength:               128000,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "prediction", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_logprobs", "top_p", "web_search_options"},
			Description:                 "openai/gpt-4o-mini-2024-07-18 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-4o-mini-search-preview": {
			Ratio:                       nativeRate(0.15),
			CompletionRatio:             4,
			ContextLength:               128000,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs", "web_search"},
			SupportedSamplingParameters: []string{"max_tokens"},
			Description:                 "GPT-4o mini Search Preview is a specialized model for web search in Chat Completions. It is trained to understand and execute web search queries.",
		},
		"openai/gpt-4o-search-preview": {
			Ratio:                       nativeRate(2.5),
			CompletionRatio:             4,
			ContextLength:               128000,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs", "web_search"},
			SupportedSamplingParameters: []string{"max_tokens"},
			Description:                 "GPT-4o Search Previewis a specialized model for web search in Chat Completions. It is trained to understand and execute web search queries.",
		},
		"openai/gpt-5": {
			Ratio:                       nativeRate(1.25),
			CompletionRatio:             8,
			CachedInputRatio:            nativeRate(0.125),
			ContextLength:               400000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"high", "medium", "low", "minimal"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-5 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-5-chat": {
			Ratio:                       nativeRate(1.25),
			CompletionRatio:             8,
			CachedInputRatio:            nativeRate(0.125),
			ContextLength:               128000,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			Description:                 "GPT-5 Chat is designed for advanced, natural, multimodal, and context-aware conversations for enterprise applications.",
		},
		"openai/gpt-5-codex": {
			Ratio:                       nativeRate(1.25),
			CompletionRatio:             8,
			CachedInputRatio:            nativeRate(0.125),
			ContextLength:               400000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			Description:                 "GPT-5-Codex is a specialized version of GPT-5 optimized for software engineering and coding workflows. It is designed for both interactive development sessions and long, independent execution of complex engineering tasks....",
		},
		"openai/gpt-5-image": {
			Ratio:                       nativeRate(1e+01),
			CompletionRatio:             1,
			CachedInputRatio:            nativeRate(1.25),
			ContextLength:               400000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"image", "text", "file"},
			OutputModalities:            []string{"image", "text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs", "logprobs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens", "logit_bias"},
			Description:                 "[GPT-5](https://openrouter.ai/openai/gpt-5) Image combines OpenAI's GPT-5 model with state-of-the-art image generation capabilities. It offers major improvements in reasoning, code quality, and user experience while incorporating GPT Image 1's superior instruction following,...",
		},
		"openai/gpt-5-image-mini": {
			Ratio:                       nativeRate(2.5),
			CompletionRatio:             0.8,
			CachedInputRatio:            nativeRate(0.25),
			ContextLength:               400000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"image", "text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs", "logprobs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens", "logit_bias"},
			Description:                 "GPT-5 Image Mini combines OpenAI's advanced language capabilities, powered by [GPT-5 Mini](https://openrouter.ai/openai/gpt-5-mini), with GPT Image 1 Mini for efficient image generation. This natively multimodal model features superior instruction following, text...",
		},
		"openai/gpt-5-mini": {
			Ratio:                       nativeRate(0.25),
			CompletionRatio:             8,
			CachedInputRatio:            nativeRate(0.024999999999999998),
			ContextLength:               400000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"high", "medium", "low", "minimal"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-5-mini on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-5-nano": {
			Ratio:                       nativeRate(0.049999999999999996),
			CompletionRatio:             8,
			CachedInputRatio:            nativeRate(0.005),
			ContextLength:               400000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"high", "medium", "low", "minimal"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-5-nano on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-5-pro": {
			Ratio:                       nativeRate(15),
			CompletionRatio:             8,
			ContextLength:               400000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"image", "text", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"high"},
			DefaultReasoningEffort:      "high",
			Description:                 "openai/gpt-5-pro on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-5.1": {
			Ratio:                       nativeRate(1.25),
			CompletionRatio:             8,
			CachedInputRatio:            nativeRate(0.125),
			ContextLength:               400000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"image", "text", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"high", "medium", "low", "none"},
			DefaultReasoningEffort:      "none",
			Description:                 "openai/gpt-5.1 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-5.1-chat": {
			Ratio:                       nativeRate(1.25),
			CompletionRatio:             8,
			CachedInputRatio:            nativeRate(0.13),
			ContextLength:               128000,
			MaxOutputTokens:             32000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"seed", "max_tokens", "max_completion_tokens"},
			Description:                 "GPT-5.1 Chat (AKA Instant is the fast, lightweight member of the 5.1 family, optimized for low-latency chat while retaining strong general intelligence. It uses adaptive reasoning to selectively “think” on...",
		},
		"openai/gpt-5.1-codex": {
			Ratio:                       nativeRate(1.25),
			CompletionRatio:             8,
			CachedInputRatio:            nativeRate(0.13),
			ContextLength:               400000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"high", "medium", "low"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-5.1-codex on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-5.1-codex-max": {
			Ratio:                       nativeRate(1.25),
			CompletionRatio:             8,
			CachedInputRatio:            nativeRate(0.125),
			ContextLength:               400000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"xhigh", "high", "medium", "low"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-5.1-codex-max on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-5.1-codex-mini": {
			Ratio:                       nativeRate(0.25),
			CompletionRatio:             8,
			CachedInputRatio:            nativeRate(0.03),
			ContextLength:               400000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"high", "medium", "low"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-5.1-codex-mini on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-5.2": {
			Ratio:                       nativeRate(1.75),
			CompletionRatio:             8,
			CachedInputRatio:            nativeRate(0.175),
			ContextLength:               400000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"xhigh", "high", "medium", "low", "none"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-5.2 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-5.2-chat": {
			Ratio:                       nativeRate(1.75),
			CompletionRatio:             8,
			CachedInputRatio:            nativeRate(0.175),
			ContextLength:               128000,
			MaxOutputTokens:             32000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"max_completion_tokens", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			Description:                 "openai/gpt-5.2-chat on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-5.2-codex": {
			Ratio:                       nativeRate(1.75),
			CompletionRatio:             8,
			CachedInputRatio:            nativeRate(0.175),
			ContextLength:               400000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"xhigh", "high", "medium", "low"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-5.2-codex on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-5.2-pro": {
			Ratio:                       nativeRate(21),
			CompletionRatio:             8,
			ContextLength:               400000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"image", "text", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"xhigh", "high", "medium"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-5.2-pro on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-5.3-chat": {
			Ratio:                       nativeRate(1.75),
			CompletionRatio:             8,
			CachedInputRatio:            nativeRate(0.175),
			ContextLength:               128000,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"seed", "max_tokens", "max_completion_tokens"},
			Description:                 "GPT-5.3 Chat is an update to ChatGPT's most-used model that makes everyday conversations smoother, more useful, and more directly helpful. It delivers more accurate answers with better contextualization and significantly...",
		},
		"openai/gpt-5.3-codex": {
			Ratio:                       nativeRate(1.75),
			CompletionRatio:             8,
			CachedInputRatio:            nativeRate(0.175),
			ContextLength:               400000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"xhigh", "high", "medium", "low", "none"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-5.3-codex on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-5.4": {
			Ratio:            nativeRate(2.5),
			CompletionRatio:  6,
			CachedInputRatio: nativeRate(0.25),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(5),
				CompletionRatio:     4.5,
				CachedInputRatio:    nativeRate(0.5),
				InputTokenThreshold: 272000,
			},
			},
			ContextLength:               1050000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"xhigh", "high", "medium", "low", "none"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-5.4 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-5.4-image-2": {
			Ratio:                       nativeRate(8),
			CompletionRatio:             1.875,
			CachedInputRatio:            nativeRate(2),
			ContextLength:               272000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"image", "text", "file"},
			OutputModalities:            []string{"image", "text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs", "logprobs", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens", "logit_bias"},
			Description:                 "[GPT-5.4](https://openrouter.ai/openai/gpt-5.4) Image 2 combines OpenAI's GPT-5.4 model with state-of-the-art image generation capabilities from GPT Image 2. It enables rich multimodal workflows, allowing users to seamlessly move between reasoning, coding, and...",
		},
		"openai/gpt-5.4-mini": {
			Ratio:                       nativeRate(0.75),
			CompletionRatio:             6,
			CachedInputRatio:            nativeRate(0.075),
			ContextLength:               400000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"xhigh", "high", "medium", "low", "none"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-5.4-mini on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-5.4-nano": {
			Ratio:                       nativeRate(0.19999999999999998),
			CompletionRatio:             6.250000000000001,
			CachedInputRatio:            nativeRate(0.02),
			ContextLength:               400000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"xhigh", "high", "medium", "low", "none"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-5.4-nano on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-5.4-pro": {
			Ratio:           nativeRate(3e+01),
			CompletionRatio: 6,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(6e+01),
				CompletionRatio:     4.5,
				InputTokenThreshold: 272000,
			},
			},
			ContextLength:               1050000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"xhigh", "high", "medium"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-5.4-pro on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-5.5": {
			Ratio:            nativeRate(5),
			CompletionRatio:  6,
			CachedInputRatio: nativeRate(0.5),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1e+01),
				CompletionRatio:     4.5,
				CachedInputRatio:    nativeRate(1),
				InputTokenThreshold: 272000,
			},
			},
			ContextLength:               1050000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"xhigh", "high", "medium", "low", "none"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-5.5 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-5.5-pro": {
			Ratio:           nativeRate(3e+01),
			CompletionRatio: 6,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(6e+01),
				CompletionRatio:     4.5,
				InputTokenThreshold: 272000,
			},
			},
			ContextLength:               1050000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"xhigh", "high", "medium"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-5.5-pro on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-5.6-luna": {
			Ratio:             nativeRate(0.19999999999999998),
			CompletionRatio:   6,
			CachedInputRatio:  nativeRate(0.02),
			CacheWrite5mRatio: nativeRate(0.25),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.39999999999999997),
				CompletionRatio:     4.5,
				CachedInputRatio:    nativeRate(0.04),
				CacheWrite5mRatio:   nativeRate(0.5),
				InputTokenThreshold: 272000,
			},
			},
			ContextLength:               1050000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low", "none"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-5.6-luna on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-5.6-luna-pro": {
			Ratio:             nativeRate(0.19999999999999998),
			CompletionRatio:   6,
			CachedInputRatio:  nativeRate(0.02),
			CacheWrite5mRatio: nativeRate(0.25),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.39999999999999997),
				CompletionRatio:     4.5,
				CachedInputRatio:    nativeRate(0.04),
				CacheWrite5mRatio:   nativeRate(0.5),
				InputTokenThreshold: 272000,
			},
			},
			ContextLength:               1050000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low", "none"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-5.6-luna-pro on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-5.6-sol": {
			Ratio:             nativeRate(2),
			CompletionRatio:   5,
			CachedInputRatio:  nativeRate(0.19999999999999998),
			CacheWrite5mRatio: nativeRate(2.5),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(4),
				CompletionRatio:     3.75,
				CachedInputRatio:    nativeRate(0.39999999999999997),
				CacheWrite5mRatio:   nativeRate(5),
				InputTokenThreshold: 272000,
			},
			},
			ContextLength:               1050000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low", "none"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-5.6-sol on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-5.6-sol-pro": {
			Ratio:             nativeRate(2),
			CompletionRatio:   5,
			CachedInputRatio:  nativeRate(0.19999999999999998),
			CacheWrite5mRatio: nativeRate(2.5),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(4),
				CompletionRatio:     3.75,
				CachedInputRatio:    nativeRate(0.39999999999999997),
				CacheWrite5mRatio:   nativeRate(5),
				InputTokenThreshold: 272000,
			},
			},
			ContextLength:               1050000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"file", "image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_completion_tokens", "max_tokens", "reasoning", "reasoning_effort", "response_format", "seed", "structured_outputs", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low", "none"},
			DefaultReasoningEffort:      "medium",
			Description:                 "openai/gpt-5.6-sol-pro on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
