package openrouter

import "github.com/Laisky/one-api/relay/adaptor"

// z_aiModels returns the z_ai model defaults for openrouter.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func z_aiModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"z-ai/glm-4-32b": {
			Ratio:                       nativeRate(0.1),
			CompletionRatio:             1,
			ContextLength:               128000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "max_tokens"},
			Description:                 "GLM 4 32B is a cost-effective foundation language model. It can efficiently perform complex tasks and has significantly enhanced capabilities in tool use, online search, and code-related intelligent tasks. It... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"z-ai/glm-4.5": {
			Ratio:                       nativeRate(0.6),
			CompletionRatio:             3.666666666666667,
			CachedInputRatio:            nativeRate(0.11),
			ContextLength:               131072,
			MaxOutputTokens:             98304,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "response_format", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "zai-org/GLM-4.5",
			Description:                 "z-ai/glm-4.5 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"z-ai/glm-4.5-air": {
			Ratio:                       nativeRate(0.13),
			CompletionRatio:             6.538461538461538,
			CachedInputRatio:            nativeRate(0.024999999999999998),
			ContextLength:               131072,
			MaxOutputTokens:             98304,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "max_tokens", "presence_penalty", "reasoning", "repetition_penalty", "seed", "stop", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "zai-org/GLM-4.5-Air",
			Description:                 "z-ai/glm-4.5-air on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"z-ai/glm-4.5-air:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               131072,
			MaxOutputTokens:             96000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "max_tokens"},
			HuggingFaceID:               "zai-org/GLM-4.5-Air",
			Description:                 "GLM-4.5-Air is the lightweight variant of our latest flagship model family, also purpose-built for agent-centric applications. Like GLM-4.5, it adopts the Mixture-of-Experts (MoE) architecture but with a more compact parameter... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"z-ai/glm-4.5v": {
			Ratio:                       nativeRate(0.6),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.11),
			ContextLength:               65536,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "max_tokens", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "zai-org/GLM-4.5V",
			Description:                 "z-ai/glm-4.5v on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"z-ai/glm-4.6": {
			Ratio:                       nativeRate(0.43),
			CompletionRatio:             4.069767441860465,
			CachedInputRatio:            nativeRate(0.08),
			ContextLength:               204800,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "zai-org/GLM-4.6",
			Description:                 "z-ai/glm-4.6 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"z-ai/glm-4.6v": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.055),
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"image", "text", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "max_tokens", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "zai-org/GLM-4.6V",
			Description:                 "z-ai/glm-4.6v on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"z-ai/glm-4.7": {
			Ratio:                       nativeRate(0.39999999999999997),
			CompletionRatio:             4.375,
			CachedInputRatio:            nativeRate(0.08),
			ContextLength:               204800,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_a", "top_k", "top_p"},
			HuggingFaceID:               "zai-org/GLM-4.7",
			Description:                 "z-ai/glm-4.7 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"z-ai/glm-4.7-flash": {
			Ratio:                       nativeRate(0.060500000000000005),
			CompletionRatio:             6.611570247933884,
			CachedInputRatio:            nativeRate(0.01),
			ContextLength:               200000,
			MaxOutputTokens:             117964,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "zai-org/GLM-4.7-Flash",
			Description:                 "z-ai/glm-4.7-flash on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"z-ai/glm-5": {
			Ratio:                       nativeRate(0.6),
			CompletionRatio:             3.2,
			CachedInputRatio:            nativeRate(0.12),
			ContextLength:               204800,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_tokens", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "zai-org/GLM-5",
			Description:                 "z-ai/glm-5 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"z-ai/glm-5-turbo": {
			Ratio:                       nativeRate(1.2),
			CompletionRatio:             3.3333333333333335,
			CachedInputRatio:            nativeRate(0.24),
			ContextLength:               202752,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "response_format", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			Description:                 "z-ai/glm-5-turbo on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"z-ai/glm-5.1": {
			Ratio:                       nativeRate(0.966),
			CompletionRatio:             3.142857142857143,
			CachedInputRatio:            nativeRate(0.1794),
			ContextLength:               204800,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "zai-org/GLM-5.1",
			Description:                 "z-ai/glm-5.1 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"z-ai/glm-5.2": {
			Ratio:                       nativeRate(0.6496),
			CompletionRatio:             3.142857142857143,
			CachedInputRatio:            nativeRate(0.12064),
			ContextLength:               1048576,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "parallel_tool_calls", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"xhigh", "high"},
			DefaultReasoningEffort:      "high",
			HuggingFaceID:               "zai-org/GLM-5.2",
			Description:                 "z-ai/glm-5.2 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"z-ai/glm-5.2:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             29491,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "max_tokens", "min_p", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "seed", "stop", "temperature", "top_k", "top_p"},
			SupportedReasoningEfforts:   []string{"xhigh", "high"},
			DefaultReasoningEffort:      "high",
			HuggingFaceID:               "zai-org/GLM-5.2",
			Description:                 "z-ai/glm-5.2:free on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"z-ai/glm-5.3": {
			Ratio:                       nativeRate(0.84),
			CompletionRatio:             3.1428571428571432,
			CachedInputRatio:            nativeRate(0.156),
			ContextLength:               1310720,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "parallel_tool_calls", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"max", "high", "low"},
			DefaultReasoningEffort:      "max",
			HuggingFaceID:               "zai-org/GLM-5.3",
			Description:                 "z-ai/glm-5.3 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"z-ai/glm-5.3-flash": {
			Ratio:                       nativeRate(0.15),
			CompletionRatio:             3.3333333333333335,
			CachedInputRatio:            nativeRate(0.049999999999999996),
			ContextLength:               1310720,
			MaxOutputTokens:             943718,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "parallel_tool_calls", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"max", "high", "low"},
			DefaultReasoningEffort:      "max",
			HuggingFaceID:               "zai-org/GLM-5.3-Flash",
			Description:                 "z-ai/glm-5.3-flash on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"z-ai/glm-5.3-flashx": {
			Ratio:                       nativeRate(0.37),
			CompletionRatio:             3.3783783783783785,
			CachedInputRatio:            nativeRate(0.09),
			ContextLength:               1048576,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "reasoning_effort", "response_format", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			SupportedReasoningEfforts:   []string{"max", "high", "low"},
			DefaultReasoningEffort:      "max",
			Description:                 "z-ai/glm-5.3-flashx on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"z-ai/glm-5.3-prime": {
			Ratio:                       nativeRate(2.8),
			CompletionRatio:             3.1428571428571432,
			CachedInputRatio:            nativeRate(0.56),
			ContextLength:               1000000,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_tokens", "presence_penalty", "reasoning", "reasoning_effort", "response_format", "seed", "stop", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"max", "high", "low"},
			DefaultReasoningEffort:      "max",
			Description:                 "z-ai/glm-5.3-prime on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"z-ai/glm-5v-turbo": {
			Ratio:                       nativeRate(1.2),
			CompletionRatio:             3.3333333333333335,
			CachedInputRatio:            nativeRate(0.24),
			ContextLength:               202752,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"image", "text", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "response_format", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			Description:                 "z-ai/glm-5v-turbo on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"~z-ai/glm-flash-latest": {
			Ratio:                       nativeRate(0.075),
			CompletionRatio:             3.3333333333333335,
			CachedInputRatio:            nativeRate(0.015),
			ContextLength:               1310720,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "parallel_tool_calls", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"max", "high", "low"},
			DefaultReasoningEffort:      "max",
			Description:                 "~z-ai/glm-flash-latest on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"~z-ai/glm-latest": {
			Ratio:                       nativeRate(0.5625),
			CompletionRatio:             4.444444444444445,
			CachedInputRatio:            nativeRate(0.125),
			ContextLength:               1310720,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "parallel_tool_calls", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"max", "high", "low"},
			DefaultReasoningEffort:      "max",
			Description:                 "~z-ai/glm-latest on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
