package openrouter

import "github.com/Laisky/one-api/relay/adaptor"

// mistralaiModels returns the mistralai model defaults for openrouter.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func mistralaiModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"mistralai/codestral-2508": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.03),
			ContextLength:               256000,
			MaxOutputTokens:             204800,
			InputModalities:             []string{"text", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "max_tokens", "prediction", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_p"},
			Description:                 "mistralai/codestral-2508 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"mistralai/devstral-2512": {
			Ratio:                       nativeRate(0.4),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.04),
			ContextLength:               262144,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			HuggingFaceID:               "mistralai/Devstral-2-123B-Instruct-2512",
			Description:                 "Devstral 2 is a state-of-the-art open-source model by Mistral AI specializing in agentic coding. It is a 123B-parameter dense transformer model supporting a 256K context window. Devstral 2 supports exploring...",
		},
		"mistralai/devstral-medium": {
			Ratio:                       nativeRate(0.4),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.04),
			ContextLength:               131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Devstral Medium is a high-performance code generation and agentic reasoning model developed jointly by Mistral AI and All Hands AI. Positioned as a step up from Devstral Small, it achieves... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"mistralai/devstral-small": {
			Ratio:                       nativeRate(0.1),
			CompletionRatio:             2.9999999999999996,
			CachedInputRatio:            nativeRate(0.01),
			ContextLength:               131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			HuggingFaceID:               "mistralai/Devstral-Small-2507",
			Description:                 "Devstral Small 1.1 is a 24B parameter open-weight language model for software engineering agents, developed by Mistral AI in collaboration with All Hands AI. Finetuned from Mistral Small 3.1 and... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"mistralai/ministral-14b-2512": {
			Ratio:                       nativeRate(0.19999999999999998),
			CompletionRatio:             1,
			CachedInputRatio:            nativeRate(0.02),
			ContextLength:               262144,
			MaxOutputTokens:             209715,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "max_tokens", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_p"},
			HuggingFaceID:               "mistralai/Ministral-3-14B-Instruct-2512",
			Description:                 "mistralai/ministral-14b-2512 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"mistralai/ministral-3b-2512": {
			Ratio:                       nativeRate(0.09999999999999999),
			CompletionRatio:             1,
			CachedInputRatio:            nativeRate(0.01),
			ContextLength:               131072,
			MaxOutputTokens:             104857,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "max_tokens", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_p"},
			HuggingFaceID:               "mistralai/Ministral-3-3B-Instruct-2512",
			Description:                 "mistralai/ministral-3b-2512 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"mistralai/ministral-8b-2512": {
			Ratio:                       nativeRate(0.15),
			CompletionRatio:             1,
			CachedInputRatio:            nativeRate(0.015),
			ContextLength:               262144,
			MaxOutputTokens:             209715,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "max_tokens", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_p"},
			HuggingFaceID:               "mistralai/Ministral-3-8B-Instruct-2512",
			Description:                 "mistralai/ministral-8b-2512 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"mistralai/mistral-7b-instruct-v0.1": {
			Ratio:                       nativeRate(0.11),
			CompletionRatio:             1.7272727272727273,
			ContextLength:               2824,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "seed", "max_tokens"},
			HuggingFaceID:               "mistralai/Mistral-7B-Instruct-v0.1",
			Description:                 "A 7.3B parameter model that outperforms Llama 2 13B on all benchmarks, with optimizations for speed and context length. [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"mistralai/mistral-large": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.19999999999999998),
			ContextLength:               128000,
			MaxOutputTokens:             102400,
			InputModalities:             []string{"text", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "max_tokens", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_p"},
			Description:                 "mistralai/mistral-large on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"mistralai/mistral-large-2407": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.19999999999999998),
			ContextLength:               131072,
			MaxOutputTokens:             104857,
			InputModalities:             []string{"text", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "max_tokens", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_p"},
			Description:                 "mistralai/mistral-large-2407 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"mistralai/mistral-large-2411": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.2),
			ContextLength:               131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Mistral Large 2 2411 is an update of [Mistral Large 2](/mistralai/mistral-large) released together with [Pixtral Large 2411](/mistralai/pixtral-large-2411) It provides a significant upgrade on the previous [Mistral Large 24.07](/mistralai/mistral-large-2407), with notable... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"mistralai/mistral-large-2512": {
			Ratio:                       nativeRate(0.5),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.05),
			ContextLength:               262144,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Mistral Large 3 2512 is Mistral’s most capable model to date, featuring a sparse mixture-of-experts architecture with 41B active parameters (675B total), and released under the Apache 2.0 license.",
		},
		"mistralai/mistral-medium-3": {
			Ratio:                       nativeRate(0.39999999999999997),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.04),
			ContextLength:               131072,
			MaxOutputTokens:             104857,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "max_tokens", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_p"},
			Description:                 "mistralai/mistral-medium-3 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"mistralai/mistral-medium-3-5": {
			Ratio:                       nativeRate(1.5),
			CompletionRatio:             5,
			ContextLength:               262144,
			MaxOutputTokens:             209715,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "max_tokens", "presence_penalty", "reasoning", "reasoning_effort", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_p"},
			SupportedReasoningEfforts:   []string{"high", "none"},
			DefaultReasoningEffort:      "high",
			Description:                 "mistralai/mistral-medium-3-5 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"mistralai/mistral-medium-3.1": {
			Ratio:                       nativeRate(0.39999999999999997),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.04),
			ContextLength:               131072,
			MaxOutputTokens:             104857,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "max_tokens", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_p"},
			Description:                 "mistralai/mistral-medium-3.1 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"mistralai/mistral-nemo": {
			Ratio:                       nativeRate(0.019000000000000003),
			CompletionRatio:             1.5789473684210524,
			ContextLength:               131072,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "mistralai/Mistral-Nemo-Instruct-2407",
			Description:                 "mistralai/mistral-nemo on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"mistralai/mistral-saba": {
			Ratio:                       nativeRate(0.19999999999999998),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.02),
			ContextLength:               32768,
			MaxOutputTokens:             26214,
			InputModalities:             []string{"text", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "max_tokens", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_p"},
			Description:                 "mistralai/mistral-saba on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"mistralai/mistral-small-24b-instruct-2501": {
			Ratio:                       nativeRate(0.049999999999999996),
			CompletionRatio:             1.6,
			ContextLength:               32768,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "top_k", "top_p"},
			HuggingFaceID:               "mistralai/Mistral-Small-24B-Instruct-2501",
			Description:                 "mistralai/mistral-small-24b-instruct-2501 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"mistralai/mistral-small-2603": {
			Ratio:                       nativeRate(0.15),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.015),
			ContextLength:               262144,
			MaxOutputTokens:             209715,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "max_tokens", "presence_penalty", "reasoning", "reasoning_effort", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_p"},
			SupportedReasoningEfforts:   []string{"high", "none"},
			DefaultReasoningEffort:      "high",
			HuggingFaceID:               "mistralai/Mistral-Small-4-119B-2603",
			Description:                 "mistralai/mistral-small-2603 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"mistralai/mistral-small-3.1-24b-instruct": {
			Ratio:                       nativeRate(0.351),
			CompletionRatio:             1.5811965811965811,
			ContextLength:               128000,
			MaxOutputTokens:             102400,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "seed", "stop", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "mistralai/Mistral-Small-3.1-24B-Instruct-2503",
			Description:                 "mistralai/mistral-small-3.1-24b-instruct on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"mistralai/mistral-small-3.2-24b-instruct": {
			Ratio:                       nativeRate(0.09375),
			CompletionRatio:             2.6666666666666665,
			ContextLength:               256000,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "mistralai/Mistral-Small-3.2-24B-Instruct-2506",
			Description:                 "mistralai/mistral-small-3.2-24b-instruct on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"mistralai/mixtral-8x22b-instruct": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.19999999999999998),
			ContextLength:               65536,
			MaxOutputTokens:             52428,
			InputModalities:             []string{"text", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "max_tokens", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_p"},
			HuggingFaceID:               "mistralai/Mixtral-8x22B-Instruct-v0.1",
			Description:                 "mistralai/mixtral-8x22b-instruct on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"mistralai/pixtral-large-2411": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.2),
			ContextLength:               131072,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Pixtral Large is a 124B parameter, open-weight, multimodal model built on top of [Mistral Large 2](/mistralai/mistral-large-2411). The model is able to understand documents, charts and natural images. The model is... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"mistralai/voxtral-small-24b-2507": {
			Ratio:                       nativeRate(0.1),
			CompletionRatio:             2.9999999999999996,
			CachedInputRatio:            nativeRate(0.01),
			ContextLength:               32000,
			InputModalities:             []string{"text", "audio"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "stop", "seed", "max_tokens"},
			HuggingFaceID:               "mistralai/Voxtral-Small-24B-2507",
			Description:                 "Voxtral Small is an enhancement of Mistral Small 3, incorporating state-of-the-art audio input capabilities while retaining best-in-class text performance. It excels at speech transcription, translation and audio understanding. Input audio...",
		},
	}
}
