package openrouter

import "github.com/Laisky/one-api/relay/adaptor"

// deepseekModels returns the deepseek model defaults for openrouter.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func deepseekModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"deepseek/deepseek-chat": {
			Ratio:                       nativeRate(0.32),
			CompletionRatio:             2.7812499999999996,
			ContextLength:               163840,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "deepseek-ai/DeepSeek-V3",
			Description:                 "deepseek/deepseek-chat on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-chat-v3-0324": {
			Ratio:                       nativeRate(0.25),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.135),
			ContextLength:               163840,
			MaxOutputTokens:             147456,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "deepseek-ai/DeepSeek-V3-0324",
			Description:                 "deepseek/deepseek-chat-v3-0324 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-chat-v3.1": {
			Ratio:                       nativeRate(0.25),
			CompletionRatio:             3.8,
			CachedInputRatio:            nativeRate(0.13),
			ContextLength:               163840,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "deepseek-ai/DeepSeek-V3.1",
			Description:                 "deepseek/deepseek-chat-v3.1 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-r1": {
			Ratio:                       nativeRate(0.7),
			CompletionRatio:             3.5714285714285716,
			ContextLength:               64000,
			MaxOutputTokens:             16000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "max_tokens", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "deepseek-ai/DeepSeek-R1",
			Description:                 "deepseek/deepseek-r1 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-r1-0528": {
			Ratio:                       nativeRate(0.5),
			CompletionRatio:             4.300000000000001,
			CachedInputRatio:            nativeRate(0.35),
			ContextLength:               163840,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "deepseek-ai/DeepSeek-R1-0528",
			Description:                 "deepseek/deepseek-r1-0528 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-r1-distill-llama-70b": {
			Ratio:                       nativeRate(0.7999999999999999),
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             7372,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "max_tokens", "presence_penalty", "reasoning", "repetition_penalty", "seed", "stop", "temperature", "top_k", "top_p"},
			HuggingFaceID:               "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
			Description:                 "deepseek/deepseek-r1-distill-llama-70b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-r1-distill-qwen-32b": {
			Ratio:                       nativeRate(0.29),
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs", "logprobs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			HuggingFaceID:               "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
			Description:                 "DeepSeek R1 Distill Qwen 32B is a distilled large language model based on [Qwen 2.5 32B](https://huggingface.co/Qwen/Qwen2.5-32B), using outputs from [DeepSeek R1](/deepseek/deepseek-r1). It outperforms OpenAI's o1-mini across various benchmarks, achieving new... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"deepseek/deepseek-v3.1-terminus": {
			Ratio:                       nativeRate(0.27),
			CompletionRatio:             3.7037037037037033,
			CachedInputRatio:            nativeRate(0.135),
			ContextLength:               163840,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "deepseek-ai/DeepSeek-V3.1-Terminus",
			Description:                 "deepseek/deepseek-v3.1-terminus on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-v3.2": {
			Ratio:                       nativeRate(0.26899999999999996),
			CompletionRatio:             1.4869888475836432,
			CachedInputRatio:            nativeRate(0.13449999999999998),
			ContextLength:               163840,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "deepseek-ai/DeepSeek-V3.2",
			Description:                 "deepseek/deepseek-v3.2 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-v3.2-exp": {
			Ratio:                       nativeRate(0.27),
			CompletionRatio:             1.5185185185185184,
			ContextLength:               163840,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "deepseek-ai/DeepSeek-V3.2-Exp",
			Description:                 "deepseek/deepseek-v3.2-exp on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-v3.2-speciale": {
			Ratio:                       nativeRate(0.287),
			CompletionRatio:             1.5017421602787457,
			CachedInputRatio:            nativeRate(0.058),
			ContextLength:               163840,
			MaxOutputTokens:             163840,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logit_bias"},
			HuggingFaceID:               "deepseek-ai/DeepSeek-V3.2-Speciale",
			Description:                 "DeepSeek-V3.2-Speciale is a high-compute variant of DeepSeek-V3.2 optimized for maximum reasoning and agentic performance. It builds on DeepSeek Sparse Attention (DSA) for efficient long-context processing, then scales post-training reinforcement learning... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"deepseek/deepseek-v4-flash": {
			Ratio:                       nativeRate(0.088606),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.017721200000000003),
			ContextLength:               1048576,
			MaxOutputTokens:             384000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_completion_tokens", "max_tokens", "min_p", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_a", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"xhigh", "high"},
			DefaultReasoningEffort:      "high",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V4-Flash",
			Description:                 "deepseek/deepseek-v4-flash on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-v4-flash-0731": {
			Ratio:                       nativeRate(0.04),
			CompletionRatio:             16,
			CachedInputRatio:            nativeRate(0.016),
			ContextLength:               1310720,
			MaxOutputTokens:             943718,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "parallel_tool_calls", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_a", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"max", "high", "low"},
			DefaultReasoningEffort:      "high",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V4-Flash-0731",
			Description:                 "deepseek/deepseek-v4-flash-0731 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-v4-flash-vision-exp": {
			Ratio:                       nativeRate(0.22),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.007),
			ContextLength:               1048576,
			MaxOutputTokens:             943718,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"max", "high", "low"},
			DefaultReasoningEffort:      "high",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V4-Flash-Vision-Exp",
			Description:                 "deepseek/deepseek-v4-flash-vision-exp on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-v4-flash:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               1048576,
			MaxOutputTokens:             384000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"stop", "max_tokens"},
			HuggingFaceID:               "deepseek-ai/DeepSeek-V4-Flash",
			Description:                 "Free tier of DeepSeek V4 Flash with rate limits. [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"deepseek/deepseek-v4-pro": {
			Ratio:                       nativeRate(0.9396),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.07830000000000001),
			ContextLength:               1048576,
			MaxOutputTokens:             384000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_completion_tokens", "max_tokens", "min_p", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"xhigh", "high"},
			DefaultReasoningEffort:      "high",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V4-Pro",
			Description:                 "deepseek/deepseek-v4-pro on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-v4-pro-0813": {
			Ratio:                       nativeRate(0.46199999999999997),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.015399999999999999),
			ContextLength:               1048576,
			MaxOutputTokens:             384000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"max", "high", "low"},
			DefaultReasoningEffort:      "high",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V4-Pro-0813",
			Description:                 "deepseek/deepseek-v4-pro-0813 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-v4.1-flash": {
			Ratio:                       nativeRate(0.14),
			CompletionRatio:             2.9999999999999996,
			CachedInputRatio:            nativeRate(0.004200000000000001),
			ContextLength:               1048576,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"max", "high", "low"},
			DefaultReasoningEffort:      "high",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V4.1-Flash",
			Description:                 "deepseek/deepseek-v4.1-flash on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"~deepseek/deepseek-flash-latest": {
			Ratio:                       nativeRate(0.099),
			CompletionRatio:             6.06060606060606,
			CachedInputRatio:            nativeRate(0.06),
			ContextLength:               1048576,
			MaxOutputTokens:             943718,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"max", "high", "low"},
			DefaultReasoningEffort:      "high",
			Description:                 "~deepseek/deepseek-flash-latest on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"~deepseek/deepseek-pro-latest": {
			Ratio:                       nativeRate(0.3865),
			CompletionRatio:             7.503234152652006,
			CachedInputRatio:            nativeRate(0.25),
			ContextLength:               1048576,
			MaxOutputTokens:             943718,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"max", "high", "low"},
			DefaultReasoningEffort:      "high",
			Description:                 "~deepseek/deepseek-pro-latest on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"~deepseek/deepseek-v4-flash-latest": {
			Ratio:                       nativeRate(0.038000000000000006),
			CompletionRatio:             14.473684210526315,
			CachedInputRatio:            nativeRate(0.022799999999999997),
			ContextLength:               1310720,
			MaxOutputTokens:             943718,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "parallel_tool_calls", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_a", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"max", "high", "low"},
			DefaultReasoningEffort:      "high",
			Description:                 "~deepseek/deepseek-v4-flash-latest on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
