package openrouter

import "github.com/Laisky/one-api/relay/adaptor"

// nex_agiModels returns the nex_agi model defaults for openrouter.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func nex_agiModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"nex-agi/deepseek-v3.1-nex-n1": {
			Ratio:                       nativeRate(0.135),
			CompletionRatio:             3.7037037037037033,
			ContextLength:               131072,
			MaxOutputTokens:             163840,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "max_tokens"},
			HuggingFaceID:               "nex-agi/DeepSeek-V3.1-Nex-N1",
			Description:                 "DeepSeek V3.1 Nex-N1 is the flagship release of the Nex-N1 series — a post-trained model designed to highlight agent autonomy, tool use, and real-world productivity. Nex-N1 demonstrates competitive performance across... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"nex-agi/nex-n2-pro": {
			Ratio:                       nativeRate(0.25),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.025),
			ContextLength:               262144,
			MaxOutputTokens:             262144,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "max_tokens"},
			HuggingFaceID:               "nex-agi/Nex-N2-Pro",
			Description:                 "Nex-N2-Pro is an agentic mixture-of-experts model from Nex AGI, with 17B active parameters out of 397B total. Built on the Qwen3.5 architecture, it accepts text and image input...",
		},
		"nex-agi/nex-n2-pro:free": {
			Ratio:             0,
			CompletionRatio:   1,
			ContextLength:     262144,
			MaxOutputTokens:   262144,
			InputModalities:   []string{"text", "image"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "structured_outputs", "reasoning", "logprobs"},
			Description:       "[Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"nex-agi/nex-n2.5-mini": {
			Ratio:                       nativeRate(0.024999999999999998),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.0025),
			ContextLength:               262144,
			MaxOutputTokens:             235929,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"include_reasoning", "logprobs", "max_tokens", "reasoning", "reasoning_effort", "structured_outputs", "temperature", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"high", "medium", "none"},
			DefaultReasoningEffort:      "high",
			HuggingFaceID:               "nex-agi/Nex-N2.5-mini",
			Description:                 "nex-agi/nex-n2.5-mini on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"nex-agi/nex-n2.5-mini:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               262144,
			MaxOutputTokens:             235929,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"include_reasoning", "logprobs", "max_tokens", "reasoning", "reasoning_effort", "response_format", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"high", "medium", "none"},
			DefaultReasoningEffort:      "high",
			HuggingFaceID:               "nex-agi/Nex-N2.5-mini",
			Description:                 "nex-agi/nex-n2.5-mini:free on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"nex-agi/nex-n2.5-pro": {
			Ratio:                       nativeRate(0.075),
			CompletionRatio:             3.3333333333333335,
			CachedInputRatio:            nativeRate(0.015),
			ContextLength:               262144,
			MaxOutputTokens:             235929,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"include_reasoning", "logprobs", "max_tokens", "reasoning", "reasoning_effort", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"high", "medium", "none"},
			DefaultReasoningEffort:      "high",
			HuggingFaceID:               "nex-agi/Nex-N2.5-Pro",
			Description:                 "nex-agi/nex-n2.5-pro on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"nex-agi/nex-n2.5-pro:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               262144,
			MaxOutputTokens:             235929,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"include_reasoning", "logprobs", "max_tokens", "reasoning", "reasoning_effort", "response_format", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"high", "medium", "none"},
			DefaultReasoningEffort:      "high",
			HuggingFaceID:               "nex-agi/Nex-N2.5-Pro",
			Description:                 "nex-agi/nex-n2.5-pro:free on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
