package openrouter

import "github.com/Laisky/one-api/relay/adaptor"

// googleModels returns the google model defaults for openrouter.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func googleModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"google/gemini-2.0-flash-001": {
			Ratio:                       nativeRate(0.1),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.025),
			CacheWrite5mRatio:           nativeRate(0.083333333333),
			ContextLength:               1000000,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image", "file", "audio", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "stop", "seed", "max_tokens"},
			Description:                 "Gemini Flash 2.0 offers a significantly faster time to first token (TTFT) compared to [Gemini Flash 1.5](/google/gemini-flash-1.5), while maintaining quality on par with larger models like [Gemini Pro 1.5](/google/gemini-pro-1.5). It... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"google/gemini-2.0-flash-lite-001": {
			Ratio:                       nativeRate(0.075),
			CompletionRatio:             4,
			ContextLength:               1048576,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image", "file", "audio", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "stop", "seed", "max_tokens"},
			Description:                 "Gemini 2.0 Flash Lite offers a significantly faster time to first token (TTFT) compared to [Gemini Flash 1.5](/google/gemini-flash-1.5), while maintaining quality on par with larger models like [Gemini Pro 1.5](/google/gemini-pro-1.5),... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"google/gemini-2.5-flash": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             8.333333333333334,
			CachedInputRatio:            nativeRate(0.03),
			CacheWrite5mRatio:           nativeRate(0.083333333333),
			ContextLength:               1048576,
			MaxOutputTokens:             65535,
			InputModalities:             []string{"file", "image", "text", "audio", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "stop", "seed", "max_tokens"},
			Description:                 "Gemini 2.5 Flash is Google's state-of-the-art workhorse model, specifically designed for advanced reasoning, coding, mathematics, and scientific tasks. It includes built-in \"thinking\" capabilities, enabling it to provide responses with greater...",
		},
		"google/gemini-2.5-flash-image": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             8.333333333333334,
			CachedInputRatio:            nativeRate(0.03),
			CacheWrite5mRatio:           nativeRate(0.083333333333),
			ContextLength:               32768,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"image", "text"},
			OutputModalities:            []string{"image", "text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "stop", "seed", "max_tokens"},
			Description:                 "Gemini 2.5 Flash Image, a.k.a. \"Nano Banana,\" is now generally available. It is a state of the art image generation model with contextual understanding. It is capable of image generation,...",
		},
		"google/gemini-2.5-flash-lite": {
			Ratio:                       nativeRate(0.1),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.01),
			CacheWrite5mRatio:           nativeRate(0.083333333333),
			ContextLength:               1048576,
			MaxOutputTokens:             65535,
			InputModalities:             []string{"text", "image", "file", "audio", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "stop", "seed", "max_tokens"},
			Description:                 "Gemini 2.5 Flash-Lite is a lightweight reasoning model in the Gemini 2.5 family, optimized for ultra-low latency and cost efficiency. It offers improved throughput, faster token generation, and better performance...",
		},
		"google/gemini-2.5-flash-lite-preview-09-2025": {
			Ratio:                       nativeRate(0.1),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.01),
			CacheWrite5mRatio:           nativeRate(0.083333333333),
			ContextLength:               1048576,
			MaxOutputTokens:             65535,
			InputModalities:             []string{"text", "image", "file", "audio", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "stop", "seed", "max_tokens"},
			Description:                 "Gemini 2.5 Flash-Lite is a lightweight reasoning model in the Gemini 2.5 family, optimized for ultra-low latency and cost efficiency. It offers improved throughput, faster token generation, and better performance... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"google/gemini-2.5-pro": {
			Ratio:                       nativeRate(1.25),
			CompletionRatio:             8,
			CachedInputRatio:            nativeRate(0.125),
			CacheWrite5mRatio:           nativeRate(0.375),
			ContextLength:               1048576,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "image", "file", "audio", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "stop", "seed", "max_tokens"},
			Description:                 "Gemini 2.5 Pro is Google’s state-of-the-art AI model designed for advanced reasoning, coding, mathematics, and scientific tasks. It employs “thinking” capabilities, enabling it to reason through responses with enhanced accuracy...",
		},
		"google/gemini-2.5-pro-preview": {
			Ratio:                       nativeRate(1.25),
			CompletionRatio:             8,
			CachedInputRatio:            nativeRate(0.125),
			CacheWrite5mRatio:           nativeRate(0.375),
			ContextLength:               1048576,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"file", "image", "text", "audio"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "stop", "seed", "max_tokens"},
			Description:                 "Gemini 2.5 Pro is Google’s state-of-the-art AI model designed for advanced reasoning, coding, mathematics, and scientific tasks. It employs “thinking” capabilities, enabling it to reason through responses with enhanced accuracy...",
		},
		"google/gemini-2.5-pro-preview-05-06": {
			Ratio:                       nativeRate(1.25),
			CompletionRatio:             8,
			CachedInputRatio:            nativeRate(0.125),
			CacheWrite5mRatio:           nativeRate(0.375),
			ContextLength:               1048576,
			MaxOutputTokens:             65535,
			InputModalities:             []string{"text", "image", "file", "audio", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "stop", "seed", "max_tokens"},
			Description:                 "Gemini 2.5 Pro is Google’s state-of-the-art AI model designed for advanced reasoning, coding, mathematics, and scientific tasks. It employs “thinking” capabilities, enabling it to reason through responses with enhanced accuracy...",
		},
		"google/gemini-3-flash-preview": {
			Ratio:                       nativeRate(0.5),
			CompletionRatio:             6,
			CachedInputRatio:            nativeRate(0.05),
			CacheWrite5mRatio:           nativeRate(0.083333333333),
			ContextLength:               1048576,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "image", "file", "audio", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "stop", "seed", "max_tokens"},
			Description:                 "Gemini 3 Flash Preview is a high speed, high value thinking model designed for agentic workflows, multi turn chat, and coding assistance. It delivers near Pro level reasoning and tool...",
		},
		"google/gemini-3-pro-image": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             6,
			CachedInputRatio:            nativeRate(0.2),
			CacheWrite5mRatio:           nativeRate(0.375),
			ContextLength:               65536,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"image", "text"},
			OutputModalities:            []string{"image", "text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "stop", "seed", "max_tokens"},
			Description:                 "Nano Banana Pro is Google’s most advanced image-generation and editing model, built on Gemini 3 Pro...",
		},
		"google/gemini-3-pro-image-preview": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             6,
			CachedInputRatio:            nativeRate(0.2),
			CacheWrite5mRatio:           nativeRate(0.375),
			ContextLength:               65536,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"image", "text"},
			OutputModalities:            []string{"image", "text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "stop", "seed", "max_tokens"},
			Description:                 "Nano Banana Pro is Google’s most advanced image-generation and editing model, built on Gemini 3 Pro. It extends the original Nano Banana with significantly improved multimodal reasoning, real-world grounding, and...",
		},
		"google/gemini-3.1-flash-image": {
			Ratio:                       nativeRate(0.5),
			CompletionRatio:             6,
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"image", "text"},
			OutputModalities:            []string{"image", "text"},
			SupportedFeatures:           []string{"structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "max_tokens"},
			Description:                 "Gemini 3.1 Flash Image, a.k.a. \"Nano Banana 2,\" is Google’s latest state of the art image generation and editing model, delivering Pro-level visual quality at Flash speed...",
		},
		"google/gemini-3.1-flash-image-preview": {
			Ratio:                       nativeRate(0.5),
			CompletionRatio:             6,
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"image", "text"},
			OutputModalities:            []string{"image", "text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "stop", "seed", "max_tokens"},
			Description:                 "Gemini 3.1 Flash Image Preview, a.k.a. \"Nano Banana 2,\" is Google’s latest state of the art image generation and editing model, delivering Pro-level visual quality at Flash speed. It combines...",
		},
		"google/gemini-3.1-flash-lite": {
			Ratio:                       nativeRate(0.25),
			CompletionRatio:             6,
			CachedInputRatio:            nativeRate(0.025),
			CacheWrite5mRatio:           nativeRate(0.083333333333),
			ContextLength:               1048576,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "image", "video", "file", "audio"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "stop", "seed", "max_tokens"},
			Description:                 "Gemini 3.1 Flash Lite is Google’s GA high-efficiency multimodal model optimized for low-latency, high-volume workloads. It supports text, image, video, audio, and PDF inputs.",
		},
		"google/gemini-3.1-flash-lite-preview": {
			Ratio:                       nativeRate(0.25),
			CompletionRatio:             6,
			CachedInputRatio:            nativeRate(0.025),
			CacheWrite5mRatio:           nativeRate(0.083333333333),
			ContextLength:               1048576,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "image", "video", "file", "audio"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "stop", "seed", "max_tokens"},
			Description:                 "Gemini 3.1 Flash Lite Preview is Google's high-efficiency model optimized for high-volume use cases. It outperforms Gemini 2.5 Flash Lite on overall quality and approaches Gemini 2.5 Flash performance across...",
		},
		"google/gemini-3.1-pro-preview": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             6,
			CachedInputRatio:            nativeRate(0.2),
			CacheWrite5mRatio:           nativeRate(0.375),
			ContextLength:               1048576,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"audio", "file", "image", "text", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "stop", "seed", "max_tokens"},
			Description:                 "Gemini 3.1 Pro Preview is Google’s frontier reasoning model, delivering enhanced software engineering performance, improved agentic reliability, and more efficient token usage across complex workflows. Building on the multimodal foundation...",
		},
		"google/gemini-3.1-pro-preview-customtools": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             6,
			CachedInputRatio:            nativeRate(0.2),
			CacheWrite5mRatio:           nativeRate(0.375),
			ContextLength:               1048576,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "audio", "image", "video", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "stop", "seed", "max_tokens"},
			Description:                 "Gemini 3.1 Pro Preview Custom Tools is a variant of Gemini 3.1 Pro that improves tool selection behavior by preventing overuse of a general bash tool when more efficient third-party...",
		},
		"google/gemini-3.5-flash": {
			Ratio:                       nativeRate(1.5),
			CompletionRatio:             6,
			CachedInputRatio:            nativeRate(0.15),
			CacheWrite5mRatio:           nativeRate(0.083333333333),
			ContextLength:               1048576,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "image", "video", "file", "audio"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "stop", "seed", "max_tokens"},
			Description:                 "Gemini 3.5 Flash is Google's high-efficiency multimodal model, bringing near-Pro level coding and reasoning at Flash-tier cost and speed. Highly optimized for coding proficiency and parallel agentic workflows.",
		},
		"google/gemma-2-27b-it": {
			Ratio:                       nativeRate(0.65),
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "max_tokens", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "top_p"},
			HuggingFaceID:               "google/gemma-2-27b-it",
			Description:                 "google/gemma-2-27b-it on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"google/gemma-3-12b-it": {
			Ratio:                       nativeRate(0.049999999999999996),
			CompletionRatio:             3,
			ContextLength:               131072,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "google/gemma-3-12b-it",
			Description:                 "google/gemma-3-12b-it on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"google/gemma-3-27b-it": {
			Ratio:                       nativeRate(0.08),
			CompletionRatio:             5.624999999999999,
			CachedInputRatio:            nativeRate(0.04),
			ContextLength:               131072,
			MaxOutputTokens:             117964,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "google/gemma-3-27b-it",
			Description:                 "google/gemma-3-27b-it on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"google/gemma-3-4b-it": {
			Ratio:                       nativeRate(0.049999999999999996),
			CompletionRatio:             2,
			ContextLength:               131072,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "top_k", "top_p"},
			HuggingFaceID:               "google/gemma-3-4b-it",
			Description:                 "google/gemma-3-4b-it on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"google/gemma-3n-e4b-it": {
			Ratio:                       nativeRate(0.06),
			CompletionRatio:             2,
			ContextLength:               32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "max_tokens", "logit_bias"},
			HuggingFaceID:               "google/gemma-3n-E4B-it",
			Description:                 "Gemma 3n E4B-it is optimized for efficient execution on mobile and low-resource devices, such as phones, laptops, and tablets. It supports multimodal inputs—including text, visual data, and audio—enabling diverse tasks...",
		},
		"google/gemma-4-26b-a4b-it": {
			Ratio:                       nativeRate(0.09),
			CompletionRatio:             3.3333333333333335,
			CachedInputRatio:            nativeRate(0.049999999999999996),
			ContextLength:               262144,
			MaxOutputTokens:             235929,
			InputModalities:             []string{"image", "text", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "google/gemma-4-26B-A4B-it",
			Description:                 "google/gemma-4-26b-a4b-it on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"google/gemma-4-26b-a4b-it:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"image", "text", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "response_format", "seed", "temperature", "tool_choice", "tools", "top_p"},
			HuggingFaceID:               "google/gemma-4-26B-A4B-it",
			Description:                 "google/gemma-4-26b-a4b-it:free on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"google/gemma-4-31b-it": {
			Ratio:                       nativeRate(0.09),
			CompletionRatio:             3.7777777777777777,
			CachedInputRatio:            nativeRate(0.049999999999999996),
			ContextLength:               262144,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"image", "text", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "google/gemma-4-31B-it",
			Description:                 "google/gemma-4-31b-it on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"google/gemma-4-31b-it:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"image", "text", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "response_format", "seed", "temperature", "tool_choice", "tools", "top_p"},
			HuggingFaceID:               "google/gemma-4-31B-it",
			Description:                 "google/gemma-4-31b-it:free on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"google/lyria-3-clip-preview": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               1048576,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text", "audio"},
			SupportedFeatures:           []string{"json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "seed", "max_tokens"},
			Description:                 "30 second duration clips are priced at $0.04 per clip. Lyria 3 is Google's family of music generation models, available through the Gemini API. With Lyria 3, you can generate...",
		},
		"google/lyria-3-pro-preview": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               1048576,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text", "audio"},
			SupportedFeatures:           []string{"json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "seed", "max_tokens"},
			Description:                 "Full-length songs are priced at $0.08 per song. Lyria 3 is Google's family of music generation models, available through the Gemini API. With Lyria 3, you can generate high-quality, 48kHz...",
		},
		"~google/gemini-flash-latest": {
			Ratio:                       nativeRate(1.5),
			CompletionRatio:             6,
			CachedInputRatio:            nativeRate(0.15),
			CacheWrite5mRatio:           nativeRate(0.083333333333),
			ContextLength:               1048576,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "image", "file", "audio", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "stop", "seed", "max_tokens"},
			Description:                 "This model always redirects to the latest model in the Google Gemini Flash family.",
		},
		"~google/gemini-pro-latest": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             6,
			CachedInputRatio:            nativeRate(0.2),
			CacheWrite5mRatio:           nativeRate(0.375),
			ContextLength:               1048576,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"audio", "file", "image", "text", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "stop", "seed", "max_tokens"},
			Description:                 "This model always redirects to the latest model in the Google Gemini Pro family.",
		},
	}
}
