package openrouter

import "github.com/Laisky/one-api/relay/adaptor"

// qwenModels returns the qwen model defaults for openrouter.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func qwenModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"qwen/qwen-2.5-72b-instruct": {
			Ratio:                       nativeRate(0.36),
			CompletionRatio:             1.1111111111111112,
			ContextLength:               32768,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "Qwen/Qwen2.5-72B-Instruct",
			Description:                 "qwen/qwen-2.5-72b-instruct on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen-2.5-7b-instruct": {
			Ratio:                       nativeRate(0.09999999999999999),
			CompletionRatio:             2,
			ContextLength:               32768,
			MaxOutputTokens:             29491,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "Qwen/Qwen2.5-7B-Instruct",
			Description:                 "qwen/qwen-2.5-7b-instruct on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen-2.5-coder-32b-instruct": {
			Ratio:                       nativeRate(0.66),
			CompletionRatio:             1.5151515151515151,
			ContextLength:               32768,
			MaxOutputTokens:             29491,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "temperature", "top_k", "top_p"},
			HuggingFaceID:               "Qwen/Qwen2.5-Coder-32B-Instruct",
			Description:                 "qwen/qwen-2.5-coder-32b-instruct on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen-plus": {
			Ratio:             nativeRate(0.26),
			CompletionRatio:   3,
			CachedInputRatio:  nativeRate(0.052000000000000005),
			CacheWrite5mRatio: nativeRate(0.325),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.78),
				CompletionRatio:     2.9999999999999996,
				CachedInputRatio:    nativeRate(0.156),
				CacheWrite5mRatio:   nativeRate(0.975),
				InputTokenThreshold: 256000,
			},
			},
			ContextLength:               1000000,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logprobs", "max_tokens", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			Description:                 "qwen/qwen-plus on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen-plus-2025-07-28": {
			Ratio:           nativeRate(0.26),
			CompletionRatio: 3,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.78),
				CompletionRatio:     2.9999999999999996,
				InputTokenThreshold: 256000,
			},
			},
			ContextLength:               1000000,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logprobs", "max_tokens", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			Description:                 "qwen/qwen-plus-2025-07-28 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen-plus-2025-07-28:thinking": {
			Ratio:                       nativeRate(0.26),
			CompletionRatio:             3,
			CacheWrite5mRatio:           nativeRate(0.325),
			ContextLength:               1000000,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "presence_penalty", "seed", "max_tokens"},
			Description:                 "Qwen Plus 0728, based on the Qwen3 foundation model, is a 1 million context hybrid reasoning model with a balanced performance, speed, and cost combination.",
		},
		"qwen/qwen2.5-vl-72b-instruct": {
			Ratio:                       nativeRate(0.7999999999999999),
			CompletionRatio:             1.25,
			CachedInputRatio:            nativeRate(0.39999999999999997),
			ContextLength:               128000,
			MaxOutputTokens:             115200,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Qwen/Qwen2.5-VL-72B-Instruct",
			Description:                 "qwen/qwen2.5-vl-72b-instruct on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-14b": {
			Ratio:                       nativeRate(0.12),
			CompletionRatio:             2,
			ContextLength:               131072,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3-14B",
			Description:                 "qwen/qwen3-14b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-235b-a22b": {
			Ratio:                       nativeRate(0.45499999999999996),
			CompletionRatio:             4,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "max_tokens", "presence_penalty", "reasoning", "response_format", "seed", "stop", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3-235B-A22B",
			Description:                 "qwen/qwen3-235b-a22b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-235b-a22b-2507": {
			Ratio:                       nativeRate(0.0875),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.0175),
			ContextLength:               262144,
			MaxOutputTokens:             235929,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3-235B-A22B-Instruct-2507",
			Description:                 "qwen/qwen3-235b-a22b-2507 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-235b-a22b-thinking-2507": {
			Ratio:                       nativeRate(0.22999999999999998),
			CompletionRatio:             10,
			ContextLength:               131072,
			MaxOutputTokens:             117964,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_tokens", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3-235B-A22B-Thinking-2507",
			Description:                 "qwen/qwen3-235b-a22b-thinking-2507 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-30b-a3b": {
			Ratio:                       nativeRate(0.12),
			CompletionRatio:             4.166666666666667,
			ContextLength:               131072,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3-30B-A3B",
			Description:                 "qwen/qwen3-30b-a3b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-30b-a3b-instruct-2507": {
			Ratio:                       nativeRate(0.04815),
			CompletionRatio:             4.009345794392524,
			ContextLength:               262144,
			MaxOutputTokens:             32000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3-30B-A3B-Instruct-2507",
			Description:                 "qwen/qwen3-30b-a3b-instruct-2507 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-30b-a3b-thinking-2507": {
			Ratio:                       nativeRate(0.19999999999999998),
			CompletionRatio:             12,
			ContextLength:               81920,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "max_tokens", "presence_penalty", "reasoning", "response_format", "seed", "stop", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3-30B-A3B-Thinking-2507",
			Description:                 "qwen/qwen3-30b-a3b-thinking-2507 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-32b": {
			Ratio:                       nativeRate(0.08),
			CompletionRatio:             3.5000000000000004,
			ContextLength:               131072,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3-32B",
			Description:                 "qwen/qwen3-32b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-8b": {
			Ratio:                       nativeRate(0.117),
			CompletionRatio:             3.8888888888888884,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "max_tokens", "presence_penalty", "reasoning", "response_format", "seed", "stop", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3-8B",
			Description:                 "qwen/qwen3-8b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-coder": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             3.3333333333333335,
			CachedInputRatio:            nativeRate(0.09999999999999999),
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3-Coder-480B-A35B-Instruct",
			Description:                 "qwen/qwen3-coder on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-coder-30b-a3b-instruct": {
			Ratio:                       nativeRate(0.07),
			CompletionRatio:             4,
			ContextLength:               262144,
			MaxOutputTokens:             235929,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logprobs", "max_tokens", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3-Coder-30B-A3B-Instruct",
			Description:                 "qwen/qwen3-coder-30b-a3b-instruct on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-coder-flash": {
			Ratio:             nativeRate(0.195),
			CompletionRatio:   5,
			CachedInputRatio:  nativeRate(0.039),
			CacheWrite5mRatio: nativeRate(0.24375),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.325),
				CompletionRatio:     5,
				CachedInputRatio:    nativeRate(0.065),
				CacheWrite5mRatio:   nativeRate(0.40625),
				InputTokenThreshold: 32000,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(0.52),
					CompletionRatio:     5,
					CachedInputRatio:    nativeRate(0.10400000000000001),
					CacheWrite5mRatio:   nativeRate(0.65),
					InputTokenThreshold: 128000,
				},
			},
			ContextLength:               1000000,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logprobs", "max_tokens", "presence_penalty", "response_format", "seed", "stop", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			Description:                 "qwen/qwen3-coder-flash on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-coder-next": {
			Ratio:                       nativeRate(0.12),
			CompletionRatio:             6.666666666666666,
			CachedInputRatio:            nativeRate(0.07),
			ContextLength:               262144,
			MaxOutputTokens:             235929,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3-Coder-Next",
			Description:                 "qwen/qwen3-coder-next on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-coder-plus": {
			Ratio:             nativeRate(0.65),
			CompletionRatio:   5,
			CachedInputRatio:  nativeRate(0.13),
			CacheWrite5mRatio: nativeRate(0.8125),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1.17),
				CompletionRatio:     5,
				CachedInputRatio:    nativeRate(0.234),
				CacheWrite5mRatio:   nativeRate(1.4625),
				InputTokenThreshold: 32000,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(1.95),
					CompletionRatio:     5,
					CachedInputRatio:    nativeRate(0.39),
					CacheWrite5mRatio:   nativeRate(2.4375),
					InputTokenThreshold: 128000,
				},
			},
			ContextLength:               1000000,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logprobs", "max_tokens", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			Description:                 "qwen/qwen3-coder-plus on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-coder:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               262000,
			MaxOutputTokens:             262000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "stop", "max_tokens"},
			HuggingFaceID:               "Qwen/Qwen3-Coder-480B-A35B-Instruct",
			Description:                 "Qwen3-Coder-480B-A35B-Instruct is a Mixture-of-Experts (MoE) code generation model developed by the Qwen team. It is optimized for agentic coding tasks such as function calling, tool use, and long-context reasoning over...",
		},
		"qwen/qwen3-max": {
			Ratio:             nativeRate(0.78),
			CompletionRatio:   5,
			CachedInputRatio:  nativeRate(0.156),
			CacheWrite5mRatio: nativeRate(0.975),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1.56),
				CompletionRatio:     5,
				CachedInputRatio:    nativeRate(0.312),
				CacheWrite5mRatio:   nativeRate(1.95),
				InputTokenThreshold: 32000,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(1.95),
					CompletionRatio:     5,
					CachedInputRatio:    nativeRate(0.39),
					CacheWrite5mRatio:   nativeRate(2.4375),
					InputTokenThreshold: 128000,
				},
			},
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logprobs", "max_tokens", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			Description:                 "qwen/qwen3-max on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-max-thinking": {
			Ratio:           nativeRate(0.78),
			CompletionRatio: 5,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1.56),
				CompletionRatio:     5,
				InputTokenThreshold: 32000,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(1.95),
					CompletionRatio:     5,
					InputTokenThreshold: 128000,
				},
			},
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_tokens", "presence_penalty", "reasoning", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			Description:                 "qwen/qwen3-max-thinking on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-next-80b-a3b-instruct": {
			Ratio:                       nativeRate(0.09999999999999999),
			CompletionRatio:             11.000000000000002,
			CachedInputRatio:            nativeRate(0.07),
			ContextLength:               262144,
			MaxOutputTokens:             235929,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3-Next-80B-A3B-Instruct",
			Description:                 "qwen/qwen3-next-80b-a3b-instruct on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-next-80b-a3b-instruct:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               262144,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "stop", "max_tokens"},
			HuggingFaceID:               "Qwen/Qwen3-Next-80B-A3B-Instruct",
			Description:                 "Qwen3-Next-80B-A3B-Instruct is an instruction-tuned chat model in the Qwen3-Next series optimized for fast, stable responses without “thinking” traces. It targets complex tasks across reasoning, code generation, knowledge QA, and multilingual...",
		},
		"qwen/qwen3-next-80b-a3b-thinking": {
			Ratio:                       nativeRate(0.15),
			CompletionRatio:             8,
			ContextLength:               262144,
			MaxOutputTokens:             235929,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_tokens", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3-Next-80B-A3B-Thinking",
			Description:                 "qwen/qwen3-next-80b-a3b-thinking on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-vl-235b-a22b-instruct": {
			Ratio:                       nativeRate(0.21),
			CompletionRatio:             9.047619047619047,
			CachedInputRatio:            nativeRate(0.09999999999999999),
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3-VL-235B-A22B-Instruct",
			Description:                 "qwen/qwen3-vl-235b-a22b-instruct on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-vl-235b-a22b-thinking": {
			Ratio:                       nativeRate(0.39999999999999997),
			CompletionRatio:             10,
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_tokens", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3-VL-235B-A22B-Thinking",
			Description:                 "qwen/qwen3-vl-235b-a22b-thinking on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-vl-30b-a3b-instruct": {
			Ratio:                       nativeRate(0.13),
			CompletionRatio:             4,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3-VL-30B-A3B-Instruct",
			Description:                 "qwen/qwen3-vl-30b-a3b-instruct on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-vl-30b-a3b-thinking": {
			Ratio:                       nativeRate(0.19999999999999998),
			CompletionRatio:             12,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_tokens", "presence_penalty", "reasoning", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3-VL-30B-A3B-Thinking",
			Description:                 "qwen/qwen3-vl-30b-a3b-thinking on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-vl-32b-instruct": {
			Ratio:                       nativeRate(0.10400000000000001),
			CompletionRatio:             4,
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logprobs", "max_tokens", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3-VL-32B-Instruct",
			Description:                 "qwen/qwen3-vl-32b-instruct on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-vl-8b-instruct": {
			Ratio:                       nativeRate(0.117),
			CompletionRatio:             3.8888888888888884,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3-VL-8B-Instruct",
			Description:                 "qwen/qwen3-vl-8b-instruct on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-vl-8b-thinking": {
			Ratio:                       nativeRate(0.18),
			CompletionRatio:             11.666666666666664,
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_tokens", "presence_penalty", "reasoning", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3-VL-8B-Thinking",
			Description:                 "qwen/qwen3-vl-8b-thinking on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.5-122b-a10b": {
			Ratio:                       nativeRate(0.26),
			CompletionRatio:             8,
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3.5-122B-A10B",
			Description:                 "qwen/qwen3.5-122b-a10b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.5-27b": {
			Ratio:                       nativeRate(0.195),
			CompletionRatio:             8,
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3.5-27B",
			Description:                 "qwen/qwen3.5-27b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.5-35b-a3b": {
			Ratio:                       nativeRate(0.3125),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.15625),
			ContextLength:               262144,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3.5-35B-A3B",
			Description:                 "qwen/qwen3.5-35b-a3b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.5-397b-a17b": {
			Ratio:                       nativeRate(0.55),
			CompletionRatio:             6.363636363636363,
			CachedInputRatio:            nativeRate(0.22499999999999998),
			ContextLength:               262144,
			MaxOutputTokens:             235929,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3.5-397B-A17B",
			Description:                 "qwen/qwen3.5-397b-a17b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.5-9b": {
			Ratio:                       nativeRate(0.09999999999999999),
			CompletionRatio:             1.5,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3.5-9B",
			Description:                 "qwen/qwen3.5-9b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.5-flash-02-23": {
			Ratio:                       nativeRate(0.065),
			CompletionRatio:             4,
			ContextLength:               1000000,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "max_tokens", "presence_penalty", "reasoning", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			Description:                 "qwen/qwen3.5-flash-02-23 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.5-plus-02-15": {
			Ratio:           nativeRate(0.26),
			CompletionRatio: 6,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.325),
				CompletionRatio:     6,
				InputTokenThreshold: 256000,
			},
			},
			ContextLength:               1000000,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_tokens", "presence_penalty", "reasoning", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			Description:                 "qwen/qwen3.5-plus-02-15 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.5-plus-20260420": {
			Ratio:             nativeRate(0.3),
			CompletionRatio:   6,
			CacheWrite5mRatio: nativeRate(0.375),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.375),
				CompletionRatio:     6,
				CacheWrite5mRatio:   nativeRate(0.46875),
				InputTokenThreshold: 256000,
			},
			},
			ContextLength:               1000000,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_tokens", "presence_penalty", "reasoning", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			Description:                 "qwen/qwen3.5-plus-20260420 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.6-27b": {
			Ratio:                       nativeRate(0.32),
			CompletionRatio:             8.4375,
			CachedInputRatio:            nativeRate(0.15),
			ContextLength:               262144,
			MaxOutputTokens:             262140,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3.6-27B",
			Description:                 "qwen/qwen3.6-27b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.6-35b-a3b": {
			Ratio:                       nativeRate(0.15),
			CompletionRatio:             6.666666666666667,
			CachedInputRatio:            nativeRate(0.049999999999999996),
			ContextLength:               262144,
			MaxOutputTokens:             235929,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Qwen/Qwen3.6-35B-A3B",
			Description:                 "qwen/qwen3.6-35b-a3b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.6-flash": {
			Ratio:             nativeRate(0.1875),
			CompletionRatio:   6,
			CacheWrite5mRatio: nativeRate(0.234375),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.75),
				CompletionRatio:     4,
				CacheWrite5mRatio:   nativeRate(0.9375),
				InputTokenThreshold: 256000,
			},
			},
			ContextLength:               1000000,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_tokens", "presence_penalty", "reasoning", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			Description:                 "qwen/qwen3.6-flash on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.6-max-preview": {
			Ratio:             nativeRate(1.0270000000000001),
			CompletionRatio:   5.999999999999999,
			CacheWrite5mRatio: nativeRate(1.28375),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1.5799999999999998),
				CompletionRatio:     6.000000000000001,
				CacheWrite5mRatio:   nativeRate(1.975),
				InputTokenThreshold: 128000,
			},
			},
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_tokens", "presence_penalty", "reasoning", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			Description:                 "qwen/qwen3.6-max-preview on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.6-plus": {
			Ratio:             nativeRate(0.325),
			CompletionRatio:   6,
			CacheWrite5mRatio: nativeRate(0.40625),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1.3),
				CompletionRatio:     3,
				CacheWrite5mRatio:   nativeRate(1.625),
				InputTokenThreshold: 256000,
			},
			},
			ContextLength:               1000000,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_tokens", "presence_penalty", "reasoning", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			Description:                 "qwen/qwen3.6-plus on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.7-flash": {
			Ratio:             nativeRate(0.03),
			CompletionRatio:   4.333333333333334,
			CachedInputRatio:  nativeRate(0.006),
			CacheWrite5mRatio: nativeRate(0.038000000000000006),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.09999999999999999),
				CompletionRatio:     4,
				CachedInputRatio:    nativeRate(0.02),
				CacheWrite5mRatio:   nativeRate(0.125),
				InputTokenThreshold: 32000,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(0.19999999999999998),
					CompletionRatio:     4,
					CachedInputRatio:    nativeRate(0.04),
					CacheWrite5mRatio:   nativeRate(0.25),
					InputTokenThreshold: 256000,
				},
			},
			ContextLength:               1000000,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"include_reasoning", "logprobs", "max_tokens", "presence_penalty", "reasoning", "response_format", "seed", "temperature", "tool_choice", "tools", "top_logprobs", "top_p"},
			Description:                 "qwen/qwen3.7-flash on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
