package openrouter

import "github.com/Laisky/one-api/relay/adaptor"

// other_2Models returns the other model defaults for openrouter.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func other_2Models() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"sao10k/l3-lunaris-8b": {
			Ratio:                       nativeRate(0.04),
			CompletionRatio:             1.2499999999999998,
			ContextLength:               8192,
			MaxOutputTokens:             7372,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Sao10K/L3-8B-Lunaris-v1",
			Description:                 "sao10k/l3-lunaris-8b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"sao10k/l3.1-70b-hanami-x1": {
			Ratio:                       nativeRate(3),
			CompletionRatio:             1,
			ContextLength:               16000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logit_bias"},
			HuggingFaceID:               "Sao10K/L3.1-70B-Hanami-x1",
			Description:                 "This is [Sao10K](/sao10k)'s experiment over [Euryale v2.2](/sao10k/l3.1-euryale-70b).",
		},
		"sao10k/l3.1-euryale-70b": {
			Ratio:                       nativeRate(0.85),
			CompletionRatio:             1,
			ContextLength:               131072,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "Sao10K/L3.1-70B-Euryale-v2.2",
			Description:                 "sao10k/l3.1-euryale-70b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"sao10k/l3.3-euryale-70b": {
			Ratio:                       nativeRate(0.65),
			CompletionRatio:             1.1538461538461537,
			ContextLength:               131072,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logprobs", "max_tokens", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "top_logprobs", "top_p"},
			HuggingFaceID:               "Sao10K/L3.3-70B-Euryale-v2.3",
			Description:                 "sao10k/l3.3-euryale-70b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"stealth/space-bunny-alpha": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               1000000,
			MaxOutputTokens:             524288,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "reasoning_effort", "response_format", "temperature", "tool_choice", "tools", "top_p"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low"},
			DefaultReasoningEffort:      "max",
			Description:                 "stealth/space-bunny-alpha on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"stepfun/step-3.5-flash": {
			Ratio:                       nativeRate(0.09999999999999999),
			CompletionRatio:             3,
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "max_tokens", "reasoning", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "stepfun-ai/Step-3.5-Flash",
			Description:                 "stepfun/step-3.5-flash on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"stepfun/step-3.7-flash": {
			Ratio:                       nativeRate(0.19999999999999998),
			CompletionRatio:             5.75,
			CachedInputRatio:            nativeRate(0.04),
			ContextLength:               262144,
			MaxOutputTokens:             230400,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"high", "medium", "low"},
			DefaultReasoningEffort:      "medium",
			HuggingFaceID:               "stepfun-ai/Step-3.7-Flash",
			Description:                 "stepfun/step-3.7-flash on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"switchpoint/router": {
			Ratio:                       nativeRate(0.85),
			CompletionRatio:             4,
			ContextLength:               131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "stop", "seed", "max_tokens"},
			Description:                 "Switchpoint AI's router instantly analyzes your request and directs it to the optimal AI from an ever-evolving library. As the world of LLMs advances, our router gets smarter, ensuring you... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"thedrummer/cydonia-24b-v4.1": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             1.6666666666666667,
			CachedInputRatio:            nativeRate(0.15),
			ContextLength:               131072,
			MaxOutputTokens:             117964,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "thedrummer/cydonia-24b-v4.1",
			Description:                 "thedrummer/cydonia-24b-v4.1 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"thedrummer/rocinante-12b": {
			Ratio:                       nativeRate(0.25),
			CompletionRatio:             2,
			ContextLength:               65536,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logit_bias"},
			HuggingFaceID:               "TheDrummer/Rocinante-12B-v1.1",
			Description:                 "Rocinante 12B is designed for engaging storytelling and rich prose. Early testers have reported: - Expanded vocabulary with unique and expressive word choices - Enhanced creativity for vivid narratives -...",
		},
		"thedrummer/skyfall-36b-v2": {
			Ratio:                       nativeRate(0.55),
			CompletionRatio:             1.4545454545454544,
			CachedInputRatio:            nativeRate(0.25),
			ContextLength:               32768,
			MaxOutputTokens:             29491,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "TheDrummer/Skyfall-36B-v2",
			Description:                 "thedrummer/skyfall-36b-v2 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"thedrummer/unslopnemo-12b": {
			Ratio:                       nativeRate(0.39999999999999997),
			CompletionRatio:             1,
			ContextLength:               1024000,
			MaxOutputTokens:             819200,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "presence_penalty", "repetition_penalty", "seed", "stop", "structured_outputs", "temperature", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "TheDrummer/UnslopNemo-12B-v4.1",
			Description:                 "thedrummer/unslopnemo-12b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"thinkingmachines/inkling": {
			Ratio:                       nativeRate(1),
			CompletionRatio:             4.05,
			CachedInputRatio:            nativeRate(0.16999999999999998),
			ContextLength:               1048576,
			MaxOutputTokens:             471859,
			InputModalities:             []string{"text", "image", "audio"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "max_tokens", "min_p", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "seed", "stop", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			SupportedReasoningEfforts:   []string{"max", "high", "medium", "low", "minimal", "none"},
			DefaultReasoningEffort:      "high",
			HuggingFaceID:               "thinkingmachines/Inkling",
			Description:                 "thinkingmachines/inkling on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"thinkingmachines/inkling-small": {
			Ratio:                       nativeRate(0.44999999999999996),
			CompletionRatio:             2.666666666666667,
			CachedInputRatio:            nativeRate(0.09999999999999999),
			ContextLength:               1048576,
			MaxOutputTokens:             262144,
			InputModalities:             []string{"text", "image", "audio"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "max_tokens", "min_p", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "seed", "stop", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			SupportedReasoningEfforts:   []string{"max", "high", "medium", "low", "minimal", "none"},
			DefaultReasoningEffort:      "high",
			HuggingFaceID:               "thinkingmachines/Inkling-Small",
			Description:                 "thinkingmachines/inkling-small on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"thinkingmachines/inkling-small:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               1048576,
			MaxOutputTokens:             262144,
			InputModalities:             []string{"text", "image", "audio"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "max_tokens", "presence_penalty", "reasoning", "reasoning_effort", "seed", "stop", "temperature", "tools", "top_p"},
			SupportedReasoningEfforts:   []string{"max", "high", "medium", "low", "minimal", "none"},
			DefaultReasoningEffort:      "high",
			HuggingFaceID:               "thinkingmachines/Inkling-Small",
			Description:                 "thinkingmachines/inkling-small:free on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"thinkingmachines/inkling:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               1048576,
			MaxOutputTokens:             262144,
			InputModalities:             []string{"text", "image", "audio"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "max_tokens", "presence_penalty", "reasoning", "reasoning_effort", "seed", "stop", "temperature", "tools", "top_p"},
			SupportedReasoningEfforts:   []string{"max", "high", "medium", "low", "minimal", "none"},
			DefaultReasoningEffort:      "high",
			HuggingFaceID:               "thinkingmachines/Inkling",
			Description:                 "thinkingmachines/inkling:free on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"unbiased/pareto": {
			Ratio:                       nativeRate(2.5),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.25),
			ContextLength:               262144,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"max_tokens", "temperature", "tool_choice", "tools", "top_p"},
			Description:                 "unbiased/pareto on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"undi95/remm-slerp-l2-13b": {
			Ratio:                       nativeRate(0.35),
			CompletionRatio:             1.8571428571428574,
			ContextLength:               6144,
			MaxOutputTokens:             5529,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "top_a", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Undi95/ReMM-SLERP-L2-13B",
			Description:                 "undi95/remm-slerp-l2-13b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"upstage/solar-mini4": {
			Ratio:                       nativeRate(0.049999999999999996),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.005),
			ContextLength:               524288,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "max_tokens", "parallel_tool_calls", "presence_penalty", "reasoning", "reasoning_effort", "response_format", "structured_outputs", "temperature", "tool_choice", "tools", "top_p"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low", "minimal", "none"},
			DefaultReasoningEffort:      "medium",
			Description:                 "upstage/solar-mini4 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"upstage/solar-pro-3": {
			Ratio:                       nativeRate(0.15),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.015),
			ContextLength:               131072,
			MaxOutputTokens:             117964,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "max_tokens", "parallel_tool_calls", "presence_penalty", "reasoning", "reasoning_effort", "response_format", "structured_outputs", "temperature", "tool_choice", "tools", "top_p"},
			SupportedReasoningEfforts:   []string{"high", "medium", "low", "minimal", "none"},
			DefaultReasoningEffort:      "medium",
			Description:                 "upstage/solar-pro-3 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"upstage/solar-pro4": {
			Ratio:                       nativeRate(0.09),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.018),
			ContextLength:               524288,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "max_tokens", "parallel_tool_calls", "presence_penalty", "reasoning", "reasoning_effort", "response_format", "structured_outputs", "temperature", "tool_choice", "tools", "top_p"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high", "medium", "low", "minimal", "none"},
			DefaultReasoningEffort:      "medium",
			Description:                 "upstage/solar-pro4 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"writer/palmyra-x5": {
			Ratio:                       nativeRate(0.6),
			CompletionRatio:             10,
			ContextLength:               1040000,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"max_tokens", "stop", "temperature", "top_k", "top_p"},
			Description:                 "writer/palmyra-x5 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
