package openrouter

import "github.com/Laisky/one-api/relay/adaptor"

// poolsideModels returns the poolside model defaults for openrouter.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func poolsideModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"poolside/laguna-m.1": {
			Ratio:                       nativeRate(0.2),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.1),
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "max_tokens"},
			HuggingFaceID:               "poolside/Laguna-M.1",
			Description:                 "Laguna M.1 is the flagship coding agent model from Poolside, optimized for complex software engineering tasks...",
		},
		"poolside/laguna-m.1:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "max_tokens"},
			Description:                 "Laguna M.1 is the flagship coding agent model from [Poolside](https://poolside.ai), optimized for complex software engineering tasks. Designed for agentic coding workflows, it supports tool calling and reasoning, with a 128K...",
		},
		"poolside/laguna-s-2.1": {
			Ratio:                       nativeRate(0.09),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.009),
			ContextLength:               1048576,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "temperature", "tool_choice", "tools"},
			HuggingFaceID:               "poolside/Laguna-S-2.1",
			Description:                 "poolside/laguna-s-2.1 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"poolside/laguna-s-2.1:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "temperature", "tool_choice", "tools"},
			HuggingFaceID:               "poolside/Laguna-S-2.1",
			Description:                 "poolside/laguna-s-2.1:free on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"poolside/laguna-xs-2.1": {
			Ratio:                       nativeRate(0.06),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.03),
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "temperature", "tool_choice", "tools"},
			HuggingFaceID:               "poolside/Laguna-XS-2.1",
			Description:                 "poolside/laguna-xs-2.1 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"poolside/laguna-xs-2.1:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "temperature", "tool_choice", "tools"},
			HuggingFaceID:               "poolside/Laguna-XS-2.1",
			Description:                 "poolside/laguna-xs-2.1:free on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"poolside/laguna-xs.2": {
			Ratio:                       nativeRate(0.1),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.05),
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "max_tokens"},
			HuggingFaceID:               "poolside/Laguna-XS.2",
			Description:                 "Laguna XS.2 is the second-generation model in the XS size class from Poolside, their efficient coding agent series... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"poolside/laguna-xs.2:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "max_tokens"},
			HuggingFaceID:               "poolside/Laguna-XS.2",
			Description:                 "Laguna XS.2 is the second-generation model in the XS size class from [Poolside](https://poolside.ai), their efficient coding agent series. It combines tool calling and reasoning capabilities with a compact footprint, offering... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
	}
}
