package openrouter

import "github.com/Laisky/one-api/relay/adaptor"

// otherModels returns the other model defaults for openrouter.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func otherModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"ai21/jamba-large-1.7": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             4,
			ContextLength:               256000,
			MaxOutputTokens:             4096,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "stop", "max_tokens"},
			HuggingFaceID:               "ai21labs/AI21-Jamba-Large-1.7",
			Description:                 "Jamba Large 1.7 is the latest model in the Jamba open family, offering improvements in grounding, instruction-following, and overall efficiency. Built on a hybrid SSM-Transformer architecture with a 256K context...",
		},
		"alfredpros/codellama-7b-instruct-solidity": {
			Ratio:                       nativeRate(0.8),
			CompletionRatio:             1.4999999999999998,
			ContextLength:               4096,
			MaxOutputTokens:             4096,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			HuggingFaceID:               "AlfredPros/CodeLlama-7b-Instruct-Solidity",
			Description:                 "A finetuned 7 billion parameters Code LLaMA - Instruct model to generate Solidity smart contract using 4-bit QLoRA finetuning provided by PEFT library. [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"alibaba/tongyi-deepresearch-30b-a3b": {
			Ratio:                       nativeRate(0.09),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.09),
			ContextLength:               131072,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logit_bias"},
			HuggingFaceID:               "Alibaba-NLP/Tongyi-DeepResearch-30B-A3B",
			Description:                 "Tongyi DeepResearch is an agentic large language model developed by Tongyi Lab, with 30 billion total parameters activating only 3 billion per token. It's optimized for long-horizon, deep information-seeking tasks... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"allenai/olmo-3-32b-think": {
			Ratio:                       nativeRate(0.15),
			CompletionRatio:             3.3333333333333335,
			ContextLength:               65536,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logit_bias"},
			HuggingFaceID:               "allenai/Olmo-3-32B-Think",
			Description:                 "Olmo 3 32B Think is a large-scale, 32-billion-parameter model purpose-built for deep reasoning, complex logic chains and advanced instruction-following scenarios. Its capacity enables strong performance on demanding evaluation tasks and...",
		},
		"amazon/nova-2-lite-v1": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             8.333333333333334,
			ContextLength:               1000000,
			MaxOutputTokens:             65535,
			InputModalities:             []string{"text", "image", "video", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "stop", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			Description:                 "amazon/nova-2-lite-v1 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"amazon/nova-lite-v1": {
			Ratio:                       nativeRate(0.06),
			CompletionRatio:             4,
			ContextLength:               300000,
			MaxOutputTokens:             5120,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"max_tokens", "stop", "temperature", "tools", "top_k", "top_p"},
			Description:                 "amazon/nova-lite-v1 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"amazon/nova-micro-v1": {
			Ratio:                       nativeRate(0.035),
			CompletionRatio:             4,
			ContextLength:               128000,
			MaxOutputTokens:             5120,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"max_tokens", "stop", "temperature", "tools", "top_k", "top_p"},
			Description:                 "amazon/nova-micro-v1 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"amazon/nova-premier-v1": {
			Ratio:                       nativeRate(2.5),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.625),
			ContextLength:               1000000,
			MaxOutputTokens:             32000,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"max_tokens", "stop", "temperature", "tools", "top_k", "top_p"},
			Description:                 "amazon/nova-premier-v1 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"amazon/nova-pro-v1": {
			Ratio:                       nativeRate(0.7999999999999999),
			CompletionRatio:             4,
			ContextLength:               300000,
			MaxOutputTokens:             5120,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"max_tokens", "stop", "temperature", "tools", "top_k", "top_p"},
			Description:                 "amazon/nova-pro-v1 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"anthracite-org/magnum-v4-72b": {
			Ratio:                       nativeRate(2.5),
			CompletionRatio:             2,
			ContextLength:               32768,
			MaxOutputTokens:             4096,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "top_a", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "anthracite-org/magnum-v4-72b",
			Description:                 "anthracite-org/magnum-v4-72b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"bytedance/ui-tars-1.5-7b": {
			Ratio:                       nativeRate(0.09999999999999999),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.09999999999999999),
			ContextLength:               128000,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"image", "text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "presence_penalty", "repetition_penalty", "seed", "stop", "structured_outputs", "temperature", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "ByteDance-Seed/UI-TARS-1.5-7B",
			Description:                 "bytedance/ui-tars-1.5-7b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"cognitivecomputations/dolphin-mistral-24b-venice-edition": {
			Ratio:                       nativeRate(0.19999999999999998),
			CompletionRatio:             4.5,
			ContextLength:               128000,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode"},
			SupportedSamplingParameters: []string{"frequency_penalty", "max_tokens", "presence_penalty", "response_format", "stop", "temperature", "top_k", "top_p"},
			HuggingFaceID:               "cognitivecomputations/Dolphin-Mistral-24B-Venice-Edition",
			Description:                 "cognitivecomputations/dolphin-mistral-24b-venice-edition on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"cognitivecomputations/dolphin-mistral-24b-venice-edition:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "stop", "max_tokens"},
			HuggingFaceID:               "cognitivecomputations/Dolphin-Mistral-24B-Venice-Edition",
			Description:                 "Venice Uncensored Dolphin Mistral 24B Venice Edition is a fine-tuned variant of Mistral-Small-24B-Instruct-2501, developed by dphn.ai in collaboration with Venice.ai. This model is designed as an “uncensored” instruct-tuned LLM, preserving...",
		},
		"deepcogito/cogito-v2.1-671b": {
			Ratio:                       nativeRate(1.25),
			CompletionRatio:             1,
			ContextLength:               128000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "max_tokens", "logit_bias"},
			Description:                 "Cogito v2.1 671B MoE represents one of the strongest open models globally, matching performance of frontier closed and open models. This model is trained using self play with reinforcement learning...",
		},
		"dots-studio/dots-3-note-preview:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               512000,
			MaxOutputTokens:             460800,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "response_format", "structured_outputs", "temperature", "tool_choice", "tools", "top_p"},
			Description:                 "dots-studio/dots-3-note-preview:free on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"essentialai/rnj-1-instruct": {
			Ratio:                       nativeRate(0.15),
			CompletionRatio:             1,
			ContextLength:               32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "max_tokens", "logit_bias"},
			HuggingFaceID:               "EssentialAI/rnj-1-instruct",
			Description:                 "Rnj-1 is an 8B-parameter, dense, open-weight model family developed by Essential AI and trained from scratch with a focus on programming, math, and scientific reasoning. The model demonstrates strong performance... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"gryphe/mythomax-l2-13b": {
			Ratio:                       nativeRate(0.08),
			CompletionRatio:             1.375,
			ContextLength:               8192,
			MaxOutputTokens:             3686,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "top_a", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "Gryphe/MythoMax-L2-13b",
			Description:                 "gryphe/mythomax-l2-13b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"ibm-granite/granite-4.0-h-micro": {
			Ratio:                       nativeRate(0.017),
			CompletionRatio:             6.588235294117647,
			ContextLength:               131000,
			MaxOutputTokens:             117900,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "temperature", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "ibm-granite/granite-4.0-h-micro",
			Description:                 "ibm-granite/granite-4.0-h-micro on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"ibm-granite/granite-4.1-8b": {
			Ratio:                       nativeRate(0.05),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.05),
			ContextLength:               131072,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "seed", "stop", "max_tokens"},
			HuggingFaceID:               "ibm-granite/granite-4.1-8b",
			Description:                 "Granite 4.1 8B is a dense, decoder-only 8-billion-parameter language model from IBM, part of the Granite 4.1 family. It supports a 131K-token context window and is designed for enterprise tasks.",
		},
		"ibm-granite/granite-4.2-8b": {
			Ratio:                       nativeRate(0.06),
			CompletionRatio:             4.166666666666667,
			CachedInputRatio:            nativeRate(0.015),
			ContextLength:               131072,
			MaxOutputTokens:             117964,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"high", "low", "none"},
			DefaultReasoningEffort:      "high",
			HuggingFaceID:               "ibm-granite/granite-4.2-8b",
			Description:                 "ibm-granite/granite-4.2-8b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"inception/mercury-2": {
			Ratio:                       nativeRate(0.25),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.024999999999999998),
			ContextLength:               128000,
			MaxOutputTokens:             50000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "reasoning_effort", "response_format", "stop", "structured_outputs", "temperature", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"high", "medium", "low", "none"},
			DefaultReasoningEffort:      "medium",
			Description:                 "inception/mercury-2 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"inception/mercury-2.5": {
			Ratio:                       nativeRate(0.04),
			CompletionRatio:             3.75,
			CachedInputRatio:            nativeRate(0.004),
			ContextLength:               260000,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "max_tokens", "reasoning", "reasoning_effort", "response_format", "stop", "structured_outputs", "temperature", "tool_choice", "tools"},
			SupportedReasoningEfforts:   []string{"high", "medium", "low", "none"},
			DefaultReasoningEffort:      "medium",
			Description:                 "inception/mercury-2.5 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"inference-net/schematron-v2-small": {
			Ratio:                       nativeRate(0.049999999999999996),
			CompletionRatio:             4.6,
			CachedInputRatio:            nativeRate(0.049999999999999996),
			ContextLength:               128000,
			MaxOutputTokens:             4096,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "max_tokens", "min_p", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "top_k", "top_p"},
			HuggingFaceID:               "inference-net/schematron-v2-llama-3.2-3b",
			Description:                 "inference-net/schematron-v2-small on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"inference-net/schematron-v2-turbo": {
			Ratio:                       nativeRate(0.03),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.03),
			ContextLength:               128000,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "max_tokens", "min_p", "presence_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "top_k", "top_p"},
			HuggingFaceID:               "inference-net/schematron-v2-granite-4.0-h-micro",
			Description:                 "inference-net/schematron-v2-turbo on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"inflection/inflection-3-pi": {
			Ratio:                       nativeRate(2.5),
			CompletionRatio:             4,
			ContextLength:               8000,
			MaxOutputTokens:             1024,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "stop", "max_tokens"},
			Description:                 "Inflection 3 Pi powers Inflection's [Pi](https://pi.ai) chatbot, including backstory, emotional intelligence, productivity, and safety. It has access to recent news, and excels in scenarios like customer support and roleplay. Pi...",
		},
		"inflection/inflection-3-productivity": {
			Ratio:                       nativeRate(2.5),
			CompletionRatio:             4,
			ContextLength:               8000,
			MaxOutputTokens:             1024,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "stop", "max_tokens"},
			Description:                 "Inflection 3 Productivity is optimized for following instructions. It is better for tasks requiring JSON output or precise adherence to provided guidelines. It has access to recent news. For emotional...",
		},
		"kwaipilot/kat-coder-pro-v2": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.06),
			ContextLength:               256000,
			MaxOutputTokens:             80000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logit_bias"},
			Description:                 "KAT-Coder-Pro V2 is the latest high-performance model in KwaiKAT’s KAT-Coder series, designed for complex enterprise-grade software engineering and SaaS integration. It builds on the agentic coding strengths of earlier versions,...",
		},
		"kwaipilot/kat-coder-pro-v2.5": {
			Ratio:                       nativeRate(0.74),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.15),
			ContextLength:               262144,
			MaxOutputTokens:             235929,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			Description:                 "kwaipilot/kat-coder-pro-v2.5 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"liquid/lfm-2-24b-a2b": {
			Ratio:                       nativeRate(0.03),
			CompletionRatio:             4,
			ContextLength:               32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "max_tokens", "logit_bias"},
			HuggingFaceID:               "LiquidAI/LFM2-24B-A2B",
			Description:                 "LFM2-24B-A2B is the largest model in the LFM2 family of hybrid architectures designed for efficient on-device deployment. Built as a 24B parameter Mixture-of-Experts model with only 2B active parameters per... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"liquid/lfm-2.5-1.2b-instruct:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			HuggingFaceID:               "LiquidAI/LFM2.5-1.2B-Instruct",
			Description:                 "LFM2.5-1.2B-Instruct is a compact, high-performance instruction-tuned model built for fast on-device AI. It delivers strong chat quality in a 1.2B parameter footprint, with efficient edge inference and broad runtime support.",
		},
		"liquid/lfm-2.5-1.2b-thinking:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			HuggingFaceID:               "LiquidAI/LFM2.5-1.2B-Thinking",
			Description:                 "LFM2.5-1.2B-Thinking is a lightweight reasoning-focused model optimized for agentic tasks, data extraction, and RAG—while still running comfortably on edge devices. It supports long context (up to 32K tokens) and is...",
		},
		"liquid/lfm-2.5-2.6b:free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               65536,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_completion_tokens", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "LiquidAI/LFM2.5-2.6B",
			Description:                 "liquid/lfm-2.5-2.6b:free on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"mancer/weaver": {
			Ratio:                       nativeRate(0.39999999999999997),
			CompletionRatio:             1.8750000000000002,
			ContextLength:               8000,
			MaxOutputTokens:             6000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "logprobs", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "temperature", "top_a", "top_k", "top_logprobs", "top_p"},
			Description:                 "mancer/weaver on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"meituan/longcat-2.0": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.006),
			ContextLength:               1048756,
			MaxOutputTokens:             262144,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logit_bias", "max_tokens", "min_p", "presence_penalty", "reasoning", "repetition_penalty", "seed", "stop", "temperature", "tool_choice", "tools", "top_k", "top_p"},
			HuggingFaceID:               "meituan-longcat/LongCat-2.0",
			Description:                 "meituan/longcat-2.0 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"microsoft/phi-4": {
			Ratio:                       nativeRate(0.07),
			CompletionRatio:             2,
			ContextLength:               16384,
			MaxOutputTokens:             14745,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logit_bias", "max_tokens", "min_p", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "top_k", "top_p"},
			HuggingFaceID:               "microsoft/phi-4",
			Description:                 "microsoft/phi-4 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"microsoft/phi-4-mini-instruct": {
			Ratio:                       nativeRate(0.08),
			CompletionRatio:             4.375,
			CachedInputRatio:            nativeRate(0.08),
			ContextLength:               131072,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logit_bias"},
			HuggingFaceID:               "microsoft/Phi-4-mini-instruct",
			Description:                 "Phi-4-mini-instruct is a lightweight open model built upon synthetic data and filtered publicly available websites - with a focus on high-quality, reasoning dense data. The model belongs to the Phi-4 family. [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"microsoft/wizardlm-2-8x22b": {
			Ratio:                       nativeRate(0.62),
			CompletionRatio:             1,
			ContextLength:               65535,
			MaxOutputTokens:             8000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode"},
			SupportedSamplingParameters: []string{"frequency_penalty", "max_tokens", "presence_penalty", "repetition_penalty", "response_format", "seed", "stop", "temperature", "top_k", "top_p"},
			HuggingFaceID:               "microsoft/WizardLM-2-8x22B",
			Description:                 "microsoft/wizardlm-2-8x22b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"morph/morph-v3-fast": {
			Ratio:                       nativeRate(0.7999999999999999),
			CompletionRatio:             1.5,
			ContextLength:               81920,
			MaxOutputTokens:             38000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"max_tokens", "stop", "temperature"},
			Description:                 "morph/morph-v3-fast on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"morph/morph-v3-large": {
			Ratio:                       nativeRate(0.8999999999999999),
			CompletionRatio:             2.111111111111111,
			ContextLength:               262144,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"logprobs", "max_tokens", "response_format", "stop", "structured_outputs", "temperature", "top_logprobs"},
			Description:                 "morph/morph-v3-large on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openrouter/free": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               200000,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_completion_tokens", "max_tokens", "min_p", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			Description:                 "openrouter/free on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openrouter/owl-alpha": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               1048756,
			MaxOutputTokens:             262144,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logit_bias"},
			Description:                 "Owl Alpha is a high-performance foundation model designed for agentic workloads. Natively supports tool use, and long-context tasks, with strong performance in code generation, automated workflows, and reasoning. [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"perceptron/perceptron-mk1": {
			Ratio:                       nativeRate(0.15),
			CompletionRatio:             10,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "max_tokens", "presence_penalty", "reasoning", "structured_outputs", "temperature", "top_k", "top_p"},
			Description:                 "perceptron/perceptron-mk1 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"perplexity/sonar": {
			Ratio:                       nativeRate(1),
			CompletionRatio:             1,
			ContextLength:               127072,
			MaxOutputTokens:             114364,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"frequency_penalty", "max_tokens", "presence_penalty", "temperature", "top_k", "top_p", "web_search_options"},
			Description:                 "perplexity/sonar on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"perplexity/sonar-deep-research": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             4,
			ContextLength:               128000,
			MaxOutputTokens:             115200,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "max_tokens", "presence_penalty", "reasoning", "temperature", "top_k", "top_p", "web_search_options"},
			Description:                 "perplexity/sonar-deep-research on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"perplexity/sonar-pro": {
			Ratio:                       nativeRate(3),
			CompletionRatio:             5,
			ContextLength:               200000,
			MaxOutputTokens:             8000,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"frequency_penalty", "max_tokens", "presence_penalty", "temperature", "top_k", "top_p", "web_search_options"},
			Description:                 "perplexity/sonar-pro on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"perplexity/sonar-pro-search": {
			Ratio:                       nativeRate(3),
			CompletionRatio:             5,
			ContextLength:               200000,
			MaxOutputTokens:             8000,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "max_tokens", "presence_penalty", "reasoning", "structured_outputs", "temperature", "top_k", "top_p", "web_search_options"},
			Description:                 "perplexity/sonar-pro-search on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"perplexity/sonar-reasoning-pro": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             4,
			ContextLength:               128000,
			MaxOutputTokens:             115200,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"reasoning"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "max_tokens", "presence_penalty", "reasoning", "temperature", "top_k", "top_p", "web_search_options"},
			Description:                 "perplexity/sonar-reasoning-pro on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"prime-intellect/intellect-3": {
			Ratio:                       nativeRate(0.2),
			CompletionRatio:             5.5,
			ContextLength:               131072,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "max_tokens"},
			HuggingFaceID:               "PrimeIntellect/INTELLECT-3-FP8",
			Description:                 "INTELLECT-3 is a 106B-parameter Mixture-of-Experts model (12B active) post-trained from GLM-4.5-Air-Base using supervised fine-tuning (SFT) followed by large-scale reinforcement learning (RL). It offers state-of-the-art performance for its size across math,... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
		"prism-ml/ternary-bonsai-2-27b": {
			Ratio:                       nativeRate(0.075),
			CompletionRatio:             6.666666666666667,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_tokens", "presence_penalty", "reasoning", "reasoning_effort", "repetition_penalty", "response_format", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			SupportedReasoningEfforts:   []string{"xhigh", "medium"},
			DefaultReasoningEffort:      "xhigh",
			HuggingFaceID:               "prism-ml/Ternary-Bonsai-2-27B-gguf",
			Description:                 "prism-ml/ternary-bonsai-2-27b on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"rekaai/reka-edge": {
			Ratio:                       nativeRate(0.09999999999999999),
			CompletionRatio:             1,
			ContextLength:               16384,
			MaxOutputTokens:             14745,
			InputModalities:             []string{"image", "text", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "logprobs", "max_tokens", "presence_penalty", "seed", "stop", "structured_outputs", "temperature", "tool_choice", "tools", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "RekaAI/reka-edge-2603",
			Description:                 "rekaai/reka-edge on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"rekaai/reka-flash-3": {
			Ratio:                       nativeRate(0.09999999999999999),
			CompletionRatio:             2,
			ContextLength:               65536,
			MaxOutputTokens:             58982,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"structured_outputs", "reasoning", "logprobs"},
			SupportedSamplingParameters: []string{"frequency_penalty", "include_reasoning", "logprobs", "max_tokens", "presence_penalty", "reasoning", "seed", "stop", "structured_outputs", "temperature", "top_k", "top_logprobs", "top_p"},
			HuggingFaceID:               "RekaAI/reka-flash-3",
			Description:                 "rekaai/reka-flash-3 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"relace/relace-apply-3": {
			Ratio:                       nativeRate(0.85),
			CompletionRatio:             1.4705882352941178,
			ContextLength:               256000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"max_tokens", "seed", "stop"},
			Description:                 "relace/relace-apply-3 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"relace/relace-search": {
			Ratio:                       nativeRate(1),
			CompletionRatio:             3,
			ContextLength:               256000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"max_tokens", "response_format", "seed", "stop", "temperature", "tool_choice", "tools", "top_p"},
			Description:                 "relace/relace-search on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"sakana/fugu-max": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.25),
			ContextLength:               1000000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "reasoning", "reasoning_effort", "structured_outputs", "tool_choice", "tools", "web_search_options"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high"},
			DefaultReasoningEffort:      "high",
			Description:                 "sakana/fugu-max on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"sakana/fugu-ultra": {
			Ratio:            nativeRate(5),
			CompletionRatio:  6,
			CachedInputRatio: nativeRate(0.5),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1e+01),
				CompletionRatio:     4.5,
				CachedInputRatio:    nativeRate(1),
				InputTokenThreshold: 272000,
			},
			},
			ContextLength:               1000000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "reasoning", "reasoning_effort", "structured_outputs", "tool_choice", "tools", "web_search_options"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high"},
			DefaultReasoningEffort:      "xhigh",
			Description:                 "sakana/fugu-ultra on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"sakana/fugu-ultra-v2": {
			Ratio:            nativeRate(5),
			CompletionRatio:  6,
			CachedInputRatio: nativeRate(0.5),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1e+01),
				CompletionRatio:     4.5,
				CachedInputRatio:    nativeRate(1),
				InputTokenThreshold: 272000,
			},
			},
			ContextLength:               1000000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "reasoning", "reasoning_effort", "structured_outputs", "tool_choice", "tools", "web_search_options"},
			SupportedReasoningEfforts:   []string{"max", "xhigh", "high"},
			DefaultReasoningEffort:      "xhigh",
			Description:                 "sakana/fugu-ultra-v2 on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"sakana/sakana-namazu": {
			Ratio:                       nativeRate(0.95),
			CompletionRatio:             4.2105263157894735,
			CachedInputRatio:            nativeRate(0.15),
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"include_reasoning", "reasoning", "reasoning_effort", "structured_outputs", "tool_choice", "tools", "web_search_options"},
			SupportedReasoningEfforts:   []string{"high", "none"},
			DefaultReasoningEffort:      "high",
			Description:                 "sakana/sakana-namazu on openrouter; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"sao10k/l3-euryale-70b": {
			Ratio:                       nativeRate(1.48),
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			HuggingFaceID:               "Sao10K/L3-70B-Euryale-v2.1",
			Description:                 "Euryale 70B v2.1 is a model focused on creative roleplay from [Sao10k](https://ko-fi.com/sao10k). - Better prompt adherence. - Better anatomy / spatial awareness. - Adapts much better to unique and custom... [Deprecated: no longer listed on OpenRouter's live model catalog as of 2026-07-13]",
		},
	}
}
