package mcp

import (
	"bytes"
	"encoding/json"
	"io"
	"strings"

	"github.com/Laisky/errors/v2"
)

const maxMCPResponseBodyBytes int64 = 32 << 20

type mcpJSONRPCError struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    any    `json:"data,omitempty"`
}

type mcpJSONRPCEnvelope struct {
	JSONRPC string           `json:"jsonrpc"`
	ID      json.RawMessage  `json:"id"`
	Result  json.RawMessage  `json:"result"`
	Error   *mcpJSONRPCError `json:"error,omitempty"`
}

// readMCPResponseBody reads an MCP response through a fixed allocation boundary.
//
// Parameters:
//   - reader: the remote HTTP response body.
//
// Return values:
//   - []byte: the response body when it does not exceed maxMCPResponseBodyBytes.
//   - error: a wrapped read or size error when the response cannot be consumed safely.
func readMCPResponseBody(reader io.Reader) ([]byte, error) {
	if reader == nil {
		return nil, errors.New("mcp response body is nil")
	}
	body, err := io.ReadAll(io.LimitReader(reader, maxMCPResponseBodyBytes+1))
	if err != nil {
		return nil, errors.Wrap(err, "read bounded mcp response body")
	}
	if int64(len(body)) > maxMCPResponseBodyBytes {
		return nil, errors.Errorf("mcp response body exceeds %d bytes", maxMCPResponseBodyBytes)
	}
	return body, nil
}

// parseMCPResponseEnvelope validates a JSON-RPC response and correlates it with one request.
//
// Parameters:
//   - body: the JSON response envelope.
//   - expectedID: the string request identifier generated by the client.
//
// Return values:
//   - *mcpJSONRPCEnvelope: the validated response envelope.
//   - error: a wrapped JSON, version, or response-correlation error.
func parseMCPResponseEnvelope(body []byte, expectedID string) (*mcpJSONRPCEnvelope, error) {
	var envelope mcpJSONRPCEnvelope
	if err := json.Unmarshal(body, &envelope); err != nil {
		return nil, errors.Wrap(err, "decode mcp JSON-RPC response")
	}
	if envelope.JSONRPC != "2.0" {
		return nil, errors.Errorf("mcp response jsonrpc must be 2.0, got %q", envelope.JSONRPC)
	}
	if err := validateMCPResponseID(envelope.ID, expectedID); err != nil {
		return nil, err
	}
	return &envelope, nil
}

// extractMCPResponseEnvelope finds the SSE data event correlated with one request identifier.
//
// Parameters:
//   - body: a finite Server-Sent Events response body.
//   - expectedID: the string request identifier generated by the client.
//
// Return values:
//   - []byte: the matching JSON-RPC response envelope.
//   - error: a wrapped error when no valid event matches expectedID.
func extractMCPResponseEnvelope(body []byte, expectedID string) ([]byte, error) {
	normalized := strings.ReplaceAll(string(body), "\r\n", "\n")
	normalized = strings.ReplaceAll(normalized, "\r", "\n")
	foundData := false
	for _, block := range strings.Split(normalized, "\n\n") {
		dataLines := make([]string, 0)
		for _, line := range strings.Split(block, "\n") {
			if !strings.HasPrefix(line, "data:") {
				continue
			}
			foundData = true
			dataLines = append(dataLines, strings.TrimPrefix(strings.TrimPrefix(line, "data:"), " "))
		}
		if len(dataLines) == 0 {
			continue
		}
		candidate := []byte(strings.Join(dataLines, "\n"))
		var envelope struct {
			ID json.RawMessage `json:"id"`
		}
		if err := json.Unmarshal(candidate, &envelope); err != nil {
			continue
		}
		if validateMCPResponseID(envelope.ID, expectedID) == nil {
			return candidate, nil
		}
	}
	if !foundData {
		return nil, errors.New("mcp SSE response has no data fields")
	}
	return nil, errors.Errorf("mcp SSE response has no event for request id %q", expectedID)
}

// validateMCPResponseID verifies that a JSON-RPC response ID is the expected string identifier.
//
// Parameters:
//   - rawID: the encoded JSON-RPC response ID.
//   - expectedID: the string request identifier generated by the client.
//
// Return values:
//   - error: a correlation error when the ID is missing, has another type, or does not match.
func validateMCPResponseID(rawID json.RawMessage, expectedID string) error {
	if len(bytes.TrimSpace(rawID)) == 0 {
		return errors.New("mcp response id is missing")
	}
	var responseID string
	if err := json.Unmarshal(rawID, &responseID); err != nil {
		return errors.Wrap(err, "decode mcp response id")
	}
	if responseID != expectedID {
		return errors.Errorf("mcp response id mismatch: expected %q, got %q", expectedID, responseID)
	}
	return nil
}
