package baichuan

import "github.com/Laisky/one-api/relay/adaptor"

// baichuanModels returns the baichuan model defaults for baichuan.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func baichuanModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"Baichuan-M2": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             10,
			ContextLength:               32000,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "frequency_penalty", "presence_penalty", "seed"},
			Description:                 "Baichuan-M2 on baichuan; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Baichuan-M2-Plus": {
			Ratio:                       nativeRate(1e+01),
			CompletionRatio:             3,
			ContextLength:               32000,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "frequency_penalty", "presence_penalty", "seed"},
			Description:                 "Baichuan-M2-Plus on baichuan; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Baichuan-M3": {
			Ratio:                       nativeRate(1e+01),
			CompletionRatio:             3,
			ContextLength:               32000,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "frequency_penalty", "presence_penalty", "seed"},
			Description:                 "Baichuan-M3 on baichuan; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Baichuan-M3-Plus": {
			Ratio:                       nativeRate(5),
			CompletionRatio:             1.8,
			ContextLength:               32000,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "frequency_penalty", "presence_penalty", "seed"},
			Description:                 "Baichuan-M3-Plus on baichuan; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Baichuan-Text-Embedding": {
			Ratio:           nativeRate(0.5),
			CompletionRatio: 0,
			Embedding: &adaptor.EmbeddingPricingConfig{
				TextTokenRatio: nativeRate(0.5),
			},
			ContextLength:    512,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"text"},
			Description:      "Baichuan-Text-Embedding on baichuan; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Baichuan2-53B": {
			Ratio:           nativeRate(2e+01),
			CompletionRatio: 1,
			TimeWindows: []adaptor.TimeWindow{adaptor.TimeWindow{
				Name:     "baichuan-daypart",
				TimeZone: "Asia/Shanghai",
				Ranges: []adaptor.ClockRange{adaptor.ClockRange{
					Start: "00:00",
					End:   "08:00",
				},
				},
				Overlay: adaptor.ModelConfig{
					Ratio:           nativeRate(1e+01),
					CompletionRatio: 1,
				},
			},
				adaptor.TimeWindow{
					Name:     "baichuan-daypart",
					TimeZone: "Asia/Shanghai",
					Ranges: []adaptor.ClockRange{adaptor.ClockRange{
						Start: "08:00",
						End:   "00:00",
					},
					},
					Overlay: adaptor.ModelConfig{
						Ratio:           nativeRate(2e+01),
						CompletionRatio: 1,
					},
				},
			},
			ContextLength: 32000,
			Description:   "Baichuan2-53B on baichuan; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Baichuan2-Turbo": {
			Ratio:                       nativeRate(8),
			CompletionRatio:             1,
			ContextLength:               32000,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "frequency_penalty", "presence_penalty", "seed"},
			Quantization:                "bf16",
			HuggingFaceID:               "baichuan-inc/Baichuan2-13B-Chat",
			Description:                 "Baichuan2-Turbo on baichuan; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Baichuan3-Turbo": {
			Ratio:                       nativeRate(12),
			CompletionRatio:             1,
			ContextLength:               32000,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "frequency_penalty", "presence_penalty", "seed"},
			Description:                 "Baichuan3-Turbo on baichuan; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Baichuan3-Turbo-128k": {
			Ratio:                       nativeRate(24),
			CompletionRatio:             1,
			ContextLength:               128000,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "frequency_penalty", "presence_penalty", "seed"},
			Description:                 "Baichuan3-Turbo-128k on baichuan; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Baichuan4": {
			Ratio:                       nativeRate(1e+02),
			CompletionRatio:             1,
			ContextLength:               32000,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "frequency_penalty", "presence_penalty", "seed"},
			Description:                 "Baichuan4 on baichuan; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Baichuan4-Air": {
			Ratio:                       nativeRate(0.98),
			CompletionRatio:             1,
			ContextLength:               32000,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "frequency_penalty", "presence_penalty", "seed"},
			Description:                 "Baichuan4-Air on baichuan; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Baichuan4-Turbo": {
			Ratio:                       nativeRate(15),
			CompletionRatio:             1,
			ContextLength:               32000,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "frequency_penalty", "presence_penalty", "seed"},
			Description:                 "Baichuan4-Turbo on baichuan; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
