package deepinfra

import "github.com/Laisky/one-api/relay/adaptor"

// deepseek_aiModels returns the deepseek_ai model defaults for deepinfra.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func deepseek_aiModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"deepseek-ai/DeepSeek-R1-0528": {
			Ratio:                       nativeRate(0.5),
			CompletionRatio:             4.3,
			CachedInputRatio:            nativeRate(0.35),
			ContextLength:               163840,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "deepseek-ai/DeepSeek-R1-0528 on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek-ai/DeepSeek-V3": {
			Ratio:                       nativeRate(0.32),
			CompletionRatio:             2.7812499999999996,
			ContextLength:               163840,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "deepseek-ai/DeepSeek-V3 on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek-ai/DeepSeek-V3-0324": {
			Ratio:                       nativeRate(0.24),
			CompletionRatio:             3.7500000000000004,
			CachedInputRatio:            nativeRate(0.135),
			ContextLength:               160000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "DeepInfra hosted text-generation model.",
		},
		"deepseek-ai/DeepSeek-V3.1": {
			Ratio:                       nativeRate(0.25),
			CompletionRatio:             3.8000000000000003,
			CachedInputRatio:            nativeRate(0.13),
			ContextLength:               163840,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "deepseek-ai/DeepSeek-V3.1 on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek-ai/DeepSeek-V3.2": {
			Ratio:                       nativeRate(0.26),
			CompletionRatio:             1.4615384615384615,
			CachedInputRatio:            nativeRate(0.13),
			ContextLength:               163840,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "deepseek-ai/DeepSeek-V3.2 on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek-ai/DeepSeek-V4-Flash": {
			Ratio:                       nativeRate(0.09),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.018),
			ContextLength:               1048576,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "deepseek-ai/DeepSeek-V4-Flash on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek-ai/DeepSeek-V4-Flash-0731": {
			Ratio:                       nativeRate(0.060000000000000005),
			CompletionRatio:             2.9999999999999996,
			CachedInputRatio:            nativeRate(0.015000000000000001),
			ContextLength:               1048576,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "deepseek-ai/DeepSeek-V4-Flash-0731 on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek-ai/DeepSeek-V4-Flash-Vision-Exp": {
			Ratio:             nativeRate(0.21559999999999999),
			CompletionRatio:   3.0000000000000004,
			CachedInputRatio:  nativeRate(0.006859999608),
			ContextLength:     1048576,
			InputModalities:   []string{"text", "image"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			Description:       "deepseek-ai/DeepSeek-V4-Flash-Vision-Exp on DeepInfra. Observed 51% promotion on 2026-09-24; discount applied once to token/cache prices. No end date published; this is a dated quote, not a permanent-price guarantee.",
		},
		"deepseek-ai/DeepSeek-V4-Pro": {
			Ratio:                       nativeRate(1.2999999999999998),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.10000000399999999),
			ContextLength:               1048576,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "deepseek-ai/DeepSeek-V4-Pro on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek-ai/DeepSeek-V4-Pro-0813": {
			Ratio:                       nativeRate(1.2999999999999998),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.10000000399999999),
			ContextLength:               1048576,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "deepseek-ai/DeepSeek-V4-Pro-0813 on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek-ai/DeepSeek-V4.1-Flash": {
			Ratio:             nativeRate(0.13999999999999999),
			CompletionRatio:   3,
			CachedInputRatio:  nativeRate(0.0042),
			ContextLength:     1048576,
			InputModalities:   []string{"text", "image"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			Description:       "deepseek-ai/DeepSeek-V4.1-Flash on DeepInfra. Observed 30% promotion on 2026-09-24; discount applied once to token/cache prices. No end date published; this is a dated quote, not a permanent-price guarantee.",
		},
		"deepseek-ai/Janus-Pro-1B": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.0005,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				MinImages:        1,
				MaxImages:        4,
			},
			InputModalities:  []string{"text"},
			OutputModalities: []string{"image"},
			Description:      "Janus Pro 1B image generation model.",
		},
		"deepseek-ai/Janus-Pro-7B": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.002,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				MinImages:        1,
				MaxImages:        4,
			},
			InputModalities:  []string{"text"},
			OutputModalities: []string{"image"},
			Description:      "Janus Pro 7B image generation model.",
		},
	}
}
