package deepinfra

// mediaCatalog20260819 contains active DeepInfra models whose relay protocol
// and published pricing can be represented exactly by one-api. Iteration-priced
// and output-token-priced image models, video/world/music/OCR models, and the
// image-document reranker are intentionally excluded.
func init() {
	addDeepInfraCatalogModel("nvidia/llama-nemotron-embed-vl-1b-v2", catalogEmbeddingModel(0.01, 10000, []string{"text", "image"}, "Nemotron VL 1B multimodal embedding model."))
	addDeepInfraCatalogModel("sentence-transformers/clip-ViT-B-32", catalogEmbeddingModel(0.005, 77, []string{"text", "image"}, "CLIP ViT-B/32 text and image embedding model."))
	addDeepInfraCatalogModel("sentence-transformers/clip-ViT-B-32-multilingual-v1", catalogEmbeddingModel(0.005, 512, []string{"text", "image"}, "Multilingual CLIP ViT-B/32 embedding model."))
	addDeepInfraCatalogModel("shibing624/text2vec-base-chinese", catalogEmbeddingModel(0.005, 512, []string{"text"}, "Chinese Text2Vec base embedding model."))
	addDeepInfraCatalogModel("thenlper/gte-base", catalogEmbeddingModel(0.005, 512, []string{"text"}, "GTE base text embedding model."))
	addDeepInfraCatalogModel("thenlper/gte-large", catalogEmbeddingModel(0.01, 512, []string{"text"}, "GTE large text embedding model."))
	addDeepInfraCatalogModel("XiaomiMiMo/MiMo-V2.5-tts", characterPricedAudioModel(0, "MiMo V2.5 text-to-speech model."))
	addDeepInfraCatalogModel("XiaomiMiMo/MiMo-V2.5-tts-voiceclone", characterPricedAudioModel(0, "MiMo V2.5 voice-cloning speech model."))
	addDeepInfraCatalogModel("XiaomiMiMo/MiMo-V2.5-tts-voicedesign", characterPricedAudioModel(0, "MiMo V2.5 voice-design speech model."))
	addDeepInfraCatalogModel("Bria/Bria-3.2", flatImageModel(0.04, false, "Bria 3.2 commercial text-to-image model."))
	addDeepInfraCatalogModel("Bria/Bria-3.2-vector", flatImageModel(0.04, false, "Bria 3.2 Vector text-to-vector-image model."))
	addDeepInfraCatalogModel("Bria/blur_background", flatImageModel(0.04, true, "Bria licensed-data background blur model."))
	addDeepInfraCatalogModel("Bria/enhance", flatImageModel(0.04, true, "Bria licensed-data image enhancement model."))
	addDeepInfraCatalogModel("Bria/erase", flatImageModel(0.04, true, "Bria licensed-data object eraser."))
	addDeepInfraCatalogModel("Bria/erase_foreground", flatImageModel(0.04, true, "Bria licensed-data foreground eraser."))
	addDeepInfraCatalogModel("Bria/expand", flatImageModel(0.04, true, "Bria licensed-data image expansion model."))
	addDeepInfraCatalogModel("Bria/fibo", flatImageModel(0.04, false, "Bria FIBO structured text-to-image model."))
	addDeepInfraCatalogModel("Bria/fibo_edit", flatImageModel(0.04, true, "Bria FIBO image editing model."))
	addDeepInfraCatalogModel("Bria/gen_fill", flatImageModel(0.04, true, "Bria licensed-data generative fill model."))
	addDeepInfraCatalogModel("Bria/remove_background", flatImageModel(0.018, true, "Bria background removal model."))
	addDeepInfraCatalogModel("Bria/replace_background", flatImageModel(0.04, true, "Bria background replacement model."))
	addDeepInfraCatalogModel("ByteDance/Seedream-4", flatImageModel(0.04, true, "Seedream 4 multimodal image generation and editing model."))
	addDeepInfraCatalogModel("ByteDance/Seedream-4.5", flatImageModel(0.04, true, "Seedream 4.5 multimodal image generation and editing model."))
	addDeepInfraCatalogModel("ClarityAI/creative", flatImageModel(0.05, true, "ClarityAI creative image upscaler."))
	addDeepInfraCatalogModel("ClarityAI/crystal", flatImageModel(0.05, true, "ClarityAI portrait and product upscaler."))
	addDeepInfraCatalogModel("ClarityAI/flux", flatImageModel(0.2, true, "ClarityAI FLUX-powered image upscaler."))
	addDeepInfraCatalogModel("PrunaAI/p-image", flatImageModel(0.005, false, "Pruna P-Image real-time generation model."))
	addDeepInfraCatalogModel("PrunaAI/p-image-Edit", flatImageModel(0.01, true, "Pruna P-Image-Edit transformation model."))
	addDeepInfraCatalogModel("Qwen/Qwen-Image-Edit-Max", flatImageModel(0.075, true, "Qwen Image Edit Max model."))
	addDeepInfraCatalogModel("Qwen/Qwen-Image-Max", flatImageModel(0.075, false, "Qwen Image Max generation model."))
	addDeepInfraCatalogModel("Wan-AI/Wan2.6-Image-Edit", flatImageModel(0.03, true, "Wan 2.6 image generation and editing model."))
	addDeepInfraCatalogModel("Wan-AI/Wan2.6-T2I", flatImageModel(0.03, false, "Wan 2.6 text-to-image model."))
	addDeepInfraCatalogModel("Wan-AI/Wan2.7-Image-Edit", flatImageModel(0.03, true, "Wan 2.7 image generation and editing model."))
	addDeepInfraCatalogModel("black-forest-labs/FLUX-1.1-pro", flatImageModel(0.04, false, "FLUX 1.1 Pro text-to-image model."))
	addDeepInfraCatalogModel("black-forest-labs/FLUX-2-max", flatImageModel(0.07, true, "FLUX 2 Max image generation and editing model."))
	addDeepInfraCatalogModel("black-forest-labs/FLUX-2-pro", flatImageModel(0.015, true, "FLUX 2 Pro image generation and editing model."))
	addDeepInfraCatalogModel("deepseek-ai/Janus-Pro-1B", flatImageModel(0.0005, false, "Janus Pro 1B image generation model."))
	addDeepInfraCatalogModel("deepseek-ai/Janus-Pro-7B", flatImageModel(0.002, false, "Janus Pro 7B image generation model."))
}
