package deepinfra

import "github.com/Laisky/one-api/relay/adaptor"

// otherModels returns the other model defaults for deepinfra.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func otherModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"Audio8/Audio8-TTS-Preview-0.6b": {
			Ratio:            nativeRate(5),
			CompletionRatio:  1,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"audio"},
			Description:      "Audio8 compact preview text-to-speech model.",
		},
		"ClarityAI/creative": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.05,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				MinImages:        1,
				MaxImages:        4,
			},
			InputModalities:  []string{"text", "image"},
			OutputModalities: []string{"image"},
			Description:      "ClarityAI creative image upscaler.",
		},
		"ClarityAI/crystal": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.05,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				MinImages:        1,
				MaxImages:        4,
			},
			InputModalities:  []string{"text", "image"},
			OutputModalities: []string{"image"},
			Description:      "ClarityAI portrait and product upscaler.",
		},
		"ClarityAI/flux": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.2,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				MinImages:        1,
				MaxImages:        4,
			},
			InputModalities:  []string{"text", "image"},
			OutputModalities: []string{"image"},
			Description:      "ClarityAI FLUX-powered image upscaler.",
		},
		"Gryphe/MythoMax-L2-13b": {
			Ratio:                       nativeRate(0.4),
			CompletionRatio:             1,
			ContextLength:               4096,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Gryphe/MythoMax-L2-13b on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"MiniMaxAI/MiniMax-M2.7": {
			Ratio:                       nativeRate(0.25),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.05),
			ContextLength:               196608,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "MiniMax M2.7 reasoning model.",
		},
		"MiniMaxAI/MiniMax-M2.7-Turbo": {
			Ratio:                       nativeRate(0.38),
			CompletionRatio:             4.473684210526316,
			CachedInputRatio:            nativeRate(0.07000000140000001),
			ContextLength:               196608,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "MiniMaxAI/MiniMax-M2.7-Turbo on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"MiniMaxAI/MiniMax-M3": {
			Ratio:                       nativeRate(0.27999999999999997),
			CompletionRatio:             3.9285714285714293,
			CachedInputRatio:            nativeRate(0.055999999999999994),
			ContextLength:               524288,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "MiniMaxAI/MiniMax-M3 on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"NousResearch/Hermes-3-Llama-3.1-405B": {
			Ratio:                       nativeRate(1),
			CompletionRatio:             1,
			ContextLength:               131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "NousResearch/Hermes-3-Llama-3.1-405B on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"NousResearch/Hermes-3-Llama-3.1-70B": {
			Ratio:                       nativeRate(0.7),
			CompletionRatio:             1,
			ContextLength:               131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "NousResearch/Hermes-3-Llama-3.1-70B on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"PrunaAI/p-image": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.005,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				MinImages:        1,
				MaxImages:        4,
			},
			InputModalities:  []string{"text"},
			OutputModalities: []string{"image"},
			Description:      "Pruna P-Image real-time generation model.",
		},
		"PrunaAI/p-image-Edit": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.01,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				MinImages:        1,
				MaxImages:        4,
			},
			InputModalities:  []string{"text", "image"},
			OutputModalities: []string{"image"},
			Description:      "Pruna P-Image-Edit transformation model.",
		},
		"ResembleAI/chatterbox-multilingual": {
			Ratio:            nativeRate(1),
			CompletionRatio:  1,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"audio"},
			Description:      "Multilingual Chatterbox text-to-speech model.",
		},
		"ResembleAI/chatterbox-turbo": {
			Ratio:            nativeRate(1),
			CompletionRatio:  1,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"audio"},
			Description:      "Low-latency Chatterbox text-to-speech model.",
		},
		"Sao10K/L3-8B-Lunaris-v1-Turbo": {
			Ratio:                       nativeRate(0.04),
			CompletionRatio:             1.25,
			ContextLength:               8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Sao10K/L3-8B-Lunaris-v1-Turbo on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Sao10K/L3.1-70B-Euryale-v2.2": {
			Ratio:                       nativeRate(0.8500000000000001),
			CompletionRatio:             1,
			ContextLength:               131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Sao10K/L3.1-70B-Euryale-v2.2 on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Wan-AI/Wan2.6-Image-Edit": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.03,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				MinImages:        1,
				MaxImages:        4,
			},
			InputModalities:  []string{"text", "image"},
			OutputModalities: []string{"image"},
			Description:      "Wan 2.6 image generation and editing model.",
		},
		"Wan-AI/Wan2.6-T2I": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.03,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				MinImages:        1,
				MaxImages:        4,
			},
			InputModalities:  []string{"text"},
			OutputModalities: []string{"image"},
			Description:      "Wan 2.6 text-to-image model.",
		},
		"Wan-AI/Wan2.7-Image-Edit": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.03,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				MinImages:        1,
				MaxImages:        4,
			},
			InputModalities:  []string{"text", "image"},
			OutputModalities: []string{"image"},
			Description:      "Wan 2.7 image generation and editing model.",
		},
		"XiaomiMiMo/MiMo-V2.5": {
			Ratio:                       nativeRate(0.4),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.08),
			ContextLength:               262144,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "MiMo V2.5 general reasoning model.",
		},
		"XiaomiMiMo/MiMo-V2.5-Pro": {
			Ratio:                       nativeRate(1),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.2),
			ContextLength:               1048576,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "MiMo V2.5 Pro long-context reasoning model.",
		},
		"XiaomiMiMo/MiMo-V2.5-tts": {
			Ratio:            0,
			CompletionRatio:  1,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"audio"},
			Description:      "MiMo V2.5 text-to-speech model.",
		},
		"XiaomiMiMo/MiMo-V2.5-tts-voiceclone": {
			Ratio:            0,
			CompletionRatio:  1,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"audio"},
			Description:      "MiMo V2.5 voice-cloning speech model.",
		},
		"XiaomiMiMo/MiMo-V2.5-tts-voicedesign": {
			Ratio:            0,
			CompletionRatio:  1,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"audio"},
			Description:      "MiMo V2.5 voice-design speech model.",
		},
		"black-forest-labs/FLUX-1.1-pro": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.04,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				MinImages:        1,
				MaxImages:        4,
			},
			InputModalities:  []string{"text"},
			OutputModalities: []string{"image"},
			Description:      "FLUX 1.1 Pro text-to-image model.",
		},
		"black-forest-labs/FLUX-2-klein-4b": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.014,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				MinImages:        1,
				MaxImages:        4,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1024x1536": 1.5,
					"1536x1024": 1.5,
					"512x512":   0.25,
					"768x768":   0.5625,
				},
			},
			InputModalities:  []string{"text", "image"},
			OutputModalities: []string{"image"},
			Description:      "FLUX.2 Klein 4B text-to-image and image editing model.",
		},
		"black-forest-labs/FLUX-2-klein-9b": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.015,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				MinImages:        1,
				MaxImages:        4,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1024x1536": 1.5,
					"1536x1024": 1.5,
					"512x512":   0.25,
					"768x768":   0.5625,
				},
			},
			InputModalities:  []string{"text", "image"},
			OutputModalities: []string{"image"},
			Description:      "FLUX.2 Klein 9B text-to-image and image editing model.",
		},
		"black-forest-labs/FLUX-2-max": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.07,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				MinImages:        1,
				MaxImages:        4,
			},
			InputModalities:  []string{"text", "image"},
			OutputModalities: []string{"image"},
			Description:      "FLUX 2 Max image generation and editing model.",
		},
		"black-forest-labs/FLUX-2-pro": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.015,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				MinImages:        1,
				MaxImages:        4,
			},
			InputModalities:  []string{"text", "image"},
			OutputModalities: []string{"image"},
			Description:      "FLUX 2 Pro image generation and editing model.",
		},
		"bosonai/HiggsAudioV2.5": {
			Ratio:            nativeRate(2e+01),
			CompletionRatio:  1,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"audio"},
			Description:      "HiggsAudio V2.5 natural text-to-speech model.",
		},
		"canopylabs/orpheus-3b-0.1-ft": {
			Ratio:            nativeRate(7),
			CompletionRatio:  1,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"audio"},
			Description:      "Orpheus empathetic text-to-speech model.",
		},
		"hexgrad/Kokoro-82M": {
			Ratio:            nativeRate(0.62),
			CompletionRatio:  1,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"audio"},
			Description:      "Compact and efficient Kokoro text-to-speech model.",
		},
		"ibm-granite/granite-4.2-30b": {
			Ratio:             nativeRate(0.16),
			CompletionRatio:   4.062499999999999,
			CachedInputRatio:  nativeRate(0.04),
			ContextLength:     131072,
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "json_mode", "reasoning"},
			Description:       "ibm-granite/granite-4.2-30b on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"ibm-granite/granite-4.2-3b": {
			Ratio:             nativeRate(0.030000000000000002),
			CompletionRatio:   4,
			CachedInputRatio:  nativeRate(0.007500000000000001),
			ContextLength:     131072,
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "json_mode", "reasoning"},
			Description:       "ibm-granite/granite-4.2-3b on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"ibm-granite/granite-4.2-8b": {
			Ratio:             nativeRate(0.060000000000000005),
			CompletionRatio:   4.166666666666666,
			CachedInputRatio:  nativeRate(0.015000000000000001),
			ContextLength:     131072,
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "json_mode", "reasoning"},
			Description:       "ibm-granite/granite-4.2-8b on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"inclusionAI/Ling-3.0-flash": {
			Ratio:                       nativeRate(0.060000000000000005),
			CompletionRatio:             2.9999999999999996,
			CachedInputRatio:            nativeRate(0.012000000000000002),
			ContextLength:               131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "inclusionAI/Ling-3.0-flash on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"inclusionAI/Ling-3.0-flash-Fin": {
			Ratio:             nativeRate(0.060000000000000005),
			CompletionRatio:   2.9999999999999996,
			CachedInputRatio:  nativeRate(0.012000000000000002),
			ContextLength:     262144,
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			Description:       "inclusionAI/Ling-3.0-flash-Fin on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"inclusionAI/Ling-3.0-flash-VL": {
			Ratio:             nativeRate(0.060000000000000005),
			CompletionRatio:   2.9999999999999996,
			CachedInputRatio:  nativeRate(0.012000000000000002),
			ContextLength:     131072,
			InputModalities:   []string{"text", "image", "video"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			Description:       "inclusionAI/Ling-3.0-flash-VL on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"intfloat/e5-base-v2": {
			Ratio:           nativeRate(0.005),
			CompletionRatio: 0,
			Embedding: &adaptor.EmbeddingPricingConfig{
				TextTokenRatio: nativeRate(0.005),
			},
			ContextLength:    512,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"embedding"},
			Description:      "intfloat/e5-base-v2 on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"intfloat/e5-large-v2": {
			Ratio:           nativeRate(0.01),
			CompletionRatio: 0,
			Embedding: &adaptor.EmbeddingPricingConfig{
				TextTokenRatio: nativeRate(0.01),
			},
			ContextLength:    512,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"embedding"},
			Description:      "intfloat/e5-large-v2 on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"intfloat/multilingual-e5-large": {
			Ratio:           nativeRate(0.01),
			CompletionRatio: 0,
			Embedding: &adaptor.EmbeddingPricingConfig{
				TextTokenRatio: nativeRate(0.01),
			},
			ContextLength:    512,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"embedding"},
			Description:      "intfloat/multilingual-e5-large on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"intfloat/multilingual-e5-large-instruct": {
			Ratio:           nativeRate(0.01),
			CompletionRatio: 0,
			Embedding: &adaptor.EmbeddingPricingConfig{
				TextTokenRatio: nativeRate(0.01),
			},
			ContextLength:    512,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"embedding"},
			Description:      "intfloat/multilingual-e5-large-instruct on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"inworld-ai/realtime-tts-1.5-max": {
			Ratio:            nativeRate(5e+01),
			CompletionRatio:  1,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"audio"},
			Description:      "High-quality Inworld real-time text-to-speech model.",
		},
		"inworld-ai/realtime-tts-1.5-mini": {
			Ratio:            nativeRate(25),
			CompletionRatio:  1,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"audio"},
			Description:      "Low-latency Inworld real-time text-to-speech model.",
		},
		"inworld-ai/realtime-tts-2": {
			Ratio:            nativeRate(35),
			CompletionRatio:  1,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"audio"},
			Description:      "Steerable Inworld real-time text-to-speech model.",
		},
		"meta-models/Muse-Glimmer-30B": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.039999999),
			ContextLength:               131072,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "meta-models/Muse-Glimmer-30B on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"microsoft/phi-4": {
			Ratio:                       nativeRate(0.06999999999999999),
			CompletionRatio:             2,
			ContextLength:               16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "microsoft/phi-4 on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"mistralai/Mistral-Nemo-Instruct-2407": {
			Ratio:                       nativeRate(0.019),
			CompletionRatio:             1.5789473684210529,
			ContextLength:               131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "mistralai/Mistral-Nemo-Instruct-2407 on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"mistralai/Mistral-Small-24B-Instruct-2501": {
			Ratio:                       nativeRate(0.05),
			CompletionRatio:             1.5999999999999999,
			ContextLength:               32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "mistralai/Mistral-Small-24B-Instruct-2501 on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"mistralai/Mistral-Small-3.2-24B-Instruct-2506": {
			Ratio:                       nativeRate(0.075),
			CompletionRatio:             2.666666666666667,
			ContextLength:               128000,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "mistralai/Mistral-Small-3.2-24B-Instruct-2506 on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"mistralai/Voxtral-Mini-3B-2507": {
			Ratio:           nativeRate(1.6666666666666667),
			CompletionRatio: 1,
			Audio: &adaptor.AudioPricingConfig{
				PromptTokensPerSecond: 10,
				UsdPerSecond:          1.6666666666666667e-05,
			},
			InputModalities:  []string{"audio"},
			OutputModalities: []string{"text"},
			Description:      "Voxtral Mini transcription and speech translation model.",
		},
		"mistralai/Voxtral-Small-24B-2507": {
			Ratio:           nativeRate(5),
			CompletionRatio: 1,
			Audio: &adaptor.AudioPricingConfig{
				PromptTokensPerSecond: 10,
				UsdPerSecond:          5e-05,
			},
			InputModalities:  []string{"audio"},
			OutputModalities: []string{"text"},
			Description:      "Voxtral Small transcription and speech translation model.",
		},
		"moonshotai/Kimi-K2.5": {
			Ratio:                       nativeRate(0.45),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.07),
			ContextLength:               262144,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Kimi K2.5 general reasoning model.",
		},
		"moonshotai/Kimi-K2.6": {
			Ratio:                       nativeRate(0.7499999999999999),
			CompletionRatio:             4.666666666666667,
			CachedInputRatio:            nativeRate(0.15),
			ContextLength:               262144,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "moonshotai/Kimi-K2.6 on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"moonshotai/Kimi-K2.7-Code": {
			Ratio:                       nativeRate(0.68),
			CompletionRatio:             4.999999999999999,
			CachedInputRatio:            nativeRate(0.136),
			ContextLength:               262144,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Kimi K2.7 optimized for software engineering.",
		},
		"moonshotai/Kimi-K3": {
			Ratio:                       nativeRate(2.85),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.28500000000000003),
			ContextLength:               1048576,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "moonshotai/Kimi-K3 on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"sesame/csm-1b": {
			Ratio:            nativeRate(7),
			CompletionRatio:  1,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"audio"},
			Description:      "Sesame conversational speech generation model.",
		},
		"shibing624/text2vec-base-chinese": {
			Ratio:           nativeRate(0.005),
			CompletionRatio: 0,
			Embedding: &adaptor.EmbeddingPricingConfig{
				TextTokenRatio: nativeRate(0.005),
			},
			ContextLength:    512,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"embedding"},
			Description:      "shibing624/text2vec-base-chinese on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"stepfun-ai/Step-3.7-Flash": {
			Ratio:                       nativeRate(0.16000000000000003),
			CompletionRatio:             5.75,
			CachedInputRatio:            nativeRate(0.03200000000000001),
			ContextLength:               262144,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "stepfun-ai/Step-3.7-Flash on DeepInfra. Observed 20% promotion on 2026-09-24; discount applied once to token/cache prices. No end date published; this is a dated quote, not a permanent-price guarantee.",
		},
		"tencent/Hy3": {
			Ratio:                       nativeRate(0.13),
			CompletionRatio:             4.076923076923077,
			CachedInputRatio:            nativeRate(0.0329999995),
			ContextLength:               262144,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "tencent/Hy3 on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"thenlper/gte-base": {
			Ratio:           nativeRate(0.005),
			CompletionRatio: 0,
			Embedding: &adaptor.EmbeddingPricingConfig{
				TextTokenRatio: nativeRate(0.005),
			},
			ContextLength:    512,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"embedding"},
			Description:      "thenlper/gte-base on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"thenlper/gte-large": {
			Ratio:           nativeRate(0.01),
			CompletionRatio: 0,
			Embedding: &adaptor.EmbeddingPricingConfig{
				TextTokenRatio: nativeRate(0.01),
			},
			ContextLength:    512,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"embedding"},
			Description:      "thenlper/gte-large on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"thinkingmachines/Inkling": {
			Ratio:                       nativeRate(0.95),
			CompletionRatio:             4.2631578947368425,
			CachedInputRatio:            nativeRate(0.16),
			ContextLength:               512000,
			InputModalities:             []string{"text", "image", "audio"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "DeepInfra hosted text-generation model.",
		},
		"thinkingmachines/Inkling-Small": {
			Ratio:                       nativeRate(0.45),
			CompletionRatio:             2.6666666666666665,
			CachedInputRatio:            nativeRate(0.1),
			ContextLength:               512000,
			InputModalities:             []string{"text", "image", "audio"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "DeepInfra hosted text-generation model.",
		},
	}
}
