package deepinfra

import "github.com/Laisky/one-api/relay/adaptor"

// qwenModels returns the qwen model defaults for deepinfra.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func qwenModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"Qwen/Qwen-Image-Edit-Max": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.075,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				MinImages:        1,
				MaxImages:        4,
			},
			InputModalities:  []string{"text", "image"},
			OutputModalities: []string{"image"},
			Description:      "Qwen Image Edit Max model.",
		},
		"Qwen/Qwen-Image-Max": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.075,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				MinImages:        1,
				MaxImages:        4,
			},
			InputModalities:  []string{"text"},
			OutputModalities: []string{"image"},
			Description:      "Qwen Image Max generation model.",
		},
		"Qwen/Qwen2.5-72B-Instruct": {
			Ratio:                       nativeRate(0.36),
			CompletionRatio:             1.1111111111111112,
			ContextLength:               32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Qwen/Qwen2.5-72B-Instruct on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3-14B": {
			Ratio:                       nativeRate(0.12000000000000001),
			CompletionRatio:             2,
			ContextLength:               40960,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Qwen/Qwen3-14B on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3-235B-A22B-Instruct-2507": {
			Ratio:                       nativeRate(0.09),
			CompletionRatio:             6.111111111111112,
			ContextLength:               262144,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Qwen/Qwen3-235B-A22B-Instruct-2507 on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3-30B-A3B": {
			Ratio:                       nativeRate(0.12000000000000001),
			CompletionRatio:             4.166666666666666,
			ContextLength:               40960,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Qwen/Qwen3-30B-A3B on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3-32B": {
			Ratio:                       nativeRate(0.08),
			CompletionRatio:             3.4999999999999996,
			ContextLength:               40960,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Qwen/Qwen3-32B on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3-ASR-0.6B": {
			Ratio:           nativeRate(0.3333333333333333),
			CompletionRatio: 1,
			Audio: &adaptor.AudioPricingConfig{
				PromptTokensPerSecond: 10,
				UsdPerSecond:          3.3333333333333333e-06,
			},
			InputModalities:  []string{"audio"},
			OutputModalities: []string{"text"},
			Description:      "Compact multilingual Qwen3 speech recognition model.",
		},
		"Qwen/Qwen3-ASR-1.7B": {
			Ratio:           nativeRate(0.75),
			CompletionRatio: 1,
			Audio: &adaptor.AudioPricingConfig{
				PromptTokensPerSecond: 10,
				UsdPerSecond:          7.5e-06,
			},
			InputModalities:  []string{"audio"},
			OutputModalities: []string{"text"},
			Description:      "Flagship multilingual Qwen3 speech recognition model.",
		},
		"Qwen/Qwen3-Coder-480B-A35B-Instruct-Turbo": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             3.3333333333333335,
			CachedInputRatio:            nativeRate(0.09999999899999999),
			ContextLength:               262144,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Qwen/Qwen3-Coder-480B-A35B-Instruct-Turbo on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3-Embedding-0.6B": {
			Ratio:           nativeRate(0.01),
			CompletionRatio: 0,
			Embedding: &adaptor.EmbeddingPricingConfig{
				TextTokenRatio: nativeRate(0.01),
			},
			ContextLength:    32768,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"embedding"},
			Description:      "Qwen/Qwen3-Embedding-0.6B on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3-Embedding-4B": {
			Ratio:           nativeRate(0.02),
			CompletionRatio: 0,
			Embedding: &adaptor.EmbeddingPricingConfig{
				TextTokenRatio: nativeRate(0.02),
			},
			ContextLength:    32768,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"embedding"},
			Description:      "Qwen/Qwen3-Embedding-4B on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3-Embedding-8B": {
			Ratio:           nativeRate(0.01),
			CompletionRatio: 0,
			Embedding: &adaptor.EmbeddingPricingConfig{
				TextTokenRatio: nativeRate(0.01),
			},
			ContextLength:    32768,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"embedding"},
			Description:      "Qwen/Qwen3-Embedding-8B on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3-Max": {
			Ratio:                       nativeRate(1.2),
			CompletionRatio:             4.999999999999999,
			CachedInputRatio:            nativeRate(0.24),
			ContextLength:               256000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Qwen/Qwen3-Max on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3-Max-Thinking": {
			Ratio:                       nativeRate(1.2),
			CompletionRatio:             4.999999999999999,
			CachedInputRatio:            nativeRate(0.24),
			ContextLength:               256000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Qwen/Qwen3-Max-Thinking on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3-Next-80B-A3B-Instruct": {
			Ratio:                       nativeRate(0.09),
			CompletionRatio:             12.222222222222223,
			ContextLength:               262144,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Qwen/Qwen3-Next-80B-A3B-Instruct on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3-Reranker-0.6B": {
			Ratio:                       nativeRate(0.01),
			CompletionRatio:             0,
			ContextLength:               32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"top_n"},
			Description:                 "Qwen/Qwen3-Reranker-0.6B on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3-Reranker-4B": {
			Ratio:                       nativeRate(0.025),
			CompletionRatio:             0,
			ContextLength:               32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"top_n"},
			Description:                 "Qwen/Qwen3-Reranker-4B on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3-Reranker-8B": {
			Ratio:                       nativeRate(0.05),
			CompletionRatio:             0,
			ContextLength:               32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"top_n"},
			Description:                 "Qwen/Qwen3-Reranker-8B on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3-TTS": {
			Ratio:            nativeRate(2e+01),
			CompletionRatio:  1,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"audio"},
			Description:      "Qwen3 text-to-speech model.",
		},
		"Qwen/Qwen3-TTS-VoiceDesign": {
			Ratio:            nativeRate(2e+01),
			CompletionRatio:  1,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"audio"},
			Description:      "Qwen3 TTS model with prompt-driven voice design.",
		},
		"Qwen/Qwen3-VL-235B-A22B-Instruct": {
			Ratio:                       nativeRate(0.2),
			CompletionRatio:             4.3999999999999995,
			CachedInputRatio:            nativeRate(0.11000000000000001),
			ContextLength:               262144,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Qwen/Qwen3-VL-235B-A22B-Instruct on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3-VL-30B-A3B-Instruct": {
			Ratio:                       nativeRate(0.15),
			CompletionRatio:             4,
			ContextLength:               262144,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Qwen/Qwen3-VL-30B-A3B-Instruct on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3.5-122B-A10B": {
			Ratio:                       nativeRate(0.29),
			CompletionRatio:             8.275862068965518,
			ContextLength:               262144,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Qwen/Qwen3.5-122B-A10B on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3.5-27B": {
			Ratio:                       nativeRate(0.26),
			CompletionRatio:             9.999999999999998,
			ContextLength:               262144,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Qwen/Qwen3.5-27B on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3.5-35B-A3B": {
			Ratio:                       nativeRate(0.13999999999999999),
			CompletionRatio:             7.142857142857143,
			CachedInputRatio:            nativeRate(0.050000000399999994),
			ContextLength:               262144,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Qwen/Qwen3.5-35B-A3B on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3.5-397B-A17B": {
			Ratio:                       nativeRate(0.45),
			CompletionRatio:             6.666666666666665,
			CachedInputRatio:            nativeRate(0.22000000050000001),
			ContextLength:               262144,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Qwen/Qwen3.5-397B-A17B on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3.5-9B": {
			Ratio:                       nativeRate(0.1),
			CompletionRatio:             1.4999999999999998,
			ContextLength:               262144,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Qwen/Qwen3.5-9B on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3.6-27B": {
			Ratio:                       nativeRate(0.32),
			CompletionRatio:             10,
			ContextLength:               262144,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Qwen/Qwen3.6-27B on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3.6-35B-A3B": {
			Ratio:                       nativeRate(0.1),
			CompletionRatio:             9.5,
			ContextLength:               262144,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Qwen/Qwen3.6-35B-A3B on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3.7-Max": {
			Ratio:                       nativeRate(2.5),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.5),
			ContextLength:               256000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Qwen/Qwen3.7-Max on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3.8-2.4T-A95B": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             2.9999999999999996,
			CachedInputRatio:            nativeRate(0.2),
			ContextLength:               262144,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Qwen/Qwen3.8-2.4T-A95B on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3.8-27B": {
			Ratio:                       nativeRate(0.15000000000000002),
			CompletionRatio:             12.499999999999998,
			CachedInputRatio:            nativeRate(0.037500000000000006),
			ContextLength:               262144,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Qwen/Qwen3.8-27B on DeepInfra. Observed 25% promotion on 2026-09-24; discount applied once to token/cache prices. No end date published; this is a dated quote, not a permanent-price guarantee.",
		},
		"Qwen/Qwen3.8-Flash": {
			Ratio:             nativeRate(0.113),
			CompletionRatio:   3.3805309734513274,
			CachedInputRatio:  nativeRate(0.01409999988),
			ContextLength:     1000000,
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "json_mode", "structured_outputs"},
			Description:       "Qwen/Qwen3.8-Flash on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3.8-Max": {
			Ratio:                       nativeRate(1.65),
			CompletionRatio:             3.000606060606061,
			CachedInputRatio:            nativeRate(0.205999992),
			ContextLength:               256000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Qwen/Qwen3.8-Max on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
