package deepinfra

import "github.com/Laisky/one-api/relay/adaptor"

// googleModels returns the google model defaults for deepinfra.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func googleModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"google/embeddinggemma-300m": {
			Ratio:           nativeRate(0.002),
			CompletionRatio: 0,
			Embedding: &adaptor.EmbeddingPricingConfig{
				TextTokenRatio: nativeRate(0.002),
			},
			ContextLength:    2048,
			InputModalities:  []string{"text"},
			OutputModalities: []string{"embedding"},
			Description:      "google/embeddinggemma-300m on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"google/gemini-2.5-flash": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             8.333333333333334,
			ContextLength:               976000,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "DeepInfra hosted text-generation model.",
		},
		"google/gemini-2.5-pro": {
			Ratio:                       nativeRate(1.25),
			CompletionRatio:             8,
			ContextLength:               976000,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "DeepInfra hosted text-generation model.",
		},
		"google/gemini-3.1-flash-lite": {
			Ratio:                       nativeRate(0.25),
			CompletionRatio:             6,
			ContextLength:               976000,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "DeepInfra hosted text-generation model.",
		},
		"google/gemini-3.1-pro": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             6,
			ContextLength:               976000,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "DeepInfra hosted text-generation model.",
		},
		"google/gemini-3.5-flash": {
			Ratio:                       nativeRate(0.5),
			CompletionRatio:             6,
			ContextLength:               976000,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "DeepInfra hosted text-generation model.",
		},
		"google/gemini-3.7-flash": {
			Ratio:                       nativeRate(0.5),
			CompletionRatio:             6,
			ContextLength:               976000,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "DeepInfra hosted text-generation model.",
		},
		"google/gemma-3-12b-it": {
			Ratio:                       nativeRate(0.05),
			CompletionRatio:             2.9999999999999996,
			ContextLength:               131072,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "google/gemma-3-12b-it on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"google/gemma-3-27b-it": {
			Ratio:                       nativeRate(0.08),
			CompletionRatio:             2,
			ContextLength:               131072,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "google/gemma-3-27b-it on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"google/gemma-3-4b-it": {
			Ratio:                       nativeRate(0.05),
			CompletionRatio:             2,
			ContextLength:               131072,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "google/gemma-3-4b-it on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"google/gemma-4-26B-A4B-it": {
			Ratio:                       nativeRate(0.06999999999999999),
			CompletionRatio:             4.857142857142858,
			ContextLength:               262144,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "google/gemma-4-26B-A4B-it on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"google/gemma-4-31B-it": {
			Ratio:                       nativeRate(0.13),
			CompletionRatio:             2.923076923076923,
			ContextLength:               262144,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "Gemma 4 31B instruction model.",
		},
		"google/gemma-4-31B-it-Ultra": {
			Ratio:                       nativeRate(0.26999999999999996),
			CompletionRatio:             2.8148148148148153,
			ContextLength:               131072,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "google/gemma-4-31B-it-Ultra on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"google/gemma-4-31B-it-turbo": {
			Ratio:                       nativeRate(0.09),
			CompletionRatio:             3.777777777777778,
			CachedInputRatio:            nativeRate(0.050000000399999994),
			ContextLength:               262144,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "google/gemma-4-31B-it-turbo on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"google/gemma-4-E4B-it": {
			Ratio:                       nativeRate(0.02),
			CompletionRatio:             5,
			ContextLength:               131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice", "n"},
			Description:                 "google/gemma-4-E4B-it on deepinfra; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
