package ali

import (
	"github.com/Laisky/one-api/relay/adaptor"
	"github.com/Laisky/one-api/relay/billing/ratio"
)

// qwenOpenModelRatios captures pricing and metadata for Alibaba's open-weight
// Qwen lineups exposed via Model Studio: Qwen 2 / 2.5 instruct, Qwen 1.5 chat,
// Qwen 2 / 2.5 -Math / -Coder / -VL, plus the QwQ and QVQ reasoning previews.
//
// Open-weight models populate HuggingFaceID (matching the canonical card under
// https://huggingface.co/Qwen) and Quantization "bf16" reflecting the precision
// Alibaba serves on Model Studio (verified via the Hugging Face model cards on
// 2026-05-01). Context lengths follow the Hugging Face cards / Model Studio docs;
// where the upstream card and Model Studio differ, we prefer the served value.
var qwenOpenModelRatios = map[string]adaptor.ModelConfig{
	// ----- Qwen 2.5 Instruct (open) -------------------------------------------
	"qwen2.5-72b-instruct": {
		Ratio:                       0.004 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-72B-Instruct",
		Description:                 "Qwen2.5 72B Instruct: open-weight flagship instruct model with 128K context.",
	},
	"qwen2.5-32b-instruct": {
		Ratio:                       0.03 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-32B-Instruct",
		Description:                 "Qwen2.5 32B Instruct: open-weight mid-tier instruct model with 128K context.",
	},
	"qwen2.5-14b-instruct": {
		Ratio:                       0.001 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-14B-Instruct",
		Description:                 "Qwen2.5 14B Instruct: open-weight instruct model with 128K context.",
	},
	"qwen2.5-7b-instruct": {
		Ratio:                       0.0005 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-7B-Instruct",
		Description:                 "Qwen2.5 7B Instruct: open-weight cost-efficient instruct model with 128K context.",
	},
	"qwen2.5-3b-instruct": {
		Ratio:                       0.006 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-3B-Instruct",
		Description:                 "Qwen2.5 3B Instruct: open-weight small instruct model.",
	},
	"qwen2.5-1.5b-instruct": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-1.5B-Instruct",
		Description:                 "Qwen2.5 1.5B Instruct: open-weight compact instruct model.",
	},
	"qwen2.5-0.5b-instruct": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-0.5B-Instruct",
		Description:                 "Qwen2.5 0.5B Instruct: open-weight micro instruct model.",
	},

	// ----- Qwen 2 Instruct (open) ---------------------------------------------
	"qwen2-72b-instruct": {
		Ratio:                       0.004 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2-72B-Instruct",
		Description:                 "Qwen2 72B Instruct: previous-generation open-weight flagship.",
	},
	"qwen2-57b-a14b-instruct": {
		Ratio:                       0.0035 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               65536,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2-57B-A14B-Instruct",
		Description:                 "Qwen2 57B-A14B Instruct: open-weight MoE instruct model (14B active).",
	},
	"qwen2-7b-instruct": {
		Ratio:                       0.001 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2-7B-Instruct",
		Description:                 "Qwen2 7B Instruct: open-weight previous-generation instruct model.",
	},
	"qwen2-1.5b-instruct": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2-1.5B-Instruct",
		Description:                 "Qwen2 1.5B Instruct: open-weight compact instruct model.",
	},
	"qwen2-0.5b-instruct": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2-0.5B-Instruct",
		Description:                 "Qwen2 0.5B Instruct: open-weight micro instruct model.",
	},

	// ----- Qwen 1.5 Chat (open) ------------------------------------------------
	"qwen1.5-110b-chat": {
		Ratio:                       0.008 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen1.5-110B-Chat",
		Description:                 "Qwen1.5 110B Chat: open-weight legacy flagship chat model.",
	},
	"qwen1.5-72b-chat": {
		Ratio:                       0.004 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen1.5-72B-Chat",
		Description:                 "Qwen1.5 72B Chat: open-weight legacy chat model.",
	},
	"qwen1.5-32b-chat": {
		Ratio:                       0.002 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen1.5-32B-Chat",
		Description:                 "Qwen1.5 32B Chat: open-weight legacy chat model.",
	},
	"qwen1.5-14b-chat": {
		Ratio:                       0.001 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen1.5-14B-Chat",
		Description:                 "Qwen1.5 14B Chat: open-weight legacy chat model.",
	},
	"qwen1.5-7b-chat": {
		Ratio:                       0.0005 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen1.5-7B-Chat",
		Description:                 "Qwen1.5 7B Chat: open-weight legacy chat model.",
	},
	"qwen1.5-1.8b-chat": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen1.5-1.8B-Chat",
		Description:                 "Qwen1.5 1.8B Chat: open-weight legacy compact chat model.",
	},
	"qwen1.5-0.5b-chat": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen1.5-0.5B-Chat",
		Description:                 "Qwen1.5 0.5B Chat: open-weight legacy micro chat model.",
	},

	// ----- Qwen 2.5 / 2 Math (open) -------------------------------------------
	"qwen2.5-math-72b-instruct": {
		Ratio:                       0.004 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               4096,
		MaxOutputTokens:             3072,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-Math-72B-Instruct",
		Description:                 "Qwen2.5-Math 72B Instruct: open-weight math-specialized model.",
	},
	"qwen2.5-math-7b-instruct": {
		Ratio:                       0.001 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               4096,
		MaxOutputTokens:             3072,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-Math-7B-Instruct",
		Description:                 "Qwen2.5-Math 7B Instruct: open-weight math-specialized model.",
	},
	"qwen2.5-math-1.5b-instruct": {
		Ratio:                       0,
		CompletionRatio:             1,
		ContextLength:               4096,
		MaxOutputTokens:             3072,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-Math-1.5B-Instruct",
		Description:                 "Qwen2.5-Math 1.5B Instruct: open-weight compact math model (free trial).",
	},
	"qwen2-math-72b-instruct": {
		Ratio:                       0.004 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               4096,
		MaxOutputTokens:             3072,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2-Math-72B-Instruct",
		Description:                 "Qwen2-Math 72B Instruct: open-weight math-specialized model.",
	},
	"qwen2-math-7b-instruct": {
		Ratio:                       0.0005 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               4096,
		MaxOutputTokens:             3072,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2-Math-7B-Instruct",
		Description:                 "Qwen2-Math 7B Instruct: open-weight math-specialized model.",
	},
	"qwen2-math-1.5b-instruct": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               4096,
		MaxOutputTokens:             3072,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2-Math-1.5B-Instruct",
		Description:                 "Qwen2-Math 1.5B Instruct: open-weight compact math model.",
	},

	// ----- Qwen 2.5 Coder (open) ----------------------------------------------
	"qwen2.5-coder-32b-instruct": {
		Ratio:                       0.002 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-Coder-32B-Instruct",
		Description:                 "Qwen2.5-Coder 32B Instruct: open-weight coder flagship with 128K context.",
	},
	"qwen2.5-coder-14b-instruct": {
		Ratio:                       0.001 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-Coder-14B-Instruct",
		Description:                 "Qwen2.5-Coder 14B Instruct: open-weight coder model with 128K context.",
	},
	"qwen2.5-coder-7b-instruct": {
		Ratio:                       0.0005 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-Coder-7B-Instruct",
		Description:                 "Qwen2.5-Coder 7B Instruct: open-weight coder model with 128K context.",
	},
	"qwen2.5-coder-3b-instruct": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-Coder-3B-Instruct",
		Description:                 "Qwen2.5-Coder 3B Instruct: open-weight compact coder model.",
	},
	"qwen2.5-coder-1.5b-instruct": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-Coder-1.5B-Instruct",
		Description:                 "Qwen2.5-Coder 1.5B Instruct: open-weight compact coder model.",
	},
	"qwen2.5-coder-0.5b-instruct": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-Coder-0.5B-Instruct",
		Description:                 "Qwen2.5-Coder 0.5B Instruct: open-weight micro coder model.",
	},

	// ----- Qwen 2.5 VL (open vision) ------------------------------------------
	"qwen2.5-vl-72b-instruct": {
		Ratio:                       0.004 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-VL-72B-Instruct",
		Description:                 "Qwen2.5-VL 72B Instruct: open-weight flagship vision-language model.",
	},
	"qwen2.5-vl-7b-instruct": {
		Ratio:                       0.0005 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-VL-7B-Instruct",
		Description:                 "Qwen2.5-VL 7B Instruct: open-weight vision-language model with 128K context.",
	},
	"qwen2.5-vl-2b-instruct": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-VL-2B-Instruct",
		Description:                 "Qwen2.5-VL 2B Instruct: open-weight compact vision-language model.",
	},
	"qwen2.5-vl-1b-instruct": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		// Hugging Face card not published for the 1B variant; left blank rather
		// than guessing a slug. Operators relying on HF-id mapping should fall
		// back to the closest 2B/3B sibling.
		Description: "Qwen2.5-VL 1B Instruct: open-weight micro vision-language model (HF card not published).",
	},
	"qwen2.5-vl-0.5b-instruct": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		// HF slug not published for the 0.5B variant on the Qwen org page.
		Description: "Qwen2.5-VL 0.5B Instruct: open-weight micro vision-language model (HF card not published).",
	},

	// ----- Qwen 2 VL (open vision) --------------------------------------------
	"qwen2-vl-7b-instruct": {
		Ratio:                       0.0005 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2-VL-7B-Instruct",
		Description:                 "Qwen2-VL 7B Instruct: open-weight previous-generation vision-language model.",
	},
	"qwen2-vl-2b-instruct": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2-VL-2B-Instruct",
		Description:                 "Qwen2-VL 2B Instruct: open-weight compact previous-generation vision-language model.",
	},

	// ----- Qwen Audio (open) ---------------------------------------------------
	"qwen2-audio-instruct": {
		Ratio:                       0,
		CompletionRatio:             1,
		ContextLength:               8192,
		MaxOutputTokens:             2048,
		InputModalities:             []string{"text", "file"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2-Audio-7B-Instruct",
		Description:                 "Qwen2-Audio Instruct: open-weight audio-understanding model (currently free trial).",
	},

	// ----- QwQ / QVQ reasoning previews (open) --------------------------------
	"qwq-32b-preview": {
		Ratio:                       0.002 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenReasoningFeatures(),
		SupportedSamplingParameters: qwenReasoningSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/QwQ-32B-Preview",
		Description:                 "QwQ 32B Preview: open-weight reasoning-focused preview model with chain-of-thought.",
	},
	"qvq-72b-preview": {
		Ratio:                       0.012 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenReasoningFeatures(),
		SupportedSamplingParameters: qwenReasoningSamplingParameters(),
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/QVQ-72B-Preview",
		Description:                 "QVQ 72B Preview: open-weight multimodal reasoning preview model.",
	},
}
