package ali

import (
	"github.com/Laisky/one-api/relay/adaptor"
	"github.com/Laisky/one-api/relay/billing/ratio"
)

// qwenClosedModelRatios captures pricing and metadata for Alibaba's closed-weight
// Qwen tiers exposed via Model Studio (turbo / plus / max / long / flash) plus the
// closed-weight Qwen-VL, Qwen-Audio, Qwen-Math, Qwen-Coder, and Qwen-MT variants.
// HuggingFaceID is intentionally empty for these models because their weights are
// not published. Quantization is likewise unspecified (Alibaba does not document
// the served numeric format for managed models).
//
// Context-length and max-output figures are taken from
// https://help.aliyun.com/zh/model-studio/getting-started/models (verified 2026-05-01)
// and the corresponding English Model Studio documentation. Where Alibaba publishes
// multiple tiers (e.g. qwen-plus 128K vs 1M), we record the most commonly used tier
// and document the alternative in the description so operators can disambiguate.
var qwenClosedModelRatios = map[string]adaptor.ModelConfig{
	// ----- Qwen Turbo (closed) -------------------------------------------------
	"qwen-turbo": {
		Ratio:                       0.0006 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               1000000,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen Turbo: closed-weight cost-optimized chat tier with up to 1M-token context.",
	},
	"qwen-turbo-latest": {
		Ratio:                       0.0006 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               1000000,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen Turbo (latest snapshot alias).",
	},

	// ----- Qwen Plus (closed) --------------------------------------------------
	"qwen-plus": {
		Ratio:                       0.002 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen Plus: closed-weight balanced tier with 128K context (1M tier also available).",
	},
	"qwen-plus-latest": {
		Ratio:                       0.002 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen Plus (latest snapshot alias).",
	},

	// ----- Qwen Max (closed) ---------------------------------------------------
	"qwen-max": {
		Ratio:                       0.006 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen Max: closed-weight flagship; tiered pricing 32K/128K/252K, lowest tier billed here.",
	},
	"qwen-max-latest": {
		Ratio:                       0.006 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen Max (latest snapshot alias).",
	},
	"qwen-max-longcontext": {
		Ratio:                       0.006 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               30720,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen Max long-context legacy variant; superseded by qwen-max tiered pricing.",
	},

	// ----- Qwen-VL (closed vision) --------------------------------------------
	"qwen-vl-max": {
		Ratio:                       0.001 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32000,
		MaxOutputTokens:             2000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen-VL Max: closed-weight high-end multimodal model accepting text+image input.",
	},
	"qwen-vl-max-latest": {
		Ratio:                       0.001 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32000,
		MaxOutputTokens:             2000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen-VL Max (latest snapshot alias).",
	},
	"qwen-vl-plus": {
		Ratio:                       0.001 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32000,
		MaxOutputTokens:             2000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen-VL Plus: closed-weight balanced multimodal tier.",
	},
	"qwen-vl-plus-latest": {
		Ratio:                       0.001 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32000,
		MaxOutputTokens:             2000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen-VL Plus (latest snapshot alias).",
	},
	"qwen-vl-ocr": {
		Ratio:                       0.005 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               34096,
		MaxOutputTokens:             4096,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen-VL OCR: closed-weight model tuned for document/scene OCR extraction.",
	},
	"qwen-vl-ocr-latest": {
		Ratio:                       0.005 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               34096,
		MaxOutputTokens:             4096,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen-VL OCR (latest snapshot alias).",
	},

	// ----- Qwen-Audio (closed) -------------------------------------------------
	"qwen-audio-turbo": {
		Ratio:                       0,
		CompletionRatio:             1,
		ContextLength:               8192,
		MaxOutputTokens:             2000,
		InputModalities:             []string{"text", "file"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen-Audio Turbo: closed-weight audio-understanding model (currently free trial).",
	},

	// ----- Qwen Math (closed) --------------------------------------------------
	"qwen-math-plus": {
		Ratio:                       0.004 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               4096,
		MaxOutputTokens:             3072,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen-Math Plus: closed-weight model tuned for mathematical reasoning.",
	},
	"qwen-math-plus-latest": {
		Ratio:                       0.004 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               4096,
		MaxOutputTokens:             3072,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen-Math Plus (latest snapshot alias).",
	},
	"qwen-math-turbo": {
		Ratio:                       0.002 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               4096,
		MaxOutputTokens:             3072,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen-Math Turbo: cost-optimized closed-weight math model.",
	},
	"qwen-math-turbo-latest": {
		Ratio:                       0.002 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               4096,
		MaxOutputTokens:             3072,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen-Math Turbo (latest snapshot alias).",
	},

	// ----- Qwen Coder (closed) -------------------------------------------------
	"qwen-coder-plus": {
		Ratio:                       0.004 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen-Coder Plus: closed-weight model tuned for code generation and completion.",
	},
	"qwen-coder-plus-latest": {
		Ratio:                       0.004 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen-Coder Plus (latest snapshot alias).",
	},
	"qwen-coder-turbo": {
		Ratio:                       0.002 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen-Coder Turbo: cost-optimized closed-weight coder model.",
	},
	"qwen-coder-turbo-latest": {
		Ratio:                       0.002 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               131072,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           qwenChatFeatures(),
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen-Coder Turbo (latest snapshot alias).",
	},

	// ----- Qwen MT (machine translation, closed) -------------------------------
	"qwen-mt-plus": {
		Ratio:                       0.0018 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               4096,
		MaxOutputTokens:             2048,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen-MT Plus: closed-weight machine-translation tier.",
	},
	"qwen-mt-turbo": {
		Ratio:                       0.0007 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               4096,
		MaxOutputTokens:             2048,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen-MT Turbo: cost-optimized closed-weight translation model.",
	},

	// ----- Legacy closed-weight Qwen 1.x chat ---------------------------------
	"qwen-72b-chat": {
		Ratio:                       0.004 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             8192,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen 72B Chat (Qwen 1 generation, hosted only).",
	},
	"qwen-14b-chat": {
		Ratio:                       0.001 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               8192,
		MaxOutputTokens:             2048,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen 14B Chat (Qwen 1 generation, hosted only).",
	},
	"qwen-7b-chat": {
		Ratio:                       0.0005 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               8192,
		MaxOutputTokens:             2048,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen 7B Chat (Qwen 1 generation, hosted only).",
	},
	"qwen-1.8b-chat": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               8192,
		MaxOutputTokens:             2048,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen 1.8B Chat (Qwen 1 generation, hosted only).",
	},
	"qwen-1.8b-longcontext-chat": {
		Ratio:                       0.0003 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             2048,
		InputModalities:             []string{"text"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{"tools"},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen 1.8B Long-Context Chat (Qwen 1 generation, hosted only).",
	},

	// ----- Legacy closed Qwen-VL / Qwen-Audio v1 ------------------------------
	"qwen-vl-v1": {
		Ratio:                       0.001 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               2048,
		MaxOutputTokens:             1500,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen-VL v1: legacy closed-weight multimodal base model.",
	},
	"qwen-vl-chat-v1": {
		Ratio:                       0.001 * 1000 * ratio.MilliTokensRmb,
		CompletionRatio:             1,
		ContextLength:               2048,
		MaxOutputTokens:             1500,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen-VL Chat v1: legacy closed-weight multimodal chat model.",
	},
	"qwen-audio-chat": {
		Ratio:                       0,
		CompletionRatio:             1,
		ContextLength:               8192,
		MaxOutputTokens:             2000,
		InputModalities:             []string{"text", "file"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           []string{},
		SupportedSamplingParameters: qwenStandardSamplingParameters(),
		Description:                 "Qwen-Audio Chat: legacy closed-weight audio chat model (free trial).",
	},
}
