package ali

import "github.com/Laisky/one-api/relay/adaptor"

// deepseekModels returns the deepseek model defaults for ali.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func deepseekModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"deepseek-r1": {
			Ratio:                       nativeRate(4),
			CompletionRatio:             4,
			ContextLength:               16384,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			MaxReasoningTokens:          16384,
			Quantization:                "bf16",
			HuggingFaceID:               "deepseek-ai/DeepSeek-R1",
			Description:                 "deepseek-r1 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek-r1-0528": {
			Ratio:                       nativeRate(4),
			CompletionRatio:             4,
			ContextLength:               16384,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			MaxReasoningTokens:          16384,
			Quantization:                "bf16",
			HuggingFaceID:               "deepseek-ai/DeepSeek-R1-0528",
			Description:                 "deepseek-r1-0528 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek-r1-distill-llama-70b": {
			Ratio:                       0,
			CompletionRatio:             2,
			ContextLength:               32768,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			MaxReasoningTokens:          16384,
			Quantization:                "bf16",
			HuggingFaceID:               "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
			Description:                 "DeepSeek-R1 distilled into Llama 70B (reasoning-focused). Free-trial-only (目前仅供免费体验) on Alibaba Model Studio: not callable once the free quota is exhausted (no paid tier currently).",
		},
		"deepseek-r1-distill-llama-8b": {
			Ratio:                       nativeRate(0.14),
			CompletionRatio:             0.28,
			ContextLength:               32768,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			MaxReasoningTokens:          16384,
			Quantization:                "bf16",
			HuggingFaceID:               "deepseek-ai/DeepSeek-R1-Distill-Llama-8B",
			Description:                 "DeepSeek-R1 distilled into Llama 8B (reasoning-focused). Retired (已下线) on Alibaba Model Studio; Aliyun recommends 深度思考/DeepSeek-Ali/Kimi-Ali as replacements.",
		},
		"deepseek-r1-distill-qwen-1.5b": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			MaxReasoningTokens:          16384,
			Quantization:                "bf16",
			HuggingFaceID:               "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B",
			Description:                 "deepseek-r1-distill-qwen-1.5b on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek-r1-distill-qwen-14b": {
			Ratio:                       nativeRate(1),
			CompletionRatio:             3,
			ContextLength:               32768,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			MaxReasoningTokens:          16384,
			Quantization:                "bf16",
			HuggingFaceID:               "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B",
			Description:                 "deepseek-r1-distill-qwen-14b on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek-r1-distill-qwen-32b": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             3,
			ContextLength:               32768,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			MaxReasoningTokens:          16384,
			Quantization:                "bf16",
			HuggingFaceID:               "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
			Description:                 "deepseek-r1-distill-qwen-32b on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek-r1-distill-qwen-7b": {
			Ratio:                       nativeRate(0.5),
			CompletionRatio:             2,
			ContextLength:               32768,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			MaxReasoningTokens:          16384,
			Quantization:                "bf16",
			HuggingFaceID:               "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
			Description:                 "deepseek-r1-distill-qwen-7b on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek-v3": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             4,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V3",
			Description:                 "deepseek-v3 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek-v3.1": {
			Ratio:                       nativeRate(4),
			CompletionRatio:             3,
			ContextLength:               131072,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			MaxReasoningTokens:          65536,
			Quantization:                "bf16",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V3.1",
			Description:                 "deepseek-v3.1 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek-v3.2": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             1.5,
			CachedInputRatio:            nativeRate(0.4),
			ContextLength:               131072,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			MaxReasoningTokens:          65536,
			Quantization:                "bf16",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V3.2",
			Description:                 "deepseek-v3.2 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek-v3.2-exp": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             1.5,
			ContextLength:               131072,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			MaxReasoningTokens:          65536,
			Quantization:                "bf16",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V3.2-Exp",
			Description:                 "deepseek-v3.2-exp on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek-v4-flash": {
			Ratio:                       nativeRate(1),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.2),
			ContextLength:               1000000,
			MaxOutputTokens:             393216,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			MaxReasoningTokens:          393216,
			Quantization:                "fp8",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V4-Flash",
			Description:                 "deepseek-v4-flash on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek-v4-flash-0731": {
			Ratio:           nativeRate(1.5),
			CompletionRatio: 3,
			TimeWindows: []adaptor.TimeWindow{adaptor.TimeWindow{
				Name:     "beijing-peak",
				TimeZone: "Asia/Shanghai",
				Ranges: []adaptor.ClockRange{adaptor.ClockRange{
					Start: "08:00",
					End:   "22:00",
				},
				},
				Overlay: adaptor.ModelConfig{
					Ratio:           nativeRate(3),
					CompletionRatio: 3,
				},
			},
			},
			Description: "deepseek-v4-flash-0731 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek-v4-pro": {
			Ratio:                       nativeRate(12),
			CompletionRatio:             2,
			CachedInputRatio:            0.17142857142857143,
			ContextLength:               1000000,
			MaxOutputTokens:             393216,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			MaxReasoningTokens:          393216,
			Quantization:                "fp8",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V4-Pro",
			Description:                 "deepseek-v4-pro on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek-v4-pro-0813": {
			Ratio:           nativeRate(4.5),
			CompletionRatio: 3,
			TimeWindows: []adaptor.TimeWindow{adaptor.TimeWindow{
				Name:     "beijing-peak",
				TimeZone: "Asia/Shanghai",
				Ranges: []adaptor.ClockRange{adaptor.ClockRange{
					Start: "08:00",
					End:   "22:00",
				},
				},
				Overlay: adaptor.ModelConfig{
					Ratio:           nativeRate(9),
					CompletionRatio: 3,
				},
			},
			},
			Description: "deepseek-v4-pro-0813 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek-v4.1-flash": {
			Ratio:           nativeRate(1),
			CompletionRatio: 4,
			TimeWindows: []adaptor.TimeWindow{adaptor.TimeWindow{
				Name:     "beijing-peak",
				TimeZone: "Asia/Shanghai",
				Ranges: []adaptor.ClockRange{adaptor.ClockRange{
					Start: "08:00",
					End:   "22:00",
				},
				},
				Overlay: adaptor.ModelConfig{
					Ratio:           nativeRate(2),
					CompletionRatio: 4,
				},
			},
			},
			Description: "deepseek-v4.1-flash on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
