package ali

import "github.com/Laisky/one-api/relay/adaptor"

// qwen_4Models returns the qwen model defaults for ali.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func qwen_4Models() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"qwen3.6-flash": {
			Ratio:            nativeRate(1.2),
			CompletionRatio:  6,
			CachedInputRatio: nativeRate(0.24000000000000002),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(4.8),
				CompletionRatio:     6,
				InputTokenThreshold: 256001,
			},
			},
			ContextLength:               1000000,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "qwen3.6-flash on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.6-flash-2026-04-16": {
			Ratio:           nativeRate(1.2),
			CompletionRatio: 6,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(4.8),
				CompletionRatio:     6,
				InputTokenThreshold: 256001,
			},
			},
			Description: "qwen3.6-flash-2026-04-16 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.6-max-preview": {
			Ratio:            nativeRate(9),
			CompletionRatio:  6,
			CachedInputRatio: nativeRate(1.8),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(15),
				CompletionRatio:     6,
				InputTokenThreshold: 128001,
			},
			},
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			MaxReasoningTokens:          65536,
			Description:                 "qwen3.6-max-preview on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.6-plus": {
			Ratio:            nativeRate(2),
			CompletionRatio:  6,
			CachedInputRatio: nativeRate(0.4),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(8),
				CompletionRatio:     6,
				InputTokenThreshold: 256001,
			},
			},
			ContextLength:               1000000,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "qwen3.6-plus on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.6-plus-2026-04-02": {
			Ratio:           nativeRate(2),
			CompletionRatio: 6,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(8),
				CompletionRatio:     6,
				InputTokenThreshold: 256001,
			},
			},
			Description: "qwen3.6-plus-2026-04-02 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.7-flash": {
			Ratio:           nativeRate(0.2),
			CompletionRatio: 4,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.6),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(1.2),
					CompletionRatio:     4,
					InputTokenThreshold: 256001,
				},
			},
			Description: "qwen3.7-flash on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.7-flash-2026-07-15": {
			Ratio:           nativeRate(0.2),
			CompletionRatio: 4,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.6),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(1.2),
					CompletionRatio:     4,
					InputTokenThreshold: 256001,
				},
			},
			Description: "qwen3.7-flash-2026-07-15 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.7-max": {
			Ratio:                       nativeRate(12),
			CompletionRatio:             3,
			CachedInputRatio:            0.08571428571428572,
			ContextLength:               1000000,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			Description:                 "qwen3.7-max on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.7-max-2026-05-17": {
			Ratio:           nativeRate(12),
			CompletionRatio: 3,
			Description:     "qwen3.7-max-2026-05-17 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.7-max-2026-05-20": {
			Ratio:           nativeRate(12),
			CompletionRatio: 3,
			Description:     "qwen3.7-max-2026-05-20 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.7-max-2026-06-08": {
			Ratio:           nativeRate(12),
			CompletionRatio: 3,
			Description:     "qwen3.7-max-2026-06-08 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.7-max-latest": {
			Ratio:                       nativeRate(12),
			CompletionRatio:             3,
			CachedInputRatio:            0.08571428571428572,
			ContextLength:               1000000,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			Description:                 "Qwen3.7 Max (latest alias).",
		},
		"qwen3.7-max-preview": {
			Ratio:           nativeRate(12),
			CompletionRatio: 3,
			Description:     "qwen3.7-max-preview on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.7-plus": {
			Ratio:            nativeRate(1.6),
			CompletionRatio:  4,
			CachedInputRatio: nativeRate(0.4),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(4.8),
				CompletionRatio:     4,
				InputTokenThreshold: 256001,
			},
			},
			ContextLength:               1000000,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "qwen3.7-plus on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.7-plus-2026-05-26": {
			Ratio:           nativeRate(2),
			CompletionRatio: 4,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(6),
				CompletionRatio:     4,
				InputTokenThreshold: 256001,
			},
			},
			Description: "qwen3.7-plus-2026-05-26 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.7-plus-latest": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.4),
			ContextLength:               1000000,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen3.7 Plus (latest alias).",
		},
		"qwen3.8-2.4t-a95b": {
			Ratio:           nativeRate(12),
			CompletionRatio: 3,
			Description:     "qwen3.8-2.4t-a95b on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.8-27b": {
			Ratio:           nativeRate(3),
			CompletionRatio: 4,
			Description:     "qwen3.8-27b on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.8-flash": {
			Ratio:           nativeRate(0.8),
			CompletionRatio: 3.375,
			Description:     "qwen3.8-flash on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.8-max": {
			Ratio:           nativeRate(12),
			CompletionRatio: 3,
			Description:     "qwen3.8-max on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.8-max-0902": {
			Ratio:           nativeRate(12),
			CompletionRatio: 3,
			Description:     "qwen3.8-max-0902 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.8-max-prime": {
			Ratio:           nativeRate(24),
			CompletionRatio: 3,
			Description:     "qwen3.8-max-prime on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
