package ali

import "github.com/Laisky/one-api/relay/adaptor"

// qwen_3Models returns the qwen model defaults for ali.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func qwen_3Models() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"qwen3-coder-flash": {
			Ratio:            nativeRate(1),
			CompletionRatio:  4,
			CachedInputRatio: nativeRate(0.2),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1.5),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(2.5),
					CompletionRatio:     4,
					InputTokenThreshold: 128001,
				},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(5),
					CompletionRatio:     5,
					InputTokenThreshold: 256001,
				},
			},
			ContextLength:               1000000,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "qwen3-coder-flash on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-coder-flash-2025-07-28": {
			Ratio:           nativeRate(1),
			CompletionRatio: 4,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1.5),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(2.5),
					CompletionRatio:     4,
					InputTokenThreshold: 128001,
				},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(5),
					CompletionRatio:     5,
					InputTokenThreshold: 256001,
				},
			},
			Description: "qwen3-coder-flash-2025-07-28 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-coder-next": {
			Ratio:           nativeRate(1),
			CompletionRatio: 4,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1.5),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(2.5),
					CompletionRatio:     4,
					InputTokenThreshold: 128001,
				},
			},
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-Coder-Next",
			Description:                 "qwen3-coder-next on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-coder-plus": {
			Ratio:            nativeRate(4),
			CompletionRatio:  4,
			CachedInputRatio: nativeRate(0.8),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(6),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(1e+01),
					CompletionRatio:     4,
					InputTokenThreshold: 128001,
				},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(2e+01),
					CompletionRatio:     10,
					InputTokenThreshold: 256001,
				},
			},
			ContextLength:               1000000,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "qwen3-coder-plus on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-coder-plus-2025-07-22": {
			Ratio:           nativeRate(4),
			CompletionRatio: 4,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(6),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(1e+01),
					CompletionRatio:     4,
					InputTokenThreshold: 128001,
				},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(2e+01),
					CompletionRatio:     10,
					InputTokenThreshold: 256001,
				},
			},
			Description: "qwen3-coder-plus-2025-07-22 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-coder-plus-2025-09-23": {
			Ratio:           nativeRate(4),
			CompletionRatio: 4,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(6),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(1e+01),
					CompletionRatio:     4,
					InputTokenThreshold: 128001,
				},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(2e+01),
					CompletionRatio:     10,
					InputTokenThreshold: 256001,
				},
			},
			Description: "qwen3-coder-plus-2025-09-23 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-max": {
			Ratio:            nativeRate(2.5),
			CompletionRatio:  4,
			CachedInputRatio: nativeRate(0.5),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(4),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(7),
					CompletionRatio:     4,
					InputTokenThreshold: 128001,
				},
			},
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "qwen3-max on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-max-2025-09-23": {
			Ratio:           nativeRate(6),
			CompletionRatio: 4,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1e+01),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(15),
					CompletionRatio:     4,
					InputTokenThreshold: 128001,
				},
			},
			Description: "qwen3-max-2025-09-23 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-max-2026-01-23": {
			Ratio:           nativeRate(2.5),
			CompletionRatio: 4,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(4),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(7),
					CompletionRatio:     4,
					InputTokenThreshold: 128001,
				},
			},
			Description: "qwen3-max-2026-01-23 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-max-preview": {
			Ratio:            nativeRate(6),
			CompletionRatio:  4,
			CachedInputRatio: nativeRate(0.5),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1e+01),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(15),
					CompletionRatio:     4,
					InputTokenThreshold: 128001,
				},
			},
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "qwen3-max-preview on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-next-80b-a3b-instruct": {
			Ratio:                       nativeRate(0.78),
			CompletionRatio:             3.96,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-Next-80B-A3B-Instruct",
			Description:                 "Qwen3 Next 80B A3B Instruct: open-weight MoE (3B active) with extended 256K context.",
		},
		"qwen3-next-80b-a3b-thinking": {
			Ratio:                       nativeRate(0.78),
			CompletionRatio:             3.96,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			MaxReasoningTokens:          38912,
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-Next-80B-A3B-Thinking",
			Description:                 "Qwen3 Next 80B A3B Thinking: open-weight MoE reasoning model with 256K context.",
		},
		"qwen3-omni-flash": {
			Ratio:                       nativeRate(1.8),
			CompletionRatio:             3.8333,
			ContextLength:               262144,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen3-Omni Flash: closed-weight multimodal (text/image/audio/video) tier (text I/O rate billed here; audio billing is per-modality upstream).",
		},
		"qwen3-vl-235b-a22b-instruct": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             4,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-VL-235B-A22B-Instruct",
			Description:                 "qwen3-vl-235b-a22b-instruct on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-vl-235b-a22b-thinking": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             10,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			MaxReasoningTokens:          38912,
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-VL-235B-A22B-Thinking",
			Description:                 "qwen3-vl-235b-a22b-thinking on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-vl-30b-a3b-instruct": {
			Ratio:                       nativeRate(0.75),
			CompletionRatio:             4,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-VL-30B-A3B-Instruct",
			Description:                 "qwen3-vl-30b-a3b-instruct on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-vl-30b-a3b-thinking": {
			Ratio:                       nativeRate(0.75),
			CompletionRatio:             10,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			MaxReasoningTokens:          38912,
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-VL-30B-A3B-Thinking",
			Description:                 "qwen3-vl-30b-a3b-thinking on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-vl-32b-instruct": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             4,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-VL-32B-Instruct",
			Description:                 "qwen3-vl-32b-instruct on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-vl-32b-thinking": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             10,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			MaxReasoningTokens:          38912,
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-VL-32B-Thinking",
			Description:                 "qwen3-vl-32b-thinking on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-vl-8b-instruct": {
			Ratio:                       nativeRate(0.5),
			CompletionRatio:             4,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-VL-8B-Instruct",
			Description:                 "qwen3-vl-8b-instruct on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-vl-8b-thinking": {
			Ratio:                       nativeRate(0.5),
			CompletionRatio:             10,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			MaxReasoningTokens:          38912,
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-VL-8B-Thinking",
			Description:                 "qwen3-vl-8b-thinking on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-vl-flash": {
			Ratio:            nativeRate(0.15),
			CompletionRatio:  10,
			CachedInputRatio: nativeRate(0.030000000000000002),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.3),
				CompletionRatio:     10,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(0.6),
					CompletionRatio:     10,
					InputTokenThreshold: 128001,
				},
			},
			ContextLength:               262144,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "qwen3-vl-flash on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-vl-flash-2025-10-15": {
			Ratio:           nativeRate(0.15),
			CompletionRatio: 10,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.3),
				CompletionRatio:     10,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(0.6),
					CompletionRatio:     10,
					InputTokenThreshold: 128001,
				},
			},
			Description: "qwen3-vl-flash-2025-10-15 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-vl-flash-2026-01-22": {
			Ratio:           nativeRate(0.15),
			CompletionRatio: 10,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.3),
				CompletionRatio:     10,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(0.6),
					CompletionRatio:     10,
					InputTokenThreshold: 128001,
				},
			},
			Description: "qwen3-vl-flash-2026-01-22 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-vl-plus": {
			Ratio:            nativeRate(1),
			CompletionRatio:  10,
			CachedInputRatio: nativeRate(0.2),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1.5),
				CompletionRatio:     10,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(3),
					CompletionRatio:     10,
					InputTokenThreshold: 128001,
				},
			},
			ContextLength:               262144,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "qwen3-vl-plus on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-vl-plus-2025-09-23": {
			Ratio:           nativeRate(1),
			CompletionRatio: 10,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1.5),
				CompletionRatio:     10,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(3),
					CompletionRatio:     10,
					InputTokenThreshold: 128001,
				},
			},
			Description: "qwen3-vl-plus-2025-09-23 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-vl-plus-2025-12-19": {
			Ratio:           nativeRate(1),
			CompletionRatio: 10,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1.5),
				CompletionRatio:     10,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(3),
					CompletionRatio:     10,
					InputTokenThreshold: 128001,
				},
			},
			Description: "qwen3-vl-plus-2025-12-19 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.5-122b-a10b": {
			Ratio:           nativeRate(0.8),
			CompletionRatio: 8,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(2),
				CompletionRatio:     8,
				InputTokenThreshold: 128001,
			},
			},
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3.5-122B-A10B",
			Description:                 "qwen3.5-122b-a10b on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.5-27b": {
			Ratio:           nativeRate(0.6),
			CompletionRatio: 8,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1.8),
				CompletionRatio:     8,
				InputTokenThreshold: 128001,
			},
			},
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3.5-27B",
			Description:                 "qwen3.5-27b on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.5-35b-a3b": {
			Ratio:           nativeRate(0.4),
			CompletionRatio: 8,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1.6),
				CompletionRatio:     8,
				InputTokenThreshold: 128001,
			},
			},
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3.5-35B-A3B",
			Description:                 "qwen3.5-35b-a3b on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.5-397b-a17b": {
			Ratio:           nativeRate(1.2),
			CompletionRatio: 6,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(3),
				CompletionRatio:     6,
				InputTokenThreshold: 128001,
			},
			},
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3.5-397B-A17B",
			Description:                 "qwen3.5-397b-a17b on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.5-flash": {
			Ratio:            nativeRate(0.2),
			CompletionRatio:  10,
			CachedInputRatio: nativeRate(0.04),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.8),
				CompletionRatio:     10,
				InputTokenThreshold: 128001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(1.2),
					CompletionRatio:     10,
					InputTokenThreshold: 256001,
				},
			},
			ContextLength:               1000000,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "qwen3.5-flash on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.5-flash-2026-02-23": {
			Ratio:           nativeRate(0.2),
			CompletionRatio: 10,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.8),
				CompletionRatio:     10,
				InputTokenThreshold: 128001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(1.2),
					CompletionRatio:     10,
					InputTokenThreshold: 256001,
				},
			},
			Description: "qwen3.5-flash-2026-02-23 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.5-omni-plus": {
			Ratio:                       nativeRate(7),
			CompletionRatio:             5.714285714285714,
			ContextLength:               262144,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image", "audio", "video"},
			OutputModalities:            []string{"text", "audio"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen3.5 Omni Plus: closed-weight multimodal model accepting text/image/audio/video inputs with text and audio outputs; 262K context.",
		},
		"qwen3.5-omni-plus-realtime": {
			Ratio:                       0.7142857142857143,
			CompletionRatio:             6,
			ContextLength:               262144,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image", "audio", "video"},
			OutputModalities:            []string{"text", "audio"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen3.5 Omni Plus Realtime: closed-weight realtime multimodal model accepting text/image/audio/video inputs with text and audio outputs; 262K context (text I/O rate billed here; audio billing is per-modality upstream).",
		},
		"qwen3.5-plus": {
			Ratio:            nativeRate(0.8),
			CompletionRatio:  5.999999999999999,
			CachedInputRatio: nativeRate(0.16),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(2),
				CompletionRatio:     6,
				InputTokenThreshold: 128001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(4),
					CompletionRatio:     6,
					InputTokenThreshold: 256001,
				},
			},
			ContextLength:               1000000,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "qwen3.5-plus on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.5-plus-2026-02-15": {
			Ratio:           nativeRate(0.8),
			CompletionRatio: 5.999999999999999,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(2),
				CompletionRatio:     6,
				InputTokenThreshold: 128001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(4),
					CompletionRatio:     6,
					InputTokenThreshold: 256001,
				},
			},
			Description: "qwen3.5-plus-2026-02-15 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.5-plus-2026-04-20": {
			Ratio:           nativeRate(0.8),
			CompletionRatio: 5.999999999999999,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(2),
				CompletionRatio:     6,
				InputTokenThreshold: 128001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(4),
					CompletionRatio:     6,
					InputTokenThreshold: 256001,
				},
			},
			Description: "qwen3.5-plus-2026-04-20 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.6-27b": {
			Ratio:                       nativeRate(3),
			CompletionRatio:             6,
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3.6-27B",
			Description:                 "qwen3.6-27b on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3.6-35b-a3b": {
			Ratio:                       nativeRate(1.8),
			CompletionRatio:             6,
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3.6-35B-A3B",
			Description:                 "qwen3.6-35b-a3b on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
