package ali

import "github.com/Laisky/one-api/relay/adaptor"

// otherModels returns the other model defaults for ali.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func otherModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"MiniMax-M2.1": {
			Ratio:           nativeRate(2.1),
			CompletionRatio: 4,
			Description:     "MiniMax-M2.1 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"MiniMax-M2.5": {
			Ratio:           nativeRate(2.1),
			CompletionRatio: 4,
			Description:     "MiniMax-M2.5 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"MiniMax/MiniMax-M2.1": {
			Ratio:           nativeRate(2.1),
			CompletionRatio: 4,
			Description:     "MiniMax/MiniMax-M2.1 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"MiniMax/MiniMax-M2.5": {
			Ratio:           nativeRate(2.1),
			CompletionRatio: 4,
			Description:     "MiniMax/MiniMax-M2.5 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"MiniMax/MiniMax-M2.7": {
			Ratio:           nativeRate(2.1),
			CompletionRatio: 4,
			Description:     "MiniMax/MiniMax-M2.7 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"MiniMax/MiniMax-M3": {
			Ratio:           nativeRate(4.2),
			CompletionRatio: 4,
			Description:     "MiniMax/MiniMax-M3 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Moonshot-Kimi-K2-Instruct": {
			Ratio:           nativeRate(4),
			CompletionRatio: 4,
			Description:     "Moonshot-Kimi-K2-Instruct on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"ali-stable-diffusion-v1.5": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.02,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				PromptTokenLimit: 4000,
				MinImages:        1,
				MaxImages:        4,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1024x576":  1,
					"1024x768":  1,
					"512x1024":  1,
					"576x1024":  1,
				},
			},
			InputModalities:  []string{"text"},
			OutputModalities: []string{"image"},
			Description:      "Alibaba-hosted Stable Diffusion v1.5 text-to-image endpoint.",
		},
		"ali-stable-diffusion-xl": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.02,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				PromptTokenLimit: 4000,
				MinImages:        1,
				MaxImages:        4,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1024x576":  1,
					"1024x768":  1,
					"512x1024":  1,
					"576x1024":  1,
				},
			},
			InputModalities:  []string{"text"},
			OutputModalities: []string{"image"},
			Description:      "Alibaba-hosted Stable Diffusion XL text-to-image endpoint.",
		},
		"kimi-k2-thinking": {
			Ratio:           nativeRate(4),
			CompletionRatio: 4,
			Description:     "kimi-k2-thinking on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"kimi-k2.5": {
			Ratio:           nativeRate(4),
			CompletionRatio: 5.25,
			Description:     "kimi-k2.5 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"kimi-k2.6": {
			Ratio:           nativeRate(6.5),
			CompletionRatio: 4.153846153846154,
			Description:     "kimi-k2.6 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"kimi-k2.7-code": {
			Ratio:           nativeRate(6.5),
			CompletionRatio: 4.153846153846154,
			Description:     "kimi-k2.7-code on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"kimi-k3": {
			Ratio:           nativeRate(2e+01),
			CompletionRatio: 5,
			Description:     "kimi-k3 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"kimi/kimi-k2.5": {
			Ratio:           nativeRate(4),
			CompletionRatio: 5.25,
			Description:     "kimi/kimi-k2.5 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"kimi/kimi-k2.6": {
			Ratio:           nativeRate(6.5),
			CompletionRatio: 4.153846153846154,
			Description:     "kimi/kimi-k2.6 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"kimi/kimi-k2.7-code": {
			Ratio:           nativeRate(6.5),
			CompletionRatio: 4.153846153846154,
			Description:     "kimi/kimi-k2.7-code on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"kimi/kimi-k2.7-code-highspeed": {
			Ratio:           nativeRate(13),
			CompletionRatio: 4.153846153846154,
			Description:     "kimi/kimi-k2.7-code-highspeed on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"kimi/kimi-k3": {
			Ratio:           nativeRate(2e+01),
			CompletionRatio: 5,
			Description:     "kimi/kimi-k3 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qvq-72b-preview": {
			Ratio:                       nativeRate(12.370000000000001),
			CompletionRatio:             3,
			ContextLength:               32768,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			MaxReasoningTokens:          38912,
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/QVQ-72B-Preview",
			Description:                 "QVQ 72B Preview: open-weight multimodal reasoning preview model.",
		},
		"qvq-max": {
			Ratio:                       nativeRate(8),
			CompletionRatio:             4,
			ContextLength:               131072,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			MaxReasoningTokens:          38912,
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/QVQ-72B-Preview",
			Description:                 "qvq-max on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qvq-plus": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             2.5,
			ContextLength:               131072,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			MaxReasoningTokens:          38912,
			Description:                 "qvq-plus on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwq-32b": {
			Ratio:                       nativeRate(2.06),
			CompletionRatio:             2.995,
			ContextLength:               131072,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			MaxReasoningTokens:          38912,
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/QwQ-32B",
			Description:                 "QwQ 32B: open-weight reasoning model with 128K context.",
		},
		"qwq-32b-preview": {
			Ratio:                       nativeRate(2.06),
			CompletionRatio:             2.995,
			ContextLength:               32768,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			MaxReasoningTokens:          38912,
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/QwQ-32B-Preview",
			Description:                 "QwQ 32B Preview: open-weight reasoning-focused preview model with chain-of-thought.",
		},
		"qwq-plus": {
			Ratio:                       nativeRate(1.6),
			CompletionRatio:             2.5,
			ContextLength:               131072,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			MaxReasoningTokens:          38912,
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/QwQ-32B",
			Description:                 "qwq-plus on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"siliconflow/deepseek-r1-0528": {
			Ratio:           nativeRate(4),
			CompletionRatio: 4,
			Description:     "siliconflow/deepseek-r1-0528 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"siliconflow/deepseek-v3-0324": {
			Ratio:           nativeRate(2),
			CompletionRatio: 4,
			Description:     "siliconflow/deepseek-v3-0324 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"siliconflow/deepseek-v3.1-terminus": {
			Ratio:           nativeRate(4),
			CompletionRatio: 3,
			Description:     "siliconflow/deepseek-v3.1-terminus on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"siliconflow/deepseek-v3.2": {
			Ratio:           nativeRate(2),
			CompletionRatio: 1.5,
			Description:     "siliconflow/deepseek-v3.2 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"stepfun/step-3.7-flash": {
			Ratio:           nativeRate(1.35),
			CompletionRatio: 5.999999999999999,
			Description:     "stepfun/step-3.7-flash on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"stepfun/step-5-preview": {
			Ratio:           nativeRate(7),
			CompletionRatio: 2.857142857142857,
			Description:     "stepfun/step-5-preview on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"tongyi-embedding-vision-plus": {
			Ratio:           nativeRate(0.5),
			CompletionRatio: 1,
			Embedding: &adaptor.EmbeddingPricingConfig{
				TextTokenRatio: nativeRate(0.5),
			},
			ContextLength:    8192,
			InputModalities:  []string{"text", "image"},
			OutputModalities: []string{},
			Description:      "DashScope tongyi-embedding-vision-plus: multimodal (text + image) embedding endpoint.",
		},
		"tongyi-intent-detect-v3": {
			Ratio:           nativeRate(0.4),
			CompletionRatio: 2.5,
			Description:     "tongyi-intent-detect-v3 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"tongyi-xiaomi-analysis-flash": {
			Ratio:           nativeRate(0.2),
			CompletionRatio: 2,
			Description:     "tongyi-xiaomi-analysis-flash on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"tongyi-xiaomi-analysis-pro": {
			Ratio:           nativeRate(1),
			CompletionRatio: 2.7,
			Description:     "tongyi-xiaomi-analysis-pro on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"unisound/unisound-u2": {
			Ratio:           nativeRate(1),
			CompletionRatio: 2,
			Description:     "unisound/unisound-u2 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"wanx-v1": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.02,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				PromptTokenLimit: 4000,
				MinImages:        1,
				MaxImages:        4,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1280x720":  1,
					"720x1280":  1,
				},
			},
			InputModalities:  []string{"text"},
			OutputModalities: []string{"image"},
			Description:      "DashScope wanx-v1: Alibaba's first-generation Wanx text-to-image model.",
		},
		"wanx2.0-t2i-turbo": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.005,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				PromptTokenLimit: 4000,
				MinImages:        1,
				MaxImages:        4,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1280x720":  1,
					"720x1280":  1,
				},
			},
			InputModalities:  []string{"text"},
			OutputModalities: []string{"image"},
			Description:      "DashScope wanx2.0-t2i-turbo: legacy Wan 2.0 cost-optimized text-to-image (¥0.04/image).",
		},
		"wanx2.1-t2i-plus": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.025,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				PromptTokenLimit: 4000,
				MinImages:        1,
				MaxImages:        4,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1152x768":  1,
					"1280x720":  1,
					"720x1280":  1,
					"768x1152":  1,
				},
			},
			InputModalities:  []string{"text"},
			OutputModalities: []string{"image"},
			Description:      "DashScope wanx2.1-t2i-plus: higher-fidelity Wan 2.1 text-to-image tier (~¥0.20/image).",
		},
		"wanx2.1-t2i-turbo": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.01813,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				PromptTokenLimit: 4000,
				MinImages:        1,
				MaxImages:        4,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1152x768":  1,
					"1280x720":  1,
					"720x1280":  1,
					"768x1152":  1,
				},
			},
			InputModalities:  []string{"text"},
			OutputModalities: []string{"image"},
			Description:      "DashScope wanx2.1-t2i-turbo: cost-optimized Wan 2.1 text-to-image tier (¥0.145/image).",
		},
		"xiaomi/mimo-v2.5-pro": {
			Ratio:           nativeRate(7),
			CompletionRatio: 3,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(14),
				CompletionRatio:     3,
				InputTokenThreshold: 256001,
			},
			},
			Description: "xiaomi/mimo-v2.5-pro on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"z-image-turbo": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.015,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				PromptTokenLimit: 4000,
				MinImages:        1,
				MaxImages:        1,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1536x1536": 1,
					"2048x2048": 1,
				},
			},
			InputModalities:  []string{"text"},
			OutputModalities: []string{"image"},
			Description:      "DashScope z-image-turbo: lightweight fast text-to-image model, fixed 1 image/request, up to 2048x2048 ($0.015/image, $0.03 with prompt_extend).",
		},
	}
}
