package ali

import "github.com/Laisky/one-api/relay/adaptor"

// qwenModels returns the qwen model defaults for ali.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func qwenModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"qwen-1.8b-chat": {
			Ratio:                       0.02142857142857143,
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen 1.8B Chat (Qwen 1 generation, hosted only).",
		},
		"qwen-1.8b-longcontext-chat": {
			Ratio:                       0.02142857142857143,
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen 1.8B Long-Context Chat (Qwen 1 generation, hosted only).",
		},
		"qwen-14b-chat": {
			Ratio:                       nativeRate(1),
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen 14B Chat (Qwen 1 generation, hosted only).",
		},
		"qwen-72b-chat": {
			Ratio:                       nativeRate(4),
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen 72B Chat (Qwen 1 generation, hosted only).",
		},
		"qwen-7b-chat": {
			Ratio:                       nativeRate(0.5),
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen 7B Chat (Qwen 1 generation, hosted only).",
		},
		"qwen-audio-chat": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             2000,
			InputModalities:             []string{"text", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen-Audio Chat: legacy closed-weight audio chat model (free trial).",
		},
		"qwen-audio-turbo": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             2000,
			InputModalities:             []string{"text", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen-Audio Turbo: closed-weight audio-understanding model (currently free trial).",
		},
		"qwen-coder-plus": {
			Ratio:                       nativeRate(3.5),
			CompletionRatio:             2,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "qwen-coder-plus on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-coder-plus-latest": {
			Ratio:                       nativeRate(3.5),
			CompletionRatio:             2,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen-Coder Plus (latest snapshot alias).",
		},
		"qwen-coder-turbo": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             3,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "qwen-coder-turbo on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-coder-turbo-latest": {
			Ratio:                       nativeRate(2.06),
			CompletionRatio:             2.995,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen-Coder Turbo (latest snapshot alias).",
		},
		"qwen-flash": {
			Ratio:            nativeRate(0.15),
			CompletionRatio:  10,
			CachedInputRatio: nativeRate(0.030000000000000002),
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.6),
				CompletionRatio:     10,
				InputTokenThreshold: 128001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(1.2),
					CompletionRatio:     10,
					InputTokenThreshold: 256001,
				},
			},
			ContextLength:               1000000,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "qwen-flash on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-flash-2025-07-28": {
			Ratio:           nativeRate(0.15),
			CompletionRatio: 10,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(0.6),
				CompletionRatio:     10,
				InputTokenThreshold: 128001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(1.2),
					CompletionRatio:     10,
					InputTokenThreshold: 256001,
				},
			},
			Description: "qwen-flash-2025-07-28 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-flash-character": {
			Ratio:           nativeRate(0.25),
			CompletionRatio: 6,
			Description:     "qwen-flash-character on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-flash-character-2026-02-26": {
			Ratio:           nativeRate(0.18),
			CompletionRatio: 8.333333333333334,
			Description:     "qwen-flash-character-2026-02-26 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-flash-latest": {
			Ratio:                       0.010714285714285714,
			CompletionRatio:             10,
			CachedInputRatio:            nativeRate(0.030000000000000002),
			ContextLength:               1000000,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen Flash (latest snapshot alias).",
		},
		"qwen-image": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.03125,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				PromptTokenLimit: 4000,
				MinImages:        1,
				MaxImages:        4,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1280x720":  1,
					"720x1280":  1,
				},
			},
			InputModalities:  []string{"text"},
			OutputModalities: []string{"image"},
			Description:      "DashScope qwen-image: Qwen Image standard tier (¥0.25/image).",
		},
		"qwen-image-2.0": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.025,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				PromptTokenLimit: 4000,
				MinImages:        1,
				MaxImages:        4,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1280x720":  1,
					"720x1280":  1,
				},
			},
			InputModalities:  []string{"text"},
			OutputModalities: []string{"image"},
			Description:      "DashScope qwen-image-2.0: Qwen Image 2.0 standard tier (¥0.20/image).",
		},
		"qwen-image-2.0-pro": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.0625,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "hd",
				PromptTokenLimit: 4000,
				MinImages:        1,
				MaxImages:        4,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1024x1536": 1,
					"1280x720":  1,
					"1536x1024": 1,
					"720x1280":  1,
				},
			},
			InputModalities:  []string{"text"},
			OutputModalities: []string{"image"},
			Description:      "DashScope qwen-image-2.0-pro: canonical 2.0 high-fidelity tier with 4K support (¥0.50/image).",
		},
		"qwen-image-edit": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.0375,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				PromptTokenLimit: 4000,
				MinImages:        1,
				MaxImages:        4,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
				},
			},
			InputModalities:  []string{"text", "image"},
			OutputModalities: []string{"image"},
			Description:      "DashScope qwen-image-edit: Qwen Image editing baseline tier (¥0.30/image).",
		},
		"qwen-image-edit-max": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.0625,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "hd",
				PromptTokenLimit: 4000,
				MinImages:        1,
				MaxImages:        4,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
				},
			},
			InputModalities:  []string{"text", "image"},
			OutputModalities: []string{"image"},
			Description:      "DashScope qwen-image-edit-max: high-fidelity image editing tier (¥0.50/image).",
		},
		"qwen-image-edit-plus": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.025,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				PromptTokenLimit: 4000,
				MinImages:        1,
				MaxImages:        4,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
				},
			},
			InputModalities:  []string{"text", "image"},
			OutputModalities: []string{"image"},
			Description:      "DashScope qwen-image-edit-plus: image editing tier (¥0.20/image).",
		},
		"qwen-image-max": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.0625,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "hd",
				PromptTokenLimit: 4000,
				MinImages:        1,
				MaxImages:        4,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1024x1536": 1,
					"1280x720":  1,
					"1536x1024": 1,
					"720x1280":  1,
				},
			},
			InputModalities:  []string{"text"},
			OutputModalities: []string{"image"},
			Description:      "DashScope qwen-image-max: top-tier Qwen Image text-to-image model (¥0.50/image).",
		},
		"qwen-image-plus": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.025,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "standard",
				PromptTokenLimit: 4000,
				MinImages:        1,
				MaxImages:        4,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1152x768":  1,
					"1280x720":  1,
					"720x1280":  1,
					"768x1152":  1,
				},
			},
			InputModalities:  []string{"text"},
			OutputModalities: []string{"image"},
			Description:      "DashScope qwen-image-plus: cost-effective Qwen Image text-to-image tier (¥0.20/image).",
		},
		"qwen-image-pro": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.0625,
				DefaultSize:      "1024x1024",
				DefaultQuality:   "hd",
				PromptTokenLimit: 4000,
				MinImages:        1,
				MaxImages:        4,
				SizeMultipliers: map[string]float64{
					"1024x1024": 1,
					"1024x1536": 1,
					"1280x720":  1,
					"1536x1024": 1,
					"720x1280":  1,
				},
			},
			InputModalities:  []string{"text"},
			OutputModalities: []string{"image"},
			Description:      "DashScope qwen-image-pro: Qwen Image 2.0 high-fidelity tier (¥0.50/image).",
		},
		"qwen-long": {
			Ratio:                       nativeRate(0.5),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.1),
			ContextLength:               10000000,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "qwen-long on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-long-2025-01-25": {
			Ratio:           nativeRate(0.5),
			CompletionRatio: 4,
			Description:     "qwen-long-2025-01-25 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-long-latest": {
			Ratio:           nativeRate(0.5),
			CompletionRatio: 4,
			Description:     "qwen-long-latest on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-math-plus": {
			Ratio:                       nativeRate(4),
			CompletionRatio:             3,
			ContextLength:               4096,
			MaxOutputTokens:             3072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "qwen-math-plus on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-math-plus-latest": {
			Ratio:                       nativeRate(4),
			CompletionRatio:             3,
			ContextLength:               4096,
			MaxOutputTokens:             3072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen-Math Plus (latest snapshot alias).",
		},
		"qwen-math-turbo": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             3,
			ContextLength:               4096,
			MaxOutputTokens:             3072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "qwen-math-turbo on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-math-turbo-latest": {
			Ratio:                       nativeRate(2.06),
			CompletionRatio:             2.995,
			ContextLength:               4096,
			MaxOutputTokens:             3072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen-Math Turbo (latest snapshot alias).",
		},
		"qwen-max": {
			Ratio:                       nativeRate(2.4),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.48000000000000004),
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "qwen-max on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-max-latest": {
			Ratio:                       0.17142857142857143,
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.48000000000000004),
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen Max (latest snapshot alias).",
		},
		"qwen-max-longcontext": {
			Ratio:                       0.17142857142857143,
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.48000000000000004),
			ContextLength:               30720,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen Max long-context legacy variant; superseded by tiered qwen-max.",
		},
		"qwen-mt-flash": {
			Ratio:                       nativeRate(0.7000000000000001),
			CompletionRatio:             2.786,
			ContextLength:               4096,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen-MT Flash: cost-optimized closed-weight machine-translation tier.",
		},
		"qwen-mt-lite": {
			Ratio:                       0.04285714285714286,
			CompletionRatio:             2.667,
			ContextLength:               4096,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen-MT Lite: lowest-cost closed-weight machine-translation tier.",
		},
		"qwen-mt-plus": {
			Ratio:                       nativeRate(1.86),
			CompletionRatio:             2.995,
			ContextLength:               4096,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen-MT Plus: closed-weight machine-translation tier.",
		},
		"qwen-mt-turbo": {
			Ratio:                       0.05142857142857143,
			CompletionRatio:             2.79,
			ContextLength:               4096,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen-MT Turbo: cost-optimized closed-weight translation model.",
		},
		"qwen-omni-turbo": {
			Ratio:                       nativeRate(0.4),
			CompletionRatio:             4,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen-Omni Turbo: closed-weight multimodal tier (text I/O rate billed here; audio billing is per-modality upstream).",
		},
		"qwen-plus": {
			Ratio:                       nativeRate(0.8),
			CompletionRatio:             2.5,
			CachedInputRatio:            nativeRate(0.16),
			ContextLength:               1000000,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen Plus: closed-weight balanced tier with tiered 1M context pricing (base 0-128K tier billed here).",
		},
		"qwen-plus-2024-12-20": {
			Ratio:           nativeRate(0.8),
			CompletionRatio: 2.5,
			Description:     "qwen-plus-2024-12-20 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-plus-2025-01-12": {
			Ratio:           nativeRate(0.8),
			CompletionRatio: 2.5,
			Description:     "qwen-plus-2025-01-12 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-plus-2025-01-25": {
			Ratio:           nativeRate(0.8),
			CompletionRatio: 2.5,
			Description:     "qwen-plus-2025-01-25 on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-plus-character": {
			Ratio:           nativeRate(0.8),
			CompletionRatio: 2.5,
			Description:     "qwen-plus-character on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-plus-latest": {
			Ratio:                       nativeRate(0.8),
			CompletionRatio:             2.5,
			CachedInputRatio:            nativeRate(0.16),
			ContextLength:               1000000,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen Plus (latest snapshot alias).",
		},
		"qwen-turbo": {
			Ratio:                       nativeRate(0.31),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.062),
			ContextLength:               1000000,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen Turbo: closed-weight cost-optimized chat tier with up to 1M context (deprecated; use qwen-flash).",
		},
		"qwen-turbo-latest": {
			Ratio:                       nativeRate(0.31),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.062),
			ContextLength:               1000000,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen Turbo (latest snapshot alias); deprecated alongside qwen-turbo.",
		},
		"qwen-vl-chat-v1": {
			Ratio:                       nativeRate(1),
			CompletionRatio:             1,
			ContextLength:               2048,
			MaxOutputTokens:             1500,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen-VL Chat v1: legacy closed-weight multimodal chat model.",
		},
		"qwen-vl-max": {
			Ratio:                       nativeRate(1.6),
			CompletionRatio:             2.5,
			ContextLength:               32000,
			MaxOutputTokens:             2000,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "qwen-vl-max on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-vl-max-latest": {
			Ratio:                       nativeRate(1.6),
			CompletionRatio:             2.5,
			ContextLength:               32000,
			MaxOutputTokens:             2000,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen-VL Max (latest snapshot alias).",
		},
		"qwen-vl-ocr": {
			Ratio:                       nativeRate(5.15),
			CompletionRatio:             1,
			ContextLength:               34096,
			MaxOutputTokens:             4096,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen-VL OCR: closed-weight model tuned for document/scene OCR (5.15 CNY per 1M tokens).",
		},
		"qwen-vl-ocr-latest": {
			Ratio:                       nativeRate(5.15),
			CompletionRatio:             1,
			ContextLength:               34096,
			MaxOutputTokens:             4096,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen-VL OCR (latest snapshot alias).",
		},
		"qwen-vl-plus": {
			Ratio:                       nativeRate(0.8),
			CompletionRatio:             2.5,
			ContextLength:               32000,
			MaxOutputTokens:             2000,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "qwen-vl-plus on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen-vl-plus-latest": {
			Ratio:                       nativeRate(0.8),
			CompletionRatio:             2.5,
			ContextLength:               32000,
			MaxOutputTokens:             2000,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen-VL Plus (latest snapshot alias).",
		},
		"qwen-vl-v1": {
			Ratio:                       nativeRate(1),
			CompletionRatio:             1,
			ContextLength:               2048,
			MaxOutputTokens:             1500,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Description:                 "Qwen-VL v1: legacy closed-weight multimodal base model.",
		},
		"qwen1.5-0.5b-chat": {
			Ratio:                       0.02142857142857143,
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen1.5-0.5B-Chat",
			Description:                 "Qwen1.5 0.5B Chat: open-weight legacy micro chat model.",
		},
		"qwen1.5-1.8b-chat": {
			Ratio:                       0.02142857142857143,
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen1.5-1.8B-Chat",
			Description:                 "Qwen1.5 1.8B Chat: open-weight legacy compact chat model.",
		},
	}
}
