package ali

import "github.com/Laisky/one-api/relay/adaptor"

// qwen_2Models returns the qwen model defaults for ali.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func qwen_2Models() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"qwen1.5-110b-chat": {
			Ratio:                       nativeRate(8),
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen1.5-110B-Chat",
			Description:                 "Qwen1.5 110B Chat: open-weight legacy flagship chat model.",
		},
		"qwen1.5-14b-chat": {
			Ratio:                       nativeRate(1),
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen1.5-14B-Chat",
			Description:                 "Qwen1.5 14B Chat: open-weight legacy chat model.",
		},
		"qwen1.5-32b-chat": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen1.5-32B-Chat",
			Description:                 "Qwen1.5 32B Chat: open-weight legacy chat model.",
		},
		"qwen1.5-72b-chat": {
			Ratio:                       nativeRate(4),
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen1.5-72B-Chat",
			Description:                 "Qwen1.5 72B Chat: open-weight legacy chat model.",
		},
		"qwen1.5-7b-chat": {
			Ratio:                       nativeRate(0.5),
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen1.5-7B-Chat",
			Description:                 "Qwen1.5 7B Chat: open-weight legacy chat model.",
		},
		"qwen2-0.5b-instruct": {
			Ratio:                       0.02142857142857143,
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2-0.5B-Instruct",
			Description:                 "Qwen2 0.5B Instruct: open-weight micro instruct model.",
		},
		"qwen2-1.5b-instruct": {
			Ratio:                       0.02142857142857143,
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2-1.5B-Instruct",
			Description:                 "Qwen2 1.5B Instruct: open-weight compact instruct model.",
		},
		"qwen2-57b-a14b-instruct": {
			Ratio:                       nativeRate(3.5),
			CompletionRatio:             1,
			ContextLength:               65536,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2-57B-A14B-Instruct",
			Description:                 "Qwen2 57B-A14B Instruct: open-weight MoE instruct model (14B active).",
		},
		"qwen2-72b-instruct": {
			Ratio:                       nativeRate(4),
			CompletionRatio:             1,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2-72B-Instruct",
			Description:                 "Qwen2 72B Instruct: previous-generation open-weight flagship.",
		},
		"qwen2-7b-instruct": {
			Ratio:                       nativeRate(1),
			CompletionRatio:             1,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2-7B-Instruct",
			Description:                 "Qwen2 7B Instruct: open-weight previous-generation instruct model.",
		},
		"qwen2-audio-instruct": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             2048,
			InputModalities:             []string{"text", "file"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2-Audio-7B-Instruct",
			Description:                 "Qwen2-Audio Instruct: open-weight audio-understanding model (currently free trial).",
		},
		"qwen2-math-1.5b-instruct": {
			Ratio:                       0.02142857142857143,
			CompletionRatio:             1,
			ContextLength:               4096,
			MaxOutputTokens:             3072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2-Math-1.5B-Instruct",
			Description:                 "Qwen2-Math 1.5B Instruct: open-weight compact math model.",
		},
		"qwen2-math-72b-instruct": {
			Ratio:                       nativeRate(4),
			CompletionRatio:             1,
			ContextLength:               4096,
			MaxOutputTokens:             3072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2-Math-72B-Instruct",
			Description:                 "Qwen2-Math 72B Instruct: open-weight math-specialized model.",
		},
		"qwen2-math-7b-instruct": {
			Ratio:                       nativeRate(0.5),
			CompletionRatio:             1,
			ContextLength:               4096,
			MaxOutputTokens:             3072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2-Math-7B-Instruct",
			Description:                 "Qwen2-Math 7B Instruct: open-weight math-specialized model.",
		},
		"qwen2-vl-2b-instruct": {
			Ratio:                       0.02142857142857143,
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2-VL-2B-Instruct",
			Description:                 "Qwen2-VL 2B Instruct: open-weight compact previous-generation vision-language model.",
		},
		"qwen2-vl-7b-instruct": {
			Ratio:                       nativeRate(0.5),
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2-VL-7B-Instruct",
			Description:                 "Qwen2-VL 7B Instruct: open-weight previous-generation vision-language model.",
		},
		"qwen2.5-0.5b-instruct": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-0.5B-Instruct",
			Description:                 "Qwen2.5 0.5B Instruct: open-weight micro instruct model (free trial).",
		},
		"qwen2.5-1.5b-instruct": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-1.5B-Instruct",
			Description:                 "Qwen2.5 1.5B Instruct: open-weight compact instruct model (limited-time free trial).",
		},
		"qwen2.5-14b-instruct": {
			Ratio:                       nativeRate(1.03),
			CompletionRatio:             3,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-14B-Instruct",
			Description:                 "Qwen2.5 14B Instruct: open-weight instruct model with 128K context.",
		},
		"qwen2.5-32b-instruct": {
			Ratio:                       nativeRate(2.06),
			CompletionRatio:             2.995,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-32B-Instruct",
			Description:                 "Qwen2.5 32B Instruct: open-weight mid-tier instruct model with 128K context.",
		},
		"qwen2.5-3b-instruct": {
			Ratio:                       0.04285714285714286,
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-3B-Instruct",
			Description:                 "Qwen2.5 3B Instruct: open-weight small instruct model.",
		},
		"qwen2.5-72b-instruct": {
			Ratio:                       nativeRate(4.11),
			CompletionRatio:             3.01,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-72B-Instruct",
			Description:                 "Qwen2.5 72B Instruct: open-weight flagship instruct model with 128K context.",
		},
		"qwen2.5-7b-instruct": {
			Ratio:                       nativeRate(0.52),
			CompletionRatio:             1.98,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-7B-Instruct",
			Description:                 "Qwen2.5 7B Instruct: open-weight cost-efficient instruct model with 128K context.",
		},
		"qwen2.5-coder-0.5b-instruct": {
			Ratio:                       0.02142857142857143,
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-Coder-0.5B-Instruct",
			Description:                 "Qwen2.5-Coder 0.5B Instruct: open-weight micro coder model.",
		},
		"qwen2.5-coder-1.5b-instruct": {
			Ratio:                       0.02142857142857143,
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-Coder-1.5B-Instruct",
			Description:                 "Qwen2.5-Coder 1.5B Instruct: open-weight compact coder model.",
		},
		"qwen2.5-coder-14b-instruct": {
			Ratio:                       nativeRate(1),
			CompletionRatio:             1,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-Coder-14B-Instruct",
			Description:                 "Qwen2.5-Coder 14B Instruct: open-weight coder model with 128K context.",
		},
		"qwen2.5-coder-32b-instruct": {
			Ratio:                       nativeRate(2),
			CompletionRatio:             1,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-Coder-32B-Instruct",
			Description:                 "Qwen2.5-Coder 32B Instruct: open-weight coder flagship with 128K context.",
		},
		"qwen2.5-coder-3b-instruct": {
			Ratio:                       0.02142857142857143,
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-Coder-3B-Instruct",
			Description:                 "Qwen2.5-Coder 3B Instruct: open-weight compact coder model.",
		},
		"qwen2.5-coder-7b-instruct": {
			Ratio:                       nativeRate(0.5),
			CompletionRatio:             1,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-Coder-7B-Instruct",
			Description:                 "Qwen2.5-Coder 7B Instruct: open-weight coder model with 128K context.",
		},
		"qwen2.5-math-1.5b-instruct": {
			Ratio:                       0,
			CompletionRatio:             1,
			ContextLength:               4096,
			MaxOutputTokens:             3072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-Math-1.5B-Instruct",
			Description:                 "Qwen2.5-Math 1.5B Instruct: open-weight compact math model (free trial).",
		},
		"qwen2.5-math-72b-instruct": {
			Ratio:                       nativeRate(4),
			CompletionRatio:             1,
			ContextLength:               4096,
			MaxOutputTokens:             3072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-Math-72B-Instruct",
			Description:                 "Qwen2.5-Math 72B Instruct: open-weight math-specialized model.",
		},
		"qwen2.5-math-7b-instruct": {
			Ratio:                       nativeRate(1),
			CompletionRatio:             1,
			ContextLength:               4096,
			MaxOutputTokens:             3072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-Math-7B-Instruct",
			Description:                 "Qwen2.5-Math 7B Instruct: open-weight math-specialized model.",
		},
		"qwen2.5-vl-0.5b-instruct": {
			Ratio:                       0.02142857142857143,
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			Description:                 "Qwen2.5-VL 0.5B Instruct: open-weight micro vision-language model (HF card not published).",
		},
		"qwen2.5-vl-1b-instruct": {
			Ratio:                       0.02142857142857143,
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			Description:                 "Qwen2.5-VL 1B Instruct: open-weight micro vision-language model (HF card not published).",
		},
		"qwen2.5-vl-2b-instruct": {
			Ratio:                       0.02142857142857143,
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-VL-2B-Instruct",
			Description:                 "Qwen2.5-VL 2B Instruct: open-weight compact vision-language model.",
		},
		"qwen2.5-vl-3b-instruct": {
			Ratio:                       0.02142857142857143,
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-VL-3B-Instruct",
			Description:                 "Qwen2.5-VL 3B Instruct: open-weight compact vision-language model.",
		},
		"qwen2.5-vl-72b-instruct": {
			Ratio:                       nativeRate(4),
			CompletionRatio:             1,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-VL-72B-Instruct",
			Description:                 "Qwen2.5-VL 72B Instruct: open-weight flagship vision-language model.",
		},
		"qwen2.5-vl-7b-instruct": {
			Ratio:                       nativeRate(0.5),
			CompletionRatio:             1,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-VL-7B-Instruct",
			Description:                 "Qwen2.5-VL 7B Instruct: open-weight vision-language model with 128K context.",
		},
		"qwen3-0.6b": {
			Ratio:                       nativeRate(0.31),
			CompletionRatio:             4,
			ContextLength:               32768,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-0.6B",
			Description:                 "Qwen3 0.6B: open-weight micro model with hybrid thinking modes.",
		},
		"qwen3-1.7b": {
			Ratio:                       nativeRate(0.31),
			CompletionRatio:             4,
			ContextLength:               32768,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-1.7B",
			Description:                 "Qwen3 1.7B: open-weight micro model with hybrid thinking modes.",
		},
		"qwen3-14b": {
			Ratio:                       nativeRate(1.03),
			CompletionRatio:             3.99,
			ContextLength:               131072,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-14B",
			Description:                 "Qwen3 14B: dense open-weight model with hybrid thinking modes.",
		},
		"qwen3-235b-a22b": {
			Ratio:                       nativeRate(2.06),
			CompletionRatio:             4,
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-235B-A22B-Instruct-2507",
			Description:                 "Qwen3 235B A22B: open-weight MoE flagship (22B active) with thinking/non-thinking modes.",
		},
		"qwen3-235b-a22b-instruct-2507": {
			Ratio:                       nativeRate(2.06),
			CompletionRatio:             4,
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-235B-A22B-Instruct-2507",
			Description:                 "Qwen3 235B A22B Instruct (2507 snapshot): non-thinking instruct variant.",
		},
		"qwen3-235b-a22b-thinking-2507": {
			Ratio:                       nativeRate(2.06),
			CompletionRatio:             4,
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			MaxReasoningTokens:          38912,
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-235B-A22B-Thinking-2507",
			Description:                 "Qwen3 235B A22B Thinking (2507): open-weight reasoning flagship with chain-of-thought.",
		},
		"qwen3-30b-a3b": {
			Ratio:                       nativeRate(0.75),
			CompletionRatio:             4,
			ContextLength:               131072,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-30B-A3B",
			Description:                 "Qwen3 30B A3B: open-weight MoE (3B active) with hybrid thinking modes.",
		},
		"qwen3-30b-a3b-instruct-2507": {
			Ratio:                       nativeRate(0.75),
			CompletionRatio:             4,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-30B-A3B-Instruct-2507",
			Description:                 "Qwen3 30B A3B Instruct (2507 snapshot): open-weight MoE (3B active), non-thinking instruct variant.",
		},
		"qwen3-30b-a3b-thinking-2507": {
			Ratio:                       nativeRate(0.75),
			CompletionRatio:             10,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"seed", "max_tokens"},
			MaxReasoningTokens:          38912,
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-30B-A3B-Thinking-2507",
			Description:                 "Qwen3 30B A3B Thinking (2507 snapshot): open-weight MoE reasoning variant.",
		},
		"qwen3-32b": {
			Ratio:                       nativeRate(2.06),
			CompletionRatio:             4,
			ContextLength:               131072,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-32B",
			Description:                 "Qwen3 32B: dense open-weight model with hybrid thinking/non-thinking modes.",
		},
		"qwen3-4b": {
			Ratio:                       nativeRate(0.31),
			CompletionRatio:             4,
			ContextLength:               131072,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-4B",
			Description:                 "Qwen3 4B: open-weight compact model with hybrid thinking modes.",
		},
		"qwen3-8b": {
			Ratio:                       nativeRate(0.52),
			CompletionRatio:             3.96,
			ContextLength:               131072,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-8B",
			Description:                 "Qwen3 8B: open-weight model with hybrid thinking modes.",
		},
		"qwen3-coder-30b-a3b-instruct": {
			Ratio:           nativeRate(1.5),
			CompletionRatio: 4,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(2.25),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(3.75),
					CompletionRatio:     4,
					InputTokenThreshold: 128001,
				},
			},
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-Coder-30B-A3B-Instruct",
			Description:                 "qwen3-coder-30b-a3b-instruct on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen3-coder-480b-a35b-instruct": {
			Ratio:           nativeRate(6),
			CompletionRatio: 4,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(9),
				CompletionRatio:     4,
				InputTokenThreshold: 32001,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(15),
					CompletionRatio:     4,
					InputTokenThreshold: 128001,
				},
			},
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "frequency_penalty", "presence_penalty", "repetition_penalty", "stop", "seed", "max_tokens"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-Coder-480B-A35B-Instruct",
			Description:                 "qwen3-coder-480b-a35b-instruct on ali; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
