package openai

import (
	"github.com/Laisky/one-api/relay/adaptor"
	"github.com/Laisky/one-api/relay/billing/ratio"
)

// gpt5ModelRatios captures pricing and metadata for the GPT-5 family of reasoning
// chat models. All members are reasoning models: SupportedSamplingParameters is
// constrained to ["seed","max_tokens"] (no temperature/top_p/frequency_penalty/
// presence_penalty), and SupportedFeatures includes "reasoning".
//
// Verified context windows from OpenAI docs (2026-05-01): gpt-5 family advertises
// 400K context and 128K max output. The newer gpt-5.4 / gpt-5.5 lines extend this
// to 1M context per the public model catalog. gpt-5-pro / gpt-5.x-pro variants
// allow longer reasoning budgets.
// Sources:
//   - https://platform.openai.com/docs/models/gpt-5
//   - https://platform.openai.com/docs/models/gpt-5.1
//   - https://platform.openai.com/docs/models (gpt-5.4 / gpt-5.5 entries)
var gpt5ReasoningFeatures = []string{"reasoning", "tools", "json_mode", "structured_outputs"}

var gpt5ModelRatios = map[string]adaptor.ModelConfig{
	// gpt-5.5: 1M context, 128K output (per docs page).
	"gpt-5.5": {
		Ratio:                       5.0 * ratio.MilliTokensUsd,
		CompletionRatio:             30.0 / 5.0,
		CachedInputRatio:            0.5 * ratio.MilliTokensUsd,
		ContextLength:               1_000_000,
		MaxOutputTokens:             128000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           gpt5ReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5.5: next-generation reasoning flagship with 1M context.",
	},
	"gpt-5.5-pro": {
		Ratio:                       30 * ratio.MilliTokensUsd,
		CompletionRatio:             180 / 30.0,
		ContextLength:               1_000_000,
		MaxOutputTokens:             272000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           append([]string{"web_search"}, gpt5ReasoningFeatures...),
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5.5 Pro: deep-research tier with extended reasoning budget.",
	},
	"gpt-5.5-2026-04-23": {
		Ratio:                       5.0 * ratio.MilliTokensUsd,
		CompletionRatio:             30.0 / 5.0,
		CachedInputRatio:            0.5 * ratio.MilliTokensUsd,
		ContextLength:               1_000_000,
		MaxOutputTokens:             128000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           gpt5ReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5.5 snapshot from 2026-04-23.",
	},
	// gpt-5.4: 1M context per docs page.
	"gpt-5.4": {
		Ratio:                       2.5 * ratio.MilliTokensUsd,
		CompletionRatio:             15 / 2.5,
		CachedInputRatio:            0.25 * ratio.MilliTokensUsd,
		ContextLength:               1_000_000,
		MaxOutputTokens:             128000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           gpt5ReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5.4: balanced reasoning model with 1M context.",
	},
	// gpt-5.4-mini: 400K per docs.
	"gpt-5.4-mini": {
		Ratio:                       0.75 * ratio.MilliTokensUsd,
		CompletionRatio:             4.5 / 0.75,
		CachedInputRatio:            0.075 * ratio.MilliTokensUsd,
		ContextLength:               400000,
		MaxOutputTokens:             128000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           gpt5ReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5.4 mini: cost-efficient reasoning with 400K context.",
	},
	"gpt-5.4-nano": {
		Ratio:                       0.2 * ratio.MilliTokensUsd,
		CompletionRatio:             1.25 / 0.2,
		CachedInputRatio:            0.02 * ratio.MilliTokensUsd,
		ContextLength:               400000,
		MaxOutputTokens:             128000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           gpt5ReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5.4 nano: lowest-latency reasoning tier.",
	},
	"gpt-5.4-pro": {
		Ratio:                       30 * ratio.MilliTokensUsd,
		CompletionRatio:             180 / 30.0,
		ContextLength:               1_000_000,
		MaxOutputTokens:             272000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           append([]string{"web_search"}, gpt5ReasoningFeatures...),
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5.4 Pro: deep-research tier with web search.",
	},
	"gpt-5.3-chat-latest": {
		Ratio:                       1.75 * ratio.MilliTokensUsd,
		CompletionRatio:             14 / 1.75,
		CachedInputRatio:            0.175 * ratio.MilliTokensUsd,
		ContextLength:               400000,
		MaxOutputTokens:             128000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           gpt5ReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5.3 chat-latest: rolling alias for the latest 5.3 chat snapshot.",
	},
	"gpt-5.3-codex": {
		Ratio:                       1.75 * ratio.MilliTokensUsd,
		CompletionRatio:             14 / 1.75,
		CachedInputRatio:            0.175 * ratio.MilliTokensUsd,
		ContextLength:               400000,
		MaxOutputTokens:             128000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           gpt5ReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5.3 Codex: code-tuned reasoning variant.",
	},
	"gpt-5.2": {
		Ratio:                       1.75 * ratio.MilliTokensUsd,
		CompletionRatio:             14 / 1.75,
		CachedInputRatio:            0.175 * ratio.MilliTokensUsd,
		ContextLength:               400000,
		MaxOutputTokens:             128000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           gpt5ReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5.2: reasoning chat model with 400K context.",
	},
	"gpt-5.2-2025-12-11": {
		Ratio:                       1.75 * ratio.MilliTokensUsd,
		CompletionRatio:             14 / 1.75,
		CachedInputRatio:            0.175 * ratio.MilliTokensUsd,
		ContextLength:               400000,
		MaxOutputTokens:             128000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           gpt5ReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5.2 snapshot from 2025-12-11.",
	},
	"gpt-5.2-codex": {
		Ratio:                       1.75 * ratio.MilliTokensUsd,
		CompletionRatio:             14 / 1.75,
		CachedInputRatio:            0.175 * ratio.MilliTokensUsd,
		ContextLength:               400000,
		MaxOutputTokens:             128000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           gpt5ReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5.2 Codex: code-tuned 5.2 reasoning variant.",
	},
	"gpt-5.2-pro": {
		Ratio:                       21 * ratio.MilliTokensUsd,
		CompletionRatio:             168 / 21.0,
		ContextLength:               400000,
		MaxOutputTokens:             272000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           append([]string{"web_search"}, gpt5ReasoningFeatures...),
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5.2 Pro: deep-research tier with web search.",
	},
	"gpt-5.2-pro-2025-12-11": {
		Ratio:                       21 * ratio.MilliTokensUsd,
		CompletionRatio:             168 / 21.0,
		ContextLength:               400000,
		MaxOutputTokens:             272000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           append([]string{"web_search"}, gpt5ReasoningFeatures...),
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5.2 Pro snapshot from 2025-12-11.",
	},
	// gpt-5.1: verified 400K context, 128K output, image input.
	"gpt-5.1": {
		Ratio:                       1.25 * ratio.MilliTokensUsd,
		CompletionRatio:             10 / 1.25,
		CachedInputRatio:            0.125 * ratio.MilliTokensUsd,
		ContextLength:               400000,
		MaxOutputTokens:             128000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           gpt5ReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5.1: reasoning chat model with configurable effort and 400K context.",
	},
	"gpt-5.1-2025-11-13": {
		Ratio:                       1.25 * ratio.MilliTokensUsd,
		CompletionRatio:             10 / 1.25,
		CachedInputRatio:            0.125 * ratio.MilliTokensUsd,
		ContextLength:               400000,
		MaxOutputTokens:             128000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           gpt5ReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5.1 snapshot from 2025-11-13.",
	},
	"gpt-5.1-chat-latest": {
		Ratio:                       1.25 * ratio.MilliTokensUsd,
		CompletionRatio:             10 / 1.25,
		CachedInputRatio:            0.125 * ratio.MilliTokensUsd,
		ContextLength:               400000,
		MaxOutputTokens:             128000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           gpt5ReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5.1 chat-latest: rolling alias mirroring ChatGPT's GPT-5.1 default.",
	},
	"gpt-5.1-codex": {
		Ratio:                       1.25 * ratio.MilliTokensUsd,
		CompletionRatio:             10 / 1.25,
		CachedInputRatio:            0.125 * ratio.MilliTokensUsd,
		ContextLength:               400000,
		MaxOutputTokens:             128000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           gpt5ReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5.1 Codex: code-tuned reasoning variant for agentic coding.",
	},
	"gpt-5.1-codex-mini": {
		Ratio:                       0.25 * ratio.MilliTokensUsd,
		CompletionRatio:             2 / 0.25,
		CachedInputRatio:            0.025 * ratio.MilliTokensUsd,
		ContextLength:               400000,
		MaxOutputTokens:             128000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           gpt5ReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5.1 Codex mini: cost-efficient reasoning code model.",
	},
	"gpt-5.1-codex-max": {
		Ratio:                       1.25 * ratio.MilliTokensUsd,
		CompletionRatio:             10 / 1.25,
		CachedInputRatio:            0.125 * ratio.MilliTokensUsd,
		ContextLength:               400000,
		MaxOutputTokens:             128000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           gpt5ReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5.1 Codex max: highest-effort coding reasoning tier.",
	},
	"gpt-5-chat-latest": {
		Ratio:                       1.25 * ratio.MilliTokensUsd,
		CompletionRatio:             10 / 1.25,
		CachedInputRatio:            0.125 * ratio.MilliTokensUsd,
		ContextLength:               400000,
		MaxOutputTokens:             128000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           gpt5ReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5 chat-latest: rolling alias mirroring ChatGPT's GPT-5 default.",
	},
	"gpt-5-codex": {
		Ratio:                       1.25 * ratio.MilliTokensUsd,
		CompletionRatio:             10 / 1.25,
		CachedInputRatio:            0.125 * ratio.MilliTokensUsd,
		ContextLength:               400000,
		MaxOutputTokens:             128000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           gpt5ReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5 Codex: code-tuned 5.0 reasoning variant.",
	},
	"gpt-5-pro": {
		Ratio:                       15 * ratio.MilliTokensUsd,
		CompletionRatio:             120 / 15,
		ContextLength:               400000,
		MaxOutputTokens:             272000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           append([]string{"web_search"}, gpt5ReasoningFeatures...),
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5 Pro: deep-research tier with extended reasoning and web search.",
	},
	"gpt-5-pro-2025-10-06": {
		Ratio:                       15 * ratio.MilliTokensUsd,
		CompletionRatio:             120 / 15,
		ContextLength:               400000,
		MaxOutputTokens:             272000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           append([]string{"web_search"}, gpt5ReasoningFeatures...),
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5 Pro snapshot from 2025-10-06.",
	},
	"gpt-5": {
		Ratio:                       1.25 * ratio.MilliTokensUsd,
		CompletionRatio:             10 / 1.25,
		CachedInputRatio:            0.125 * ratio.MilliTokensUsd,
		ContextLength:               400000,
		MaxOutputTokens:             128000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           gpt5ReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5: reasoning flagship with 400K context and configurable effort.",
	},
	"gpt-5-2025-08-07": {
		Ratio:                       1.25 * ratio.MilliTokensUsd,
		CompletionRatio:             10 / 1.25,
		CachedInputRatio:            0.125 * ratio.MilliTokensUsd,
		ContextLength:               400000,
		MaxOutputTokens:             128000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           gpt5ReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5 snapshot from 2025-08-07.",
	},
	"gpt-5-mini": {
		Ratio:                       0.25 * ratio.MilliTokensUsd,
		CompletionRatio:             2 / 0.25,
		CachedInputRatio:            0.025 * ratio.MilliTokensUsd,
		ContextLength:               400000,
		MaxOutputTokens:             128000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           gpt5ReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5 mini: cost-efficient reasoning model.",
	},
	"gpt-5-mini-2025-08-07": {
		Ratio:                       0.25 * ratio.MilliTokensUsd,
		CompletionRatio:             2 / 0.25,
		CachedInputRatio:            0.025 * ratio.MilliTokensUsd,
		ContextLength:               400000,
		MaxOutputTokens:             128000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           gpt5ReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5 mini snapshot from 2025-08-07.",
	},
	"gpt-5-nano": {
		Ratio:                       0.05 * ratio.MilliTokensUsd,
		CompletionRatio:             0.4 / 0.05,
		CachedInputRatio:            0.005 * ratio.MilliTokensUsd,
		ContextLength:               400000,
		MaxOutputTokens:             128000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           gpt5ReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5 nano: ultra-low-cost reasoning tier.",
	},
	"gpt-5-nano-2025-08-07": {
		Ratio:                       0.05 * ratio.MilliTokensUsd,
		CompletionRatio:             0.4 / 0.05,
		CachedInputRatio:            0.005 * ratio.MilliTokensUsd,
		ContextLength:               400000,
		MaxOutputTokens:             128000,
		InputModalities:             []string{"text", "image"},
		OutputModalities:            []string{"text"},
		SupportedFeatures:           gpt5ReasoningFeatures,
		SupportedSamplingParameters: reasoningSamplingParameters(),
		Description:                 "GPT-5 nano snapshot from 2025-08-07.",
	},
}
