package siliconflow

import "github.com/Laisky/one-api/relay/adaptor"

// qwenModels returns the qwen model defaults for siliconflow.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func qwenModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"Qwen/Qwen2-0.5B-Instruct": {
			Ratio:                       nativeRate(0.9800000000000001),
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "frequency_penalty"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2-0.5B-Instruct",
			Description:                 "Alibaba Qwen2 0.5B Instruct ultra-compact chat model with 32K context.",
		},
		"Qwen/Qwen2-1.5B-Instruct": {
			Ratio:                       nativeRate(0.9800000000000001),
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "frequency_penalty"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2-1.5B-Instruct",
			Description:                 "Alibaba Qwen2 1.5B Instruct compact chat model with 32K context.",
		},
		"Qwen/Qwen2-72B-Instruct": {
			Ratio:                       nativeRate(3.9200000000000004),
			CompletionRatio:             1,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2-72B-Instruct",
			Description:                 "Alibaba Qwen2 72B Instruct dense chat model with 128K context and tool/JSON support.",
		},
		"Qwen/Qwen2-7B-Instruct": {
			Ratio:                       nativeRate(0.49000000000000005),
			CompletionRatio:             1,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2-7B-Instruct",
			Description:                 "Alibaba Qwen2 7B Instruct chat model with 128K context.",
		},
		"Qwen/Qwen3-235B-A22B-Instruct-2507": {
			Ratio:                       0.175,
			CompletionRatio:             4.057142857142857,
			ContextLength:               262144,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "Qwen/Qwen3-235B-A22B-Instruct-2507",
			Description:                 "Alibaba Qwen3 235B/A22B Instruct MoE chat model with 256K context on SiliconFlow. (RETIRED 2026-05-15)",
		},
		"Qwen/Qwen3-235B-A22B-Thinking-2507": {
			Ratio:                       0.175,
			CompletionRatio:             4.057142857142857,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			SupportedReasoningEfforts:   []string{"low", "medium", "high"},
			DefaultReasoningEffort:      "medium",
			Quantization:                "fp8",
			HuggingFaceID:               "Qwen/Qwen3-235B-A22B-Thinking-2507",
			Description:                 "Alibaba Qwen3 235B/A22B Thinking MoE reasoning model with 256K context on SiliconFlow.",
		},
		"Qwen/Qwen3.5-122B-A10B": {
			Ratio:           nativeRate(0.8),
			CompletionRatio: 8,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(2),
				CompletionRatio:     8,
				InputTokenThreshold: 128000,
			},
			},
			ContextLength:               262144,
			MaxOutputTokens:             262144,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "Qwen/Qwen3.5-122B-A10B",
			Description:                 "Qwen/Qwen3.5-122B-A10B on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3.5-27B": {
			Ratio:           nativeRate(0.6),
			CompletionRatio: 8,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1.8),
				CompletionRatio:     8,
				InputTokenThreshold: 128000,
			},
			},
			ContextLength:               262144,
			MaxOutputTokens:             262144,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "Qwen/Qwen3.5-27B",
			Description:                 "Qwen/Qwen3.5-27B on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3.5-35B-A3B": {
			Ratio:           nativeRate(0.4),
			CompletionRatio: 8,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1.6),
				CompletionRatio:     8,
				InputTokenThreshold: 128000,
			},
			},
			Description: "Qwen/Qwen3.5-35B-A3B on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3.5-9B": {
			Ratio:                       nativeRate(0.7000000000000001),
			CompletionRatio:             1.5,
			ContextLength:               262144,
			MaxOutputTokens:             262144,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "Qwen/Qwen3.5-9B",
			Description:                 "Alibaba Qwen3.5 9B compact chat model with 262K context on SiliconFlow.",
		},
		"Qwen/Qwen3.6-27B": {
			Ratio:                       nativeRate(3),
			CompletionRatio:             6,
			ContextLength:               262144,
			MaxOutputTokens:             262144,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			SupportedReasoningEfforts:   []string{"low", "medium", "high"},
			DefaultReasoningEffort:      "medium",
			Quantization:                "fp8",
			HuggingFaceID:               "Qwen/Qwen3.6-27B",
			Description:                 "Qwen/Qwen3.6-27B on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3.6-35B-A3B": {
			Ratio:                       nativeRate(1.8),
			CompletionRatio:             6,
			ContextLength:               262144,
			MaxOutputTokens:             262144,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			SupportedReasoningEfforts:   []string{"low", "medium", "high"},
			DefaultReasoningEffort:      "medium",
			Quantization:                "fp8",
			HuggingFaceID:               "Qwen/Qwen3.6-35B-A3B",
			Description:                 "Qwen/Qwen3.6-35B-A3B on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Qwen/Qwen3.8-27B": {
			Ratio:           nativeRate(3),
			CompletionRatio: 4,
			Description:     "Qwen/Qwen3.8-27B on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
