package siliconflow

import "github.com/Laisky/one-api/relay/adaptor"

// otherModels returns the other model defaults for siliconflow.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func otherModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"01-ai/Yi-1.5-6B-Chat": {
			Ratio:                       nativeRate(0.49000000000000005),
			CompletionRatio:             1,
			ContextLength:               4096,
			MaxOutputTokens:             4096,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "frequency_penalty"},
			Quantization:                "bf16",
			HuggingFaceID:               "01-ai/Yi-1.5-6B-Chat",
			Description:                 "01.AI Yi 1.5 6B chat model with 4K context.",
		},
		"01-ai/Yi-1.5-9B-Chat-16K": {
			Ratio:                       nativeRate(0.9800000000000001),
			CompletionRatio:             1,
			ContextLength:               16384,
			MaxOutputTokens:             4096,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "frequency_penalty"},
			Quantization:                "bf16",
			HuggingFaceID:               "01-ai/Yi-1.5-9B-Chat-16K",
			Description:                 "01.AI Yi 1.5 9B chat model with 16K context (long-context variant).",
		},
		"BAAI/bge-large-en-v1.5": {
			Ratio:           0,
			CompletionRatio: 1,
			Embedding:       &adaptor.EmbeddingPricingConfig{},
			ContextLength:   512,
			InputModalities: []string{"text"},
			HuggingFaceID:   "BAAI/bge-large-en-v1.5",
			Description:     "BAAI/bge-large-en-v1.5 on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"BAAI/bge-large-zh-v1.5": {
			Ratio:           0,
			CompletionRatio: 1,
			Embedding:       &adaptor.EmbeddingPricingConfig{},
			ContextLength:   512,
			InputModalities: []string{"text"},
			HuggingFaceID:   "BAAI/bge-large-zh-v1.5",
			Description:     "BAAI/bge-large-zh-v1.5 on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"BAAI/bge-m3": {
			Ratio:           0,
			CompletionRatio: 1,
			Embedding:       &adaptor.EmbeddingPricingConfig{},
			ContextLength:   8192,
			InputModalities: []string{"text"},
			HuggingFaceID:   "BAAI/bge-m3",
			Description:     "BAAI/bge-m3 on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"BAAI/bge-reranker-v2-m3": {
			Ratio:           0,
			CompletionRatio: 1,
			Description:     "BAAI/bge-reranker-v2-m3 on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"ByteDance-Seed/Seed-OSS-36B-Instruct": {
			Ratio:           nativeRate(1.5),
			CompletionRatio: 2.6666666666666665,
			Description:     "ByteDance-Seed/Seed-OSS-36B-Instruct on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"Bytedance/Z-Image-Turbo": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.005,
				DefaultSize:      "1024x1024",
				MinImages:        1,
				MaxImages:        1,
			},
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"image"},
			SupportedFeatures: []string{"gateway_siliconflow_image"},
			Description:       "Alibaba Tongyi Z-Image-Turbo text-to-image on SiliconFlow. The historical Bytedance gateway name redirects to Tongyi-MAI/Z-Image-Turbo.",
		},
		"FunAudioLLM/CosyVoice2-0.5B": {
			Ratio:           0,
			CompletionRatio: 0,
			Audio: &adaptor.AudioPricingConfig{
				InputPriceQuantity: 1e+06,
				InputUnit:          "utf8_bytes",
				InputPriceUsd:      7.15,
			},
			InputModalities:  []string{"text"},
			OutputModalities: []string{"audio"},
			HuggingFaceID:    "FunAudioLLM/CosyVoice2-0.5B",
			Description:      "Alibaba FunAudioLLM CosyVoice 2 0.5B multilingual TTS model on SiliconFlow.",
		},
		"MiniMaxAI/MiniMax-M2.5": {
			Ratio:                       nativeRate(2.1),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.21),
			ContextLength:               196608,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "MiniMaxAI/MiniMax-M2.5",
			Description:                 "MiniMax M2.5 long-context chat model with 197K context on SiliconFlow.",
		},
		"MiniMaxAI/MiniMax-M3": {
			Ratio:                       nativeRate(2.1),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.42),
			ContextLength:               1048576,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			HuggingFaceID:               "MiniMaxAI/MiniMax-M3",
			Description:                 "MiniMax M3 native multimodal flagship (text+image+video input, 1M context, 131K output, $0.30/$1.20 per 1M).",
		},
		"PaddlePaddle/PaddleOCR-VL-1.5": {
			Ratio:           0,
			CompletionRatio: 1,
			Description:     "PaddlePaddle/PaddleOCR-VL-1.5 on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"THUDM/GLM-4-32B-0414": {
			Ratio:           nativeRate(1.89),
			CompletionRatio: 1,
			Description:     "THUDM/GLM-4-32B-0414 on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"THUDM/chatglm3-6b": {
			Ratio:                       nativeRate(0.49000000000000005),
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             4096,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "frequency_penalty"},
			Quantization:                "bf16",
			HuggingFaceID:               "THUDM/chatglm3-6b",
			Description:                 "Zhipu THUDM ChatGLM3 6B legacy chat model with 8K context.",
		},
		"THUDM/glm-4-9b-chat": {
			Ratio:                       nativeRate(0.9800000000000001),
			CompletionRatio:             1,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "THUDM/glm-4-9b-chat",
			Description:                 "Zhipu THUDM GLM-4 9B chat model with 128K context and native tool calling.",
		},
		"Tongyi-MAI/Z-Image-Turbo": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.005,
				DefaultSize:      "1024x1024",
				MinImages:        1,
				MaxImages:        1,
			},
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"image"},
			SupportedFeatures: []string{"gateway_siliconflow_image"},
			Description:       "Alibaba Tongyi Z-Image-Turbo text-to-image on SiliconFlow. The historical Bytedance gateway name redirects to Tongyi-MAI/Z-Image-Turbo.",
		},
		"XingChenAGI/Xing4.0-29B": {
			Ratio:           0,
			CompletionRatio: 1,
			Description:     "XingChenAGI/Xing4.0-29B on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"black-forest-labs/FLUX-1.1-pro": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.04,
				DefaultSize:      "1024x1024",
				MinImages:        1,
				MaxImages:        1,
			},
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"image"},
			SupportedFeatures: []string{"gateway_siliconflow_image"},
			Description:       "FLUX 1.1 [pro] managed text-to-image generator on SiliconFlow.",
		},
		"black-forest-labs/FLUX.1-schnell": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.0014,
				DefaultSize:      "1024x1024",
				MinImages:        1,
				MaxImages:        1,
			},
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"image"},
			SupportedFeatures: []string{"gateway_siliconflow_image"},
			HuggingFaceID:     "black-forest-labs/FLUX.1-schnell",
			Description:       "FLUX.1 [schnell] 12B Apache-licensed text-to-image model on SiliconFlow.",
		},
		"black-forest-labs/FLUX.1.1-pro": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.04,
				DefaultSize:      "1024x1024",
				MinImages:        1,
				MaxImages:        1,
			},
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"image"},
			SupportedFeatures: []string{"gateway_siliconflow_image"},
			Description:       "FLUX 1.1 [pro] managed text-to-image generator on SiliconFlow.",
		},
		"black-forest-labs/FLUX.2-flex": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.06,
				DefaultSize:      "1024x1024",
				MinImages:        1,
				MaxImages:        1,
			},
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"image"},
			SupportedFeatures: []string{"gateway_siliconflow_image"},
			Description:       "FLUX.2 [flex] tunable-step text-to-image variant on SiliconFlow.",
		},
		"black-forest-labs/FLUX.2-pro": {
			Ratio:           0,
			CompletionRatio: 1,
			Image: &adaptor.ImagePricingConfig{
				PricePerImageUsd: 0.03,
				DefaultSize:      "512x512",
				MinImages:        1,
				MaxImages:        1,
			},
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"image"},
			SupportedFeatures: []string{"gateway_siliconflow_image"},
			Description:       "FLUX.2 [pro] high-resolution text-to-image and multi-reference editing on SiliconFlow.",
		},
		"deepseek-chat": {
			Ratio:                       nativeRate(0.9800000000000001),
			CompletionRatio:             1,
			ContextLength:               65536,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V2.5",
			Description:                 "SiliconFlow legacy alias for DeepSeek V2.5 chat (fp8, 64K context).",
		},
		"deepseek-coder": {
			Ratio:                       nativeRate(0.9800000000000001),
			CompletionRatio:             1,
			ContextLength:               65536,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "deepseek-ai/DeepSeek-Coder-V2-Instruct",
			Description:                 "SiliconFlow legacy alias for DeepSeek Coder V2 instruct (fp8, 64K context).",
		},
		"google/gemma-2-27b-it": {
			Ratio:                       nativeRate(1.9600000000000002),
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "google/gemma-2-27b-it",
			Description:                 "Google Gemma 2 27B instruction-tuned chat model with 8K context.",
		},
		"google/gemma-2-9b-it": {
			Ratio:                       nativeRate(0.9800000000000001),
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "google/gemma-2-9b-it",
			Description:                 "Google Gemma 2 9B instruction-tuned chat model with 8K context.",
		},
		"google/gemma-4-12B-it": {
			Ratio:                       nativeRate(0.7000000000000001),
			CompletionRatio:             3,
			ContextLength:               262144,
			MaxOutputTokens:             262144,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "google/gemma-4-12B-it",
			Description:                 "Google Gemma 4 12B instruction-tuned chat model with 262K context and native function-calling on SiliconFlow.",
		},
		"google/gemma-4-26b-a4b-it": {
			Ratio:                       nativeRate(0.84),
			CompletionRatio:             3.3333333333333335,
			ContextLength:               262144,
			MaxOutputTokens:             262144,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			SupportedReasoningEfforts:   []string{"low", "medium", "high"},
			DefaultReasoningEffort:      "medium",
			Quantization:                "fp8",
			HuggingFaceID:               "google/gemma-4-26b-a4b-it",
			Description:                 "Google Gemma 4 26B/4B-active MoE multimodal chat model with 256K context on SiliconFlow.",
		},
		"google/gemma-4-31b-it": {
			Ratio:                       nativeRate(0.91),
			CompletionRatio:             3.076923076923077,
			ContextLength:               262144,
			MaxOutputTokens:             262144,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			SupportedReasoningEfforts:   []string{"low", "medium", "high"},
			DefaultReasoningEffort:      "medium",
			Quantization:                "fp8",
			HuggingFaceID:               "google/gemma-4-31b-it",
			Description:                 "Google Gemma 4 31B dense multimodal chat model with 262K context on SiliconFlow.",
		},
		"inclusionAI/Ling-flash-2.0": {
			Ratio:           nativeRate(1),
			CompletionRatio: 4,
			Description:     "inclusionAI/Ling-flash-2.0 on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"inclusionAI/Ling-mini-2.0": {
			Ratio:           nativeRate(0.5),
			CompletionRatio: 4,
			Description:     "inclusionAI/Ling-mini-2.0 on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"internlm/internlm2_5-7b-chat": {
			Ratio:                       nativeRate(0.49000000000000005),
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "internlm/internlm2_5-7b-chat",
			Description:                 "Shanghai AI Lab InternLM 2.5 7B chat model with 32K context and tool support.",
		},
		"meituan-longcat/LongCat-2.0": {
			Ratio:            nativeRate(5),
			CompletionRatio:  4,
			CachedInputRatio: nativeRate(0.1),
			Description:      "meituan-longcat/LongCat-2.0 on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"meta-llama/Meta-Llama-3-70B-Instruct": {
			Ratio:                       nativeRate(3.9200000000000004),
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "meta-llama/Meta-Llama-3-70B-Instruct",
			Description:                 "Meta Llama 3 70B Instruct dense chat model with 8K context.",
		},
		"meta-llama/Meta-Llama-3-8B-Instruct": {
			Ratio:                       nativeRate(0.49000000000000005),
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "meta-llama/Meta-Llama-3-8B-Instruct",
			Description:                 "Meta Llama 3 8B Instruct chat model with 8K context.",
		},
		"meta-llama/Meta-Llama-3.1-405B-Instruct": {
			Ratio:                       1.4,
			CompletionRatio:             1,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "meta-llama/Meta-Llama-3.1-405B-Instruct",
			Description:                 "Meta Llama 3.1 405B Instruct flagship dense chat model with 128K context; served at fp8 by SiliconFlow.",
		},
		"meta-llama/Meta-Llama-3.1-70B-Instruct": {
			Ratio:                       nativeRate(3.9200000000000004),
			CompletionRatio:             1,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "meta-llama/Meta-Llama-3.1-70B-Instruct",
			Description:                 "Meta Llama 3.1 70B Instruct dense chat model with 128K context and tool support.",
		},
		"meta-llama/Meta-Llama-3.1-8B-Instruct": {
			Ratio:                       nativeRate(0.49000000000000005),
			CompletionRatio:             1,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "meta-llama/Meta-Llama-3.1-8B-Instruct",
			Description:                 "Meta Llama 3.1 8B Instruct chat model with 128K context and tool support.",
		},
		"mistralai/Mistral-7B-Instruct-v0.2": {
			Ratio:                       nativeRate(0.49000000000000005),
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "frequency_penalty"},
			Quantization:                "bf16",
			HuggingFaceID:               "mistralai/Mistral-7B-Instruct-v0.2",
			Description:                 "Mistral 7B Instruct v0.2 chat model with 32K context (legacy build, no native tool calling).",
		},
		"mistralai/Mixtral-8x7B-Instruct-v0.1": {
			Ratio:                       nativeRate(3.9200000000000004),
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "mistralai/Mixtral-8x7B-Instruct-v0.1",
			Description:                 "Mistral Mixtral 8x7B Instruct v0.1 sparse MoE chat model with 32K context.",
		},
		"openai/gpt-oss-120b": {
			Ratio:                       nativeRate(0.35000000000000003),
			CompletionRatio:             9,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Description:                 "OpenAI GPT-OSS 120B reasoning MoE model hosted on SiliconFlow (131K ctx, $0.05/$0.45 per 1M).",
		},
		"openai/gpt-oss-20b": {
			Ratio:                       nativeRate(0.28),
			CompletionRatio:             4.5,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Description:                 "OpenAI GPT-OSS 20B reasoning model hosted on SiliconFlow (131K ctx, $0.04/$0.18 per 1M).",
		},
		"stepfun-ai/Step-3.5-Flash": {
			Ratio:           nativeRate(0.7),
			CompletionRatio: 3.0000000000000004,
			Description:     "stepfun-ai/Step-3.5-Flash on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"tencent/Hunyuan-A13B-Instruct": {
			Ratio:           nativeRate(1),
			CompletionRatio: 4,
			TimeWindows: []adaptor.TimeWindow{adaptor.TimeWindow{
				Name:     "siliconflow-daypart",
				TimeZone: "Asia/Shanghai",
				Ranges: []adaptor.ClockRange{adaptor.ClockRange{
					Start: "09:00",
					End:   "18:00",
				},
				},
				Overlay: adaptor.ModelConfig{
					Ratio:           nativeRate(1),
					CompletionRatio: 4,
				},
			},
				adaptor.TimeWindow{
					Name:     "siliconflow-daypart",
					TimeZone: "Asia/Shanghai",
					Ranges: []adaptor.ClockRange{adaptor.ClockRange{
						Start: "00:00",
						End:   "09:00",
					},
						adaptor.ClockRange{
							Start: "18:00",
							End:   "00:00",
						},
					},
					Overlay: adaptor.ModelConfig{
						Ratio:           nativeRate(0.8),
						CompletionRatio: 4,
					},
				},
			},
			ContextLength:               131072,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "tencent/Hunyuan-A13B-Instruct",
			Description:                 "tencent/Hunyuan-A13B-Instruct on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"tencent/Hunyuan-MT-7B": {
			Ratio:           0,
			CompletionRatio: 1,
			Description:     "tencent/Hunyuan-MT-7B on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"tencent/Hy3-preview": {
			Ratio:                       nativeRate(0.462),
			CompletionRatio:             3.9393939393939394,
			CachedInputRatio:            nativeRate(0.203),
			ContextLength:               262144,
			MaxOutputTokens:             262144,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Description:                 "Tencent Hunyuan 3 Preview (hy3-preview) MoE flagship, 262K context, $0.066/$0.26 per 1M.",
		},
		"tencent/Hy4-preview": {
			Ratio:            nativeRate(6),
			CompletionRatio:  3,
			CachedInputRatio: nativeRate(0.3),
			Description:      "tencent/Hy4-preview on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
