package siliconflow

import "github.com/Laisky/one-api/relay/adaptor"

// deepseek_aiModels returns the deepseek_ai model defaults for siliconflow.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func deepseek_aiModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"deepseek-ai/DeepSeek-V3.1": {
			Ratio:                       nativeRate(1.8900000000000001),
			CompletionRatio:             3.7037037037037037,
			ContextLength:               163840,
			MaxOutputTokens:             163840,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			HuggingFaceID:               "deepseek-ai/DeepSeek-V3.1",
			Description:                 "DeepSeek V3.1 reasoning model hosted on SiliconFlow (164K ctx, $0.27/$1.00 per 1M).",
		},
		"deepseek-ai/DeepSeek-V3.1-Terminus": {
			Ratio:                       nativeRate(4),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.4),
			ContextLength:               163840,
			MaxOutputTokens:             163840,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			HuggingFaceID:               "deepseek-ai/DeepSeek-V3.1-Terminus",
			Description:                 "deepseek-ai/DeepSeek-V3.1-Terminus on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek-ai/DeepSeek-V3.2": {
			Ratio:                       nativeRate(4),
			CompletionRatio:             1.5,
			CachedInputRatio:            nativeRate(0.4),
			ContextLength:               163840,
			MaxOutputTokens:             163840,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			SupportedReasoningEfforts:   []string{"low", "medium", "high"},
			DefaultReasoningEffort:      "medium",
			Quantization:                "fp8",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V3.2",
			Description:                 "deepseek-ai/DeepSeek-V3.2 on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek-ai/DeepSeek-V3.2-Exp": {
			Ratio:                       nativeRate(1.8900000000000001),
			CompletionRatio:             1.5185185185185186,
			ContextLength:               163840,
			MaxOutputTokens:             163840,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			SupportedReasoningEfforts:   []string{"low", "medium", "high"},
			DefaultReasoningEffort:      "medium",
			Quantization:                "fp8",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V3.2-Exp",
			Description:                 "DeepSeek V3.2 Exp sparse-attention hybrid reasoning + chat MoE model on SiliconFlow.",
		},
		"deepseek-ai/DeepSeek-V4-Flash": {
			Ratio:            nativeRate(1.5),
			CompletionRatio:  3,
			CachedInputRatio: nativeRate(0.15),
			TimeWindows: []adaptor.TimeWindow{adaptor.TimeWindow{
				Name:     "siliconflow-daypart",
				TimeZone: "Asia/Shanghai",
				Ranges: []adaptor.ClockRange{adaptor.ClockRange{
					Start: "02:00",
					End:   "08:00",
				},
				},
				Overlay: adaptor.ModelConfig{
					Ratio:            nativeRate(1.5),
					CompletionRatio:  3,
					CachedInputRatio: nativeRate(0.15),
				},
			},
				adaptor.TimeWindow{
					Name:     "siliconflow-daypart",
					TimeZone: "Asia/Shanghai",
					Ranges: []adaptor.ClockRange{adaptor.ClockRange{
						Start: "00:00",
						End:   "02:00",
					},
						adaptor.ClockRange{
							Start: "08:00",
							End:   "00:00",
						},
					},
					Overlay: adaptor.ModelConfig{
						Ratio:            nativeRate(3),
						CompletionRatio:  3,
						CachedInputRatio: nativeRate(0.3),
					},
				},
			},
			ContextLength:               1048576,
			MaxOutputTokens:             393216,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			SupportedReasoningEfforts:   []string{"low", "medium", "high"},
			DefaultReasoningEffort:      "medium",
			Quantization:                "fp8",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V4-Flash",
			Description:                 "deepseek-ai/DeepSeek-V4-Flash on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek-ai/DeepSeek-V4-Pro": {
			Ratio:                       nativeRate(12),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(1),
			ContextLength:               1048576,
			MaxOutputTokens:             393216,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			SupportedReasoningEfforts:   []string{"low", "medium", "high"},
			DefaultReasoningEffort:      "medium",
			Quantization:                "fp8",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V4-Pro",
			Description:                 "deepseek-ai/DeepSeek-V4-Pro on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
