package siliconflow

import "github.com/Laisky/one-api/relay/adaptor"

// moonshotaiModels returns the moonshotai model defaults for siliconflow.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func moonshotaiModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"moonshotai/Kimi-K2-Instruct-0905": {
			Ratio:                       nativeRate(2.8000000000000003),
			CompletionRatio:             5,
			ContextLength:               262144,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "moonshotai/Kimi-K2-Instruct-0905",
			Description:                 "Moonshot Kimi K2 Instruct (0905 refresh) long-context MoE chat model with 256K context on SiliconFlow. (RETIRED 2026-05-15)",
		},
		"moonshotai/Kimi-K2-Thinking": {
			Ratio:                       nativeRate(3.8500000000000005),
			CompletionRatio:             4.545454545454546,
			ContextLength:               262144,
			MaxOutputTokens:             262144,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			SupportedReasoningEfforts:   []string{"low", "medium", "high"},
			DefaultReasoningEffort:      "medium",
			Quantization:                "fp8",
			HuggingFaceID:               "moonshotai/Kimi-K2-Thinking",
			Description:                 "Moonshot Kimi K2 Thinking reasoning MoE model with 262K context on SiliconFlow.",
		},
		"moonshotai/Kimi-K2.5": {
			Ratio:                       nativeRate(3.1500000000000004),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.49000000000000005),
			ContextLength:               262144,
			MaxOutputTokens:             262144,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			SupportedReasoningEfforts:   []string{"low", "medium", "high"},
			DefaultReasoningEffort:      "medium",
			Quantization:                "fp8",
			HuggingFaceID:               "moonshotai/Kimi-K2.5",
			Description:                 "Moonshot Kimi K2.5 native multimodal MoE (1T/32B) agentic model with 256K context and switchable thinking modes on SiliconFlow.",
		},
		"moonshotai/Kimi-K2.6": {
			Ratio:                       nativeRate(5.390000000000001),
			CompletionRatio:             5.194805194805195,
			CachedInputRatio:            nativeRate(1.4000000000000001),
			ContextLength:               262144,
			MaxOutputTokens:             262144,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			SupportedReasoningEfforts:   []string{"low", "medium", "high"},
			DefaultReasoningEffort:      "medium",
			Quantization:                "fp8",
			HuggingFaceID:               "moonshotai/Kimi-K2.6",
			Description:                 "Moonshot Kimi K2.6 frontier-scale multimodal MoE agentic model with 256K context on SiliconFlow.",
		},
		"moonshotai/Kimi-K2.7-Code": {
			Ratio:                       nativeRate(6.5),
			CompletionRatio:             4.153846153846154,
			CachedInputRatio:            nativeRate(1.3),
			ContextLength:               262144,
			MaxOutputTokens:             262144,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "moonshotai/Kimi-K2.7-Code",
			Description:                 "moonshotai/Kimi-K2.7-Code on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"moonshotai/Kimi-K3": {
			Ratio:                       nativeRate(21),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(2.1),
			ContextLength:               1048576,
			MaxOutputTokens:             1048576,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"max_tokens", "stop"},
			Quantization:                "fp8",
			Description:                 "Moonshot Kimi K3 flagship (2.8T MoE) with 1M context, native visual understanding and always-on thinking on SiliconFlow.",
		},
	}
}
