package siliconflow

import "github.com/Laisky/one-api/relay/adaptor"

// zai_orgModels returns the zai_org model defaults for siliconflow.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func zai_orgModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"zai-org/GLM-4.5-Air": {
			Ratio:                       nativeRate(1),
			CompletionRatio:             6,
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			HuggingFaceID:               "zai-org/GLM-4.5-Air",
			Description:                 "zai-org/GLM-4.5-Air on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"zai-org/GLM-4.5V": {
			Ratio:           nativeRate(1),
			CompletionRatio: 6,
			Description:     "zai-org/GLM-4.5V on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"zai-org/GLM-4.6": {
			Ratio:                       nativeRate(2.7300000000000004),
			CompletionRatio:             4.871794871794871,
			ContextLength:               204800,
			MaxOutputTokens:             204800,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "zai-org/GLM-4.6",
			Description:                 "Zhipu GLM-4.6 chat model with 205K context on SiliconFlow. (RETIRED 2026-05-15)",
		},
		"zai-org/GLM-4.7": {
			Ratio:                       nativeRate(2.94),
			CompletionRatio:             5.238095238095238,
			CachedInputRatio:            nativeRate(0.77),
			ContextLength:               204800,
			MaxOutputTokens:             204800,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "zai-org/GLM-4.7",
			Description:                 "Zhipu GLM-4.7 chat model with native tool calling and 205K context on SiliconFlow.",
		},
		"zai-org/GLM-5": {
			Ratio:                       nativeRate(6.65),
			CompletionRatio:             2.6842105263157894,
			CachedInputRatio:            nativeRate(1.4000000000000001),
			ContextLength:               204800,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			SupportedReasoningEfforts:   []string{"low", "medium", "high"},
			DefaultReasoningEffort:      "medium",
			Quantization:                "fp8",
			HuggingFaceID:               "zai-org/GLM-5",
			Description:                 "Zhipu GLM-5 next-gen sparse MoE (750B/40B) with DeepSeek Sparse Attention for agentic and long-horizon tasks on SiliconFlow.",
		},
		"zai-org/GLM-5.1": {
			Ratio:                       nativeRate(8.33),
			CompletionRatio:             3.142857142857143,
			CachedInputRatio:            nativeRate(4.2),
			ContextLength:               204800,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			SupportedReasoningEfforts:   []string{"low", "medium", "high"},
			DefaultReasoningEffort:      "medium",
			Quantization:                "fp8",
			HuggingFaceID:               "zai-org/GLM-5.1",
			Description:                 "Zhipu GLM-5.1 flagship reasoning + agentic model with 205K context on SiliconFlow.",
		},
		"zai-org/GLM-5.2": {
			Ratio:                       nativeRate(8),
			CompletionRatio:             3.5,
			CachedInputRatio:            nativeRate(2),
			ContextLength:               1048576,
			MaxOutputTokens:             262144,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			SupportedReasoningEfforts:   []string{"low", "medium", "high"},
			DefaultReasoningEffort:      "medium",
			Quantization:                "fp8",
			HuggingFaceID:               "zai-org/GLM-5.2",
			Description:                 "zai-org/GLM-5.2 on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"zai-org/GLM-5.3": {
			Ratio:            nativeRate(8),
			CompletionRatio:  3.5,
			CachedInputRatio: nativeRate(2),
			Description:      "zai-org/GLM-5.3 on siliconflow; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"zai-org/GLM-5V-Turbo": {
			Ratio:                       nativeRate(8.4),
			CompletionRatio:             3.3333333333333335,
			CachedInputRatio:            nativeRate(1.68),
			ContextLength:               204800,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "seed", "response_format", "tools", "tool_choice"},
			HuggingFaceID:               "zai-org/GLM-5V-Turbo",
			Description:                 "Zhipu GLM-5V-Turbo native multimodal vision model (205K ctx, $1.20/$4.00 per 1M).",
		},
	}
}
