package novita

import (
	"github.com/Laisky/one-api/relay/adaptor"
	"github.com/Laisky/one-api/relay/billing/ratio"
)

// ModelRatios contains Novita serverless models with explicit token pricing from the public pricing page.
// Model list is derived from the keys of this map, eliminating redundancy.
// Source: https://novita.ai/pricing (retrieved 2026-04-28)
// Tiered or omnimodal rows without explicit token pricing on the public page are intentionally excluded.
var ModelRatios = map[string]adaptor.ModelConfig{
	"baidu/ernie-4.5-21B-a3b":                           {Ratio: 0.07 * ratio.MilliTokensUsd, CompletionRatio: 4},
	"baidu/ernie-4.5-21B-a3b-thinking":                  {Ratio: 0.07 * ratio.MilliTokensUsd, CompletionRatio: 4},
	"baidu/ernie-4.5-300b-a47b-paddle":                  {Ratio: 0.28 * ratio.MilliTokensUsd, CompletionRatio: 3.92857142857},
	"baidu/ernie-4.5-vl-28b-a3b":                        {Ratio: 0.14 * ratio.MilliTokensUsd, CompletionRatio: 4},
	"baidu/ernie-4.5-vl-28b-a3b-thinking":               {Ratio: 0.39 * ratio.MilliTokensUsd, CompletionRatio: 1},
	"baidu/ernie-4.5-vl-424b-a47b":                      {Ratio: 0.42 * ratio.MilliTokensUsd, CompletionRatio: 2.97619047619},
	"deepseek/deepseek-ocr-2":                           {Ratio: 0.03 * ratio.MilliTokensUsd, CompletionRatio: 1},
	"deepseek/deepseek-prover-v2-671b":                  {Ratio: 0.7 * ratio.MilliTokensUsd, CompletionRatio: 3.57142857143},
	"deepseek/deepseek-r1-0528":                         {Ratio: 0.7 * ratio.MilliTokensUsd, CompletionRatio: 3.57142857143, CachedInputRatio: 0.35 * ratio.MilliTokensUsd},
	"deepseek/deepseek-r1-distill-llama-70b":            {Ratio: 0.8 * ratio.MilliTokensUsd, CompletionRatio: 1},
	"deepseek/deepseek-r1-turbo":                        {Ratio: 0.7 * ratio.MilliTokensUsd, CompletionRatio: 3.57142857143},
	"deepseek/deepseek-v3-0324":                         {Ratio: 0.27 * ratio.MilliTokensUsd, CompletionRatio: 4.14814814815, CachedInputRatio: 0.135 * ratio.MilliTokensUsd},
	"deepseek/deepseek-v3.1":                            {Ratio: 0.27 * ratio.MilliTokensUsd, CompletionRatio: 3.7037037037, CachedInputRatio: 0.135 * ratio.MilliTokensUsd},
	"deepseek/deepseek-v3.1-terminus":                   {Ratio: 0.27 * ratio.MilliTokensUsd, CompletionRatio: 3.7037037037, CachedInputRatio: 0.135 * ratio.MilliTokensUsd},
	"deepseek/deepseek-v3.2-exp":                        {Ratio: 0.27 * ratio.MilliTokensUsd, CompletionRatio: 1.51851851852},
	"deepseek/deepseek-v3.2":                            {Ratio: 0.269 * ratio.MilliTokensUsd, CompletionRatio: 1.48698884758, CachedInputRatio: 0.1345 * ratio.MilliTokensUsd},
	"deepseek/deepseek-v3-turbo":                        {Ratio: 0.4 * ratio.MilliTokensUsd, CompletionRatio: 3.25},
	"deepseek/deepseek-v4-flash":                        {Ratio: 0.14 * ratio.MilliTokensUsd, CompletionRatio: 2, CachedInputRatio: 0.028 * ratio.MilliTokensUsd},
	"deepseek/deepseek-v4-pro":                          {Ratio: 1.74 * ratio.MilliTokensUsd, CompletionRatio: 2, CachedInputRatio: 0.145 * ratio.MilliTokensUsd},
	"elephant":                                          {Ratio: 0.1 * ratio.MilliTokensUsd, CompletionRatio: 3, CachedInputRatio: 0.02 * ratio.MilliTokensUsd},
	"google/gemma-3-27b-it":                             {Ratio: 0.119 * ratio.MilliTokensUsd, CompletionRatio: 1.68067226891},
	"google/gemma-4-26b-a4b-it":                         {Ratio: 0.13 * ratio.MilliTokensUsd, CompletionRatio: 3.07692307692},
	"google/gemma-4-31b-it":                             {Ratio: 0.14 * ratio.MilliTokensUsd, CompletionRatio: 2.85714285714},
	"inclusionai/ling-2.6-flash":                        {Ratio: 0.1 * ratio.MilliTokensUsd, CompletionRatio: 3, CachedInputRatio: 0.02 * ratio.MilliTokensUsd},
	"kwaipilot/kat-coder-pro":                           {Ratio: 0.3 * ratio.MilliTokensUsd, CompletionRatio: 4, CachedInputRatio: 0.06 * ratio.MilliTokensUsd},
	"meta-llama/llama-3.1-8b-instruct":                  {Ratio: 0.02 * ratio.MilliTokensUsd, CompletionRatio: 2.5},
	"meta-llama/llama-3.3-70b-instruct":                 {Ratio: 0.135 * ratio.MilliTokensUsd, CompletionRatio: 2.96296296296},
	"meta-llama/llama-3-70b-instruct":                   {Ratio: 0.51 * ratio.MilliTokensUsd, CompletionRatio: 1.45098039216},
	"meta-llama/llama-3-8b-instruct":                    {Ratio: 0.04 * ratio.MilliTokensUsd, CompletionRatio: 1},
	"meta-llama/llama-4-maverick-17b-128e-instruct-fp8": {Ratio: 0.27 * ratio.MilliTokensUsd, CompletionRatio: 3.14814814815},
	"meta-llama/llama-4-scout-17b-16e-instruct":         {Ratio: 0.18 * ratio.MilliTokensUsd, CompletionRatio: 3.27777777778},
	"microsoft/wizardlm-2-8x22b":                        {Ratio: 0.62 * ratio.MilliTokensUsd, CompletionRatio: 1},
	"minimax/minimax-m2.1":                              {Ratio: 0.3 * ratio.MilliTokensUsd, CompletionRatio: 4, CachedInputRatio: 0.03 * ratio.MilliTokensUsd},
	"minimax/minimax-m2.5-highspeed":                    {Ratio: 0.6 * ratio.MilliTokensUsd, CompletionRatio: 4, CachedInputRatio: 0.03 * ratio.MilliTokensUsd},
	"minimax/minimax-m2.5":                              {Ratio: 0.3 * ratio.MilliTokensUsd, CompletionRatio: 4, CachedInputRatio: 0.03 * ratio.MilliTokensUsd},
	"minimax/minimax-m2.7":                              {Ratio: 0.3 * ratio.MilliTokensUsd, CompletionRatio: 4, CachedInputRatio: 0.06 * ratio.MilliTokensUsd},
	"minimax/minimax-m2":                                {Ratio: 0.3 * ratio.MilliTokensUsd, CompletionRatio: 4, CachedInputRatio: 0.03 * ratio.MilliTokensUsd},
	"minimaxai/minimax-m1-80k":                          {Ratio: 0.55 * ratio.MilliTokensUsd, CompletionRatio: 4},
	"mistralai/mistral-nemo":                            {Ratio: 0.04 * ratio.MilliTokensUsd, CompletionRatio: 4.25},
	"moonshotai/kimi-k2-0905":                           {Ratio: 0.6 * ratio.MilliTokensUsd, CompletionRatio: 4.16666666667},
	"moonshotai/kimi-k2-instruct":                       {Ratio: 0.57 * ratio.MilliTokensUsd, CompletionRatio: 4.0350877193},
	"moonshotai/kimi-k2-thinking":                       {Ratio: 0.6 * ratio.MilliTokensUsd, CompletionRatio: 4.16666666667, CachedInputRatio: 0.15 * ratio.MilliTokensUsd},
	"moonshotai/kimi-k2.5":                              {Ratio: 0.6 * ratio.MilliTokensUsd, CompletionRatio: 5, CachedInputRatio: 0.1 * ratio.MilliTokensUsd},
	"moonshotai/kimi-k2.6":                              {Ratio: 0.95 * ratio.MilliTokensUsd, CompletionRatio: 4.21052631579, CachedInputRatio: 0.16 * ratio.MilliTokensUsd},
	"nousresearch/hermes-2-pro-llama-3-8b":              {Ratio: 0.14 * ratio.MilliTokensUsd, CompletionRatio: 1},
	"openai/gpt-oss-120b":                               {Ratio: 0.05 * ratio.MilliTokensUsd, CompletionRatio: 5},
	"openai/gpt-oss-20b":                                {Ratio: 0.04 * ratio.MilliTokensUsd, CompletionRatio: 3.75},
	"qwen/qwen-2.5-72b-instruct":                        {Ratio: 0.38 * ratio.MilliTokensUsd, CompletionRatio: 1.05263157895},
	"qwen/qwen2.5-7b-instruct":                          {Ratio: 0.07 * ratio.MilliTokensUsd, CompletionRatio: 1},
	"qwen/qwen2.5-vl-72b-instruct":                      {Ratio: 0.8 * ratio.MilliTokensUsd, CompletionRatio: 1},
	"qwen/qwen3-235b-a22b-fp8":                          {Ratio: 0.2 * ratio.MilliTokensUsd, CompletionRatio: 4},
	"qwen/qwen3-235b-a22b-instruct-2507":                {Ratio: 0.09 * ratio.MilliTokensUsd, CompletionRatio: 6.44444444444},
	"qwen/qwen3-235b-a22b-thinking-2507":                {Ratio: 0.3 * ratio.MilliTokensUsd, CompletionRatio: 10},
	"qwen/qwen3-30b-a3b-fp8":                            {Ratio: 0.09 * ratio.MilliTokensUsd, CompletionRatio: 5},
	"qwen/qwen3-32b-fp8":                                {Ratio: 0.1 * ratio.MilliTokensUsd, CompletionRatio: 4.5},
	"qwen/qwen3-4b-fp8":                                 {Ratio: 0.03 * ratio.MilliTokensUsd, CompletionRatio: 1},
	"qwen/qwen3-coder-30b-a3b-instruct":                 {Ratio: 0.07 * ratio.MilliTokensUsd, CompletionRatio: 3.85714285714},
	"qwen/qwen3-coder-480b-a35b-instruct":               {Ratio: 0.3 * ratio.MilliTokensUsd, CompletionRatio: 4.33333333333},
	"qwen/qwen3-coder-next":                             {Ratio: 0.2 * ratio.MilliTokensUsd, CompletionRatio: 7.5},
	"qwen/qwen3-next-80b-a3b-instruct":                  {Ratio: 0.15 * ratio.MilliTokensUsd, CompletionRatio: 10},
	"qwen/qwen3-next-80b-a3b-thinking":                  {Ratio: 0.15 * ratio.MilliTokensUsd, CompletionRatio: 10},
	"qwen/qwen3-vl-235b-a22b-instruct":                  {Ratio: 0.3 * ratio.MilliTokensUsd, CompletionRatio: 5},
	"qwen/qwen3-vl-235b-a22b-thinking":                  {Ratio: 0.98 * ratio.MilliTokensUsd, CompletionRatio: 4.0306122449},
	"qwen/qwen3-vl-30b-a3b-instruct":                    {Ratio: 0.2 * ratio.MilliTokensUsd, CompletionRatio: 3.5},
	"qwen/qwen3-vl-30b-a3b-thinking":                    {Ratio: 0.2 * ratio.MilliTokensUsd, CompletionRatio: 5},
	"qwen/qwen3-vl-8b-instruct":                         {Ratio: 0.08 * ratio.MilliTokensUsd, CompletionRatio: 6.25},
	"qwen/qwen-mt-plus":                                 {Ratio: 0.25 * ratio.MilliTokensUsd, CompletionRatio: 3},
	"qwen/qwen3.5-122b-a10b":                            {Ratio: 0.4 * ratio.MilliTokensUsd, CompletionRatio: 8},
	"qwen/qwen3.5-27b":                                  {Ratio: 0.3 * ratio.MilliTokensUsd, CompletionRatio: 8},
	"qwen/qwen3.5-35b-a3b":                              {Ratio: 0.25 * ratio.MilliTokensUsd, CompletionRatio: 8},
	"qwen/qwen3.5-397b-a17b":                            {Ratio: 0.6 * ratio.MilliTokensUsd, CompletionRatio: 6},
	"Sao10K/L3-8B-Stheno-v3.2":                          {Ratio: 0.05 * ratio.MilliTokensUsd, CompletionRatio: 1},
	"sao10k/l31-70b-euryale-v2.2":                       {Ratio: 1.48 * ratio.MilliTokensUsd, CompletionRatio: 1},
	"sao10k/l3-8b-lunaris":                              {Ratio: 0.05 * ratio.MilliTokensUsd, CompletionRatio: 1},
	"xiaomimimo/mimo-v2-flash":                          {Ratio: 0.1 * ratio.MilliTokensUsd, CompletionRatio: 3, CachedInputRatio: 0.02 * ratio.MilliTokensUsd},
	"zai-org/autoglm-phone-9b-multilingual":             {Ratio: 0.035 * ratio.MilliTokensUsd, CompletionRatio: 3.94285714286},
	"zai-org/glm-4.5-air":                               {Ratio: 0.13 * ratio.MilliTokensUsd, CompletionRatio: 6.53846153846, CachedInputRatio: 0.025 * ratio.MilliTokensUsd},
	"zai-org/glm-4.5":                                   {Ratio: 0.6 * ratio.MilliTokensUsd, CompletionRatio: 3.66666666667, CachedInputRatio: 0.11 * ratio.MilliTokensUsd},
	"zai-org/glm-4.5v":                                  {Ratio: 0.6 * ratio.MilliTokensUsd, CompletionRatio: 3, CachedInputRatio: 0.11 * ratio.MilliTokensUsd},
	"zai-org/glm-4.6":                                   {Ratio: 0.55 * ratio.MilliTokensUsd, CompletionRatio: 4, CachedInputRatio: 0.11 * ratio.MilliTokensUsd},
	"zai-org/glm-4.6v":                                  {Ratio: 0.3 * ratio.MilliTokensUsd, CompletionRatio: 3, CachedInputRatio: 0.055 * ratio.MilliTokensUsd},
	"zai-org/glm-4.7-flash":                             {Ratio: 0.07 * ratio.MilliTokensUsd, CompletionRatio: 5.71428571429, CachedInputRatio: 0.01 * ratio.MilliTokensUsd},
	"zai-org/glm-4.7":                                   {Ratio: 0.6 * ratio.MilliTokensUsd, CompletionRatio: 3.66666666667, CachedInputRatio: 0.11 * ratio.MilliTokensUsd},
	"zai-org/glm-5.1":                                   {Ratio: 1.4 * ratio.MilliTokensUsd, CompletionRatio: 3.14285714286, CachedInputRatio: 0.26 * ratio.MilliTokensUsd},
	"zai-org/glm-5":                                     {Ratio: 1 * ratio.MilliTokensUsd, CompletionRatio: 3.2, CachedInputRatio: 0.2 * ratio.MilliTokensUsd},
}

// ModelList derived from ModelRatios for backward compatibility
var ModelList = adaptor.GetModelListFromPricing(ModelRatios)

// NovitaToolingDefaults notes that Novita's public pricing focuses on model tokens; no tool metering is published (retrieved 2026-04-28).
// Source: https://novita.ai/pricing
var NovitaToolingDefaults = adaptor.ChannelToolConfig{}
