package novita

import (
	"github.com/Laisky/one-api/relay/adaptor"
	"github.com/Laisky/one-api/relay/billing/ratio"
)

// miscModelRatios contains lower-volume Novita model families: Inclusion AI Ling,
// KwaiPilot, Microsoft, MiniMax, Mistral, MoonshotAI Kimi, NousResearch, OpenAI
// GPT-OSS, Sao10K Llama fine-tunes, Xiaomi MiMo, plus the Novita-internal
// "elephant" alias. MiniMax M-series weights are not released, so HuggingFaceID
// is intentionally left empty for those rows.
// Source: https://novita.ai/llm-api  (retrieved 2026-04-28)
var miscModelRatios = map[string]adaptor.ModelConfig{
	// Internal/branded alias without a HuggingFace card. Capability set follows
	// Novita's documented OpenAI-compatible chat surface.
	"elephant": {
		Ratio:                       0.1 * ratio.MilliTokensUsd,
		CompletionRatio:             3,
		CachedInputRatio:            0.02 * ratio.MilliTokensUsd,
		ContextLength:               262144,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Description:                 "Novita-branded chat alias (parameters tracked via Novita pricing page).",
	},

	// Inclusion AI Ling — open-weight efficient MoE chat model.
	"inclusionai/ling-2.6-flash": {
		Ratio:                       0.1 * ratio.MilliTokensUsd,
		CompletionRatio:             3,
		CachedInputRatio:            0.02 * ratio.MilliTokensUsd,
		ContextLength:               262144,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "inclusionAI/Ling-flash-2.0",
		Description:                 "Inclusion AI Ling 2.6 Flash MoE chat model with 256K context.",
	},

	// KwaiPilot KAT-Coder Pro — coding-focused chat model.
	"kwaipilot/kat-coder-pro": {
		Ratio:                       0.3 * ratio.MilliTokensUsd,
		CompletionRatio:             4,
		CachedInputRatio:            0.06 * ratio.MilliTokensUsd,
		ContextLength:               256000,
		MaxOutputTokens:             128000,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Kwaipilot/KAT-Coder-Pro-V1",
		Description:                 "KwaiPilot KAT-Coder Pro coding chat model with 256K context.",
	},

	// Microsoft WizardLM — Mixtral 8x22B fine-tune. Treated as text-only chat.
	"microsoft/wizardlm-2-8x22b": {
		Ratio:                       0.62 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               65535,
		MaxOutputTokens:             8000,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "microsoft/WizardLM-2-8x22B",
		Description:                 "Microsoft WizardLM 2 8x22B Mixtral fine-tune with 64K context.",
	},

	// MiniMax M-series — closed-source style chat aliases hosted by Novita. The
	// upstream weights are not released, so HuggingFaceID is intentionally omitted.
	"minimax/minimax-m2.1": {
		Ratio:                       0.3 * ratio.MilliTokensUsd,
		CompletionRatio:             4,
		CachedInputRatio:            0.03 * ratio.MilliTokensUsd,
		ContextLength:               204800,
		MaxOutputTokens:             131072,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Description:                 "MiniMax M2.1 chat model with 200K context.",
	},
	"minimax/minimax-m2.5-highspeed": {
		Ratio:                       0.6 * ratio.MilliTokensUsd,
		CompletionRatio:             4,
		CachedInputRatio:            0.03 * ratio.MilliTokensUsd,
		ContextLength:               204800,
		MaxOutputTokens:             131100,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Description:                 "Throughput-optimised MiniMax M2.5 with 200K context.",
	},
	"minimax/minimax-m2.5": {
		Ratio:                       0.3 * ratio.MilliTokensUsd,
		CompletionRatio:             4,
		CachedInputRatio:            0.03 * ratio.MilliTokensUsd,
		ContextLength:               204800,
		MaxOutputTokens:             131100,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Description:                 "MiniMax M2.5 chat model with 200K context.",
	},
	"minimax/minimax-m2.7": {
		Ratio:                       0.3 * ratio.MilliTokensUsd,
		CompletionRatio:             4,
		CachedInputRatio:            0.06 * ratio.MilliTokensUsd,
		ContextLength:               204800,
		MaxOutputTokens:             131072,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Description:                 "MiniMax M2.7 chat model with 200K context.",
	},
	"minimax/minimax-m2": {
		Ratio:                       0.3 * ratio.MilliTokensUsd,
		CompletionRatio:             4,
		CachedInputRatio:            0.03 * ratio.MilliTokensUsd,
		ContextLength:               204800,
		MaxOutputTokens:             131072,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Description:                 "MiniMax M2 chat model with 200K context.",
	},
	"minimaxai/minimax-m1-80k": {
		Ratio:                       0.55 * ratio.MilliTokensUsd,
		CompletionRatio:             4,
		ContextLength:               1000000,
		MaxOutputTokens:             40000,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		HuggingFaceID:               "MiniMaxAI/MiniMax-M1-80k",
		Description:                 "MiniMax M1 80K open-weight chat model with 1M context.",
	},

	// Mistral Nemo — open-weight 12B chat model.
	"mistralai/mistral-nemo": {
		Ratio:                       0.04 * ratio.MilliTokensUsd,
		CompletionRatio:             4.25,
		ContextLength:               60288,
		MaxOutputTokens:             16000,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "mistralai/Mistral-Nemo-Instruct-2407",
		Description:                 "Mistral Nemo instruct 12B chat model with ~60K context.",
	},

	// MoonshotAI Kimi K2 family — open-weight long-context chat models.
	"moonshotai/kimi-k2-0905": {
		Ratio:                       0.6 * ratio.MilliTokensUsd,
		CompletionRatio:             4.16666666667,
		ContextLength:               262144,
		MaxOutputTokens:             262144,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "moonshotai/Kimi-K2-Instruct-0905",
		Description:                 "Moonshot Kimi K2 0905 instruct chat model with 256K context.",
	},
	"moonshotai/kimi-k2-instruct": {
		Ratio:                       0.57 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0350877193,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "moonshotai/Kimi-K2-Instruct",
		Description:                 "Moonshot Kimi K2 instruct chat model with 128K context.",
	},
	"moonshotai/kimi-k2-thinking": {
		Ratio:                       0.6 * ratio.MilliTokensUsd,
		CompletionRatio:             4.16666666667,
		CachedInputRatio:            0.15 * ratio.MilliTokensUsd,
		ContextLength:               262144,
		MaxOutputTokens:             262144,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaReasoningSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "moonshotai/Kimi-K2-Thinking",
		Description:                 "Moonshot Kimi K2 Thinking reasoning chat model with 256K context.",
	},
	"moonshotai/kimi-k2.5": {
		Ratio:                       0.6 * ratio.MilliTokensUsd,
		CompletionRatio:             5,
		CachedInputRatio:            0.1 * ratio.MilliTokensUsd,
		ContextLength:               262144,
		MaxOutputTokens:             262144,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "moonshotai/Kimi-K2.5",
		Description:                 "Moonshot Kimi K2.5 chat model with 256K context.",
	},
	"moonshotai/kimi-k2.6": {
		Ratio:                       0.95 * ratio.MilliTokensUsd,
		CompletionRatio:             4.21052631579,
		CachedInputRatio:            0.16 * ratio.MilliTokensUsd,
		ContextLength:               262144,
		MaxOutputTokens:             262144,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "moonshotai/Kimi-K2.6",
		Description:                 "Moonshot Kimi K2.6 chat model with 256K context.",
	},

	// NousResearch Hermes 2 Pro — Llama 3 8B fine-tune with strong tool calling.
	"nousresearch/hermes-2-pro-llama-3-8b": {
		Ratio:                       0.14 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               8192,
		MaxOutputTokens:             8192,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "NousResearch/Hermes-2-Pro-Llama-3-8B",
		Description:                 "NousResearch Hermes 2 Pro Llama 3 8B chat model with strong function calling.",
	},

	// OpenAI GPT-OSS family — open-weight Apache-2.0 reasoning chat models.
	"openai/gpt-oss-120b": {
		Ratio:                       0.05 * ratio.MilliTokensUsd,
		CompletionRatio:             5,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaReasoningSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "openai/gpt-oss-120b",
		Description:                 "OpenAI GPT-OSS 120B open-weight reasoning chat model with 128K context.",
	},
	"openai/gpt-oss-20b": {
		Ratio:                       0.04 * ratio.MilliTokensUsd,
		CompletionRatio:             3.75,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaReasoningSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "openai/gpt-oss-20b",
		Description:                 "OpenAI GPT-OSS 20B open-weight reasoning chat model with 128K context.",
	},

	// Sao10K Llama fine-tunes — community role-play models.
	"Sao10K/L3-8B-Stheno-v3.2": {
		Ratio:                       0.05 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               8192,
		MaxOutputTokens:             32000,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaTextOnlyFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Sao10K/L3-8B-Stheno-v3.2",
		Description:                 "Sao10K Llama 3 8B Stheno v3.2 community role-play fine-tune.",
	},
	"sao10k/l31-70b-euryale-v2.2": {
		Ratio:                       1.48 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               8192,
		MaxOutputTokens:             8192,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaTextOnlyFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Sao10K/L3.1-70B-Euryale-v2.2",
		Description:                 "Sao10K Llama 3.1 70B Euryale v2.2 community role-play fine-tune.",
	},
	"sao10k/l3-8b-lunaris": {
		Ratio:                       0.05 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               8192,
		MaxOutputTokens:             8192,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaTextOnlyFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Sao10K/L3-8B-Lunaris-v1",
		Description:                 "Sao10K Llama 3 8B Lunaris community role-play fine-tune.",
	},

	// Xiaomi MiMo — small efficient chat model.
	"xiaomimimo/mimo-v2-flash": {
		Ratio:                       0.1 * ratio.MilliTokensUsd,
		CompletionRatio:             3,
		CachedInputRatio:            0.02 * ratio.MilliTokensUsd,
		ContextLength:               262144,
		MaxOutputTokens:             32000,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "XiaomiMiMo/MiMo-V2-Flash",
		Description:                 "Xiaomi MiMo V2 Flash chat model with 256K context.",
	},
}
