package novita

import "github.com/Laisky/one-api/relay/adaptor"

// meta_llamaModels returns the meta_llama model defaults for novita.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func meta_llamaModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"meta-llama/llama-3-70b-instruct": {
			Ratio:                       nativeRate(0.51),
			CompletionRatio:             1.45098039216,
			ContextLength:               8192,
			MaxOutputTokens:             8000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "meta-llama/Meta-Llama-3-70B-Instruct",
			Description:                 "Meta Llama 3 70B instruct chat model (8K context legacy).",
		},
		"meta-llama/llama-3-8b-instruct": {
			Ratio:                       nativeRate(0.04),
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "meta-llama/Meta-Llama-3-8B-Instruct",
			Description:                 "Meta Llama 3 8B instruct chat model with 8K context.",
		},
		"meta-llama/llama-3.1-8b-instruct": {
			Ratio:                       nativeRate(0.02),
			CompletionRatio:             2.5,
			ContextLength:               16384,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "meta-llama/Llama-3.1-8B-Instruct",
			Description:                 "meta-llama/llama-3.1-8b-instruct on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"meta-llama/llama-3.2-1b-instruct": {
			Ratio:             nativeRate(0.02),
			CompletionRatio:   1,
			ContextLength:     131000,
			MaxOutputTokens:   32000,
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"structured_outputs"},
			Description:       "meta-llama/llama-3.2-1b-instruct on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"meta-llama/llama-3.2-3b-instruct": {
			Ratio:                       nativeRate(0.03),
			CompletionRatio:             1.6666666666666667,
			ContextLength:               32768,
			MaxOutputTokens:             32000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "meta-llama/Llama-3.2-3B-Instruct",
			Description:                 "Meta Llama 3.2 3B instruct chat model with 32K context.",
		},
		"meta-llama/llama-3.3-70b-instruct": {
			Ratio:                       nativeRate(0.135),
			CompletionRatio:             2.962962962962963,
			ContextLength:               12288,
			MaxOutputTokens:             12288,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "meta-llama/Llama-3.3-70B-Instruct",
			Description:                 "meta-llama/llama-3.3-70b-instruct on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"meta-llama/llama-4-maverick-17b-128e-instruct-fp8": {
			Ratio:                       nativeRate(0.27),
			CompletionRatio:             3.148148148148148,
			ContextLength:               1048576,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "meta-llama/Llama-4-Maverick-17B-128E-Instruct",
			Description:                 "meta-llama/llama-4-maverick-17b-128e-instruct-fp8 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"meta-llama/llama-4-scout-17b-16e-instruct": {
			Ratio:                       nativeRate(0.18),
			CompletionRatio:             3.2777777777777777,
			ContextLength:               131072,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "meta-llama/Llama-4-Scout-17B-16E-Instruct",
			Description:                 "meta-llama/llama-4-scout-17b-16e-instruct on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
