package novita

import "github.com/Laisky/one-api/relay/adaptor"

// zai_orgModels returns the zai_org model defaults for novita.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func zai_orgModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"zai-org/autoglm-phone-9b-multilingual": {
			Ratio:                       nativeRate(0.035),
			CompletionRatio:             3.9428571428571426,
			ContextLength:               65536,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "zai-org/AutoGLM-Phone-9B-Multilingual",
			Description:                 "zai-org/autoglm-phone-9b-multilingual on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"zai-org/glm-4.5": {
			Ratio:                       nativeRate(0.6),
			CompletionRatio:             3.66666666667,
			CachedInputRatio:            nativeRate(0.11),
			ContextLength:               131072,
			MaxOutputTokens:             98304,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "zai-org/GLM-4.5",
			Description:                 "Z.AI GLM-4.5 chat model with 128K context.",
		},
		"zai-org/glm-4.5-air": {
			Ratio:                       nativeRate(0.13),
			CompletionRatio:             6.538461538461538,
			CachedInputRatio:            nativeRate(0.025),
			ContextLength:               131072,
			MaxOutputTokens:             98304,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "zai-org/GLM-4.5-Air",
			Description:                 "zai-org/glm-4.5-air on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"zai-org/glm-4.5v": {
			Ratio:                       nativeRate(0.6),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.11),
			ContextLength:               65536,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "video", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "zai-org/GLM-4.5V",
			Description:                 "zai-org/glm-4.5v on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"zai-org/glm-4.6": {
			Ratio:                       nativeRate(0.55),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.11),
			ContextLength:               204800,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "zai-org/GLM-4.6",
			Description:                 "zai-org/glm-4.6 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"zai-org/glm-4.6v": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.055),
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "video", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "zai-org/GLM-4.6V",
			Description:                 "zai-org/glm-4.6v on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"zai-org/glm-4.7": {
			Ratio:                       nativeRate(0.6),
			CompletionRatio:             3.666666666666667,
			CachedInputRatio:            nativeRate(0.11),
			ContextLength:               204800,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "zai-org/GLM-4.7",
			Description:                 "zai-org/glm-4.7 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"zai-org/glm-4.7-flash": {
			Ratio:                       nativeRate(0.07),
			CompletionRatio:             5.714285714285714,
			CachedInputRatio:            nativeRate(0.01),
			ContextLength:               200000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "zai-org/GLM-4.7-Flash",
			Description:                 "zai-org/glm-4.7-flash on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"zai-org/glm-4.7-h": {
			Ratio:                       nativeRate(0.6),
			CompletionRatio:             3.666666666666667,
			CachedInputRatio:            nativeRate(0.11),
			ContextLength:               204800,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "zai-org/GLM-4.7-H",
			Description:                 "zai-org/glm-4.7-h on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"zai-org/glm-5": {
			Ratio:                       nativeRate(1),
			CompletionRatio:             3.2,
			CachedInputRatio:            nativeRate(0.2),
			ContextLength:               202800,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "zai-org/GLM-5",
			Description:                 "zai-org/glm-5 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"zai-org/glm-5-turbo": {
			Ratio:                       nativeRate(1.2),
			CompletionRatio:             3.3333333333333335,
			CachedInputRatio:            nativeRate(0.24),
			ContextLength:               202800,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "zai-org/GLM-5-Turbo",
			Description:                 "zai-org/glm-5-turbo on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"zai-org/glm-5.1": {
			Ratio:                       nativeRate(1.38),
			CompletionRatio:             3.1884057971014497,
			CachedInputRatio:            nativeRate(0.26),
			ContextLength:               204800,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "zai-org/GLM-5.1",
			Description:                 "zai-org/glm-5.1 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"zai-org/glm-5.2": {
			Ratio:                       nativeRate(1.4),
			CompletionRatio:             3.1428571428571432,
			CachedInputRatio:            nativeRate(0.26),
			ContextLength:               1048576,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "zai-org/GLM-5.2",
			Description:                 "zai-org/glm-5.2 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"zai-org/glm-5.3": {
			Ratio:             nativeRate(1.4),
			CompletionRatio:   3.1428571428571432,
			CachedInputRatio:  nativeRate(0.26),
			ContextLength:     1048576,
			MaxOutputTokens:   131072,
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "structured_outputs", "reasoning"},
			Description:       "zai-org/glm-5.3 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"zai-org/glm-5.3-flash": {
			Ratio:             nativeRate(0.15),
			CompletionRatio:   3.3333333333333335,
			CachedInputRatio:  nativeRate(0.03),
			ContextLength:     1048576,
			MaxOutputTokens:   131072,
			InputModalities:   []string{"text", "image", "video"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "structured_outputs", "reasoning"},
			Description:       "zai-org/glm-5.3-flash on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"zai-org/glm-5.3-p": {
			Ratio:             nativeRate(1.4),
			CompletionRatio:   3.1428571428571432,
			CachedInputRatio:  nativeRate(0.26),
			ContextLength:     1048576,
			MaxOutputTokens:   131072,
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "structured_outputs", "reasoning"},
			Description:       "zai-org/glm-5.3-p on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"zai-org/glm-5v-turbo": {
			Ratio:                       nativeRate(1.2),
			CompletionRatio:             3.3333333333333335,
			CachedInputRatio:            nativeRate(0.24),
			ContextLength:               204800,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "zai-org/GLM-5V-Turbo",
			Description:                 "zai-org/glm-5v-turbo on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"zai-org/glm-ocr": {
			Ratio:                       nativeRate(0.03),
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "zai-org/GLM-OCR",
			Description:                 "Z.AI GLM-OCR layout/parsing model accepting image input. Retired: absent from Novita's live serverless catalog and pricing page as of 2026-07-13.",
		},
	}
}
