package novita

import (
	"github.com/Laisky/one-api/relay/adaptor"
	"github.com/Laisky/one-api/relay/billing/ratio"
)

// qwenModelRatios contains Alibaba Qwen family entries served by Novita.
// The "fp8" suffix on Qwen3 dense/MoE rows reflects Novita's serving precision;
// VL variants advertise text+image input. Thinking variants use the restricted
// reasoning sampling parameter set.
// Source: https://novita.ai/llm-api  (retrieved 2026-04-28)
var qwenModelRatios = map[string]adaptor.ModelConfig{
	"qwen/qwen-2.5-72b-instruct": {
		Ratio:                       0.38 * ratio.MilliTokensUsd,
		CompletionRatio:             1.05263157895,
		ContextLength:               32000,
		MaxOutputTokens:             8192,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-72B-Instruct",
		Description:                 "Alibaba Qwen 2.5 72B instruct chat model with 32K context.",
	},
	"qwen/qwen2.5-7b-instruct": {
		Ratio:                       0.07 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               32000,
		MaxOutputTokens:             8192,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-7B-Instruct",
		Description:                 "Alibaba Qwen 2.5 7B instruct chat model with 32K context.",
	},
	"qwen/qwen2.5-vl-72b-instruct": {
		Ratio:                       0.8 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               32768,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextImageInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen2.5-VL-72B-Instruct",
		Description:                 "Qwen 2.5 vision-language 72B instruct model with text+image input and 32K context.",
	},
	"qwen/qwen3-235b-a22b-fp8": {
		Ratio:                       0.2 * ratio.MilliTokensUsd,
		CompletionRatio:             4,
		ContextLength:               40960,
		MaxOutputTokens:             20000,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3-235B-A22B",
		Description:                 "Qwen3 235B/A22B MoE chat model served at FP8 with 40K context.",
	},
	"qwen/qwen3-235b-a22b-instruct-2507": {
		Ratio:                       0.09 * ratio.MilliTokensUsd,
		CompletionRatio:             6.44444444444,
		ContextLength:               131072,
		MaxOutputTokens:             16384,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3-235B-A22B-Instruct-2507",
		Description:                 "Qwen3 235B/A22B Instruct 2507 with 128K context.",
	},
	"qwen/qwen3-235b-a22b-thinking-2507": {
		Ratio:                       0.3 * ratio.MilliTokensUsd,
		CompletionRatio:             10,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaReasoningSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3-235B-A22B-Thinking-2507",
		Description:                 "Qwen3 235B/A22B Thinking 2507 reasoning chat model with 128K context.",
	},
	"qwen/qwen3-30b-a3b-fp8": {
		Ratio:                       0.09 * ratio.MilliTokensUsd,
		CompletionRatio:             5,
		ContextLength:               40960,
		MaxOutputTokens:             20000,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3-30B-A3B",
		Description:                 "Qwen3 30B/A3B MoE chat model served at FP8 with 40K context.",
	},
	"qwen/qwen3-32b-fp8": {
		Ratio:                       0.1 * ratio.MilliTokensUsd,
		CompletionRatio:             4.5,
		ContextLength:               40960,
		MaxOutputTokens:             20000,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3-32B",
		Description:                 "Qwen3 32B dense chat model served at FP8 with 40K context.",
	},
	"qwen/qwen3-4b-fp8": {
		Ratio:                       0.03 * ratio.MilliTokensUsd,
		CompletionRatio:             1,
		ContextLength:               128000,
		MaxOutputTokens:             8192,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3-4B",
		Description:                 "Qwen3 4B compact chat model served at FP8 with 128K context.",
	},
	"qwen/qwen3-coder-30b-a3b-instruct": {
		Ratio:                       0.07 * ratio.MilliTokensUsd,
		CompletionRatio:             3.85714285714,
		ContextLength:               160000,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-Coder-30B-A3B-Instruct",
		Description:                 "Qwen3 Coder 30B/A3B Instruct MoE coding chat model with 160K context.",
	},
	"qwen/qwen3-coder-480b-a35b-instruct": {
		Ratio:                       0.3 * ratio.MilliTokensUsd,
		CompletionRatio:             4.33333333333,
		ContextLength:               262144,
		MaxOutputTokens:             65536,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3-Coder-480B-A35B-Instruct",
		Description:                 "Qwen3 Coder 480B/A35B Instruct flagship coding chat model with 256K context.",
	},
	"qwen/qwen3-coder-next": {
		Ratio:                       0.2 * ratio.MilliTokensUsd,
		CompletionRatio:             7.5,
		ContextLength:               262144,
		MaxOutputTokens:             65536,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Description:                 "Qwen3 Coder Next preview coding chat model with 256K context.",
	},
	"qwen/qwen3-next-80b-a3b-instruct": {
		Ratio:                       0.15 * ratio.MilliTokensUsd,
		CompletionRatio:             10,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-Next-80B-A3B-Instruct",
		Description:                 "Qwen3 Next 80B/A3B Instruct MoE chat model with 128K context.",
	},
	"qwen/qwen3-next-80b-a3b-thinking": {
		Ratio:                       0.15 * ratio.MilliTokensUsd,
		CompletionRatio:             10,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaReasoningSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-Next-80B-A3B-Thinking",
		Description:                 "Qwen3 Next 80B/A3B Thinking MoE reasoning chat model with 128K context.",
	},
	"qwen/qwen3-vl-235b-a22b-instruct": {
		Ratio:                       0.3 * ratio.MilliTokensUsd,
		CompletionRatio:             5,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextImageInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3-VL-235B-A22B-Instruct",
		Description:                 "Qwen3 VL 235B/A22B vision-language instruct chat model with 128K context.",
	},
	"qwen/qwen3-vl-235b-a22b-thinking": {
		Ratio:                       0.98 * ratio.MilliTokensUsd,
		CompletionRatio:             4.0306122449,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextImageInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaReasoningSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3-VL-235B-A22B-Thinking",
		Description:                 "Qwen3 VL 235B/A22B vision-language reasoning chat model with 128K context.",
	},
	"qwen/qwen3-vl-30b-a3b-instruct": {
		Ratio:                       0.2 * ratio.MilliTokensUsd,
		CompletionRatio:             3.5,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextImageInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-VL-30B-A3B-Instruct",
		Description:                 "Qwen3 VL 30B/A3B vision-language instruct chat model with 128K context.",
	},
	"qwen/qwen3-vl-30b-a3b-thinking": {
		Ratio:                       0.2 * ratio.MilliTokensUsd,
		CompletionRatio:             5,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextImageInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaReasoningFeatures,
		SupportedSamplingParameters: novitaReasoningSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-VL-30B-A3B-Thinking",
		Description:                 "Qwen3 VL 30B/A3B vision-language reasoning chat model with 128K context.",
	},
	"qwen/qwen3-vl-8b-instruct": {
		Ratio:                       0.08 * ratio.MilliTokensUsd,
		CompletionRatio:             6.25,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextImageInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3-VL-8B-Instruct",
		Description:                 "Qwen3 VL 8B vision-language instruct chat model with 128K context.",
	},
	"qwen/qwen-mt-plus": {
		Ratio:                       0.25 * ratio.MilliTokensUsd,
		CompletionRatio:             3,
		ContextLength:               16384,
		MaxOutputTokens:             8192,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Description:                 "Qwen MT Plus translation-tuned chat model with 16K context.",
	},
	"qwen/qwen3.5-122b-a10b": {
		Ratio:                       0.4 * ratio.MilliTokensUsd,
		CompletionRatio:             8,
		ContextLength:               262144,
		MaxOutputTokens:             65536,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3.5-122B-A10B",
		Description:                 "Qwen3.5 122B/A10B MoE chat model with 256K context.",
	},
	"qwen/qwen3.5-27b": {
		Ratio:                       0.3 * ratio.MilliTokensUsd,
		CompletionRatio:             8,
		ContextLength:               262144,
		MaxOutputTokens:             65536,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3.5-27B",
		Description:                 "Qwen3.5 27B dense chat model with 256K context.",
	},
	"qwen/qwen3.5-35b-a3b": {
		Ratio:                       0.25 * ratio.MilliTokensUsd,
		CompletionRatio:             8,
		ContextLength:               262144,
		MaxOutputTokens:             65536,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "Qwen/Qwen3.5-35B-A3B",
		Description:                 "Qwen3.5 35B/A3B MoE chat model with 256K context.",
	},
	"qwen/qwen3.5-397b-a17b": {
		Ratio:                       0.6 * ratio.MilliTokensUsd,
		CompletionRatio:             6,
		ContextLength:               262144,
		MaxOutputTokens:             65536,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "fp8",
		HuggingFaceID:               "Qwen/Qwen3.5-397B-A17B",
		Description:                 "Qwen3.5 397B/A17B MoE flagship chat model with 256K context.",
	},
}
