package novita

import "github.com/Laisky/one-api/relay/adaptor"

// otherModels returns the other model defaults for novita.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func otherModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"Sao10K/L3-8B-Stheno-v3.2": {
			Ratio:                       nativeRate(0.05),
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             32000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "Sao10K/L3-8B-Stheno-v3.2",
			Description:                 "Sao10K/L3-8B-Stheno-v3.2 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"baichuan/baichuan-m2-32b": {
			Ratio:                       nativeRate(0.07),
			CompletionRatio:             1,
			ContextLength:               131072,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "baichuan-inc/Baichuan-M2-32B",
			Description:                 "baichuan/baichuan-m2-32b on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"elephant": {
			Ratio:                       nativeRate(0.1),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.02),
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Description:                 "Novita-branded chat alias (parameters tracked via Novita pricing page).",
		},
		"google/gemma-3-12b-it": {
			Ratio:                       nativeRate(0.05),
			CompletionRatio:             2,
			ContextLength:               131072,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "google/gemma-3-12b-it",
			Description:                 "google/gemma-3-12b-it on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"google/gemma-3-27b-it": {
			Ratio:                       nativeRate(0.119),
			CompletionRatio:             1.6806722689075633,
			ContextLength:               98304,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "google/gemma-3-27b-it",
			Description:                 "google/gemma-3-27b-it on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"google/gemma-4-26b-a4b-it": {
			Ratio:                       nativeRate(0.13),
			CompletionRatio:             3.076923076923077,
			ContextLength:               262144,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "google/gemma-4-26b-a4b-it",
			Description:                 "google/gemma-4-26b-a4b-it on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"google/gemma-4-31b-it": {
			Ratio:                       nativeRate(0.14),
			CompletionRatio:             2.857142857142857,
			ContextLength:               262144,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "google/gemma-4-31b-it",
			Description:                 "google/gemma-4-31b-it on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"gryphe/mythomax-l2-13b": {
			Ratio:             nativeRate(0.09),
			CompletionRatio:   1,
			ContextLength:     4096,
			MaxOutputTokens:   3200,
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{},
			Description:       "gryphe/mythomax-l2-13b on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"inclusionai/ling-2.6-1t": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             8.333333333333334,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "inclusionAI/Ling-1T",
			Description:                 "Inclusion AI Ling 2.6 1T MoE chat model with 256K context.",
		},
		"inclusionai/ling-2.6-flash": {
			Ratio:                       nativeRate(0.1),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.02),
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "inclusionAI/Ling-flash-2.0",
			Description:                 "Inclusion AI Ling 2.6 Flash MoE chat model with 256K context.",
		},
		"inclusionai/ling-3.0-flash": {
			Ratio:             nativeRate(0.06),
			CompletionRatio:   3,
			CachedInputRatio:  nativeRate(0.012),
			ContextLength:     262144,
			MaxOutputTokens:   32768,
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "reasoning"},
			Description:       "inclusionai/ling-3.0-flash on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"inclusionai/ling-3.0-flash-vl": {
			Ratio:             nativeRate(0.075),
			CompletionRatio:   2.9333333333333336,
			CachedInputRatio:  nativeRate(0.015),
			ContextLength:     262144,
			MaxOutputTokens:   32768,
			InputModalities:   []string{"text", "image", "video"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "reasoning"},
			Description:       "inclusionai/ling-3.0-flash-vl on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"inclusionai/ring-2.6-1t": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             8.333333333333334,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "inclusionAI/Ring-1T",
			Description:                 "Inclusion AI Ring 2.6 1T MoE reasoning chat model with 256K context.",
		},
		"kwaipilot/kat-coder-pro": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             4,
			CachedInputRatio:            nativeRate(0.06),
			ContextLength:               256000,
			MaxOutputTokens:             128000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "Kwaipilot/KAT-Coder-Pro-V1",
			Description:                 "KwaiPilot KAT-Coder Pro coding chat model with 256K context.",
		},
		"microsoft/wizardlm-2-8x22b": {
			Ratio:                       nativeRate(0.62),
			CompletionRatio:             1,
			ContextLength:               65535,
			MaxOutputTokens:             8000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "microsoft/WizardLM-2-8x22B",
			Description:                 "microsoft/wizardlm-2-8x22b on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"mindai/macaron-v1-tall": {
			Ratio:             nativeRate(0.2475),
			CompletionRatio:   5.777777777777778,
			CachedInputRatio:  nativeRate(0.044),
			ContextLength:     262144,
			MaxOutputTokens:   32768,
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "reasoning"},
			Description:       "mindai/macaron-v1-tall on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"mindai/macaron-v1-venti": {
			Ratio:             nativeRate(0.825),
			CompletionRatio:   3.0000000000000004,
			CachedInputRatio:  nativeRate(0.165),
			ContextLength:     1048576,
			MaxOutputTokens:   131072,
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "reasoning"},
			Description:       "mindai/macaron-v1-venti on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"minimaxai/minimax-m1-80k": {
			Ratio:                       nativeRate(0.55),
			CompletionRatio:             4,
			ContextLength:               1000000,
			MaxOutputTokens:             40000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			HuggingFaceID:               "MiniMaxAI/MiniMax-M1-80k",
			Description:                 "minimaxai/minimax-m1-80k on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"mistralai/mistral-nemo": {
			Ratio:                       nativeRate(0.04),
			CompletionRatio:             4.25,
			ContextLength:               60288,
			MaxOutputTokens:             16000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "mistralai/Mistral-Nemo-Instruct-2407",
			Description:                 "mistralai/mistral-nemo on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"nousresearch/hermes-2-pro-llama-3-8b": {
			Ratio:                       nativeRate(0.14),
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "NousResearch/Hermes-2-Pro-Llama-3-8B",
			Description:                 "nousresearch/hermes-2-pro-llama-3-8b on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"nvidia/nemotron-3-nano-30b-a3b": {
			Ratio:                       nativeRate(0.05),
			CompletionRatio:             4,
			ContextLength:               262144,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B",
			Description:                 "nvidia/nemotron-3-nano-30b-a3b on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-oss-120b": {
			Ratio:                       nativeRate(0.05),
			CompletionRatio:             5,
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"max_tokens", "stop", "seed", "response_format", "tools", "tool_choice"},
			SupportedReasoningEfforts:   []string{"low", "medium", "high"},
			DefaultReasoningEffort:      "medium",
			Quantization:                "bf16",
			HuggingFaceID:               "openai/gpt-oss-120b",
			Description:                 "openai/gpt-oss-120b on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"openai/gpt-oss-20b": {
			Ratio:                       nativeRate(0.04),
			CompletionRatio:             3.75,
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"max_tokens", "stop", "seed", "response_format", "tools", "tool_choice"},
			SupportedReasoningEfforts:   []string{"low", "medium", "high"},
			DefaultReasoningEffort:      "medium",
			Quantization:                "bf16",
			HuggingFaceID:               "openai/gpt-oss-20b",
			Description:                 "openai/gpt-oss-20b on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"paddlepaddle/paddleocr-vl": {
			Ratio:                       nativeRate(0.02),
			CompletionRatio:             1,
			ContextLength:               16384,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "PaddlePaddle/PaddleOCR-VL",
			Description:                 "paddlepaddle/paddleocr-vl on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"sao10k/l3-70b-euryale-v2.1": {
			Ratio:             nativeRate(1.48),
			CompletionRatio:   1,
			ContextLength:     8192,
			MaxOutputTokens:   8192,
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools"},
			Description:       "sao10k/l3-70b-euryale-v2.1 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"sao10k/l3-8b-lunaris": {
			Ratio:                       nativeRate(0.05),
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "Sao10K/L3-8B-Lunaris-v1",
			Description:                 "sao10k/l3-8b-lunaris on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"sao10k/l31-70b-euryale-v2.2": {
			Ratio:                       nativeRate(1.48),
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "Sao10K/L3.1-70B-Euryale-v2.2",
			Description:                 "sao10k/l31-70b-euryale-v2.2 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"stepfun/step-3.7-flash": {
			Ratio:                       nativeRate(0.2),
			CompletionRatio:             5.749999999999999,
			CachedInputRatio:            nativeRate(0.04),
			ContextLength:               262144,
			MaxOutputTokens:             256000,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"max_tokens", "stop", "seed", "response_format", "tools", "tool_choice"},
			SupportedReasoningEfforts:   []string{"low", "medium", "high"},
			DefaultReasoningEffort:      "medium",
			Quantization:                "fp8",
			HuggingFaceID:               "stepfun-ai/Step-3.7-Flash",
			Description:                 "stepfun/step-3.7-flash on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"tencent/hy3": {
			Ratio:             nativeRate(0.14),
			CompletionRatio:   4.142857142857142,
			CachedInputRatio:  nativeRate(0.035),
			ContextLength:     262144,
			MaxOutputTokens:   262144,
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "structured_outputs", "reasoning"},
			Description:       "tencent/hy3 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"tencent/hy4-preview": {
			Ratio:             nativeRate(0.834),
			CompletionRatio:   2.998800959232614,
			CachedInputRatio:  nativeRate(0.042),
			ContextLength:     1000000,
			MaxOutputTokens:   64000,
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "structured_outputs", "reasoning"},
			Description:       "tencent/hy4-preview on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"thudm/glm-4-32b-0414": {
			Ratio:                       nativeRate(0.55),
			CompletionRatio:             3.0181818181818176,
			ContextLength:               32000,
			MaxOutputTokens:             32000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "THUDM/GLM-4-32B-0414",
			Description:                 "thudm/glm-4-32b-0414 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"xiaomimimo/mimo-v2-flash": {
			Ratio:                       nativeRate(0.11),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.024),
			ContextLength:               262144,
			MaxOutputTokens:             32000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "XiaomiMiMo/MiMo-V2-Flash",
			Description:                 "Xiaomi MiMo V2 Flash chat model with 256K context.",
		},
		"xiaomimimo/mimo-v2.5": {
			Ratio:                       nativeRate(0.168),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.0034),
			ContextLength:               1048576,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "XiaomiMiMo/MiMo-V2.5",
			Description:                 "xiaomimimo/mimo-v2.5 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"xiaomimimo/mimo-v2.5-pro": {
			Ratio:                       nativeRate(0.522),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.0043),
			ContextLength:               1048576,
			MaxOutputTokens:             131072,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "XiaomiMiMo/MiMo-V2.5-Pro",
			Description:                 "xiaomimimo/mimo-v2.5-pro on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
