package novita

import "github.com/Laisky/one-api/relay/adaptor"

// qwenModels returns the qwen model defaults for novita.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func qwenModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"qwen/qwen-2.5-72b-instruct": {
			Ratio:                       nativeRate(0.38),
			CompletionRatio:             1.0526315789473684,
			ContextLength:               32000,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-72B-Instruct",
			Description:                 "qwen/qwen-2.5-72b-instruct on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen-mt-plus": {
			Ratio:                       nativeRate(0.25),
			CompletionRatio:             3,
			ContextLength:               16384,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Description:                 "qwen/qwen-mt-plus on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen2.5-7b-instruct": {
			Ratio:                       nativeRate(0.07),
			CompletionRatio:             1,
			ContextLength:               32000,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-7B-Instruct",
			Description:                 "Alibaba Qwen 2.5 7B instruct chat model with 32K context.",
		},
		"qwen/qwen2.5-vl-72b-instruct": {
			Ratio:                       nativeRate(0.8),
			CompletionRatio:             1,
			ContextLength:               32768,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen2.5-VL-72B-Instruct",
			Description:                 "Qwen 2.5 vision-language 72B instruct model with text+image input and 32K context.",
		},
		"qwen/qwen3-235b-a22b-fp8": {
			Ratio:                       nativeRate(0.2),
			CompletionRatio:             4,
			ContextLength:               40960,
			MaxOutputTokens:             20000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "Qwen/Qwen3-235B-A22B",
			Description:                 "qwen/qwen3-235b-a22b-fp8 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-235b-a22b-instruct-2507": {
			Ratio:                       nativeRate(0.09),
			CompletionRatio:             6.444444444444445,
			ContextLength:               131072,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "Qwen/Qwen3-235B-A22B-Instruct-2507",
			Description:                 "qwen/qwen3-235b-a22b-instruct-2507 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-235b-a22b-thinking-2507": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             10,
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"max_tokens", "stop", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "Qwen/Qwen3-235B-A22B-Thinking-2507",
			Description:                 "qwen/qwen3-235b-a22b-thinking-2507 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-30b-a3b-fp8": {
			Ratio:                       nativeRate(0.09),
			CompletionRatio:             5,
			ContextLength:               40960,
			MaxOutputTokens:             20000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "Qwen/Qwen3-30B-A3B",
			Description:                 "Qwen3 30B/A3B MoE chat model served at FP8 with 40K context.",
		},
		"qwen/qwen3-32b-fp8": {
			Ratio:                       nativeRate(0.1),
			CompletionRatio:             4.5,
			ContextLength:               40960,
			MaxOutputTokens:             20000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "Qwen/Qwen3-32B",
			Description:                 "Qwen3 32B dense chat model served at FP8 with 40K context.",
		},
		"qwen/qwen3-4b-fp8": {
			Ratio:                       nativeRate(0.03),
			CompletionRatio:             1,
			ContextLength:               128000,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "Qwen/Qwen3-4B",
			Description:                 "Qwen3 4B compact chat model served at FP8 with 128K context.",
		},
		"qwen/qwen3-coder-30b-a3b-instruct": {
			Ratio:                       nativeRate(0.07),
			CompletionRatio:             3.857142857142857,
			ContextLength:               160000,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-Coder-30B-A3B-Instruct",
			Description:                 "qwen/qwen3-coder-30b-a3b-instruct on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-coder-480b-a35b-instruct": {
			Ratio:                       nativeRate(0.38),
			CompletionRatio:             4.078947368421053,
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "Qwen/Qwen3-Coder-480B-A35B-Instruct",
			Description:                 "qwen/qwen3-coder-480b-a35b-instruct on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-coder-next": {
			Ratio:                       nativeRate(0.2),
			CompletionRatio:             7.5,
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Description:                 "qwen/qwen3-coder-next on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-max": {
			Ratio:           nativeRate(0.845),
			CompletionRatio: 4,
			Tiers: []adaptor.ModelRatioTier{adaptor.ModelRatioTier{
				Ratio:               nativeRate(1.4),
				CompletionRatio:     4.0285714285714285,
				InputTokenThreshold: 32768,
			},
				adaptor.ModelRatioTier{
					Ratio:               nativeRate(2.11),
					CompletionRatio:     4.004739336492891,
					InputTokenThreshold: 131072,
				},
			},
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Description:                 "Alibaba Qwen3 Max flagship chat model with 256K context and tiered pricing.",
		},
		"qwen/qwen3-next-80b-a3b-instruct": {
			Ratio:                       nativeRate(0.15),
			CompletionRatio:             10,
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-Next-80B-A3B-Instruct",
			Description:                 "qwen/qwen3-next-80b-a3b-instruct on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-next-80b-a3b-thinking": {
			Ratio:                       nativeRate(0.15),
			CompletionRatio:             10,
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"max_tokens", "stop", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-Next-80B-A3B-Thinking",
			Description:                 "Qwen3 Next 80B/A3B Thinking MoE reasoning chat model with 128K context.",
		},
		"qwen/qwen3-omni-30b-a3b-instruct": {
			Ratio:                       nativeRate(0.25),
			CompletionRatio:             3.88,
			ContextLength:               65536,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image", "audio", "video"},
			OutputModalities:            []string{"text", "audio"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-Omni-30B-A3B-Instruct",
			Description:                 "Qwen3 Omni 30B/A3B omnimodal (text/image/audio/video) instruct chat model with 64K context.",
		},
		"qwen/qwen3-omni-30b-a3b-thinking": {
			Ratio:                       nativeRate(0.25),
			CompletionRatio:             3.88,
			ContextLength:               65536,
			MaxOutputTokens:             16384,
			InputModalities:             []string{"text", "image", "audio", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"max_tokens", "stop", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-Omni-30B-A3B-Thinking",
			Description:                 "Qwen3 Omni 30B/A3B omnimodal (text/image/audio/video) reasoning chat model with 64K context.",
		},
		"qwen/qwen3-vl-235b-a22b-instruct": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             5,
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "Qwen/Qwen3-VL-235B-A22B-Instruct",
			Description:                 "qwen/qwen3-vl-235b-a22b-instruct on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-vl-235b-a22b-thinking": {
			Ratio:                       nativeRate(0.98),
			CompletionRatio:             4.030612244897959,
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"max_tokens", "stop", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "Qwen/Qwen3-VL-235B-A22B-Thinking",
			Description:                 "qwen/qwen3-vl-235b-a22b-thinking on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-vl-30b-a3b-instruct": {
			Ratio:                       nativeRate(0.2),
			CompletionRatio:             3.4999999999999996,
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "video", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-VL-30B-A3B-Instruct",
			Description:                 "qwen/qwen3-vl-30b-a3b-instruct on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3-vl-30b-a3b-thinking": {
			Ratio:                       nativeRate(0.2),
			CompletionRatio:             5,
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"max_tokens", "stop", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-VL-30B-A3B-Thinking",
			Description:                 "Qwen3 VL 30B/A3B vision-language reasoning chat model with 128K context.",
		},
		"qwen/qwen3-vl-8b-instruct": {
			Ratio:                       nativeRate(0.08),
			CompletionRatio:             6.25,
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3-VL-8B-Instruct",
			Description:                 "Qwen3 VL 8B vision-language instruct chat model with 128K context.",
		},
		"qwen/qwen3.5-122b-a10b": {
			Ratio:                       nativeRate(0.4),
			CompletionRatio:             8,
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "Qwen/Qwen3.5-122B-A10B",
			Description:                 "qwen/qwen3.5-122b-a10b on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.5-27b": {
			Ratio:                       nativeRate(0.3),
			CompletionRatio:             8,
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3.5-27B",
			Description:                 "qwen/qwen3.5-27b on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.5-35b-a3b": {
			Ratio:                       nativeRate(0.25),
			CompletionRatio:             8,
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3.5-35B-A3B",
			Description:                 "qwen/qwen3.5-35b-a3b on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.5-397b-a17b": {
			Ratio:                       nativeRate(0.6),
			CompletionRatio:             6,
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "Qwen/Qwen3.5-397B-A17B",
			Description:                 "qwen/qwen3.5-397b-a17b on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.6-27b": {
			Ratio:                       nativeRate(0.6),
			CompletionRatio:             6,
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3.6-27B",
			Description:                 "qwen/qwen3.6-27b on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.6-35b-a3b": {
			Ratio:                       nativeRate(0.248),
			CompletionRatio:             5.987903225806452,
			ContextLength:               262144,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "Qwen/Qwen3.6-35B-A3B",
			Description:                 "qwen/qwen3.6-35b-a3b on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.7-max": {
			Ratio:                       nativeRate(1.25),
			CompletionRatio:             3,
			CachedInputRatio:            nativeRate(0.25),
			ContextLength:               1000000,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Description:                 "qwen/qwen3.7-max on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.8-2.4t-a95b": {
			Ratio:             nativeRate(2),
			CompletionRatio:   3,
			CachedInputRatio:  nativeRate(0.25),
			ContextLength:     1000000,
			MaxOutputTokens:   131072,
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "structured_outputs", "reasoning"},
			Description:       "qwen/qwen3.8-2.4t-a95b on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.8-27b": {
			Ratio:             nativeRate(0.42),
			CompletionRatio:   7.142857142857143,
			CachedInputRatio:  nativeRate(0.085),
			ContextLength:     1000000,
			MaxOutputTokens:   131072,
			InputModalities:   []string{"text", "image", "video"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "structured_outputs", "reasoning"},
			Description:       "qwen/qwen3.8-27b on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.8-flash": {
			Ratio:             nativeRate(0.15),
			CompletionRatio:   3.1333333333333333,
			CachedInputRatio:  nativeRate(0.016),
			ContextLength:     1000000,
			MaxOutputTokens:   131072,
			InputModalities:   []string{"text", "image", "video"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "structured_outputs", "reasoning"},
			Description:       "qwen/qwen3.8-flash on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"qwen/qwen3.8-max": {
			Ratio:             nativeRate(2),
			CompletionRatio:   3,
			CachedInputRatio:  nativeRate(0.25),
			ContextLength:     1000000,
			MaxOutputTokens:   131072,
			InputModalities:   []string{"text", "image", "video"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "structured_outputs", "reasoning"},
			Description:       "qwen/qwen3.8-max on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
