package novita

import (
	"github.com/Laisky/one-api/relay/adaptor"
	"github.com/Laisky/one-api/relay/billing/ratio"
)

// zaiGLMModelRatios contains Z.AI GLM family entries served by Novita.
// GLM 4.x and 5.x are open-weight chat and vision-language models. Vision
// variants (4.5V, 4.6V) accept text+image input.
// Source: https://novita.ai/llm-api  (retrieved 2026-04-28)
var zaiGLMModelRatios = map[string]adaptor.ModelConfig{
	"zai-org/autoglm-phone-9b-multilingual": {
		Ratio:                       0.035 * ratio.MilliTokensUsd,
		CompletionRatio:             3.94285714286,
		ContextLength:               65536,
		MaxOutputTokens:             65536,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "zai-org/AutoGLM-Phone-9B-Multilingual",
		Description:                 "Z.AI AutoGLM Phone 9B multilingual on-device chat model with 64K context.",
	},
	"zai-org/glm-4.5-air": {
		Ratio:                       0.13 * ratio.MilliTokensUsd,
		CompletionRatio:             6.53846153846,
		CachedInputRatio:            0.025 * ratio.MilliTokensUsd,
		ContextLength:               131072,
		MaxOutputTokens:             98304,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "zai-org/GLM-4.5-Air",
		Description:                 "Z.AI GLM-4.5 Air efficient chat model with 128K context.",
	},
	"zai-org/glm-4.5": {
		Ratio:                       0.6 * ratio.MilliTokensUsd,
		CompletionRatio:             3.66666666667,
		CachedInputRatio:            0.11 * ratio.MilliTokensUsd,
		ContextLength:               131072,
		MaxOutputTokens:             98304,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "zai-org/GLM-4.5",
		Description:                 "Z.AI GLM-4.5 chat model with 128K context.",
	},
	"zai-org/glm-4.5v": {
		Ratio:                       0.6 * ratio.MilliTokensUsd,
		CompletionRatio:             3,
		CachedInputRatio:            0.11 * ratio.MilliTokensUsd,
		ContextLength:               65536,
		MaxOutputTokens:             16384,
		InputModalities:             novitaTextImageInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "zai-org/GLM-4.5V",
		Description:                 "Z.AI GLM-4.5V vision-language chat model with 64K text+image context.",
	},
	"zai-org/glm-4.6": {
		Ratio:                       0.55 * ratio.MilliTokensUsd,
		CompletionRatio:             4,
		CachedInputRatio:            0.11 * ratio.MilliTokensUsd,
		ContextLength:               204800,
		MaxOutputTokens:             131072,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "zai-org/GLM-4.6",
		Description:                 "Z.AI GLM-4.6 chat model with 200K context.",
	},
	"zai-org/glm-4.6v": {
		Ratio:                       0.3 * ratio.MilliTokensUsd,
		CompletionRatio:             3,
		CachedInputRatio:            0.055 * ratio.MilliTokensUsd,
		ContextLength:               131072,
		MaxOutputTokens:             32768,
		InputModalities:             novitaTextImageInModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "zai-org/GLM-4.6V",
		Description:                 "Z.AI GLM-4.6V vision-language chat model with 128K text+image context.",
	},
	"zai-org/glm-4.7-flash": {
		Ratio:                       0.07 * ratio.MilliTokensUsd,
		CompletionRatio:             5.71428571429,
		CachedInputRatio:            0.01 * ratio.MilliTokensUsd,
		ContextLength:               200000,
		MaxOutputTokens:             128000,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "zai-org/GLM-4.7-Flash",
		Description:                 "Z.AI GLM-4.7 Flash efficient chat model with 200K context.",
	},
	"zai-org/glm-4.7": {
		Ratio:                       0.6 * ratio.MilliTokensUsd,
		CompletionRatio:             3.66666666667,
		CachedInputRatio:            0.11 * ratio.MilliTokensUsd,
		ContextLength:               204800,
		MaxOutputTokens:             131072,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "zai-org/GLM-4.7",
		Description:                 "Z.AI GLM-4.7 chat model with 200K context.",
	},
	"zai-org/glm-5.1": {
		Ratio:                       1.4 * ratio.MilliTokensUsd,
		CompletionRatio:             3.14285714286,
		CachedInputRatio:            0.26 * ratio.MilliTokensUsd,
		ContextLength:               204800,
		MaxOutputTokens:             131072,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "zai-org/GLM-5.1",
		Description:                 "Z.AI GLM-5.1 chat model with 200K context.",
	},
	"zai-org/glm-5": {
		Ratio:                       1 * ratio.MilliTokensUsd,
		CompletionRatio:             3.2,
		CachedInputRatio:            0.2 * ratio.MilliTokensUsd,
		ContextLength:               202800,
		MaxOutputTokens:             131072,
		InputModalities:             novitaTextOnlyModalities,
		OutputModalities:            novitaTextOnlyModalities,
		SupportedFeatures:           novitaChatFeatures,
		SupportedSamplingParameters: novitaSamplingParams,
		Quantization:                "bf16",
		HuggingFaceID:               "zai-org/GLM-5",
		Description:                 "Z.AI GLM-5 chat model with 200K context.",
	},
}
