package novita

import "github.com/Laisky/one-api/relay/adaptor"

// deepseekModels returns the deepseek model defaults for novita.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func deepseekModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"deepseek/deepseek-ocr": {
			Ratio:                       nativeRate(0.03),
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "deepseek-ai/DeepSeek-OCR",
			Description:                 "DeepSeek-OCR layout/parsing model accepting image input with 8K context.",
		},
		"deepseek/deepseek-ocr-2": {
			Ratio:                       nativeRate(0.03),
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "deepseek-ai/DeepSeek-OCR",
			Description:                 "deepseek/deepseek-ocr-2 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-prover-v2-671b": {
			Ratio:                       nativeRate(0.7),
			CompletionRatio:             3.57142857143,
			ContextLength:               160000,
			MaxOutputTokens:             160000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"max_tokens", "stop", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "deepseek-ai/DeepSeek-Prover-V2-671B",
			Description:                 "DeepSeek Prover V2 671B specialised theorem-proving reasoning model with 160K context.",
		},
		"deepseek/deepseek-r1": {
			Ratio:             nativeRate(4),
			CompletionRatio:   1,
			ContextLength:     64000,
			MaxOutputTokens:   16000,
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "reasoning"},
			Description:       "deepseek/deepseek-r1 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-r1-0528": {
			Ratio:                       nativeRate(0.7),
			CompletionRatio:             3.5714285714285716,
			CachedInputRatio:            nativeRate(0.35),
			ContextLength:               163840,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"max_tokens", "stop", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "deepseek-ai/DeepSeek-R1-0528",
			Description:                 "deepseek/deepseek-r1-0528 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-r1-0528-qwen3-8b": {
			Ratio:                       nativeRate(0.06),
			CompletionRatio:             1.5,
			ContextLength:               128000,
			MaxOutputTokens:             32000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{},
			SupportedSamplingParameters: []string{"max_tokens", "stop", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "deepseek-ai/DeepSeek-R1-0528-Qwen3-8B",
			Description:                 "deepseek/deepseek-r1-0528-qwen3-8b on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-r1-distill-llama-70b": {
			Ratio:                       nativeRate(0.8),
			CompletionRatio:             1,
			ContextLength:               8192,
			MaxOutputTokens:             8192,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"reasoning"},
			SupportedSamplingParameters: []string{"max_tokens", "stop", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
			Description:                 "deepseek/deepseek-r1-distill-llama-70b on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-r1-turbo": {
			Ratio:                       nativeRate(0.7),
			CompletionRatio:             3.5714285714285716,
			ContextLength:               64000,
			MaxOutputTokens:             16000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"max_tokens", "stop", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "deepseek-ai/DeepSeek-R1",
			Description:                 "deepseek/deepseek-r1-turbo on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-r1/community": {
			Ratio:             nativeRate(4),
			CompletionRatio:   1,
			ContextLength:     64000,
			MaxOutputTokens:   8000,
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "reasoning"},
			Description:       "deepseek/deepseek-r1/community on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-v3-0324": {
			Ratio:                       nativeRate(0.27),
			CompletionRatio:             4.14814814815,
			CachedInputRatio:            nativeRate(0.135),
			ContextLength:               163840,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V3-0324",
			Description:                 "DeepSeek V3 0324 chat model with 160K context and cache-read discount.",
		},
		"deepseek/deepseek-v3-turbo": {
			Ratio:                       nativeRate(0.4),
			CompletionRatio:             3.25,
			ContextLength:               64000,
			MaxOutputTokens:             16000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V3",
			Description:                 "Throughput-optimised DeepSeek V3 (Turbo) with 64K context.",
		},
		"deepseek/deepseek-v3.1": {
			Ratio:                       nativeRate(0.27),
			CompletionRatio:             3.7037037037037033,
			CachedInputRatio:            nativeRate(0.135),
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V3.1",
			Description:                 "deepseek/deepseek-v3.1 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-v3.1-terminus": {
			Ratio:                       nativeRate(0.27),
			CompletionRatio:             3.7037037037037033,
			CachedInputRatio:            nativeRate(0.135),
			ContextLength:               131072,
			MaxOutputTokens:             32768,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V3.1-Terminus",
			Description:                 "deepseek/deepseek-v3.1-terminus on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-v3.2": {
			Ratio:                       nativeRate(0.269),
			CompletionRatio:             1.486988847583643,
			CachedInputRatio:            nativeRate(0.1345),
			ContextLength:               163840,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V3.2",
			Description:                 "deepseek/deepseek-v3.2 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-v3.2-exp": {
			Ratio:                       nativeRate(0.27),
			CompletionRatio:             1.5185185185185184,
			ContextLength:               163840,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V3.2-Exp",
			Description:                 "deepseek/deepseek-v3.2-exp on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-v3/community": {
			Ratio:             nativeRate(0.89),
			CompletionRatio:   1,
			ContextLength:     64000,
			MaxOutputTokens:   8000,
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools"},
			Description:       "deepseek/deepseek-v3/community on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-v4-flash": {
			Ratio:                       nativeRate(0.14),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.028),
			ContextLength:               1048576,
			MaxOutputTokens:             393216,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V4-Flash",
			Description:                 "deepseek/deepseek-v4-flash on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-v4-flash-0731": {
			Ratio:             nativeRate(0.44),
			CompletionRatio:   3,
			CachedInputRatio:  nativeRate(0.028),
			ContextLength:     1048576,
			MaxOutputTokens:   393216,
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "structured_outputs", "reasoning"},
			Description:       "deepseek/deepseek-v4-flash-0731 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-v4-flash-vision-exp": {
			Ratio:             nativeRate(0.44),
			CompletionRatio:   3,
			CachedInputRatio:  nativeRate(0.028),
			ContextLength:     1048576,
			MaxOutputTokens:   393216,
			InputModalities:   []string{"text", "image"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "structured_outputs", "reasoning"},
			Description:       "deepseek/deepseek-v4-flash-vision-exp on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-v4-pro": {
			Ratio:                       nativeRate(1.6),
			CompletionRatio:             2,
			CachedInputRatio:            nativeRate(0.135),
			ContextLength:               1048576,
			MaxOutputTokens:             393216,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "deepseek-ai/DeepSeek-V4-Pro",
			Description:                 "deepseek/deepseek-v4-pro on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-v4-pro-0813": {
			Ratio:             nativeRate(1.32),
			CompletionRatio:   3,
			CachedInputRatio:  nativeRate(0.044),
			ContextLength:     1048576,
			MaxOutputTokens:   393216,
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "structured_outputs", "reasoning"},
			Description:       "deepseek/deepseek-v4-pro-0813 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-v4.1-flash": {
			Ratio:             nativeRate(0.3),
			CompletionRatio:   4,
			CachedInputRatio:  nativeRate(0.006),
			ContextLength:     1048576,
			MaxOutputTokens:   393216,
			InputModalities:   []string{"text", "image"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "structured_outputs", "reasoning"},
			Description:       "deepseek/deepseek-v4.1-flash on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek-v4.1-flash-z": {
			Ratio:             nativeRate(0.3),
			CompletionRatio:   4,
			CachedInputRatio:  nativeRate(0.03),
			ContextLength:     1048576,
			MaxOutputTokens:   393216,
			InputModalities:   []string{"text", "image"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools", "structured_outputs", "reasoning"},
			Description:       "deepseek/deepseek-v4.1-flash-z on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"deepseek/deepseek_v3": {
			Ratio:             nativeRate(0.89),
			CompletionRatio:   1,
			ContextLength:     64000,
			MaxOutputTokens:   16000,
			InputModalities:   []string{"text"},
			OutputModalities:  []string{"text"},
			SupportedFeatures: []string{"tools"},
			Description:       "deepseek/deepseek_v3 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
