package novita

import "github.com/Laisky/one-api/relay/adaptor"

// baiduModels returns the baidu model defaults for novita.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func baiduModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"baidu/cobuddy": {
			Ratio:                       nativeRate(0.28),
			CompletionRatio:             4.035714285714285,
			CachedInputRatio:            nativeRate(0.07),
			ContextLength:               131072,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			Description:                 "baidu/cobuddy on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"baidu/ernie-4.5-21B-a3b": {
			Ratio:                       nativeRate(0.07),
			CompletionRatio:             4,
			ContextLength:               120000,
			MaxOutputTokens:             8000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "baidu/ERNIE-4.5-21B-A3B-PT",
			Description:                 "baidu/ernie-4.5-21B-a3b on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"baidu/ernie-4.5-21B-a3b-thinking": {
			Ratio:                       nativeRate(0.07),
			CompletionRatio:             4,
			ContextLength:               131072,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"max_tokens", "stop", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "baidu/ERNIE-4.5-21B-A3B-Thinking",
			Description:                 "Thinking-mode ERNIE 4.5 21B/A3B with 128K context for reasoning workloads.",
		},
		"baidu/ernie-4.5-300b-a47b-paddle": {
			Ratio:                       nativeRate(0.28),
			CompletionRatio:             3.92857142857,
			ContextLength:               123000,
			MaxOutputTokens:             12000,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "baidu/ERNIE-4.5-300B-A47B-PT",
			Description:                 "Flagship Baidu ERNIE 4.5 300B/A47B served via PaddlePaddle backend with 123K context.",
		},
		"baidu/ernie-4.5-vl-28b-a3b": {
			Ratio:                       nativeRate(0.14),
			CompletionRatio:             4,
			ContextLength:               30000,
			MaxOutputTokens:             8000,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "baidu/ERNIE-4.5-VL-28B-A3B-PT",
			Description:                 "ERNIE 4.5 vision-language 28B/A3B with text+image input and 30K context.",
		},
		"baidu/ernie-4.5-vl-28b-a3b-thinking": {
			Ratio:                       nativeRate(0.39),
			CompletionRatio:             1,
			ContextLength:               131072,
			MaxOutputTokens:             65536,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "json_mode", "reasoning"},
			SupportedSamplingParameters: []string{"max_tokens", "stop", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "baidu/ERNIE-4.5-VL-28B-A3B-Thinking",
			Description:                 "Thinking-mode ERNIE 4.5 vision-language 28B/A3B with 128K context.",
		},
		"baidu/ernie-4.5-vl-424b-a47b": {
			Ratio:                       nativeRate(0.42),
			CompletionRatio:             2.9761904761904763,
			ContextLength:               123000,
			MaxOutputTokens:             16000,
			InputModalities:             []string{"text", "image"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "bf16",
			HuggingFaceID:               "baidu/ERNIE-4.5-VL-424B-A47B-PT",
			Description:                 "baidu/ernie-4.5-vl-424b-a47b on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
