package novita

import "github.com/Laisky/one-api/relay/adaptor"

// moonshotaiModels returns the moonshotai model defaults for novita.
// It takes no arguments and returns independently owned, directly editable Go configurations.
func moonshotaiModels() map[string]adaptor.ModelConfig {
	return map[string]adaptor.ModelConfig{
		"moonshotai/kimi-k2-0905": {
			Ratio:                       nativeRate(0.6),
			CompletionRatio:             4.166666666666667,
			ContextLength:               262144,
			MaxOutputTokens:             98304,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "moonshotai/Kimi-K2-Instruct-0905",
			Description:                 "moonshotai/kimi-k2-0905 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"moonshotai/kimi-k2-instruct": {
			Ratio:                       nativeRate(0.57),
			CompletionRatio:             4.035087719298246,
			ContextLength:               131072,
			MaxOutputTokens:             98304,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "moonshotai/Kimi-K2-Instruct",
			Description:                 "moonshotai/kimi-k2-instruct on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"moonshotai/kimi-k2-thinking": {
			Ratio:                       nativeRate(0.6),
			CompletionRatio:             4.166666666666667,
			CachedInputRatio:            nativeRate(0.15),
			ContextLength:               262144,
			MaxOutputTokens:             98304,
			InputModalities:             []string{"text"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"max_tokens", "stop", "seed", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "moonshotai/Kimi-K2-Thinking",
			Description:                 "moonshotai/kimi-k2-thinking on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"moonshotai/kimi-k2.5": {
			Ratio:                       nativeRate(0.6),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.1),
			ContextLength:               262144,
			MaxOutputTokens:             262144,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "moonshotai/Kimi-K2.5",
			Description:                 "moonshotai/kimi-k2.5 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"moonshotai/kimi-k2.6": {
			Ratio:                       nativeRate(0.8),
			CompletionRatio:             4.25,
			CachedInputRatio:            nativeRate(0.16),
			ContextLength:               262144,
			MaxOutputTokens:             262144,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "moonshotai/Kimi-K2.6",
			Description:                 "moonshotai/kimi-k2.6 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"moonshotai/kimi-k2.7-code": {
			Ratio:                       nativeRate(0.95),
			CompletionRatio:             4.2105263157894735,
			CachedInputRatio:            nativeRate(0.19),
			ContextLength:               262144,
			MaxOutputTokens:             262144,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"temperature", "top_p", "top_k", "min_p", "max_tokens", "stop", "presence_penalty", "frequency_penalty", "repetition_penalty", "seed", "n", "logit_bias", "logprobs", "top_logprobs", "response_format", "tools", "tool_choice"},
			Quantization:                "fp8",
			HuggingFaceID:               "moonshotai/Kimi-K2.7-Code",
			Description:                 "moonshotai/kimi-k2.7-code on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
		"moonshotai/kimi-k3": {
			Ratio:                       nativeRate(3),
			CompletionRatio:             5,
			CachedInputRatio:            nativeRate(0.3),
			ContextLength:               1048576,
			MaxOutputTokens:             1048576,
			InputModalities:             []string{"text", "image", "video"},
			OutputModalities:            []string{"text"},
			SupportedFeatures:           []string{"tools", "structured_outputs", "reasoning"},
			SupportedSamplingParameters: []string{"max_tokens", "stop"},
			Description:                 "moonshotai/kimi-k3 on novita; official catalog snapshot 2026-09-24. Provider access and deployment configuration remain administrator-controlled.",
		},
	}
}
